sagemathinc/cocalc

src/smc-webapp/frame-editors/_style.sass

... and probably other dropdowns as well
I checked in my chrome 77 and firefox 68, but it might be worth to try others as well.
Via browserstack, I checked the latest Safari and it also works fine.
I also tried Edge, but then https://github.com/sagemathinc/cocalc/issues/4056 happened
#4044
Front end:

webapp/frame editor: fix zoom dropdown 

---

src/package.json
src/smc-project/package.json

Prettier will be updated to 1.18.2 with the next software update. This makes the one we install for development consistent with that. The overall motivation is to catch up on a couple of improvements, and also support new syntax. In particular, this will support the new `readonly` keyword in TypeScript.
I checked tsx, js, and markdown.
Front end:

prettier 1.18.2: update and make consistent

---

src/smc-webapp/billing/actions.ts

I wonder why typescript doesn't report this?
deleted a newly created test account, this did work
worth a check if subscriptions are also deleted
Front end:

webapp: fix #4072

---

src/smc-webapp/account_page.cjsx
src/smc-webapp/app_shared.cjsx
src/smc-webapp/landing_page.cjsx

while connecting, this shows a spinner and a warning for chrome users that they might have to restart the browser.
without this, the users just sees the gray bar at the top and everything else is a white area without any info
I simulated a websocket issue by
1. being signed in as usual, and I'm in my settings/account page.
2. commenting out the line `init_primus_server(http_server)` in hub.coffee and restarting the hub
3. refreshing the page
additionally, the same as above but for a URL that tries to open a specific project! that's exactly where I was stuck last week. 
Front end:

webapp/landing page: connecting info + chrome browser issue warning

---

src/smc-webapp/r_misc/tip.tsx

to avoid popup elements to be sticky while the triggering element is gone, also hide them when leaving these
1.
1.
1.
Front end:

webapp/r_misc/tip: trigger onMouseLeave via popup elements 

---

src/jest.config.js
src/package.json
src/smc-webapp/app-framework/Store.ts
src/smc-webapp/app-framework/TypedMap.ts
src/smc-webapp/app-framework/__tests__/deep-immutable.type.test.ts
src/smc-webapp/app-framework/__tests__/store-get-in.type.test.ts
src/smc-webapp/app-framework/immutable-types.ts
src/smc-webapp/billing/store.ts
src/smc-webapp/billing/types.ts
src/smc-webapp/frame-editors/code-editor/actions.ts
src/smc-webapp/package.json

- Fix deep typing for `getIn` when the entire path was always defined
- Add deep typing for `getIn` when some part of the path MAY be defined
- Add type `DeepImmutable<T>` for converting from plain JS objects to our use of immutable js.
- Does NOT support custom classes. So *the typing* (not runtime, so use `as any` if you must) will break if you stored a custom class inside a store. So far we don't do this it seems.
```
cd src/smc-webapp
npm test
```
- Spin up a dev server and open cocalc.
- Open account
- Go to billing
Front end:

Add store getIn types

---

src/scripts/smc-install-all

@williamstein  just when you merged it, I thought what happens if one of the jobs fails. well, there is a setting to abort everything, such that an error isn't getting lost. I'll merge this in.
1.
1.
1.
Front end:

dev/npm build: stop all parallel jobs when the first one fails

---

src/smc-webapp/frame-editors/frame-tree/editor.tsx
src/smc-webapp/frame-editors/rmd-editor/actions.ts
src/smc-webapp/project_actions.ts

* fixes a stacktrace introduced by changes in 894ced87d3
* adds some type info to directory fetching
* monospace formatted error messages for rmd
* well, make an rmd file, no stacktrace appears. e.g.
---
title: "The Title"
author: John Doe
date: March 22, 2019
---
```{r}
plot(rnorm(10))
```
Front end:

webapp: fix Rmd rendering; slightly type directory listing fetch

---

src/install.py

npm ci does not work with global, AFAIU. instead, we should probably build it locally and then symlink to the module from /usr/lib/node_modules
1.
1.
1.
Front end:

build docker: just unblocking it to build

---

src/smc-webapp/frame-editors/code-editor/actions.ts
src/smc-webapp/frame-editors/x11-editor/actions.ts

* run this in a terminal
```
>>> import matplotlib.pyplot as plt
>>> plt.plot([2,3,4,3,32,2,3,2,1])
>>> plt.savefig('x.png')
```
* and the above in an X11 terminal, plus
```
plt.show()
```
which should open a window.
#4120
Front end:

terminal: set MPLBACKEND to tell matplotlib how to draw 

---

src/jest.config.js
src/smc-util/fill/define.test.ts
src/smc-util/fill/define.ts
src/smc-util/fill/fill.test.ts
src/smc-util/fill/fill.ts
src/smc-util/fill/index.ts
src/smc-util/fill/types.ts
src/smc-util/package-lock.json
src/smc-util/package.json
src/smc-webapp/app-framework/Store.ts

Creates two functions to replace `defaults opts {}` when we used Coffeescript.
`fill(opts, defaults)` takes a known object ops and applies some defaults to its optional parts. 
```typescript
interface Props {
name: string;
show?: boolean; // Optional at call site
highlight?: boolean;
}
function doSomething(props: Props) {
props = fill(props, {show: true})
// Now props.show is expected to be defined
// { name: string; show: boolean; highlight?: boolean } 
// ...
}
```
`define(props, definition, ...)` is directly converted from `defaults(obj1, obj2, ...)`.
It's typed such that props is unknown and like `fill`, knows when provided defaults change the result type to be defined.
1. In src, run `npx jest fill`
1. Open a course
1. Add some students
1. Make and distribute some assignments
Front …

Ts version of defaults

---

src/cocalc-ui/index.ts
src/smc-webapp/project/settings/project-control.tsx

Antd's Popconfirm for restarting/stopping a project.
I imported the icons to match the ones we have. Not sure if that's a good idea.
The text itself has a few little changes as well...
stop/restart a project
Front end:

Popconfirm project restart

---

src/smc-webapp/jupyter/output-messages/data.tsx
src/smc-webapp/jupyter/output-messages/image.tsx

this is something that bugs me and I today just saw it in a notebook again. if an image has no height/width, it's show as it is. for large ones, they're off screen and it's hard to scroll around, etc. this here limits the width to 100% and if you need to see it full size, you can click. this doesn't impact any of the other plots, because they all have height and width set.
I used dask to plot a graph, which is in this case larger than my screen and hence hard to understand.
```
import dask.array as da
x = da.random.random((1000, 1000), chunks=(300, 300))
y = x + x.T
z = y[::75, 100:].mean(axis=1)
rz = (z[:100].sum() / z[:100].shape[0])
rz.visualize()
```
Front end:

webapp/jupyter2: resize too large images to container width

---

src/smc-webapp/frame-editors/generic/client.ts

i saw an uncaught exception while being disconnected. I guess it's that call.
1.
1.
1.
Front end:

webapp/frame-editor: wrap touch_project call, fails in case of being disconnected

---

src/smc-hub/postgres-server-queries.coffee

I just realized this is missing
1.
1.
1.
Front end:

hub/stats: also stats about x11 files

---

src/smc_sagews/smc_sagews/tests/test_sagews.py
src/smc_sagews/smc_sagews/tests/test_sagews_modes.py

Update two tests in the pytest suite for sagews.
No change to running production code.
Tested in production CoCalc, which is still on sage-8.8, and in current Experimental environment where sage-8.9 is the default.
1.
1.
1.
Front end:

support sage-8.9 in sagews

---

src/scripts/cocalc-dirs.sh
src/scripts/smc-install-all

this is just for speeding up `npm run make`. deletes old node modules in parallel of npm ci. also,  building project first, because there is more C++ code being built.
well ... if it causes issues, it should be easy to fix. I've not noticed any problems.
Front end:

npm install: delete old node_modules by moving them out of the way

---

src/package-lock.json
src/package.json
src/smc-hub/package-lock.json
src/smc-hub/package.json
src/smc-project/package-lock.json
src/smc-project/package.json
src/test/puppeteer/package-lock.json
src/test/puppeteer/package.json

this updates typescript to 3.6.4 (previously, we had a mix of slightly different versions)
1.
1.
1.
Front end:

typescript 3.6.4

---

src/smc-webapp/project/settings/hide-delete-box.tsx
src/smc-webapp/projects/projects-filter-buttons.tsx
src/test/puppeteer/src/api_create_project.ts
src/test/puppeteer/src/del_hide_project.ts
src/test/puppeteer/src/get_project_status.ts
src/test/puppeteer/src/login_session.ts
src/test/puppeteer/src/test_driver.ts
src/test/puppeteer/src/test_sage_ker.ts
src/test/puppeteer/src/types.ts

Start to add GUI tests for [un]deleting and [un]hiding projects. The tests don't fully work yet.
Only changes to production code are addition of `cocalc-test` attributes in 
* src/smc-webapp/project/settings/hide-delete-box.tsx
* src/smc-webapp/projects/projects-filter-buttons.tsx
Sample command to hide the project specified in the creds file:
```
cd ~/cocalc/src/test/puppeteer
npm run tdbg -- -c ~/CCTEST/staging-dev-p2.yaml -p -x hide
```
1.
1.
1.
Front end:

Front end test 06

---

src/smc-webapp/_projects.sass

I noticed today that the nav items for a project (files, log, ...) are slightly lower than the file tabs. This just tweaks some padding, that's all.
see screencast
This tabs between two tabs: prod and my dev project. In one of them the descriptions line up.
Front end:

webapp/proj navbar: fix low "hanging" tab descriptions

---

src/smc-webapp/billing/billing-page.tsx
src/smc-webapp/billing/explain-resources.tsx
src/smc-webapp/billing/faq.tsx
src/smc-webapp/r_misc/A.tsx

1. taking care of #4182
2. some r_misc related cleanup and using `A` for external links
3. showing enterprise info even in the case of no card with at least one subscription
This is easy to test ... just check if the page shows up, and the enterprise info is there in that special case.
Front end:

minor pricing page changes

---

src/smc-webapp/frame-editors/html-editor/actions.ts
src/smc-webapp/frame-editors/html-editor/iframe-html.tsx
src/smc-webapp/frame-editors/html-editor/options.ts

This fixes #3984 -- or well, at least that button is actually doing something now. I hope this is not backwards…
* make a html file, open the iframe preview, and click the 3rd reload button. 
* this in the html shows a new random number each time
```
<script>
document.write(Math.random())
</script>
```
Front end:

html reload button

---

src/smc-webapp/file-associations.ts

Support for verilog, `.v` and `.vh` files.
* copy/paste https://codemirror.net/mode/verilog/ into these files
Front end:

verilog file support

---

.gitignore
src/package.json
src/scripts/check_npm_packages.py

just an idea, this could help us getting insight/warnings about version inconsistencies (e.g. as part of CI testing)
the only change that touches anything is calling this at the start of `webpack-watch`, to give us some feedback. Later, once this is down to zero inconsistencies, we can add it to travis CI to inform us about introducing new ones.
Front end:

dev: consistency checker for npm packages

---

src/smc-webapp/frame-editors/rmd-editor/rmd-converter.ts

see  #4202 .. this is trivial
incidentally, this is hard to test. the hub in a cc-in-cc project starts in a terminal, which has this env var set. that propagates down to the project and so on. you have to unset it, then start the hub, then experience the difference between setting this or not.
content
<pre>
---
title: python3 test
---
```{r setup, include=FALSE}
library(reticulate)
use_python('/usr/bin/python3')
```
```{python}
import numpy as np
import matplotlib.pyplot as plt
xx = np.linspace(0, 20, 100)
yy = np.sin(xx) + np.cos(xx)
plt.plot(xx, yy)
plt.show()
```
</pre>
Front end:

webapp/rmd: make sure mpl backend is set correctly when plotting via matplotlib

---

src/smc-webapp/frame-editors/latex-editor/pythontex.ts

This is analogous to https://github.com/sagemathinc/cocalc/pull/4204
Fixes  #4203
```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[parfill]{parskip}
\usepackage{amsmath,amssymb}
\usepackage{fullpage}
\usepackage{graphicx}
\usepackage{pythontex}
\title{Title of Document}
\author{Name of Author}
\begin{document}
\begin{pyconsole}
var = 1 + 1
import os
print(os.environ.get("MPLBACKEND"))
\end{pyconsole}
1+1 = \pycon{2}!
\begin{pylabcode}
x = linspace(0, pi, 1000)
plt.plot(x, 2*sin(x**2), label='$2 sin(x^2)$')
plt.plot(x, cos(x), label='cos(x)')
savefig("plot.pdf")
\end{pylabcode}
\begin{center}
\includegraphics[width=0.85\textwidth]{plot.pdf}
\end{center}
\end{document}
```
Front end:

webapp/latex/pythontex: tell matplotlib what to use

---

src/smc-hub/email.ts
src/smc-util/theme.js
src/smc-webapp/buttonbar.coffee
src/smc-webapp/course/upgrades.tsx
src/smc-webapp/customize.tsx
src/smc-webapp/r_help.cjsx
src/smc-webapp/share/config/config.tsx
src/smc-webapp/support.cjsx
src/smc-webapp/tasks/actions.coffee

this removes the link to the wiki portal and also gets rid of other miscellaneous usages of "wiki"
1.
1.
1.
Front end:

removing wiki portal link and misc other usages of "wiki"

---

.travis-install-services.sh
.travis.yml

this updates the linux and nodejs version for travis, but well, it doesn't fix build errors. now it is
```
+/home/travis/build/sagemathinc/cocalc/src/dev/project/start_api.py test
service_hub.py --dev --foreground --hostname=0.0.0.0 --port=54147 --proxy_port=0 --gap=0 --test start
hub  --host=0.0.0.0 --port 54147 --proxy_port 0 --share_port 0  --share_path   --base_url= --dev  --test  --foreground  
node -r esm --max-old-space-size=8000 run/hub.js --host=0.0.0.0 --port 54147 --proxy_port 0 --share_port 0 --share_path --base_url= --dev --test --foreground
/home/travis/build/sagemathinc/cocalc/src/node_modules/ts-node/src/index.ts:261
return new TSError(diagnosticText, diagnosticCodes)
^
TSError: ⨯ Unable to compile TypeScript:
postgres/changefeed.ts(49,111): error TS2322: Type '0' is not …
```

Update Travis CI

---

src/smc-project/formatters/prettier.ts
src/smc-project/formatters/rust-format.ts
src/smc-project/formatters/rust_format.ts
src/smc-util/code-formatter.ts
src/smc-util/misc2.ts
src/smc-webapp/frame-editors/code-editor/editor.ts
src/smc-webapp/frame-editors/frame-tree/title-bar.tsx

This adds formatting support for `rs` Rust files.
It also refactors the formatting code a little bit.
I checked that formatting jupyter cells, html, tsx, py, r and of course, rs files work.
example rust code I used for testing is
```
fn main() {
// `n` will take the values: 1, 2, ..., 100 in each iteration
for n in 1..101 {
if n % 15 == 0 {
println!("fizzbuzz");
} else if n % 3 == 0 {
println!("fizz");
} else if n % 5 == 0 {
println!("buzz");
} else {
println!("{}", n);
}
}
}
```
If you also want to run it: `rustc [filename.rs]` and then run the compiled binary.
Front end:

formatting support for rust

---

src/smc_pyutil/smc_pyutil/templates/linux/default.tex

this shrinks the default latex template and mentions pythontex
I texted that the engine selection still triggers the correct preamble.
Front end:

simplify default latex template and mention pythontex

---

src/smc-webapp/jupyter/top-buttonbar.tsx

This isn't doing much, just changing the cell type dropdown. That way I get at least a little bit done, more to come :roll_eyes: 
dropdown changes cell type
Front end:

webapp/jupyter: change cell type selector to be an antd dropdown

---

src/webapp-lib/doc/latex-editor.pug

This patch makes a couple of small changes to the latex landing page. It will be interesting to see if there are any performance changes.
Well, the static page build works, that's all that needs testing.
Front end:

tweaking latex landing page a little bit

---

src/smc-webapp/billing/explain-plan.tsx

The only changes are text in static page `src/smc-webapp/billing/explain-plan.tsx`.
- Remove "Purchasing course packages is mandatory!".
- Remove the following sentence because it is redundant with the "Payment options" section immediately below.
- Move last sentence of the "mandatory..." paragraph into "Payment options" section.
- Remove sentence suggesting starting a course before paying. Non-upgraded projects can't send emails to invite students who don't already have an account with that email.
- Other minor wording changes
Tested with cc-in-cc. No build errors. Here's the main part of the new text:
1.
1.
1.
Front end:

remove "mandatory" sentence & revise wording on pricing page

---

src/smc-webapp/frame-editors/x11-editor/apps.ts

this just adds a button if `grass` is available. 
1.
1.
1.
Front end:

webapp/x11: add grass launch button

---

src/smc-webapp/r_help.cjsx

remove google+ link
it not longer shows up
Front end:

webapp: remove google+

---

src/smc-hub/postgres-base.coffee
src/smc-hub/postgres-ops.coffee
src/smc-hub/test/get_stats.coffee

There are several places where the connection to the database is established. The first one is ok, but another one hardcodes `'smc'`.
1.
1.
1.
Front end:

do not hardcode DB credentials

---

src/smc-webapp/launch/share.ts

Without this patch, the Docker image build fails with the following error while running src/package.json script `webpack-production`:
```
webpack error in docker build
[2869] multi ./webapp-lib/primus/primus-engine.min.js 28 bytes {0} [built]
+ 2856 hidden modules
ERROR in /cocalc/src/smc-webapp/launch/share.ts
./smc-webapp/launch/share.ts
[tsl] ERROR in /cocalc/src/smc-webapp/launch/share.ts(59,53)
TS1055: Type 'void' is not a valid async function return type in ES5/ES3 because it does not refer to a Promise-compatible constructor value.
ERROR in /cocalc/src/smc-webapp/launch/share.ts
./smc-webapp/launch/share.ts
[tsl] ERROR in /cocalc/src/smc-webapp/launch/share.ts(154,63)
TS1055: Type 'Relationship' is not a valid async function return type in ES5/ES3 because it does not refer to a …
```

add Promise to return types for 2 functions in src/smc-webapp/launch/share.ts

---

src/smc-webapp/history.coffee
src/smc-webapp/misc/query-params.ts

This fixes `fullscreen=kiosk` in a cc-in-cc dev project for me. I'm not sure about the other issue I found, where `params` in the history file would delete `fullscreen`. I think it is ok to delete params which aren't in the page store – but then the comment must be fixed. It's also a chicken-egg problem.
All I tested was a URL like `https://cocalc.com/xxxx/port/56754/projects/xxxxx/files/foo.md?fullscreen=kiosk&session=`
Front end:

fix fullscreen=kiosk and a potential problem with history params

---

src/smc_sagews/smc_sagews/sage_server.py

in 8.9 (py2) `print "foo"` should work, not `print("foo")`
building new project on "test" now
Front end:

sagews: make print "foo" work in sage 8.9

---

src/smc-webapp/app-framework/TypedMap.ts
src/smc-webapp/project/explorer/explorer.tsx
src/smc-webapp/project/explorer/file-listing/file-listing.tsx
src/smc-webapp/project/explorer/file-listing/listing-header.tsx
src/smc-webapp/project_actions.ts
src/smc-webapp/project_store.ts

Fixes #4326
Also makes it so that `displayed_listing` is correctly recomputed only when its args are changed.
1. Change the file sort in a project
1. Change the default file sort in account settings
1. Open a new project, the sort should be that default
1. The project from step 1 should have the same sorting
1. In the browser console, run `smc.redux.getProjectStore(project_id).selectors.stripped_public_paths.fn.recomputations();` with `project_id` appropriately filled in.
1. Select some files
1. Run the same code above. The result should not have increased.
1. Toggle displaying masked files, that should work
1. Filter by searching. That should work too.
1. Recomputations should have increased.
Front end:

Fix active file sort and `displayed_listing`

---

src/smc-util/db-schema/site-defaults.ts
src/smc-webapp/customize.tsx
src/smc-webapp/project/settings/body.tsx
src/smc-webapp/project/settings/project-control.tsx

* diversify kucalc setting to include an on-prem kubernetes mode
*  add an ssh gateway setting (not used yet )
well, there is no actual change and hence there is no visible impact. kucalc ui set to 'yes' or 'no' shows/hides the quota upgrades
Front end:

additional site settings

---

src/smc-hub/email.ts
src/smc-hub/package-lock.json
src/smc-hub/package.json
src/smc-hub/test/email.js

this is a modernization of sending emails and fixing #4345. the main difference is that this is more "low level" and therefore we can do everything the V3 api is talking about. the callback has a more rich response, which is discarded. in the future, it might be a good extension to check what's actually coming back from the service. I also added a silly small test file, which helped me with development.
in my cc-in-cc project, I created an account for an invite email, invited myself, added a new student, and did a fake password reset. in all cases I got one email.
Front end:

hub/email: update sendgrid api to v3 and stop using helpers

---

src/smc-webapp/frame-editors/rmd-editor/actions.ts
src/smc-webapp/frame-editors/rmd-editor/editor.ts
src/smc-webapp/frame-editors/rmd-editor/rmd-converter.ts
src/smc-webapp/frame-editors/rmd-editor/utils.ts
src/smc-webapp/project_store.ts

* rmd processing replaces spaces with dashes in the filename (I think this is for pandoc) --  see #4351
* I also took the opportunity to clean up `project_store::_compute_file_masks` because I was very confused about what's going on there
* filemasks should still work, obviously
* an rmd file with a crazy name like `x   Y Ö_-{[]}.rmd` has a visible html or pdf preview
* well, for that name, PDF fails due to an latex error ... a less crazy one like `x   Y x.rmd` does work, though
#4351 
Front end:

webapp/rmd: fix file mangling

---

src/smc-util/message.js

Add item to API docs about starting projects when `project_exec` is called.
- tested build of cc-in-cc to make sure it starts up
- committed the generated "api.json" file to cocalc-doc
1.
1.
1.
Front end:

add to project_exec doc

---

src/smc-util/theme.js
src/smc-webapp/info/links.tsx
src/smc-webapp/projects.cjsx
src/smc-webapp/side_chat.cjsx
src/smc-webapp/smc_chat.tsx
src/smc-webapp/support.cjsx

tested to work on: help dialog, about page, files listing and side chat. any misses?
Front end:

 make the discord link configurable and let it to point to the main room

---

src/smc-webapp/frame-editors/rmd-editor/rmd-converter.ts

This just changes the Rmd compile timeout to the same 4 minutes as we have for Latex.
1.
1.
1.
Front end:

webapp/rmd: increase timeout to 4 minutes

---

src/smc-webapp/jupyter/actions.ts
src/smc-webapp/jupyter/store.ts

this in combination with a change for the next software update will hide the gap kernel in the cocalc notebook. which means you have to use the classical one to use it.
1.
1.
1.
Front end:

filter disabled jupyter kernels

---

src/smc-webapp/account_page.cjsx
src/smc-webapp/r_account.cjsx

* problem:  select a tab != preferences in account and even when you tab back and forth to a project, you still have to know that in order to reach the sign out button you have to click on preferences first
* solution: move it up, to the row where the tabs are.
sign out works just like before, not much of a surprise 
Front end:

move SignOut on top to be always accessible

---

src/webapp-lib/app-startup-style.css
src/webapp-lib/app.pug

Currently, the red error message doesn't suggest refreshing the browser strongly enough. This tweaks this a little bit. Also, it fixes the link to point to the actual doc page and some CSS.
With that, it looks like this
1.
1.
1.
Front end:

app page: tweak error message and fix some CSS

---

src/smc-webapp/project/explorer/action-box.tsx
src/smc-webapp/project/history/log-entry.tsx
src/smc-webapp/project/history/types.ts
src/smc-webapp/project_actions.ts

the core bug is showing `event.files[0]` where files is actually a string. 
1. download one or more files, before testing this
2. switch to this, the entries should show up
3. do a single/multiple file download and this time, instead of the zip file name for multiple files, the files itself show up.
Front end:

webapp/project log: fix impendance between recording and showing downloaded files

---

src/smc-webapp/sagews/output.tsx

simple reason: we know this can happen:
```
TypeError: Cannot read property 'length' of undefined
at CellOutput.render_raw_input (/cocalc/src/smc-webapp/sagews/output.tsx:136:1)
at CellOutput.render_output_mesg (/cocalc/src/smc-webapp/sagews/output.tsx:156:8)
at CellOutput.render_output (/cocalc/src/smc-webapp/sagews/output.tsx:163:20)
at CellOutput.render (/cocalc/src/smc-webapp/sagews/output.tsx:177:11) ...
```
I don't know how to trigger it, but the hub starts...
Front end:

share/sagews: sanitize "value" in raw input

---

src/smc-webapp/jupyter/output-messages/traceback.tsx

share server bug says: 
`TypeError: this.props.message.get(...).forEach is not a function at Traceback.render (/cocalc/src/smc-webapp/jupyter/output-messages/traceback.tsx:53:5) at ...`
`message.tsx` is already checking `message.get("traceback") != null`
I don't know what it got, but this change deals with a string and uses the iterator protocol for arrays and immutable js "forEach" objects. I think this should help. 
1. in a normal juypter notebook, I made `raise Exception("test")` and the traceback shows up. 
2. I shared that file in my cc-in-cc project and indeed, the stacktrace shows up.
Front end:

jupyter/traceback: make traceback processing more robust 

---

src/smc-util/db-schema/db-schema.ts
src/smc-util/db-schema/types.ts

As described internally, there are crashes like
```
TypeError: cb is not a function
at Object.instead_of_query (/cocalc/src/smc-util/db-schema/db-schema.ts:179:11)
at async.series (/cocalc/src/smc-hub/postgres-user-queries.js:2347:32)
at /cocalc/src/smc-hub/node_modules/async/lib/async.js:718:13
at Immediate.iterate (/cocalc/src/smc-hub/node_modules/async/lib/async.js:262:13)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
```
which I can trace back to `f3bb7ab2f9` which seems to trigger this as a side effect of that change. I don't know the overall reasoning behind this, needs a check. 
I also added more typing info for the callbacks, which seems to be a good idea.
* hub and static compiles and runs without errors … that's all I …

inconsistent use of "instead_of_change"

---

src/smc-hub/email.ts

below a reported stacktrace from a  hub, which can happen if we want to welcome someone but there is no email address
```
TypeError: Cannot read property 'indexOf' of undefined at exports.is_banned (/cocalc/src/smc-hub/email.ts:147:21) 
at Object.exports.send_email (/cocalc/src/smc-hub/email.ts:185:7) 
at Object.exports.welcome_email (/cocalc/src/smc-hub/email.ts:546:11) 
at async.waterfall (/cocalc/src/smc-hub/auth.js:961:22) 
[...]
```
1.
1.
1.
Front end:

hub/email: users might sign up but still have no email address

---

src/smc-webapp/frame-editors/latex-editor/actions.ts

problem: see #4394 …  additional files in the local dir don't work with using a temp dir
solution with this patch: if sagetex or pythontex are run, the output dir will be removed from the command and saved. if it detects this for the first time, it runs latex again, in the local dir, such that these aux files exist. 
1. start with a plain tex file
1. add `\usepackage{pythontex}` and also something like `1+1 = \py{1+1}`
1. upon building again, it will remove the output dir from the build command and run latex again
* I don't know why, but it doesn't always work. in any case, with the next build after a change  – or force build –  it works fine. 
I used this to check if the build dir is really the local one
```
\begin{pyconsole}
import os, sys
print(os.path.abspath('.'))
\end{pyconsole}
``` …

webapp/latex: do not set output-dir for pythontex or sagetex -- #4394

---

src/smc-webapp/frame-editors/rmd-editor/utils.ts

simple fix to the preview of an rmd file
see https://github.com/sagemathinc/cocalc/issues/4405
edit `foo bar/foo baz.rmd` and also make sure the aux files are masked in the files listing
Front end:

webapp/rmd: do not mangle dirname of rmd preview file

---

src/smc-hub/postgres-server-queries.coffee
src/smc-util/db-schema/central-log.ts
src/smc-util/db-schema/db-schema.ts

this is quite straight forward. I didn't test it, though. 
I'm guessing the only real way to test this is to deploy it in "test" and keep it running for a while. then check the DB.
Front end:

hub: add "expire" cols to tables collecting errors

---

src/smc-webapp/project_actions.ts

see #4428
instead of adding a second case (searching for ":"), I added the prefix for all paths. That shouldn't hurt.
1. tried it in my dev project server, ok
1. that's  the message being sent via the websocket: `... "data":{"cmd":"exec","opts":{"path":".","command":"rsync","args":["-rltgoDxH","./colon: path/file name.md","./colon: path/file name-3.md"],"timeout":120,"bash":false,"err_on_exit":true}}}`
1. the project log entries are also ok
Front end:

webapp/copy files: prefix all names with ./

---

src/smc-util/db-schema/site-settings-extras.ts

as requested, stripe publishable key not a password
1.
1.
1.
Front end:

webapp/admin/site settings: reveal stripe publishable key

---

src/smc-util/db-schema/site-defaults.ts

this is a tiny amendment for the landing pages: for the commercial cocalc.com setup, it allows to set the google analytics token. that's all. it's already used (I set it directly in the DB) in production. (if you wonder about other usages to set the token, there could be some but that's part of this)
1.
1.
1.
Front end:

site-settings: add GA token for cocalc.com only

---

src/smc-webapp/r_misc/uncommited-changes.tsx

see #4434
my firefox before
my firefox after
chrome, with this patch, as a reference
for testing, I flipped this `show_error` boolean around to let it always show
Front end:

webapp: fixing firefox display of uncommitted saving warning

---

src/smc-webapp/frame-editors/latex-editor/actions.ts
src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
src/smc-webapp/frame-editors/latex-editor/pythontex.ts
src/smc-webapp/frame-editors/latex-editor/sagetex.ts

Fixes  #4443 and makes a key for react unique
1. I enabled pythontex and put e.g. `\py{ 2 3 }` in a line. That triggered an error to show up and clicking on the little link, it jumped to the correct line.
Front end:

Fix pythontex errorpath

---

src/smc-project/sync/listings.ts
src/smc-project/sync/path-watcher.ts

well, two motivations
1. see if this has an impact on overall load, when there are many projects running
2. the cool thing here is that you should try "touch x" in the mini console. after I hit return there is no longer a 1 sec delay refreshing the listing :running_man: 
project restarted, listings update, ... the change is really small
Front end:

listings: debonuce harder, but also fire a change when  it happens

---

src/smc-webapp/course/handouts/handouts-panel.tsx

this is a pretty straight forward fix for #4490
1. it issued `rsync --delete ...` in my cc-in-cc dev project: `2020-04-02T14:13:33.918Z - debug: stdout='{} ', stderr='Project(project_id=bc6f81b3-25ad-4d58-ae4a-65649fae4fa5).cmd(...): rsync --delete -zaxs  [...] `
Front end:

course/handout: set overwrite to true when it should do so 

---

src/webpack.config.js

I made this change, which undoes something with ts-loader config, but I don't really know what I should look for. Is it the turnaround time of making a change until webpack finished?
Front end:

webpack: undo change to ts-loader config

---

src/smc-hub/email.ts

this should fix issue #4486
if the organization name + organization email address is set, this makes the hub use it
* set these settings to a recognizable value, then send an email verification to youself.
Front end:

respect orga name + email when sending welcome/verify emails

---

src/smc-hub/kucalc/quota.ts
src/smc-hub/test/kucalc/quota.coffee

* this catches a case where modified admin settings "override" instead of "add" to other upgrades
there is an additional test to check this
Front end:

hub/quota: slightly tweak the algorithm

---

src/smc-webapp/codemirror/modes.coffee
src/smc-webapp/file-associations.ts

saturday fun (cblc will be in the next software update)
Front end:

highlight fixed formatted cobol files

---

src/smc-util/db-schema/site-defaults.ts
src/smc-webapp/landing-page/sign-up.tsx
src/smc-webapp/landing_page.cjsx

There was an inconsistency between the sign-on logic and the theming variables – basically a missing "or"-clause. This changes it so, that if there is a ToS url, it is used primarily and a boilerplate text is show in the sign up dialog. As currently used, it is possible to replace that text with a customized version.
1.
1.
1.
Front end:

fix ToS url as a fallback to the ToS phrase

---

src/smc-hub/password.coffee

a rather trivial case, where the hardcoded dns is used but it should be the one from the server config (if it is more than an empty string)
* I didn't test it yet
Front end:

fix DNS for "normal" password reset emails

---

src/smc-webapp/share/extensions.ts
src/smc-webapp/share/file-contents.tsx

* right now, shared Rmd files don't show up on the share server at all
* with that, they're treated like markdown. that's not ideal, but better than not at all.
1.
1.
1.
Front end:

share: render Rmd files like markdown 

---

src/smc-webapp/_misc_page.sass
src/smc-webapp/client/idle.ts

either show the white default logo, or the square or square+rectangular one
1.
1.
1.
Front end:

idle banner: show customized logos or the default

---

src/smc-webapp/project/settings/about-box.tsx
src/smc-webapp/project/settings/body.tsx

* project settings: rename title box to "about"
* show when the project was created
1.
1.
1.
Front end:

project settings: show when project was created

---

src/smc-webapp/project/utils.ts

Instead of running year month and day together, this keeps the dashes. easier to read and sort-compatible with "current time"
1.
1.
1.
Front end:

new automatic filenames with dashes for year-month-day

---

src/smc-webapp/frame-editors/latex-editor/pdfjs-doc-cache.ts
src/smc-webapp/frame-editors/latex-editor/util.ts

simple fix for #4562
1.
1.
1.
Front end:

webapp/pdf viewer:  fix upperase extensions 

---

src/smc-webapp/client/welcome-file.ts

* `?anonymous=octave` does this:
1. not much to test except for that url change. any other mode isn't touched...
Front end:

anonymous welcome file for octave

---

src/smc-project/gitconfig.ts
src/smc-project/local_hub.coffee

This is pure convenience. With this, temporary cocalc, latex and python files are ignored in Git. No existing config will be harmed nor will user changes be overwritten.
* in cc-in-cc, the home directory is your actual project. should be ok for production
* what's probably nice to test is editing a jupyter file in a fresh git dir and then no aux files show up in the status
Front end:

project/git: ignore aux files by default

---

src/smc-hub/open-cocalc-server.ts
src/smc-util/db-schema/site-defaults.ts
src/webapp-lib/_inc_analytics.pug
src/webpack.config.js

addresses #4584 
add a "commercial" env variable for the templates and introduce it in webpack and the open cocalc server
1.
1.
1.
Front end:

only query analytics.js in a commerical setup

---

src/smc-hub/postgres-server-queries.coffee
src/smc-hub/utils.ts

so, with that, if `pii_retention` isn't set, it results in `false` as a boolean. :champagne: 
1.
1.
1.
Front end:

hub/server queries: process all default values as well

---

src/smc-hub/auth.ts
src/smc-hub/package-lock.json
src/smc-hub/package.json

so ,this fixes twitter, and it also sets up everything to get the email address out of facebook and twitter. twitter doesn't work, though, because we need new credentials. I didn't want to mess around with this.
1.
1.
1.
Front end:

hub/auth: wrapping twitter, email for facebook and twitter

---

src/smc-webapp/project/explorer/path-navigator.tsx
src/smc-webapp/project_actions.ts

this is a simple fix to not forget the nav history when going back to "home" and well, the depth calculation must be tweaked a little bit to avoid an off-by-one error.
navigate 2 or 3 dirs deep, switch between files and check how the path looks, also switch between files in paths that are not in a parent/child relationship.
Front end:

webapp/breadcrumb nav: don't forget history when going back home

---

src/smc-webapp/file-associations.ts

webapp: fix xsl syntax highlighting -- fixes #4613

---

src/smc-webapp/frame-editors/latex-editor/actions.ts
src/smc-webapp/frame-editors/latex-editor/latex-log-parser.ts
src/smc-webapp/frame-editors/latex-editor/latexmk.ts

this uses latexmk to detect all the files making up the project. this is more robust than reading the log. e.g. there is a large example (internally only) which breaks somewhere and only some files show up. this is negative side effects regarding saving and building the project.
* for multifile documents, all filename show up in the dropdown list.
* an important case are existing documents. for that,
*  I did first go back to `master` → reload page → select build command → no `-deps` → closed tex file
*  then I checked the `.*.syncdb` file that it is saved (as an array)
* checked out this branch  → build → reload page
*  opened the tex file and then it inserted `-deps`. saving the file, I confirmed it also changed the syncdb file. (this didn't work the first time around, not sure why)
* …

webapp/latex: make detecting of multifiles more robust 

---

src/smc-webapp/compute_environment.cjsx
src/smc-webapp/info/info.tsx

This fixes the width of the executables table, uses Row/Col of that antd wrapper, and somehow closing the info box was broken.
1.
1.
1.
Front end:

software table: fix excessive width and closing of info box

---

src/smc-project/configuration.ts
src/smc-util/code-formatter.ts
src/smc-webapp/file-associations.ts

add support for `.ptx` files as xml and fix detecting tidy for xml and html syntax
1. xml, html, ptx, ... the format button shows up and calls tidy accordingly
#4632
Front end:

Ptx xml 4632

---

src/smc-hub/email.ts
src/smc-util/db-schema/site-settings-extras.ts

The analog of what password resets are doing for verification token emails. Also some cosmetics for the admin dialog.
well, there is only one aspect to test. if the secondary email interface is set to smtp and setup fine, then for example after changing ones email address, the verification email is sent from that secondary email interface.
Front end:

hub/email: use secondary smtp server for verification emails 

---

.gitignore

ignore `tsconfig.tsbuildinfo` which started to show up for me. maybe the speedier incremental builds are finally starting to work?
1.
1.
1.
Front end:

ignore tsconfig.tsbuildinfo

---

src/smc-hub/compute-client.coffee
src/smc-hub/compute-server.coffee
src/smc-hub/postgres-base.coffee
src/smc-hub/postgres-server-queries.coffee
src/smc-project/local_hub.coffee
src/smc-util/db-schema/projects.ts
src/smc_pyutil/smc_pyutil/smc_compute.py

This is pure backend behind-the-scenes code. All it does is to inject a `{string:string}` map from the database for a specific project into the local hub. It's done in a way that the project itself is not affected (will always start, nothing funny will happen) while all spawned processes will have these env vars. What's obviously missing is some UI to set that field in the DB…
1. base case is clear: if nothing is set, projects still behave as usual
2. the fun starts once something like that is in the database:
```
update projects set env = '{"FOO": "THIS IS A TEST", "BAR": "123"}'::JSONB where project_id ='[project id]';
```
for my `cc-in-cc` project it works:
```
~$ echo $FOO 
THIS IS A TEST
```
because there is a special function `dev_env` in `smc_compute.py` passing it on. A similar …

project: support custom environment vars

---

src/smc-webapp/account/actions.ts
src/smc-webapp/app_shared.cjsx
src/smc-webapp/chat/chat-indicator.tsx
src/smc-webapp/chat/side-chat.tsx
src/smc-webapp/chat/video/launch-button.tsx
src/smc-webapp/editor.coffee
src/smc-webapp/file-use/info.tsx
src/smc-webapp/file-use/viewer.tsx
src/smc-webapp/jupyter/top-menubar.tsx
src/smc-webapp/launch/custom-image.ts
src/smc-webapp/misc_page.coffee
src/smc-webapp/project/explorer/action-bar.tsx
src/smc-webapp/project/explorer/action-box.tsx
src/smc-webapp/project/explorer/file-listing/file-row.tsx
src/smc-webapp/project/explorer/file-listing/no-files.tsx
src/smc-webapp/project/explorer/mini-terminal.tsx
src/smc-webapp/project/explorer/misc-side-buttons.tsx
src/smc-webapp/project/explorer/new-button.tsx
src/smc-webapp/project/explorer/search-bar.tsx
src/smc-webapp/project/file-tab.cjsx
src/smc-webapp/project/settings/body.tsx
src/smc-webapp/project/settings/hide-delete-box.tsx
src/smc-webapp/project/settings/project-control.tsx
src/smc-webapp/project/settings/ssh.tsx
src/smc-webapp/projects/create-project.tsx
src/smc-webapp/projects/hashtags.tsx
src/smc-webapp/projects/project-row.tsx
src/smc-webapp/projects/projects-filter-buttons.tsx
src/smc-webapp/tracker/index.ts

related to #4661 ... getting rid of analytics event, renaming it/noop. once we have a clear plan and a specific use case, we will revisit this.
1.
1.
1.
Front end:

mostly get rid of  analytics_event 

---

src/smc-webapp/billing/actions.ts

* this is #4583
* the whole point is that there is a call to update customers in `project/explorer/explorer.tsx` … this just disables this method if there is no commercial stripe setup
too late & too tired to test this now, but I'm pretty confident this should do it
#4583
Front end:

don't attempt to init stripe in commercial==no setting

---

src/smc-hub/scripts/compute

due to this the  Dockerfile.gpu  build doesnot start properly. in the tensorflow the default python is 3.x
1.
1.
1.
Front end:

moving to python 3.x print

---

src/smc-webapp/project_store.ts

webapp/files: mask __pycache__ dirs

---

src/smc-webapp/frame-editors/html-editor/iframe-html.tsx

* fix +/- zoom in iframe viewer. it uses IE's "zoom" which is nonstandard. [reference](https://caniuse.com/#feat=css-zoom)  and see  #4438
* respect the default font size. there was a hardcoded number 16, which makes no sense. i.e. the first time you click + or -, it should be more or less based on your default font size -- not 16.
all I did was to make rmd file and +/- zoon in the iframe html viewer
#4438
Front end:

html viewer fix +/- zoom button

---

src/smc-webapp/account/account-page.tsx

this fixes the problem in #4597 but at the same time it's not much better. well, this probably needs another iteration after this one here.
1.
1.
1.
Front end:

 move signout button into the row of tabs

---

src/smc-webapp/crash.html
src/smc-webapp/index.sass
src/smc-webapp/last.coffee
src/webapp-lib/app-init.ts
src/webapp-lib/app-startup-style.css
src/webapp-lib/app.pug

* this shows loading crashes to the user, which should help us to figure out what's going on quicker
*  typescripts app-init
* also show stacktraces in react crash box
* part of #3852
* if there is no error, everything works as usual. even if there are errors, the user will not see it anyways.
* to trigger it, here is what I did: I inserted `throw new Error("BANG")` either
*  in the body of `app/notification-bell.tsx` (i.e. not inside a function or anything else)
* or into the react render function.
in the first case  it crashes during startup and in the second case when react is already started. screenshots below are for case 1 and 2
#3852
Front end:

show stacktraces to users

---

src/smc-project/browser-websocket/canonical-path.ts
src/smc-webapp/frame-editors/latex-editor/actions.ts
src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
src/smc-webapp/frame-editors/latex-editor/gutters.tsx
src/smc-webapp/frame-editors/latex-editor/latex-log-parser.ts

* normalize paths for canonical lookup, in particular`./foo.tex` → `foo.tex` – otherwise there is nothing to look up in the dictionary
* processing error logs after sagetex, knitr or pythontex **replaces** the errors to display in the gutter. now, they're merge instead
* deduplicating the second latex build shouldn't use the same key for pythontex and sagetex
* modernize this errors + warnings panel. also, prioritize errors on top of all others. otherwise, for example sagetex or pythontex errors are burried below less important notices that there are no latex errors or typesetting issues
* regarding knitr, I hoped errors would also show up in the gutter (the error has the correct filename and line number) but it's too confusing for me to figure out what's going on. certainly, the …

various latex error processing improvements

---

src/smc-util/theme.js
src/smc-webapp/frame-editors/markdown-editor/actions.ts
src/smc-webapp/frame-editors/rmd-editor/actions.ts
src/smc-webapp/frame-editors/rmd-editor/build-log.tsx
src/smc-webapp/frame-editors/rmd-editor/editor.ts
src/smc-webapp/frame-editors/rmd-editor/rmd-converter.ts

* build button
* make it so clicking the build button always rebuilds
* make the refresh button of the iframe work
* save the file itself
* show build log and (if it exists) show the error log
* rebuild if content changes, see #3188 ... although, no idea if this is a good way to do this. is there a documentation for this syncstring attribute?
* my test document just had a bit of text and couple of cells like
```{r}
rnorm(4)
```
* To trigger a problem, I changed it to e.g. `rnorm(5+5+)`
#4578
#3188
Front end:

improve rmd build 

---

src/smc-webapp/frame-editors/code-editor/actions.ts
src/smc-webapp/frame-editors/frame-tree/save-button.tsx
src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
src/smc-webapp/r_misc/uncommited-changes.tsx

* this started by fixing #4434, but then I looked into this "react-logic" behind it and did some tests. so, I don't like how this is done at all.
* I ended up lifting up the state of showing the uncommitted information to the store. otherwise it resets each time one switches frames.
* I tested this by having two frames in a textfile, stopped my dev hub, and then tried to save a change. error shows up, and resolves once I start my dev hub again.
* The button also appears in chat, so, same there. Chat has no changes, because it is backwards compatible.
#4434
Front end:

tweak save button

---

src/smc-webapp/editor-data/generic.tsx
src/smc-webapp/project_actions.ts

this is #4660 + some general cleanup/modernization
Front end:

webapp/generic: do not open docx automatically

---

src/webapp-lib/app-init.ts
src/webapp-lib/app.pug

it might be the case that #4247 is already fixed ... in any case, this sets the title of the initial landing page to name/description.
1.
1.
1.
Front end:

app landing page: make sure a title is set 

---

src/smc-util/db-schema/site-defaults.ts
src/smc-util/db-schema/site-settings-extras.ts

1. domain setting is important, move it to the top and show unconditionally, and add a quick validation for immediate feedback
2. see #4662
no fundamental change in functionality
Front end:

admin/site-settings: domain on top and hide email settings if disabled

---

src/smc-webapp/jupyter/nbgrader/actions.ts

I tried to address #4696 but I have no idea what's really going on. 
* I'm 100% sure the while loop in line 158 never stops, that's what debugging shows clearly
* The remainder is a problem with closing the file and opening it again. E.g. it just hangs at `await once(actions.jupyter_actions.syncdb, "ready");` indefinitiely.
* fresh: students dir + file does NOT exist → new notebook should appear
* update: it exists → notebook should get modified cells.
With the fix below it almost works, but updating the notebook seems to be flaky. E.g. I get errors about cells being unmodifiable. However, running it twice seems to work. So, maybe a step towards fixing this, but this change here is not enough.
Front end:

webapp/jupyter/nbgrader: fix broken assignment  

---

src/smc-webapp/account/account-page.tsx
src/smc-webapp/antd-bootstrap.tsx

typical sunday evening fix
narrow:
wide
1.
1.
1.
Front end:

webapp/accounts: sign out button, 3rd (?) iteration

---

src/smc-webapp/frame-editors/rst-editor/actions.ts

The rst editor has a reload button for the code and also for the iframe view. Both aren't doing anything. This adds some code for this.
click the buttons, they should do something
Front end:

webapp/rst: fix inactive reload buttons

---

src/smc-hub/open-cocalc-server.ts
src/smc-hub/postgres/types.ts
src/smc-hub/server-settings.ts

well, where there is new code there are new bugs. this migrates from using account_creation_token to have_active_registration_tokens to determine if anon login is allowed.
1.
1.
1.
Front end:

use registration table to determine anon login

---

src/package-lock.json
src/package.json
src/smc-webapp/package-lock.json
src/smc-webapp/package.json
src/webapp-lib/resources/package-lock.json
src/webapp-lib/resources/package.json

This updates katex to 0.12.0. 
tested [two new commands](https://github.com/KaTeX/KaTeX/releases/tag/v0.12.0)
Front end:

katex 0.12.0

---

src/smc-webapp/frame-editors/latex-editor/latex-log-parser.ts

Just a small change.
a multifile doc in my dev project shows up the documents and builds fine
Front end:

latexmk in ubuntu 20.04 has a slightly different output

---

src/smc-webapp/frame-editors/x11-editor/xpra-server.ts

problem: xsel does hang when copying a buffer out of an X11 window
log:
```
2020-08-04T14:26:29.221Z - debug: primus-api request object {"cmd":"exec","opts":{"path":"","command":"xsel","args":[],"timeout":5,"bash":false,"err_on_exit":true,"env":{"DISPLAY":":1485505426"}}}
2020-08-04T14:26:29.222Z - debug: execute_code: "xsel "
2020-08-04T14:26:29.222Z - debug: Spawning the command xsel with given args  and timeout of 5s...
2020-08-04T14:26:29.296Z - debug: Listen for stdout, stderr and exit events.
2020-08-04T14:26:33.058Z - debug: Client.handle_mesg({"event":"heartbeat"}): no callback
2020-08-04T14:26:33.058Z - debug: received heartbeat on socket '80d2dfc7-d21f-4032-84ab-ae7313b6f647'
2020-08-04T14:26:33.122Z - debug: Client.active_socket(id=80d2dfc7-d21f-4032-84ab-ae7313b6f647,ip='127.0. …
```

x11: fix "xsel" hanging in 20.04

---

src/smc-webapp/frame-editors/x11-editor/xpra-server.ts
src/smc_pyutil/smc_pyutil/smc_compute.py

this makes smc_compute fit for running a cc-in-cc dev proj in ubuntu 20.04
well, I ran this hashlib + encoding('utf8') line in the older python3 and python2 interpreters. works fine everywhere.
Front end:

pyutil fix a python 3.8 incompatibility

---

src/smc-webapp/account/actions.ts
src/smc-webapp/account/init.ts
src/smc-webapp/client/password-reset.ts
src/smc-webapp/landing-page/forgot-password.tsx
src/smc-webapp/landing-page/landing-page.tsx
src/smc-webapp/landing-page/reset-password.tsx

* change forgot and reset modals to be functional components
* forgot password: disable the send button once it is sent
* reset password: there were some strange inconsistencies
* progress spinners while something is happening
* move setting the reset key out of react into the account initialization. this is particularly weird, because the key was set in a function while the global redux prop wasn't used. well, at least I'm confused about what's going on and I moved things a bit around
* prepare the password reset key to use a cookie instead of the query param
1. enter email, request email with a token
2. enter a password with 3 letters only → error
3. and with a longer password, it sets it fine
Front end:

password reset tweak

---

src/smc-webapp/jupyter/browser-actions.ts

this is a simple idea to fix #4816
but I don't know what this actually does and I wonder if there are also other usages of `this.syncdb` should be safeguarded …
1.
1.
1.
Front end:

webapp/jupyter/nbconvert: fix #4816

---

src/smc-hub/postgres-server-queries.coffee
src/smc-hub/postgres/stats.ts
src/smc-util/db-schema/stats.ts
src/smc-webapp/info/usage.tsx

* typescript stats calculation (half way done right now)
* add info about running projects (by type)
* ~~maybe other info that could be relevant for the frontend~~
* showing the total number in the UI (the screenshot is also from "test")
* dev project works, as far as I can tell
* deploying in "test" as `2020-08-27-134213-stats-projects` (hub) and `2020-08-27-145939-stats-projects` (static)
Front end:

hub/stats: running projects and more info

---

src/smc-webapp/course/configuration/actions.ts
src/smc-webapp/course/configuration/configuration-panel.tsx
src/smc-webapp/course/configuration/student-project-software-environment.tsx
src/smc-webapp/course/sync.ts
src/smc-webapp/course/types.ts

probem: changing the compute image of a course project, while student projects are already configured. by default, it should eventually be in sync.
1.
1.
1.
Front end:

webapp/course: inherit teacher project compute  image or be explicitly

---

src/smc-webapp/project/page/software-env-upgrade.tsx

well, like it says, with this there is an "x" to hide it and the dismiss button actually says to "keep" it. no other extras.
1.
1.
1.
Front end:

webapp/project: just hide software upgrade banner

---

src/smc-webapp/custom-software/init.ts

I was testing embedding cocalc. I noticed that when all projects should close, an exception appears. It's somehow happening with those react store hooks and the project listing. I don't know how to really fix this, and well, since this might happen elsewhere as well, I enabled pulling in the compute image data for the embedded mode. (or is there a way to say that a certain store might not always exist?)
The call triggering this below is `page_actions.close_project_tab(project_id);` for the last open project.
1.
1.
1.
Front end:

webapp: loading compute_images in minimal mode 

---

src/smc-project/configuration.ts
src/smc-webapp/project/settings/project-capabilites.tsx
src/smc-webapp/project_configuration.ts
src/smc_pyutil/smc_pyutil/ipynb_to_pdf.py

* this adds a field to the main project capabilities regarding converting html2pdf via chrome/chromium
* it's not doing anything beyond that, that's for another PR
* if the project is still an old one and no data is available, it defaults to "true"
* this is intended to be released as static first, and then later on the project (no rush)

project capabilities: check if html2pdf via chrome/chromium is available

---

src/smc-hub/hub_http_server.coffee
src/smc-webapp/customize.tsx

well, this doesn't do much by itself: I can run `cc.redux.getStore("customize").get("country")` to learn I'm in `AT`

expose country info in client site configuration

---

src/smc-project/sync/server.ts

I'm building this now, and if it works I'll deploy it. If you have a better fix for this, it should be a follow up…

project: remove a use of this.log after closing

---

src/smc-webapp/jupyter/nbgrader/cell-types.ts

add nbgrader code snippet templates for octave -- see #4857
webapp only
probably someone with some octave knowledge should check this, but well, at least the tests pass/fail in a meaningful way …

nbgrader: octave templates

---

src/package-lock.json
src/package.json
src/smc-hub/package-lock.json
src/smc-hub/package.json
src/smc-project/jupyter/package-lock.json
src/smc-project/package-lock.json
src/smc-project/package.json
src/smc-util-node/package-lock.json
src/smc-util-node/package.json
src/smc-util/code-formatter.ts
src/smc-util/package-lock.json
src/smc-util/package.json
src/smc-webapp/package-lock.json
src/smc-webapp/package.json
src/smc-webapp/project_configuration.ts
src/test/puppeteer/package-lock.json
src/test/puppeteer/package.json

update prettier (to keep it in sync with the system wide install) and fix postcss/css renaming. on top of that, some slight audit fixes, seems to be just mocha...
tested:
- css → needs a rename (hence a webapp update)
- ts, tsx → ok
- yaml → ok
- js → ok
- json → ok
deployment: merging this has no cross dependencies. to make css formatting work again, webapp must be updated

npm: updating prettier + audit fixes

---

src/smc-util/db-schema/site-defaults.ts

This adds a setting to specify restricted countries. E.g. for `AT IN` we now can do `cc.redux.getStore("customize").get("nonfree_countries").toJS()` → `["AT", "IN"]`
This will also be used by the landing pages.

add site setting to configure restricted countries

---

src/smc_pyutil/smc_pyutil/smc_compute.py

Workaround for stop/start project issue  described in https://github.com/sagemathinc/cocalc-docker/issues/97
This probably not compatible with python 2 if this still matters.
With this change project can be correctly stopped and strarted using current cocalc in docker.

fix issue with stop/start project sagemathinc/cocalc-docker#97

---

src/smc-util/upgrade-spec.js

I think we should update the pricing timestamp? Or is it left like that intentionally?

update pricing spec date

---

src/smc-webapp/course/student-projects/actions.ts

* see #4875
ok, I'm not sure about this. there must be somewhere some code that removes a license from a project if the student is deleted, but I don't know where. I also saw in a real course that a deleted student project had a license. So, I don't know, maybe this here helps as an additional safeguard or it makes things even worse.

course: remove license if student is deleted

---

src/smc-webapp/frame-editors/lean-editor/actions.ts

See #4893
I also changed the ordering of close calls: i.e. first set the field in the parent + close there, then the derived child. The other way around some attributes get deleted before the `_state` is changed.
well, maybe changing that ordering isn't a good idea. or not, IDK.  I'm confused. in both cases I get an exception upon closing:
```
Uncaught (in promise) TypeError: Cannot read property 'close' of undefined
at Actions.close (actions.ts?47df:500)
at Actions.close (actions.ts?81f3:179)
at Object.remove (register.ts?99e9:85)
```
The above is strange: tries to close any terminals via `this.terminals.close();` but I don't see how that terminal manager got removed. It shouldn't be removed before it cleaned up any terminals, right?

webapp/lean: safeguard debounced calls -- addresses some of #4893

---

src/smc-project/jupyter/jupyter.ts

well, while working on that project info, I'm also adding TS types here and there. When I do that for the known jupyter kernel instances, this popped out. I'm sure this is a typo, but please check if this is maybe not so good (so far, that `if` was always false)
the only thing I tested is that I can start/halt a kernel.

project/jupyter:  rename _identity to identity

---

src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
src/smc-webapp/project/explorer/file-listing/listing-header.tsx
src/smc-webapp/r_misc/icon.tsx

This makes the Icon a functional component  and enhances it to show unicode chars as icons as well. Here is chrome and firefox:
deployment: webapp only

clean button a unicode skull and change Icon to be a FC

---

src/smc-util/compute-images.ts

This is just yet another entry.

compute images: add a pointer to the previous ubunut 20.04 image

---

src/smc-hub/postgres-blobs.coffee

this query takes about `query_time_ms=5456`, despite indexing. without sorting, there is no need to look through all found results, right? and there is no pressing need to archive them in order...
deploy: hub syncstring restart
testing: I didn't test this

hub/syncstring maintenance: do not order by string_id to speed up the query

---

src/smc-project/project-info/types.ts
src/smc-webapp/project/info/project-info.tsx

I'm not sure why at all, but apparently this could be undefined. Updated type info and rejecting an incomplete object.

project info: info.processes could be undefined

---

src/smc-project/bin/smc-local-hub

This is workaround for issue described here sagemathinc/cocalc-docker#106
This code prevents starting duplicated local_hub, which is happens often for me on projects with a lot of files, which requires long time to chown. 
This code requires python-psutil to be installed
You can detect project with duplicated local_hub by seeing Loading... for every notebook and by something like this output in terminal 
```
~$ forever list
info:    Forever processes running
data:        uid  command script                                   forever pid   id logfile                                                                     uptime        
data:    [0] T1VV coffee  /cocalc/src/smc-project/local_hub.coffee 11046   11068    /projects/28943c77-d1bc-405c-9e40-cf2b82b9a645/.smc/local_hub/local_hub.log …
```

Prevent duplicate spawning of local_hub.

---

src/smc-hub/postgres-base.coffee
src/smc-util/db-schema/projects.ts

* indexing the state of a project has a significant. instead of iterating in parallel over the jsonb objects, it uses this index.
* creating an index should happen concurrently, because otherwise a table could end up being locked for writes for minutes.
deployment: hub update, and then in production, we have to remove two indices I created for testing: `project_state` and `project_state2`

database index  improvements

---

src/smc-hub/postgres/remember-me.ts

This is a 200x improvement for those cookie queries. Take away: either don't cast – or cast to the correct type.
```
smc=# explain (analyze, verbose, costs) SELECT value, expire FROM remember_me WHERE hash = 'sha512$6cc3e...499'::CHAR(127);
Index Scan using remember_me_pkey on public.remember_me  (cost=0.54..2.76 rows=1 width=162) (actual time=0.036..0.037 rows=1 loops=1)
Output: value, expire
Index Cond: (remember_me.hash = 'sha512$6cc..4499'::character(127))
Planning time: 0.079 ms
Execution time: 0.051 ms
(5 rows)
smc=# explain (analyze, verbose, costs) SELECT value, expire FROM remember_me WHERE hash = 'sha512$6cc3e...9'::TEXT;
Seq Scan on public.remember_me  (cost=0.00..7479.69 rows=591 width=162) (actual time=0.018..108.994 rows=1 loops=1)
Output: value, expire
Filter: …
```

hub/db: _get_remember_me casts the hash to text, which slows this down

---

src/smc-webapp/admin/stats/historical-stats.tsx
src/smc-webapp/admin/stats/page.tsx

its confusing to see a search stat header outside of cocalc.com if there is nothing in it

webapp/admin: hide stats section header

---

src/smc-util/db-schema/blobs.ts

well, this is an optimization for searching old blobs. the drawback is it adds about 1 gb of data for the indices, but I think this isn't that bad and the free disk space is already there anyways – and future postgres updates will give us smaller index sizes.
the real benefit is to avoid reading all those rows/pages every few minutes. if there is a period of high load, such a query might throw off caching.
deployment: nothing to do. I already added exactly these indices "concurrently"

hub/db: speed up searching for blobs to archive

---

src/smc-project/terminal/server.ts
src/smc-webapp/frame-editors/code-editor/actions.ts
src/smc-webapp/frame-editors/frame-tree/editor.tsx
src/smc-webapp/frame-editors/frame-tree/frame-tree.tsx
src/smc-webapp/frame-editors/frame-tree/leaf.tsx
src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
src/smc-webapp/frame-editors/frame-tree/types.ts
src/smc-webapp/frame-editors/terminal-editor/actions.ts
src/smc-webapp/frame-editors/terminal-editor/commands-guide-components.tsx
src/smc-webapp/frame-editors/terminal-editor/commands-guide.tsx
src/smc-webapp/frame-editors/terminal-editor/connected-terminal.ts
src/smc-webapp/frame-editors/terminal-editor/editor.ts
src/smc-webapp/project/explorer/types.ts
src/smc-webapp/share/directory-listing.tsx

This adds a side panel to the terminal, which I called "Guide" … but  I'm not sure if there is a better word. It "guides" you a little bit with terminal commands, very basic. I'm happy with the basics I have and I don't want to spend more time on this right now. There are many more details to add and enhance, but that's for later. Rather, I want to also implement such a "guide" concept for latex and jupyter. 
The only detail I was stuck was how to share some state-information across frames, such that updates about one frame travel to all other ones  … and in particular, this one here can react to it. I used `save_editor_state(id, object)` which might or might not be a good idea.
Regarding release: it also needs a newer project, but it works fine for older ones. The current directory is …

Terminal Guide

---

src/smc-webapp/frame-editors/terminal-editor/commands-guide-components.tsx
src/smc-webapp/frame-editors/terminal-editor/commands-guide.tsx

1. make this intro text expandable on demand (so, in the usual case, it doesn't use up as much space)
2. a missing "$" sign for appending arguments to a command
3. quote filenames (there could be a heuristic with proper escaping, but for now I just wrap them in `'`)

small terminal guide fixes

---

src/smc-webapp/frame-editors/terminal-editor/actions.ts
src/smc-webapp/frame-editors/terminal-editor/commands-guide-components.tsx
src/smc-webapp/frame-editors/terminal-editor/commands-guide.tsx

The only thing I need help with is how to tell it to choose this default layout if I (attempt) to close all frames. With Markdown, when I click on the "x" several times, I end up with the default split. Here, this doesn't work. I'm stuck with whatever panel was shown last.

terminal guide: ask for missing args and make guide show up by default

---

src/smc-webapp/antd-bootstrap.tsx
src/smc-webapp/frame-editors/latex-editor/build.tsx

* this should fix #4973, a very subtle issue with the style
* switches to use this antd wrapper instead of using it directly
* removes an outdated comment
testing tells me it is fine now, but I should double check this

webapp/latex: fix tab switching in build panel logs 

---

src/smc-webapp/admin/users/actions.ts

the results of an admin search for users shows up in a random order, at least for me. the sort indicator tells it should be, though.

admin/user_search: sort users by last created or active

---

src/smc-webapp/jupyter/actions.ts

webapp/jupyter: un-edit-protecting a cell still needs metadata edit permissions

---

src/smc-webapp/collaborators/add-collaborators.tsx

there were reports about a stuck help popup for the search, which must be the `notFoundContent` component. this disabled it and instead, inserts a an alert box.

Orphaned input overlay

---

src/smc-webapp/site-licenses/admin/component.tsx
src/smc-webapp/site-licenses/admin/quota.tsx
src/smc-webapp/site-licenses/purchase/quota-editor.tsx

Way too often I forgot to enable member hosting for a trial. With that, it's on by default and shown to the admin. No implications for a general user. Only webapp affected...

webapp/admin/license: enable "memeber"  by default

---

src/smc-webapp/jupyter/select-kernel.tsx

In general this could be prettier, but for now, this PR just fixes the row/col setup in such a way, that headers are headers and don't somehow float/melt with the content beneath. below are before/after pix.
---
This is a webapp only fix.

jupyter: fix row/col to make headers have their own "row"

---

src/smc-hub/auth.ts
src/smc-hub/client/create-account.ts
src/smc-hub/postgres-server-queries.coffee
src/smc-hub/postgres/types.ts
src/smc-hub/utils.ts
src/smc-webapp/account/account-page.tsx
src/smc-webapp/account/passport-types.ts
src/smc-webapp/landing-page/landing-page.tsx
src/smc-webapp/landing-page/sign-up.tsx

This adds a field `exclusive_domains` to the passport configuration, which is a list of domain names for the given SSO mechanism. The goal is to block users from signing up using the standard email/password mechanism and in turn, be diverted to use the SSO.
This is for private installs, hence no impact regarding restarting services in production.

Enforce SSO for certain domains

---

src/smc-webapp/frame-editors/jupyter-editor/snippets/main.tsx

this gets rid of a border – i.e. what bugs me if I move the mouse to the right to scroll, it misses the scrollbar by 1px and instead selects text.
what did I did try to fix, actually, is some toggle-issue. I thought it has to do with antd, but building it works fine. so, not sure yet what's going on.

jupyter/snippets: removing a border

---

src/smc-hub/stripe/client.ts
src/smc-hub/stripe/connection.ts
src/smc-hub/stripe/plans.ts
src/smc-hub/stripe/sync.ts

well, I got bitten by this. I'm building it with that fix to see if it works then.
ok: with these two commits manage builds again. there should be no side effects.
```
/home/manage/src/node_modules/ts-node/dist/index.js:181
return new TSError(diagnosticText, diagnosticCodes);
^
TSError: ⨯ Unable to compile TypeScript:
../../../cocalc/src/smc-hub/stripe/client.ts(8,27): error TS2307: Cannot find module 'smc-util/async-utils' or its corresponding type declarations.
../../../cocalc/src/smc-hub/stripe/client.ts(9,30): error TS2307: Cannot find module 'smc-util/misc' or its corresponding type declarations.
../../../cocalc/src/smc-hub/stripe/client.ts(10,26): error TS2307: Cannot find module 'smc-util/message' or its corresponding type declarations. …
```

hub: stopgap for importing pkgs in manage

---

src/smc-hub/package-lock.json
src/smc-hub/package.json

I don't see any usage of `pdfkit`. Removing this, gets rid of ~70 dependent packages :muscle:

npm/hub: rm pdfkit

---

src/webapp-lib/app-init.ts
src/webapp-lib/app-startup-style.css
src/webapp-lib/app.pug

this is just a little change on the side … instead of ascii art progress bars, this uses div/span. it also throttles the update rate.

app page: throttle progress bar updates and use div/span

---

src/smc-hub/postgres-blobs.coffee
src/smc-hub/postgres/delete-patches.ts
src/smc-hub/postgres/types.ts

incrementally deleting patches when archiving syncstrings
I tested this in "test" (earlier archive time and chunks of just "5") and it looked good. This runs in prod now, with the default values. So, regarding deployment, nothing needs to be done.

hub/syncstrings: deleting patches incrementally

---

src/smc-project/project-info/server.ts
src/smc-project/project-status/server.ts
src/smc-project/sync/project-info.ts
src/smc-project/sync/project-status.ts

I saw repeated exceptions for the chain `ProjectInfoServer.emit` → `ProjectInfoTable.publish_impl` → `sync/project-info: TypeError: Cannot read property 'get_state' of undefined` which must be in the log. Well, addressing this is fine, but why is it even being called? This removes itself from the events. The only real problem is I can't reproduce it properly.
well, this works in cc-in-cc, in the end there aren't any substantial changes. I'm building this in "test" now...

project:fix event emitter leak and exception

---

src/smc-webapp/editor.coffee
src/smc-webapp/misc-page/index.ts
src/smc-webapp/misc-page/sagews-canonical-mode.ts
src/smc-webapp/misc_page.coffee

well, this is a quick fix. not sure if this should end up in page misc or not. we can move this around later.
fixes #5098
building and deploying now

misc_page: sagews_canonical_mode no longer defined, moving it 

---

src/smc-webapp/share/server-render.ts

for shared files, all markdown code highlights were broken:
```
2020-12-17T10:49:37.931Z - debug: Uncaught exception: TypeError: elt.highlight_code is not a function
2020-12-17T10:49:37.931Z - debug: TypeError: elt.highlight_code is not a function
at render_html (/cocalc/src/smc-webapp/r_misc/html.tsx:113:21)
at Misc-HTML (/cocalc/src/smc-webapp/r_misc/html.tsx:141:160)
```

webapp/share: fix missing setup of jquery codemirror syntax highlighting

---

src/smc-webapp/editor-data/generic.tsx
src/smc-webapp/editor-tmp.ts
src/smc-webapp/editors/register-all.ts
src/smc-webapp/editors/unknown/editor.tsx
src/smc-webapp/editors/unknown/register.ts
src/smc-webapp/file-associations.ts

this fallback "editor" actually checks the content. main point here is to avoid shooting yourself in the foot by just one wrong click.
in general, I see this as a first step. in the future, certain mime types could be registered with an editor automatically, or offer running a binary file (executable ELF) in a terminal … and of course, offer more than just the code editor.
to test this, I added random bytes to a file `foo.baz`, vim-edited a file `bla.bar`, or even copied an ELF binary to `name.bin`. 
deployment: webapp only

idea for a smart editor for unknown files

---

src/smc-webapp/codemirror/extensions/edit-selection.ts

fixes `VM70:1889 Uncaught (in promise) TypeError: t.open_new_tab is not a function`

webapp/sagews: fix menu → help → open website

---

src/smc-webapp/file-associations.ts

terminal → edit init file rocket. instead of showing this as an unknown file type, we can associate init extensions with the code editor with shell syntax highlighting.

webapp/terminal: init files are bash scripts

---

src/smc-webapp/project/open-file.ts
src/smc-webapp/project/page/file-tab.tsx
src/smc-webapp/project_actions.ts
src/smc-webapp/projects/projects-nav.tsx

see #5162 and this also adds this for the project tabs
I didn't test this thoroughly, but there isn't much that could go wrong either

webapp: open project and file tabs via shift-click with a hint

---

src/smc-webapp/collaborators/current-collabs.tsx

so, besides the FC, the problem is that I can't see the confirmation here (the  last remove button is clicked) without scrolling. quite suble.
with this patch it's more obvious
TEST: yes, I checked, works fine, there is no real change in functionality
DEPLOY: webapp only

webapp/collabs: modernize react component and wrap remove button in a popover confirm

---

src/smc-hub/hub_http_server.coffee
src/smc-hub/metrics-recorder.coffee

I bet this was in january. prom-client update and this snuck in.

hub/prom: metrics() changed to be a promise since december 2020

---

src/smc-webapp/project/ask-filename.tsx
src/smc-webapp/project/explorer/new-button.tsx
src/smc-webapp/r_misc/dropdown-menu.tsx
src/smc-webapp/r_misc/search-input.tsx

See #5230
* core idea is to replace the split button with `<Button.Group>`
* FC-ing the dropdown menu component
* FC-ing AskNewFilename, and while testing discovered a bug: the SearchInput  didn't re-render upon changing `value` (that box in AskNewFilename).

webapp/files: fixing +new dropdown

---

src/smc-webapp/_projects.sass
src/smc-webapp/project/explorer/explorer.tsx
src/smc-webapp/project/explorer/path-navigator.tsx
src/smc-webapp/project/explorer/path-segment-link.tsx
src/smc-webapp/project/search/header.tsx

this will replace react bootstrap with antd. and well, I'm ok with this for now.after all of these react bootstrap is gone, we should overhaul all of this. here are some screenshot, i.e. I did check if long paths wrap around.

path nav (files, etc.): transition to antd

---

src/smc-webapp/tracker/index.ts
src/webapp-lib/_inc_analytics.pug

this switches to use the newer gtag analytics

webapp: transition analytics to use gtag

---

src/smc-webapp/frame-editors/frame-tree/save-button.tsx
src/smc-webapp/frame-editors/frame-tree/title-bar.tsx

this is for the frame title bar: it changes the buttons to be antd based, and well, the only real change here is to adjust height and margin – similar to the other dropdowns. it looks ok in FF and Chrome.

webapp/frame title bar: react-bootstrap → antd

---

src/smc-util/compute-images.ts

the code is trivial. what's left to test is if the 3 new pointers to older 20.04 versions actually do work. ok, project starts up with those three environments.

renaming ubuntu 18.04 to be "EndOfLife" and adding 3 earlier snapshots

---

src/smc-hub/postgres-server-queries.coffee
src/smc-hub/postgres/site-license/sync-subscriptions.ts
src/smc-hub/test/kucalc/sync-sitelicenses.test.coffee

well, I thought this through and ran tests. I'm basically confident that this will not cause severe troubles. Also, even if there is an issue, we can switch back to the previous version, which should undo all the mistakes. In the end, nothing gets deleted … only the expiration is set or unset.
I can certainly deploy it. It's currently running (with a different image) as `hub-stripesync-test` shadowing `hub-stripesync`.

subscription ←→ license sync

---

src/smc-webapp/jupyter/output-messages/widget.tsx

this undo's https://github.com/sagemathinc/cocalc/issues/5228 because sliders no longer show up

webapp/jupyter: reverting 4dfb08af22389787 because it breaks sliders

---

src/smc-hub/postgres-base.coffee

This addresses another stacktrace in #5269

hub: early on, metrics objects might not be defined yet

---

src/smc-hub/postgres/always-running.ts

I saw that this query is used by the manage backend to check which projects should be started. The problem is, as far as I understand it should check the run quota, not the settings. In particular, this covers licenses as well.
Deployment: `manage-idle`

hub/db: check run_quota for always_running projects

---

src/smc-util/db-schema/projects.ts

This was an oversight in #5294 – that index is important. It's already in the DB, this is the corresponding code.

db: index run_quota->>always_running

---

src/smc-webapp/jupyter/parsing.ts

This reduces the chances of messing up the code. Usual content should work as before, except when a line starts with `#%%%#`. This pops up an error message.

jupyter/formatting: avoid messing up code cells starting  with the escape sequence

---

src/smc-webapp/project/explorer/search-bar.tsx

* functional component
* clean up some details
* using useEffect to run the command async. ~~my real problem is how to actually deal with that `id` condition in the original code. the closure architecture updates the reference id, which stops this from working. but in any case, I using `useEffect` and just showing the result when it arrives is good enough for this.~~ ok, got it, useRef is what I needed, which makes total sense. I was mentally stuck with how the code was written before. … and besides that,  I didn't even remember there was a command mode :-) 
IMHO the next step here would be to rewrite the input box to use Antd, but that's for another ticket.

modernize files search box code

---

src/smc-webapp/frame-editors/jupyter-editor/snippets/utils.ts

the background of this is that the `cell.source` array lines already contain a line break. I didn't realize that.

webapp/jupyter: custom snippets introduce too many newlines

---

src/smc-hub/postgres/always-running.ts
src/smc-util/db-schema/projects.ts

optimizing a query, without breaking functionality, hopefully ;-)
deployment: manage and hub

db/always_running: x IN <array>, not x NOT IN <array>!

---

src/smc-hub/postgres/collab.ts

while testing #5308 I saw a confusing error message when entering a made-up project invite token. this suppresses the fallback test, such that the original error appears. Also, it says more than just `""`.

hub: only fallback to non-token collab adding, if there is no token

---

src/smc-webapp/_antd_fix.sass
src/smc-webapp/antd-bootstrap.tsx
src/smc-webapp/course/configuration/terminal-command.tsx
src/smc-webapp/project/explorer/mini-terminal.tsx
src/smc-webapp/projects/token.tsx
src/smc-webapp/r_misc/search-input.tsx

This makes the file search box look more like the usual Antd. I checked searching assignments, terminal input in files, running a command across courses, and searching jupyter keyboard shortcuts in Chrome and Firefox. All of them look fine to me.

webapp: make the Search Input & co more antd-like

---

src/smc-webapp/frame-editors/code-editor/actions.ts
src/smc-webapp/frame-editors/latex-editor/actions.ts

right now, automatic builds are only triggered after changing & saving the parent (master) file. with this, the children are made aware of the parent and trigger a build as well.
to test this, include a simple file, switch to it, and then save it after a change.

latex: trigger build if dependency file changes

---

src/smc-webapp/_antd_fix.sass
src/smc-webapp/course/common.tsx
src/smc-webapp/frame-editors/course-editor/course-panel-wrapper.tsx
src/smc-webapp/frame-editors/frame-tree/editor.tsx
src/smc-webapp/frame-editors/frame-tree/leaf.tsx
src/smc-webapp/jupyter/main.tsx
src/smc-webapp/r_misc/close-x.tsx
src/smc-webapp/r_misc/error-display.tsx

* basic motivator is #5252
* this uses the alert's banner mode, looks and works much better, but the stock close-x is not an option, so I came up with a better solution. that's also the reason for the small CSS fix, because otherwise parts of the text stay hidden.
* however, because this is used in so many places, I tweaked this in several ways to keep it as compatible as possible. well, it's also the case, that there are some subtle issues in some situations. but in general, it's much better now and if there is some odd case, it shouldn't be hard to fix (the element itself and also the displayed body CSS can be touched up now)

Fix close x error 

---

src/smc-webapp/landing-page/sign-in.tsx
src/smc-webapp/r_misc/error-display.tsx

well, that's a fallout of that display error fix I made last week. although, it's still fully working and accessible, this just adds line breaks and makes it larger. the whole landing page should be redone, though.

webapp/landing: tweak error display a little bit

---

src/smc-webapp/app/page.tsx

THIS PR IS NOT FULLY TESTED: Even before this patch, when I built cc-in-cc with current master and ran it, I did not see the Help button at upper right between "CoCalc" and "Account". And that is with "Commercial" set to "yes" in site settings. 
I did check that, after this change, cc-in-cc appears to work otherwise.
This is the first WCAG issue reported in a recent support request. I do not see the purpose of the vertical divider that is causing the issue, so I simply deleted the divider in this PR. To see the WCAG issue reported, sign into CoCalc in Firefox, right-click on Help, and in the context menu, select "Inspect Accessibility Properties", and look a few lines up for the element flagged "! text label".

WCAG: remove vertical divider between CoCalc info and Help

---

src/packages/frontend/billing/add-subscription.tsx

Remove 3 course buttons from Account / Purchases tab. Change wording of button at bottom from "Buy Subscription or Course Package" to "Buy Subscription.
Tested in cc-in-cc and passes `npm run tsc`.
To test: in account with no active subscriptions, select "Account" / "Purchases. See 2 buttons instead of 5, "Monthly Subscriptions" and  "Yearly Subscriptions". Button at lower right (disabled) says "Buy Subscription.

Purchase tab: remove course buttons

---

src/packages/frontend/frame-editors/x11-editor/apps.ts

* if octave gui works, check if there is a simple wrapper script. that way it won't be activated if gui is broken
* fix spyder exe name

X11: octave gui and spyder

---

src/packages/frontend/codemirror/modes.js
src/packages/frontend/file-associations.ts

my goal here is to support assembler code in `*.asm` files. problem: syntax highlighting doesn't do anything. strange. I must be missing some detail.
ref: https://codemirror.net/mode/gas/index.html

frontend: support assembler code

---

src/packages/frontend/project/info/project-info.tsx

1. highlight cpu usage properly if the cgroup's cpu limit is < 1
2. don't point to a closed ticket, instead increase timeout and explain what's most likely causing this

Tweak project info

---

src/packages/frontend/projects/actions.ts
src/packages/frontend/projects/store.ts
src/packages/util/upgrades/types.ts

this is a little enhancement of those `project_started|_stopped` events. it also records some basic info about the type of project.

frontent: record "project_started" duration + project classification

---

src/packages/hub/postgres/site-license/hook.ts

~~I didn't test this yet.~~ I do know from the log, that the hook ends with
```
"Not currently valid license -- \"...\"."
"setup site license={}"
```
for an expired license.
well, I made a quick test. what happens is that the license goes away like "poof".

hub/licenses: actualy remove a license if it is no longer valid

---

src/packages/frontend/set-version-cookie.js

* this cookie is not really a secret
* Date.now is more concise

frontend: no need to set version cookie only for https 

---

src/packages/database/postgres-server-queries.coffee
src/packages/database/postgres/types.ts
src/packages/hub/hub.ts
src/packages/server/settings/server-settings.ts

This is for configuring cocalc instances via environment variables, i.e. `COCALC_SETTING_DNS`, `COCALC_SETTING_EMAIL_SMTP_SERVER`, `COCALC_SETTING_EMAIL_SMTP_PASSWORD`, ...
One detail where I was stuck is how to properly call the `set_server_setting` method. In the end I had to change the arrows in coffeescript 🤷🏻

hub:  set server settings via environment variables

---

src/packages/next/pages/pricing/dedicated.tsx
src/packages/util/upgrades/dedicated.ts

the general motivation here is to leave 2gb of ram on each node for system services. this adds a function to derive the quota limits form the machine spec string. besides removing a source of typo errors, adjusting the numbers later on will be much easier.
~~I have to add I haven't tested this yet, only step left, but it should be fine.~~
I've also written a function to derive the price directly from the specs. This results in almost the same numbers, hence, lots of code, no changes ;-)
new: (the example 3 is different from what's online right now, because it is twice the memory)

dedicated VM: dynamically caluclate the per project quotas 

---

src/packages/database/postgres/always-running.ts

pretty minimal, shouldn't impact the DB, since it is already indexed. looks like this case was not ported over? in any case, what's missing is updating the DB version, but I don't want to cause a merge conflict.

database/always_running: does not respect admin settings

---

src/packages/hub/hub.ts

This basically fixes how environment variables configure the database (it did hardcode "smc"), adds an option for the username, gets rid of "keyspace" and unifies a duplicate hostPath import.
for testing, I did stuff like
```
export PGUSER=foo
export PGDATABASE=bar
export PGHOST=db
```
and ran it e.g. like `npx cocalc-hub-server --mode=single-user --all --hostname=0.0.0.0 --database-name=mari ...`
no surprises, everything as expected.

Fix hub db setup

---

src/packages/database/postgres-server-queries.coffee
src/packages/frontend/admin/site-settings.tsx
src/packages/server/settings/server-settings.ts
src/packages/util/consts/index.ts
src/packages/util/consts/server_settings.ts
src/packages/util/db-schema/server-settings.ts
src/packages/util/db-schema/site-settings.ts

This is an extension to controlling those server settings via environment variables. I.e. there is a new column "readonly" and it's set to true if the hub sets them in "kucalc" mode. Then, the UI blocks and informs the admin about that in the server settings. Screenshot below.
Additionally, I made a change in the db-schema, where something that looks like a check is moved to a `check_hook` and I also added a protection to block readonly fields from being written to. 
Finally, the validity of env variable values is checked as well – and reported back to the admin as an exception.
The packages to update are hub+server+util for the additional field and checks, and obviously frontend to make use of it. In particular, `frontend/admin/site-settings.tsx` queries for a new field which requires …

Server settings readonly

---

src/packages/database/pool/cached.ts
src/packages/database/pool/pool.ts
src/packages/database/postgres/types.ts
src/packages/hub/hub.ts
src/packages/server/initial-onprem-setup.ts

this allows on prem admins to automatically create an admin account and a registration token. it's fully opt-in and doesn't disturb existing settings.
once merged, [messy setups like the one I saw here](https://github.com/belonesox/cocalc-on-fedora-ansible/blob/main/templates/init-db.sql) are no longer necessary – we should give him a note about this.

on-prem: support setting up an admin account and a registration token

---

src/packages/frontend/course/students/students-panel.tsx
src/packages/frontend/course/util.ts
src/smc_sagews/smc_sagews/sage_salvus.py

- student list for onprem/docker just show "Ready" for a project. no need to talk about trial/upgrades/hosting.
- this exposes the "icon" in the UI, it was just the checkmark all the time
- using a hourglass to symbol activity when a student is added

Onprem course no trials

---

src/packages/frontend/course/configuration/configuration-panel.tsx
src/packages/frontend/course/configuration/upgrades.tsx
src/packages/frontend/frame-editors/course-editor/course-panel-wrapper.tsx

No implication for kucalc=yes and commercial, while for kucalc=onprem and not commercial, there is now the license selection dialog showing up and well, distributing/removing licenses works the same way. No changes in the logic behind all that, just some shuffling around of what's shown to the instructor.

course: simplified license upgrade config for onprem setups

---

src/packages/frontend/customize.tsx
src/packages/hub/webapp-configuration.ts
src/packages/server/settings/server-settings.ts
src/packages/util/db-schema/site-defaults.ts
src/packages/util/db-schema/types.ts

I saw there is some confusion about setting kucalc vs. commercial. The commercial setting makes only sense in the context of production use, but in the code it's not properly used. This is a general fix for this. Whenever `kucalc != yes` → `commercial` becomes `false`. In a follow up PR I'll sort out the problem of hiding the license upgrade config for student projects in a course, when `commercial` is false.

Site setting commercial

---

src/packages/util/local-storage.ts

There is a bug in the code, where trimming could get rid of of the recently used keys – that's stupid.

Fix local storage lru

---

src/packages/frontend/course/configuration/actions.ts
src/packages/frontend/course/configuration/configuration-panel.tsx
src/packages/frontend/course/configuration/upgrades.tsx
src/packages/frontend/course/store.ts
src/packages/frontend/course/types.ts

this makes upgrading the host project optional by adding a boolean switch below the license upgrade box. 
reason: the automatism causes too much confusion is some cases. ref:  #5360

frontend/course: optionally upgrade host project --

---

src/packages/frontend/frame-editors/frame-tree/frame-tree.tsx
src/packages/frontend/frame-editors/terminal-editor/commands-guide.tsx
src/packages/frontend/frame-editors/terminal-editor/connected-terminal.ts
src/packages/frontend/frame-editors/terminal-editor/terminal.tsx
src/packages/frontend/project/page/page.tsx
src/packages/frontend/project_actions.ts

- fixes #5398 – well, not 100%, but still
- refactors this `FrameTree` to be a functional component … I initially thought this is the problem and with that I have more insight into what's happening. so, that's the meat of the PR now.
- but turns out, the real issue was the delayed initialization in `frontend/project_actions.ts`  … i.e. `show()` was never called, which in turn never set `visible` to true, and without being visible, no resize happens.
- while debugging this I was also thrown off by some other issue: if it is a new terminal (i.e. only a one line history) then calling `this.terminal.resize( ... )` in  `terminal-editor/connected-terminal.ts` doesn't do anything as well. I made a note that I think this is an upstream issue. The general symptom is that if you create a new …

Fix terminal resize

---

src/smc_sagews/setup.py

this just tells setuptools that this package does not work with the newest jupyter_client

smc_sagews: be explicit about not working with jupyter_client 7

---

src/packages/database/package-lock.json
src/packages/database/package.json
src/packages/hub/package-lock.json
src/packages/hub/package.json
src/packages/project/package-lock.json
src/packages/project/package.json
src/packages/project/sync/listings.ts
src/packages/project/sync/path-watcher.ts
src/packages/server/package-lock.json
src/packages/server/package.json
src/packages/static/package-lock.json
src/packages/static/package.json
src/packages/sync/package-lock.json
src/packages/sync/package.json
src/packages/util/package-lock.json
src/packages/util/package.json

cocalc onprem setups using NFS do not watch the files reliably. there is a package "chokidar", which uses inotify or polling, and also claims to be more robust. it's used by vscode and others, so I think it's fine to add it as a dependency. I also configured it in such a way that it doesn't watch/poll for all the subdirectories – it's should be the same overall mechanism as before.

support NFS file watching by switching to chokidar

---

src/packages/util/consts/site-license.ts
src/packages/util/test/quota.test.ts
src/packages/util/types/site-licenses.ts
src/packages/util/upgrades/quota.ts

This is the a first phase of #5723, such that we can update the backend services first and then do the frontend related part.
this is ready to be merged. the main detail about all this is that all previous quota tests weren't touched and they still pass. so, no impact for the existing functionality. `util/consts/site-license.ts` defines the new upgrade types. once this is in, I'll deploy it on the backend and will test it with manually created licenses. then we can fine tune the frontend part.

backend only aspect of #5723

---

src/packages/frontend/frame-editors/frame-tree/util.ts
src/packages/frontend/frame-editors/html-editor/iframe-html.tsx
src/packages/frontend/frame-editors/latex-editor/pdfjs-doc-cache.ts
src/packages/frontend/frame-editors/pdf-editor/actions.ts
src/packages/util/misc.ts

- see #5542
- this is an issue for for pdf native, rst, iframe/html, ipynb reveal.js slideshow and .wiki files 
- I probably also fixed this for the latex editor, but %20 is forbidden in filenames anyways

frontend: fix %20 in filenames 

---

src/packages/frontend/frame-editors/frame-tree/title-bar.tsx

simple idea: wrap that button just like the "styled" buttons, because with the same styling they'll look the same 🤷🏻 
before:
after:

frontend/frame-editor: get rid of inconsistencies in buttons

---

src/packages/frontend/frame-editors/frame-tree/title-bar.tsx
src/packages/frontend/frame-editors/x11-editor/actions.ts
src/packages/frontend/frame-editors/x11-editor/launcher.tsx
src/packages/frontend/frame-editors/x11-editor/window-tab.tsx
src/packages/frontend/frame-editors/x11-editor/x11.tsx

actually, the main change is to add more zoom levels, and switching to lodash, ... everything else should be the same. what I tested:
- opening two or more apps, tabbing between them
- refreshing the entire page, and after a few secs of reconnecting to the websocket stream, I'm able to continue working with the apps
- this is the only problem left, somehow it either doesn't update or information is lost. or well, maybe this is a bug in the current version as well, not sure. 
- ok, got it, the initialization works a bit differently now
- split the x11 area in two, have two apps open at the same time, and well, it switches between them as before
- I also took care to preserve all those memoizations
- zoom/font-size: changes size and re-measures everything
- same for resizing the frames

x11 editor: functional components

---

src/packages/next/components/landing/content.tsx
src/packages/next/components/landing/image.tsx

it's complaint has a point, to avoid a flicker load of those larger images
> react_devtools_backend.js:4061 Image with src "..." was detected as the Largest Contentful Paint (LCP). Please add the "priority" property if this image is above the fold.
> Read more: https://nextjs.org/docs/api-reference/next/image#priority

next: prioritize loading those images above the fold in "Content"

---

src/packages/frontend/frame-editors/frame-tree/editor.tsx
src/packages/frontend/frame-editors/frame-tree/format-bar.tsx
src/packages/frontend/frame-editors/frame-tree/frame-tree.tsx
src/packages/frontend/frame-editors/frame-tree/leaf.tsx

this gets rid of two components used widely, hence there is some chance to introduce a problem, but I wasn't able to find anything during testing. the only change in functionality is sorting of colors – the old code accessed the "`.code`" attribute, which doesn't exist. I stayed true to that intention and well, now the colors are sorted by color.

frontend: React.FC-ing FrameTree+Leaf+FormatBar

---

src/packages/frontend/account/editor-settings/color-schemes.tsx
src/packages/frontend/account/editor-settings/x11-keyboard.tsx
src/packages/frontend/account/settings/password-setting.tsx
src/packages/frontend/account/sign-out.tsx
src/packages/frontend/components/close-x2.tsx
src/packages/frontend/components/selector-input.tsx
src/packages/frontend/components/text-input.tsx
src/packages/frontend/components/time-elapsed.tsx
src/packages/frontend/components/windowed-list.tsx
src/packages/frontend/course/nbgrader/scores.tsx
src/packages/frontend/customize.tsx
src/packages/frontend/project/utils.ts

- close-x2 cross
- TextInput: FC component and no bootstrap any more
- the "nbgrader scores" table in a student assignment row
- time elapsed (e.g. used in the project settings/control)
- getting rid of a bit of bootstrap usage in textinput
- SelectorInput: now also searchable, e.g. keyboard language
- SiteName, HelpEmailLink, Footer, ...
- SignOut button
- and well, I looked at that windowed list, and the row itself is easy, but the windowed list makes its internal state directly accessible and that must be done differently, with a callback or whatnot?, since functional components do not have an internal state

frontend: more React.FC

---

src/packages/frontend/project/settings/project-control.tsx
src/packages/project/consts.ts
src/packages/project/data.ts
src/packages/project/init-kucalc.ts
src/packages/project/kucalc.coffee
src/packages/project/servers/browser/http-server.ts
src/packages/project/servers/init.ts
src/packages/project/servers/pid-file.ts
src/packages/project/servers/secret-token.ts
src/packages/server/projects/control/base.ts
src/packages/server/projects/control/single-user.ts
src/packages/server/projects/control/util.ts
src/packages/util/db-schema/projects.ts

this is mainly to have the `start_ts` timestamp available in development mode as well. I'm also adding the `session_id`, might be useful at some point.

server/single-mode: record start_ts and session_id in project status

---

src/packages/cdn/package-lock.json
src/packages/cdn/package.json
src/packages/cdn/setup.py
src/packages/frontend/frame-editors/latex-editor/pdfjs-doc-cache.ts

- Ref #5761 
- add pdfjs-dist to our "CDN", but since it installs so many other packages, I added a whilelist mechanism. I also blacklisted typescript. That should avoid bloat. I hope this is ok and doesn't break anything? ... OK, I double checked the "dist" dir: "commander" is gone, "typescript" as well (intentional), and "pdfjs-dist" added. 
- fix the PDF.js config to load those additional files.
test:
- when opening the test document, I see a request to `https://cocalc.com/14eed217-.../port/5000/cdn/pdfjs-dist-2.9.359/cmaps/Adobe-GB1-UCS2.bcmap` and characters show up.

Chinese LaTeX

---

src/packages/frontend/jupyter/output-messages/mime-types/register.ts

There was a user reporting a `TypeError: Cannot read properties of undefined (reading 'handler')\n at HTMLDocument.eval`  … I don't now which document nor how to reproduce it, but just by going through the code I found this detail, which looks at least like a good idea to check.

jupyter: maybe fix a "TypeError: Cannot read properties of undefined 

---

src/packages/frontend/frame-editors/code-editor/actions.ts
src/packages/frontend/frame-editors/code-editor/codemirror-editor.tsx
src/packages/frontend/frame-editors/frame-tree/frame-tree.tsx
src/packages/frontend/frame-editors/frame-tree/leaf.tsx
src/packages/frontend/frame-editors/latex-editor/actions.ts
src/packages/frontend/frame-editors/latex-editor/errors-and-warnings.tsx
src/packages/project/browser-websocket/api.ts
src/packages/project/browser-websocket/canonical-path.ts

this is a half way attempt to fix #5779
The most important change I did is ```let name_leaf = `editor-${project_id}-${desc.get("path", path)}``` for the Leaf component, before that it was just the `name`. My main problem is, I have no idea what the real implications of changing any of these variables are. In this case the `CodeMirror` editor will get a different "value", and hence it starts showing a different content. At the same time it starts throwing errors: `Error: doc must be set  at SyncString.SyncDoc.to_str (sync-doc.ts ...)`.

fix switching latex deps 

---

src/packages/frontend/project/settings/site-license.tsx
src/packages/frontend/project/trial-banner.tsx
src/packages/frontend/site-licenses/input.tsx
src/packages/frontend/site-licenses/select-license.tsx

This changes the trial banner in various ways:
* if you manage any license, never red
* in the first few days of the trial, also not red
* when you click "apply", the dropdown to select a license appears right there
* I've also split this up and got rid of react-bootstrap for the `Alert`
testing: there were a few edge cases, like, new project and no license, etc. … but I think I got them all.
deployment: this is frontend only
normal (with expanded dialog)
severe:

Less intimidating trial banner

---

src/packages/project/jupyter/convert/index.ts

there was an problem reported about "pdf via latex" and I don't really understand what went wrong. in any case, this changes the default timeout to a minute. I don't know if there are other more specific timeouts …

jupyter/nbconvert: increase timeout

---

src/packages/frontend/frame-editors/latex-editor/actions.ts
src/packages/frontend/frame-editors/latex-editor/synctex.ts

- during testing I noticed synctex from pdf → tex doesn't work for `*.rnw` files, because synctex claims the file ends in `.Rnw`. This just uses the path of the actual file as a fallback, which should usually work.
- there is also a typo in the user visible error message.

frontend/latex: fix rnw/Rnw synctex processing and a typo

---

src/packages/hub/auth.ts

If we proxing cocalc with nginx http , we failed to set secure cookies, and it breaks for example password recovering.

If we proxing cocalc with nginx http , we failed to set secure cookies

---

src/packages/database/postgres/site-license/sync-subscriptions.ts
src/packages/frontend/account/licenses/managed-licenses.tsx
src/packages/frontend/site-licenses/admin/license.tsx
src/packages/frontend/site-licenses/purchase/quota-editor.tsx
src/packages/frontend/site-licenses/site-license-public-info.tsx
src/packages/next/components/licenses/license.tsx
src/packages/util/db-schema/site-licenses.ts

this is a rather simple PR
- backend/db: there is a check if a license doesn't exist during syncing it up. however, the code continues right after "WARNING: no known license '${license_id}' for subscription '${sub.id}".  … which obviously breaks right where `licenses[license_id].<any field>` is accessed. I've modified the typescript annotation to capture this, and then a few strategic questionmarks.
- code deduplication: using an existing function to generate the string describing a license instead of duplicating this. this was an issues, because there is no clause for the idle timeout upgrade
- editing a license as an admin resets the idle timeout. with this change, the default value for the dropdown is taken from the quota info
- frontend: when the managed licenses table  is shown, it …

fix license related issues

---

src/packages/database/postgres-blobs.coffee
src/packages/util/syncstring_schema.js

if the patches of a syncstring are too large: 
* swallow the error, i.e. don't bubble it up via the callbacks and break the whole operation
* instead, mark the symcstring as huge and from now on, ignore it
testing: well, this is not so trivial. what I did:
- build database and hub, hub starts fine, ok ... that's no surprise
- then I added a line `raise new Error( ... )` right after the json stringify to simulate a problem. built it again … and then `env MIN_AGE_DAYS=3 ./node_modules/.bin/cocalc-hub-maintenance-syncstrings` … indeed, the "huge" field got filled up for a few syncstrings. 
- what's weird is, when I archived a few syncstrings (no error thrown), and tried to open it again, I got errors. `INSERT INTO patches' ... error: null value in column \"time\" of relation \"patches\" …

db/syncstrings: mark syncstrings with too large patches as "huge"

---

src/packages/frontend/account/profile-settings.tsx
src/packages/frontend/components/color-picker.tsx

I opened the account settings and well, the color chooser is strange, especially on narrower pages. There is no need to always show a horizontal scrollbar, and I also don't understand the 150px width limit. What I added is an optional left alignment, to match the surrounding content.
Before:
After:

account/avatar: get rid of scrollbars and 150px width limit

---

src/packages/frontend/course/students/students-panel.tsx

there was a report that student activity isn't reflected in the listing. well, that's true. what I added is to update the list when this `user_map` changes. I tested this a bit and it's somehow not always up to date, but at least this part here is certainly updating the listing more often than before.

course/student list: carefully update list upon user_map changes

---

src/packages/next/components/statistics/opened-files.tsx

I just noticed it's recorded, but not shown.

next/status: show whiteboard stats

---

src/smc_sagews/smc_sagews/sage_salvus.py

Fixes "list index out of range" error in sagews modes().
To test:
1. See the bug before PR is applied. In current source tree:
```
$ cd ~/cocalc/src/smc_sagews
$ sage -python
...
>>> from smc_sagews import sage_salvus
>>> sage_salvus.modes()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/user/cocalc/src/smc_sagews/smc_sagews/sage_salvus.py", line 4196, in modes
mode_cmds.add(re.findall(r'%[a-zA-Z]+', s)[0])
IndexError: list index out of range
```
Kill the sage python process.
2. Apply the patch in the PR and repeat the above steps:
```
$ cd ~/cocalc/src/smc_sagews
$ sage -python
...
>>> from smc_sagews import sage_salvus
>>> sage_salvus.modes()
['%anaconda', '%auto', '%axiom', '%capture', '%coffeescript', '%command', '%cython', '%default', …
```

fix sagews modes()

---

src/packages/frontend/frame-editors/latex-editor/actions.ts
src/packages/frontend/frame-editors/latex-editor/build-command.tsx
src/packages/frontend/frame-editors/latex-editor/latexmk.ts
src/packages/frontend/frame-editors/latex-editor/util.ts

- see #5910
- this also fixes nonsense sanitizations when someone selects "<disabled>" and similar issues

frontend/latex: add "no output dir" options and some fixes to sanitization functions

---

src/packages/frontend/frame-editors/x11-editor/apps.ts

frontend/x11: change spyder icon to the one for python

---

src/packages/frontend/frame-editors/frame-tree/title-bar.tsx
src/packages/frontend/frame-editors/latex-editor/actions.ts
src/packages/frontend/frame-editors/latex-editor/build-command.tsx
src/packages/frontend/frame-editors/latex-editor/build.tsx
src/packages/frontend/frame-editors/latex-editor/editor.ts
src/packages/frontend/frame-editors/latex-editor/latexmk.ts

While working on software updates, I did this. It's a cocalc specific extension to these `!TeX` build directives. The main use case is to hardcode the build instruction in the document, such that CoCalc will always set the build command based on the file's content. It's 100% optional, and the content isn't automatically changed.
The existing support for selecting the engine is enhanced, e.g. more flexible whitespace and case insensitiveness.

latex: introduce support for !TeX cocalc = hardcoded command

---

src/packages/util/licenses/purchase/compute-cost.ts

This requires a version update of server and next, and then replace the next hubs.

next/store: fix min floor of price for small boost subscriptions

---

src/packages/frontend/account/upgrades/upgrades-page.tsx
src/packages/frontend/billing/billing-page.tsx
src/packages/frontend/billing/subscription-list.tsx
src/packages/frontend/project/explorer/explorer.tsx
src/packages/frontend/site-licenses/purchase/purchase-method.tsx
src/packages/frontend/site-licenses/purchase/quota-editor.tsx
src/packages/next/components/billing/layout.tsx
src/packages/next/components/licenses/layout.tsx

- weed out purchases page
- preserve the student pay option
- this also removes those yellow links to the old pages from the newer next.js's billing and licenses pages.
I'll only make a few changes. I think it's better to merge this earlier, and then go on with other changes in a different PR.  The only result of this is a more minimal purchases page, i.e.:
… and I realized parts of that page are relevant for the student pay option, which is still working (and I did some minor fixes). i.e.

cleaning up purchase options page

---

src/workspaces.py

after updating node, it's always reverting npm to a version 6, which causes the build to fail. this just makes this fail early.

npm build: check if npm is at least version 8

---

src/packages/server/email/send-email.ts
src/packages/server/email/smtp.ts

- see #5949
- I also found something weird, the secure setting is set based on the port. I don't understand why this isn't the "secure" setting.
- ~~I didn't test this yet, didn't want to mess up the versions again.~~ ... ok, I tested this in my dev project, just the smtp settings. looks good, including making use of the override toggle. the sendgrid sending logic isn't touched, so, should be fine as well, but probably a good idea to double check before deploying.

next/server: fix email setup

---

src/packages/frontend/project_store.ts

TIL there is also a `*_cache` subdirectory, which should be masked just like the `*_files` dir

frontend: mask Rmd cache (a subdirectory)

---

src/packages/frontend/components/copy-to-clipboard.tsx
src/packages/frontend/share/config.tsx
src/packages/frontend/share/configure-name.tsx
src/packages/next/components/path/path.tsx
src/packages/next/lib/share/handle-raw.ts

This fixes #5928 and also tweaks the public files dialog in the frontend a little bit (line break, spacing).
The original path in the ticket is broken due to a comma being encoded, and the test path I used for development is `test/sub dir/file space, (comma ) .md`. So, that's fine. I got pretty lost when I started to test more variations. E.g. a percent sign and question marks in the filename don't work as well. I tried some ideas, but no luck. I think the underlying complication is next.js itself does decode the URL component, internally. So, maybe this must change to an query parameter (maybe that helps, I don't know) or more general, we might want to warn/block renaming files to contain such problematic characters (`?`, `%` and `#` come to my mind, there are probably more)
I also tried …

Fix sharing files with commas

---

src/packages/database/postgres-base.coffee

this fixes #6030
Main hurdle was to replicate the problem. i.e. I made a new database setup, new user, require password auth, etc. Then `env DATA=... PGUSER=postgres PGHOST=127.0.0.1 PGDATABASE=cocalc ./node_modules/.bin/cocalc-hub-server --mode=kucalc --hostname=localhost --update-database-schema --websocket-server` to mimic kucalc's setup.

db: fix initial setup if DB does not yet exist and a password is required

---

src/packages/frontend/admin/site-settings.tsx
src/packages/frontend/customize.tsx
src/packages/hub/servers/server-settings.ts
src/packages/static/src/load.tsx
src/packages/static/src/startup-banner.tsx
src/packages/static/tsconfig.json
src/packages/static/webpack.config.js
src/packages/tsconfig.json
src/packages/util/db-schema/site-defaults.ts
src/packages/util/upgrades/quota.ts

1. process the string value using the `to_val` function right when the data comes in from the DB
2. the above means it is no longer necessary in the frontend
3. fix/enhance typing
4. I also noticed errors in "static", where the local source files are in `./src`. I added them.
5. … and when I edited the tsconfig file, it also complaint about not setting the module resolution ordering, i.e. if     `"resolveJsonModule": true` → I set `moduleResolution": "node"`. More background about that [in the moduleResolution documentation](https://www.typescriptlang.org/docs/handbook/module-resolution.html). If this setting introduces problems, which I hope it doesn't, we should definitely fix them and not revert the setting.

some fixes around processing server settings

---

src/packages/frontend/custom-software/selector.tsx
src/packages/frontend/projects/create-project.tsx
src/packages/frontend/projects/projects-page.tsx
src/packages/frontend/site-licenses/input.tsx
src/packages/frontend/site-licenses/select-license.tsx

This adds a bit of "antd" to the new project dialog and a dropdown to add or select a license. I also saw traces of giving projects a default name, which didn't work. It's fixed and I'm also adding a timestamp to the default name.
how it looks now:
and after expanding the add license part:

frontend: let users add their license easily when they create a new project

---

src/packages/next/components/landing/content.tsx
src/packages/next/components/landing/sign-in.tsx
src/packages/next/pages/index.tsx
src/packages/util/db-schema/site-defaults.ts

- got some feedback, and it's not ideal to show the shared files listing on the landing page for onprem. hence this changes it to only show up if in production
- the additional information block replaces the image right at the top, to make that text visible above the fold (if someone wants to show an image in the text, it's possible via html or markdown, no problem)
- finally, I'm also tweaking the description texts for the iframe and index page info site setting configuration.

landing page + settings: no shared listing on landing page

---

src/packages/next/pages/policies/enterprise-terms.tsx

File `src/packages/next/pages/policies/enterprise-terms.tsx` added. This file is a copy of `terms.tsx` with suggested changes merged in. Full details are in the internal dev notes md file - see daily chat.
The only testing I have done is to make sure the new file compiles with typescript.

add enterprise tos

---

src/packages/hub/servers/express-app.ts
src/packages/next/next.config.js
src/packages/project/http-api/server.ts
src/packages/project/servers/browser/http-server.ts

- ref #6101
- for testing, I used curl in my dev project:
before:
```
~$ curl -I http://localhost:5000/.../port/5000/info
HTTP/1.1 200 OK
X-Powered-By: Next.js
[...]
~$ curl -I http://localhost:5000/.../port/projects/.../files/
HTTP/1.1 308 Permanent Redirect
X-Powered-By: Express
[...]
```
and with this patch these headers are gone.
```
~$ curl -Is http://localhost:5000/.../port/5000/info | grep Powered
~$ curl -Is http://localhost:5000/.../port/projects/.../files/ | grep Powered
```

next.js/express.js: disable X-Powered-By everywhere 

---

src/packages/next/components/billing/layout.tsx
src/packages/next/components/billing/menu.tsx
src/packages/next/components/billing/overview.tsx
src/packages/next/components/billing/payment-methods.tsx
src/packages/next/components/licenses/layout.tsx
src/packages/next/components/licenses/menu.tsx
src/packages/next/components/licenses/overview.tsx
src/packages/next/components/statistics/index.tsx
src/packages/next/components/store/index.tsx
src/packages/next/components/store/menu.tsx
src/packages/next/components/store/overview.tsx
src/packages/next/lib/styles/layouts.tsx
src/packages/next/pages/billing/[[...page]].tsx
src/packages/next/pages/licenses/[[...page]].tsx
src/packages/next/pages/policies/accessibility.tsx
src/packages/next/pages/store/[[...page]].tsx

this enhances the look&feel of licenses and billing pages, and to make to 2x2 matrix of icons complete (for commercial mode only), I'm adding cross references to cancelling or managing licenses from either side.

next/billing+licenses: streamlining the layout similar to "store"

---

src/packages/util/compute-images.ts

our most recent frozen compute image is from april. This is a new one, i.e. 2022-08-17` was pretty stable and from before the fall started.

util/compute-images: adding 2022-08-17

---

src/packages/frontend/editors/task-editor/editor.tsx
src/packages/frontend/editors/task-editor/find.tsx
src/packages/frontend/editors/task-editor/hashtag-bar.tsx

1. I overlooked several times that I had an active search, which is remembered across sessions. So, this just adds this warning highlight to the clear button, like it shows up in other search&find boxes as well
2. just something trivial: if there are no tags, don't render an empty div

Tasks highlight active search

---

src/packages/util/compute-images.ts

this introduces a way for users to select the upcoming 22.04 test image, that's all. a lot is still in flux and needs to be done, but in case there is interest, this exposes that.
I also renamed "Experimental" to "Testing", sounds more suitable.

util/compute_images: add entry for 22.04 testing

---

src/packages/frontend/admin/page.tsx
src/packages/frontend/site-licenses/admin/actions.ts
src/packages/frontend/site-licenses/admin/component.tsx
src/packages/frontend/site-licenses/admin/license.tsx
src/packages/frontend/site-licenses/admin/quota.tsx
src/packages/frontend/site-licenses/admin/store.ts
src/packages/frontend/site-licenses/purchase/quota-editor.tsx
src/packages/util/types/site-licenses.ts

- this is for onprem only. admins get a way to define `{ext_rw:true}` which mounts the readonly `/ext` directory as read/write. this is only for the license.
- it hides member hosting, that makes no sense for onprem
- this tweaks a bit the UI of the license admin panel
- it does not touch the embedded payment form, and for non-onprem there is no change in actual functionality

onprem: license quota to make /ext read/writeable

---

src/packages/database/postgres/load-sso-conf.ts
src/packages/hub/auth.ts
src/packages/server/auth/sso/types.ts
src/scripts/auth/gen-sso.py

This introduces a simple for administrators to configure the SSO settings, without having to fiddle around with the DB. Later, we can always implement something more sophisticated via a UI.
In any case, the idea is the env var `$COCALC_SSO_CONFIG` points to a file, containing a JSON config. This could easily be a k8s secret mounted as a file as well. If this file exists, upsert/delete operations are done accordingly, before the actual sso endpoint initialization happens.

onprem: load SSO configs via a file

---

src/packages/frontend/project/settings/site-license.tsx
src/packages/frontend/site-licenses/purchase/buy-license-for-project.tsx

This is a follow up of that PR about purchasing a license for a project (with automatic application). All this does is to replace the "Buy a license" link with an identical one, which opens the store with that `?project_id=` query param. Pretty trivial.

frontend: replace "Buy a license" button in project settings with link to store

---

src/packages/database/postgres-server-queries.coffee
src/packages/hub/password.coffee
src/packages/server/auth/password-reset.ts
src/packages/util/db-schema/password-reset.ts

This adds an expiration field, for one day. More than enough. 
Before this goes live we have to clean up that table...

db: expire entries in password_reset_attempts

---

src/packages/frontend/account/licenses/about-licenses.tsx
src/packages/frontend/account/licenses/licenses-page.tsx
src/packages/frontend/site-licenses/purchase/buy-license-for-project.tsx
src/packages/frontend/site-licenses/purchase/link.tsx

This replaces the embedded form in account/licenses with a link to the store. It also only shows that button-link, if customize/commercial is true!

Account/licenses: link to store

---

src/packages/frontend/course/configuration/configuration-panel.tsx
src/packages/frontend/course/student-projects/actions.ts

This fixes a few details:
1. what if there is already more than one license assigned to a student project? → only pick the first one which still has a seat free.
2. there was a fix to remove licenses from deleted student projects, but the `ids` never included the deleted student projects. This explicitly iterates over all deleted student projects and removes the licenses.
3. there is a toggle to upgrade the host/instructor project or not. if not, we do not deduce "1" from the number of available seats per license.

course: fix edge cases serial licensing strategy

---

src/packages/frontend/billing/explain-course-licenses.tsx
src/packages/next/components/landing/pricing-item.tsx
src/packages/next/components/store/link.tsx
src/packages/next/components/store/quota-query-params.ts
src/packages/next/pages/pricing/_shared.tsx
src/packages/next/pages/pricing/courses.tsx
src/packages/next/pages/pricing/dedicated.tsx
src/packages/next/pages/pricing/index.tsx
src/packages/next/pages/pricing/onprem.tsx
src/packages/next/pages/pricing/products.tsx
src/packages/next/pages/pricing/subscriptions.tsx

- I discovered hardcoded price values on these pages, which are certainly wrong.
- added "select" links for course and subscription examples to the store/site-license
- expanding on-prem descriptions and remove the "kubernetes" option
- also fixed broken links
testing:
- regarding the hardcoded prices, a neat test is to look at the price examples for subscriptions and courses and then click on the select button to check if the price matches. it might be off a bit for courses, but overall it is very close to the real number.

fix some /pricing pages

---

src/packages/frontend/account/ssh-keys/ssh-key-adder.tsx
src/packages/frontend/admin/site-settings.tsx
src/packages/frontend/customize.tsx
src/packages/frontend/project/settings/ssh.tsx
src/packages/server/settings/customize.ts
src/packages/util/db-schema/site-defaults.ts

1. new `ssh_gateway_dns` setting
2. use it in the ssh box in the project settings
3. I also tweaked the UI a little bit and mentioned, that projects need to run
deployment: update frontend first (also "util"). if there is no value set via the customization endpoint, it falls back to `ssh.${dns}`, which is fine for prod and test.

ssh gateway custom domain

---

.github/workflows/make-and-test.yml

This caches ~/.npm to speed up builds

github actions: cache ~/.npm to speed up builds

---

.github/workflows/make-and-test.yml
.github/workflows/sizewatcher.yml

with that, two quick pushes to the same repo should abort the older action runs of the same workflow. 
I got this from here, combining the last two examples: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value

github actions: newer commits abort currently running actions in the same workflow

---

src/packages/project/data.ts
src/packages/project/init-kucalc.ts
src/packages/project/init-program.ts
src/packages/project/sshd.ts

this moves the sshd server launch to the project, i.e. instead of doing this in the init.sh file. later, we can figure out if we ever want to customize this, get rid of the start script, etc.

project: optionally launch the sshd server

---

src/packages/server/prices.test.ts

ignore some time tests if machine is not in UTC

server/test prices: ignore time tests if underlying system is not UTC

---

src/packages/database/pool/util.test.ts

- occasionally, there is a +/- 1 difference and "close to" is only for fractions of one after the decimal point
- `valueOf` is somehow discouraged since [mdn docs say](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/valueOf#description) "This method is usually called internally by JavaScript and not explicitly in code."

database/pool test: fix off-by-one

---

src/packages/project/init-kucalc.ts
src/packages/project/init-program.ts
src/packages/project/init-script.ts
src/packages/server/projects/control/util.ts

This moves the logic of running `project_init.sh` to the project hub itself. Same behavior. However, there is also an important change: I added this parameter to the `launchProjectDaemon` function, which has implications for single and multi user project modes. So, that means we get feature parity with "kucalc" projects.

project: optionally run an init script

---

src/packages/frontend/account/types.ts
src/packages/frontend/customize.tsx
src/packages/frontend/project/settings/body.tsx
src/packages/frontend/project/settings/datastore.tsx
src/packages/frontend/project/settings/quota-console.tsx
src/packages/frontend/project/settings/upgrade-usage.tsx
src/packages/util/db-schema/site-defaults.ts

- for onprem mode, a toggle to show the "datastore" config panel in the settings
- there was a problem when the default value is true, i.e. the frontend didn't check properly if it should use a default fallback for an undefined value. also made the conversion to a boolean idempotent.
- I also noticed that the body for the settings isn't a React FC yet, so I fixed that as well.

admin config for "datastore" and FC-ing settings body

---

src/packages/frontend/components/date-time-picker.tsx

- **this fixex #6261**
- I think this is the equivalent to "LLL", but I can't remember exactly what we had. I'm always in favor to format dates in ISO, that's also the default by antd.
- However, since this came up from time to time, I've added `Z` to the format to show the time zone offset. see https://day.js.org/docs/en/display/format for options.
- obligatory screenshot for a due date in a course:

frontend: fix DateTimePicker displaying format 

---

src/packages/frontend/client/project.ts
src/packages/frontend/project/client-side-throttle.ts
src/packages/frontend/project/start-button.tsx
src/packages/frontend/project/trial-banner.tsx
src/packages/frontend/project/websocket/connect.ts
src/packages/frontend/projects/actions.ts

The `too_many_free_projects` function was removed, hence free projects in restricted countries can't really do anything any more. This re-introduces this check, at the very end of the chain, by calling the endpoint directly.
~~What's left to do is to make this check an effect, such that a promise can be used.~~ Also, maybe add some caching, but I think that's not really necessary.
OK, what's left is testing. This is a hook and I think I found all usages and properly "await"ed them.

frontend: check if free project in restricted country is allowed to run

---

src/packages/frontend/lib/server-stats.ts
src/packages/frontend/project/client-side-throttle.ts

follow up to that free project in restricted countries limit.
the only real change is that this caches getting the stats data (globally, can be re-used by other parts of the frontend).
I tested this locally by restricting myself (country "XX") and one free project. It works! Even double checked with the debugger.
The `/stats` endpoint is cached for 5 minutes and now this here also for 5 minutes, but ok, a certain lag is fine for this.

frontend/free project limit: cache getting stats

---

src/packages/database/postgres-base.coffee

I haven't tested this. Should not cause any problems. Resolves a problem, where an index is removed, but the safety_check in `__do_query` says this is unsafe ... i.e. this one https://github.com/sagemathinc/cocalc/blob/master/src/packages/database/postgres-base.coffee#L709

db: bypass "safety_check" when dropping an index

---

src/packages/database/consts.ts
src/packages/database/pool/pool.ts
src/packages/database/postgres-base.coffee

- this fixes #6014
- uses the `statement_timeout` parameter of `pg.Client` and `pg.Pool` → ref: https://node-postgres.com/apis/client
- makes the timeout configurable via an env variable

db: set statement_timeout

---

src/packages/frontend/jupyter/commands.ts
src/packages/frontend/jupyter/keyboard-shortcuts.tsx

I instinctively use the delete key all the time, but it never works. This adds a shortcut for it.

frontend/jupyter: add shortcut to delete a cell with the delete keys

---

src/packages/frontend/project/no-internet-banner.tsx
src/packages/frontend/project/page/page.tsx
src/packages/frontend/project/project-banner.tsx
src/packages/frontend/project/start-button.tsx
src/packages/frontend/project/trial-banner.tsx
src/packages/frontend/project_actions.ts
src/packages/frontend/project_store.ts

- see #6314
- overall, this diversifies the trial banner into a second variant, which is dismissible and only talks about the missing internet quota – even for those cases, where there is a license (but probably expired or exhausted)
- this also uses the run quota (or its stale data) for the trial and no internet banner. Hence, this is much more accurate.

frontend/project banner: this adds a "no internet" banner

---

src/packages/util/compute-images.ts

Before merging #6284 it makes sense to introduce a stable version of 22.04, which is not the default yet. Also, this adds recent snapshots.

software images: make 22.04 more prominent, but not yet the default

---

src/packages/frontend/project/no-internet-banner.tsx
src/packages/frontend/project/settings/quota-console.tsx
src/packages/frontend/project/trial-banner.tsx

- if there is internet access, there must be a license applied ... this means it's not a trial any more.
- it's also not a trial project, if there is a license somewhere – i.e. it assumes users are beyond trial testing.
– in these cases, this makes the banner dismissable as well
- saw a crash when there is no quota set for the admin quota editor

frontend/trial banner: remove "Trial" if internet accessible

---

src/packages/frontend/project/settings/run-quota/hooks.tsx
src/packages/util/upgrade-spec.js

- main idea is to get rid of the two additional fields in the `field_order`. This is used in several places and sure, this could cause problems.
- I'm only adding these two field names in the hook, specific to listing the run quotas in the project settings (without modifying that fields list)
I wasn't able to test this, since I don't know yet how to get these deprecated upgrade subscriptions. In any case, I think this is certainly of help.

Fix quota upgrades form

---

src/packages/next/components/billing/subscriptions.tsx
src/packages/next/components/licenses/license.tsx

I saw (and maybe @DrXyzzy meant that?) missing descriptions in the list of subscriptions. To fix this, I'm reusing a component, which does load more info about a license … only in those cases, where it isn't part of the list of invoices it got. Long story short, here are before and after screenshots of what I have in my dev project:
(apart from that, I'm also adding the optional `style` property for the outer div. That was in the list of props, but not used at all)

next/billing/subscriptions: fill in blank descriptions

---

src/packages/database/postgres/site-license/hook.test.ts
src/packages/util/quota.test.ts
src/packages/util/upgrades/quota.ts

- this is a very subtle problem I have never seen before, but makes 100% sense: somewhere the quota function modifies licenses, which have unintended consequences when used again. all tests just assume a single call!
- however, the postgres/site-license/hook progressively applies licenses and in some cases, subsequent calls with modified licenses start to be incompatible.
- there is now a test applying partially and then all licenses, which trigger this problem.
- but it doesn't fail, because quota now does a deep copy of all arguments

util/quota: avoid modifying passed in objects

---

src/packages/next/components/landing/header.tsx
src/packages/next/components/landing/sub-nav.tsx

only show the subnav menu, when there is actually data for it

next/subnav: push down the logic when to show it 

---

src/packages/next/components/landing/cocalc-com-features.tsx

just a small typo: the "onprem" section wrongly links to features, so I collected those URLs and fixed it

next/index: wrong link for onprem

---

src/packages/next/next.config.js

navigating back usually restores the scroll position. not so with next.js's magic. this enableds this.

next: enable scrollRestoration

---

src/packages/hub/servers/app/customize.ts
src/packages/hub/servers/express-app.ts
src/packages/hub/webapp-configuration.ts

Requesting the strategies right after starting the hub might throw, because the passport manager isn't available yet. This fixes this by waiting on it, essentially.
I also made it so the json sent via /customize is pretty-printed, which makes it easier to read for debugging. (that's where that strategy info is sent to the frontend)

hub: passport manager not available right after startup

---

src/packages/hub/package.json

«hub» package need deps «escape-html»
```
client.coffee
36:{ escapeHtml }       = require("escape-html")
```
- [ *] Testing instructions are provided, if not obvious
- [ *] Release instructions are provided, if not obvious

«hub» package need deps «escape-html»

---

src/packages/server/auth/sso/oauth2-user-profile-callback.ts

When OAuth1 SSO is used, here (because of hardcoding for oauth2) crash (null dereference) occured 
I am not sure that «useAuthorizationHeaderforGET» member exists for «_oauth2» (have no OAuth2 test setup), but this member definitely absent for «_oauth».
- [*] Testing instructions are provided, if not obvious
- [*] Release instructions are provided, if not obvious

Fix crash when OAuth1 protocol is used

---

src/packages/frontend/frame-editors/frame-tree/title-bar.tsx

- don't show scrollbars, i.e. this is ugly:
- add "title to be able to see full title when hovering

frontend/terminal: fix showing scrollbars when narrow

---

src/packages/next/components/store/dedicated.tsx
src/packages/next/components/store/overview.tsx

Yesterday, Blaec mentioned to add links from the store to the on-prem offerings. This does it in two spots…

next/store: link to on-prem offerings

---

src/packages/frontend/course/common/student-assignment-info.tsx

Somehow, this must have been broken in the latest update. Wrapping this in a div helped.
Also removed a margin from the button, unclear what its purpose is.

frontend/course/assignment: fix entering a grade in markdown input

---

src/packages/frontend/chat/chatroom.tsx
src/packages/frontend/chat/input.tsx
src/packages/frontend/components/color-picker.tsx
src/packages/frontend/editors/markdown-input/multimode.tsx
src/packages/frontend/editors/slate/edit-bar/color-button.tsx
src/packages/frontend/editors/slate/edit-bar/component.tsx
src/packages/frontend/editors/slate/edit-bar/marks-bar.tsx
src/packages/frontend/editors/slate/editable-markdown.tsx

* Antd fix modal deprecation, that "color" modal in the MD editor
* Sorting various imports along the way
* Using `localStorage` directly could cause a crash, hence using the wrapper with the LRU cache instead

frontend: small code fixes

---

src/packages/frontend/_project_page.sass
src/packages/frontend/components/sortable-tabs.tsx
src/packages/frontend/project/page/file-tabs.tsx

This tweaks the files tab bar and the dropdown showing more.

frontend/files-tab: make them wider and tweak the "more" dropdown

---

src/packages/frontend/editors/markdown-input/complete.tsx

This touches the "@" menu, to get rid of the deprecation, and well, I also made a font slightly smaller and made sure to popup to the top in chat (since for me, it sometimes opens up to the bottom and then I can't see or select some). I also tested this in slate markdown, works ok as well.

frontend/chat+slate: antd modernize @-dropdown

---

src/packages/frontend/account/account-page.tsx
src/packages/frontend/account/ssh-keys/ssh-key-list.tsx
src/packages/frontend/antd-bootstrap.tsx
src/packages/frontend/components/help-icon.tsx
src/packages/frontend/components/setting-box.tsx
src/packages/frontend/jupyter/about.tsx
src/packages/util/theme.ts

- account tabs: now an array of objects  + some tweaks to the wrapper component
- ssh list: actually, that help popup icon needs some tweaks
- jupyter: modernize about modal and fix jupyter vs. classic link to docs

frontend: antd deprecations

---

src/packages/frontend/account/default-file-name-generator.ts
src/packages/frontend/account/other-settings.tsx
src/packages/frontend/account/store.ts
src/packages/frontend/account/types.ts
src/packages/frontend/project/ask-filename.tsx
src/packages/frontend/project/utils.ts
src/packages/frontend/project_actions.ts
src/packages/util/db-schema/defaults.ts

- change the default type of new generated file names to be `ymd_semantic` (after 4 years, instead of quote: "Change it to "semantic" after a week or two…")
- add special cases for e.g. folders and x11
- sanitize the family type
- fix the time-prefix string for python and sage files, i.e. all underscore, not just the filename tokens.

frontend/project/new filename: make ymd_semantic the default 

---

src/packages/frontend/project/start-button.tsx

minor tweaks to the project's connecting/start banner. i.e. make it a banner (like the other project banner) and some minor cleanups.

frontend/project: tweak "connecting/start" banner

---

src/packages/frontend/_antd_fix.sass
src/packages/frontend/frame-editors/frame-tree/title-bar.tsx

this fixes #6467
it also removes two divs, which are replaced by left and right margins :shrug:

frontend/antd: make dialog modals be on top of popovers -- #6467

---

src/packages/frontend/chat/input.tsx
src/packages/frontend/chat/side-chat.tsx
src/packages/frontend/editors/markdown-input/multimode.tsx
src/packages/frontend/editors/slate/editable-markdown.tsx

Ref #6454
With this, there is a toggleable Popover with these EditBar-buttons

frontend/side-chat: fixing hidden slate icons

---

src/packages/server/projects/control/multi-user.ts
src/packages/server/projects/control/util.ts

Implementation of discussion 
https://github.com/sagemathinc/cocalc/discussions/6484#discussioncomment-5110002
by simplest solution «just never delete the user.».
Actually, this need little more than commenting one line (+one function), but looks it working, 
tested on production (`pnpm make`) on one of my cocalc sites.
(Also I look at Project Settings UI, <s>and it seems to me, looks like there is a lot of attributes of table `projects` that has no UI, also there may be lot of other setting that may be better store as JSON doc…</s> so I decide not to touch «Project Settings» right now, let Cocalc Architect makes this solution). 
- [*] Testing instructions are provided, if not obvious
Testing is obvious, «start»/«stop» many times any project, and on stopped state something like «sudo -u …

[needs review] Lets dont remove user on stop project

---

src/packages/next/components/landing/sub-nav.tsx
src/packages/next/pages/software/executables/[name].tsx
src/packages/next/pages/software/index.tsx
src/packages/next/pages/software/octave/[name].tsx
src/packages/next/pages/software/python/[name].tsx
src/packages/next/pages/software/r/[name].tsx
src/packages/next/pages/software/sagemath/[name].tsx

this is just a small details that bugged me. on the next/software pages, when switching the software environment, it always jumped back to the executables sub-page. this gets rid of that behavior.
Also, a bit of title/css cosmetics.

next/software: switching software env should not switch subpage category

---

src/packages/frontend/project/page/file-tab.tsx
src/packages/project/named-servers/list.ts

- fix #6492 by disabling it
- make jupyter lab's RTC configurable (env var)
- make the command more readable by splitting it, and adding some comments about what they are
- fix #6490 
Testing: what I checked was starting both jupyter servers in my dev project. Not sure how to trigger the xsrf cookie problem … but well, I added a link to the docs in the sources, which imply this will fix it :man_shrugging:

Tweak servers jupyterlab issue 6492

---

src/packages/next/components/billing/subscriptions.tsx
src/packages/next/components/licenses/license.tsx
src/packages/server/billing/get-invoices-and-receipts.ts
src/packages/server/stripe/client.ts
src/packages/util/misc.ts
src/packages/util/types/stripe.ts

Right now, the "Cost" column in the overview of subscriptions only lists the cost for a single unit. I.e. run limit/quantity is not taken into account. This was a bit tricky, because the info is actually in the license data, but that isn't always available (like, it is for the description column as well). In any case, here are two rows from my dev project, shows the actual cost in the cost column.
(I'm also adding some typing to have less surprises about which field is where, etc.)

next/billing/subscriptions: fix the "cost" column

---

src/packages/next/package.json

This is just tiny, and we discussed this and forgot about it. I think that build-dev step (the first one of two) in next's build target is pointless. I was wondering if this should be "build-deps" instead, but well, I don't think so. We always call make-dev (and that workspaces script). So, with that change it's more straight to the point.
Why the change? Running build-dev twice wastes a lot of time.

next/npm: do not call build-dev twice from build target

---

src/packages/next/components/logo.tsx

I guess by mistake, 5088bddeb4584dbceed5c6c19c3cd4d4799c403c introduced a closing bracket, which is visible on the HTML page

next/index: "fake" logo for on-prem has a closing bracket

---

src/packages/next/lib/landing/consts.ts
src/packages/next/lib/landing/landing.test.ts
src/packages/next/lib/landing/software-data.ts
src/packages/next/lib/landing/software-specs.ts

I noticed performance issues upon loading the pages. This split next/landing/consts up to avoid loading the software fallback data. There are probably other such silly details going on as well. This should also help with next.js development, because there is less client code to keep track of.
next.js full build on master:
```
Route (pages)                                    Size     First Load JS
┌ λ /                                            8.8 kB         4.96 MB
```
after the first commit:
```
Route (pages)                                    Size     First Load JS
┌ λ /                                            8.8 kB          1.3 MB
```
… I looked further, and what I saw are many embedded source maps. I don't know if they're also in production, because the files looks different …

next: reduce size of assets

---

src/packages/next/components/auth/sso.tsx
src/packages/next/pages/sso/index.tsx

There is a mysterious (?) margin on the left. Removing this turns this
into

next/sso: StrategyAvatar icons referenced by an URL are cut off on the right

---

src/packages/frontend/_projects.sass
src/packages/frontend/components/path-link.tsx
src/packages/frontend/project/history/log.tsx
src/packages/frontend/project/page/home-page/block.tsx
src/packages/frontend/project/page/home-page/index.tsx
src/packages/frontend/project/page/home-page/recent-files.tsx
src/packages/frontend/projects/project-row.tsx

- this adds a block for "recent files" (deduplicated, easy to click due to using a large list entry) for convenience
- reorgs some details with that home page, e.g. the avatar is less distracting, instead behaves like title and description
- when GPT disabled, remove GPT box entirely, such that the other boxes can move up
- max width, reactive for narrower screens
- and some small refactorings in some of the files I saw

frontend/project/home: show recently active files on home page

---

src/packages/frontend/components/paste-button.tsx
src/packages/frontend/frame-editors/chatgpt/title-bar-button.tsx
src/packages/frontend/frame-editors/jupyter-editor/cell-notebook/actions.ts
src/packages/frontend/jupyter/_jupyter.sass
src/packages/frontend/jupyter/cell-input.tsx
src/packages/frontend/jupyter/cell-list.tsx
src/packages/frontend/jupyter/chatgpt/explain.tsx
src/packages/frontend/jupyter/insert-cell.tsx
src/packages/frontend/jupyter/output-handler.ts
src/packages/frontend/project/page/home-page/chatgpt-generate-jupyter.tsx

The goal here is to improve that blue hover insert bar
and the jupyter cell:

frontend/jupyter: improve quick insert bar

---

src/packages/frontend/jupyter/_jupyter.sass
src/packages/frontend/jupyter/insert-cell.tsx

- during hover out, it stays around a bit longer
- at the bottom, a less dominantly styled bar stays around all the time
- the one at the bottom is now also visible for touch devices (the others ones are still not there at all)

Jupyter tweak insert bar

---

src/packages/frontend/jupyter/status.tsx

When the kernel starts, this shows a "startup progress indicator" where the cpu/mem info is.
It also classifies "starting" as "starting || spawning", which changes the displayed text a little bit. e.g. it now says the kernel is starting when it starts.

jupyter/status: startup progress indicator

---

src/packages/frontend/app/notifications.tsx

First fallout I noticed, the unread chat counter didn't go up. Looks like it happened in this line: https://github.com/sagemathinc/cocalc/pull/6610/files#diff-81379188322f5ecf5bf580873fa41662dd5f19f326cc4dfde78a59498a9a3a8fR51

frontend/notification: "news" branch erroneously removed a dependency

---

src/packages/project/autorenice.ts
src/packages/project/project-info/server.ts
src/packages/project/sync/usage-info.ts
src/packages/project/usage-info/server.ts

- use getLogger instead of debug directly
- sort imports

project: use getLogger everywhere

---

src/packages/pnpm-lock.yaml
src/packages/project/init-kucalc.ts
src/packages/project/jupyter/pool-params.ts
src/packages/project/jupyter/pool.ts
src/packages/project/package.json
src/packages/project/project-setup.ts

- jupyter pool parameters can be tuned by either the admin or by the user via project env vars.
- also: respect env vars by initializing that juypter pool **after** env vars are set.
- installing @types/node-cleanup for development, can't hurt
What I tested:
Setting this in my dev project's env variables:
```
{
"ASDFASDF": "12345",
"COCALC_JUPYTER_POOL_SIZE": "3"
}
```
and then after restarting the notebook (and well, earlier there was a python3 notebook) it did spawn 3:
```
cocalc:debug:jupyter:pool replenishPool {"name":"python3","opts":{"env":{"COCALC_JUPYTER_KERNELNAME":"python3","PLOTLY_RENDERER":"colab"}}} {"size":3,"timeout_s":3600}
```
Then, setting the size to 0 and restarting, there were no extra kernels in my processes list.

project/jupyter-pool: configure from env vars + respect env vars

---

src/packages/database/postgres/news.ts
src/packages/next/components/landing/news-banner.tsx
src/packages/next/components/news/news.tsx
src/packages/next/components/news/useDateStr.ts
src/packages/next/pages/index.tsx
src/packages/util/types/news.ts

This replaces the static yellow banner on the index page with the most recent news item + link to all news.

next/news: show most recent one on landing page

---

src/packages/frontend/project/no-internet-banner.tsx
src/packages/frontend/project/project-banner.tsx
src/packages/frontend/project/trial-banner.tsx
src/packages/frontend/site-licenses/purchase/buy-license-for-project.tsx
src/packages/util/consts/billing.ts

Tweaking the trial banner
1. dismissable in the first month
2. smaller in the beginning
3. the "with a license" buy link uses the same component, as we use for the buy button. i.e. this triggers automatic application of the license to the project.
4. explicitly mention "internet access" is missing
5. Welcome → "Hello :hand:" and a link to the documentation (main index page)
Initially
After 10 days, a bit more prominent but dismissable
After 30 days

frontend/trial-banner: make it dismissable in the first month

---

src/packages/next/components/landing/news-banner.tsx
src/packages/next/components/news/news.tsx

next/index: ensure news are one line only 

---

src/packages/static/src/crash.tsx

This is just a minor change to the crash box, to mention to update browser and clean this up a little bit. Motivation is that I got this crash report from an on prem installation: `SyntaxError: private fields are not currently supported` related to latex/pdfjs. Not confirmed, but the error happens for old Firefox versions: https://caniuse.com/mdn-javascript_classes_private_class_fields
So, that's why there is now a link to a page I found, which will tell you if your browser is outdated.

static/crash: mention to update browser

---

src/packages/frontend/project/trial-banner.tsx
src/packages/frontend/site-licenses/input.tsx
src/packages/frontend/site-licenses/purchase/buy-license-for-project.tsx
src/packages/frontend/site-licenses/select-license.tsx

A little tweak to the trial banner, showing the link to redeem a voucher and when applying a license, buy+redeem buttons.

frontend/trial banner: voucher redeem + buy button

---

src/packages/frontend/account/tours.tsx
src/packages/frontend/antd-bootstrap.tsx
src/packages/frontend/frame-editors/latex-editor/build.tsx
src/packages/frontend/jupyter/output-messages/widget.tsx
src/packages/frontend/project/explorer/path-navigator.tsx
src/packages/frontend/project/explorer/path-segment-link.tsx
src/packages/next/components/landing/main.tsx
src/packages/next/pages/news/[id].tsx
src/packages/next/pages/news/[id]/[timestamp].tsx
src/packages/next/pages/news/edit/[id].tsx

-  Antd Tabs.TabPane is deprecated
- Breadcrumb.Item

frontend: address Antd deprecations

---

src/packages/frontend/codemirror/custom-modes.ts
src/packages/frontend/codemirror/mode/python.js
src/packages/frontend/file-associations.ts

Just a little playful thing: adding support for mojo files, hidden in the menu, and testing if the emoji extension works.

frontend: add mojo file extensions support (hidden, like python)

---

src/packages/next/components/auth/password-reset.tsx
src/packages/next/components/auth/sign-in.tsx

Next's "sign-in" page raised an hydration error, and I also made the CSS of the main div the same as with the password reset page.

next/auth/sign-in: fix hydration error

---

src/packages/frontend/project/page/flyouts/log.tsx
src/packages/frontend/project_actions.ts

- fixes https://github.com/sagemathinc/cocalc/issues/6765 by not deleting the table.
- there is also the recent file list for the "home" part, which doesn't use the "_all" variant. So, I'm not sure if this is a good fix or not. In general, I wasn't aware that there are two separate data sources for the activity log. I thought there is one and with that button, it just gets longer.

frontend/flyout/log: also load the complete log

---

src/packages/frontend/project/page/file-tab.tsx
src/packages/frontend/project/page/flyouts/control.tsx
src/packages/frontend/project/page/flyouts/servers.tsx
src/packages/frontend/project/page/home-page/button.tsx
src/packages/frontend/project/page/page.tsx
src/packages/frontend/project/page/tabs.tsx
src/packages/frontend/project/settings/run-quota/hooks.tsx
src/packages/frontend/project/settings/run-quota/misc.ts
src/packages/frontend/project/settings/run-quota/run-quota.tsx

- also convert MB→GB to save width

frontend/flyout: round 4 of fixes

---

src/packages/frontend/account/other-settings.tsx
src/packages/frontend/chat/register.ts
src/packages/frontend/components/copy-button.tsx
src/packages/frontend/components/help-icon.tsx
src/packages/frontend/components/path-link.tsx
src/packages/frontend/editors/task-editor/find.tsx
src/packages/frontend/editors/task-editor/list.tsx
src/packages/frontend/frame-editors/task-editor/editor.ts
src/packages/frontend/index.sass
src/packages/frontend/project/history/log-entry.tsx
src/packages/frontend/project/history/utils.ts
src/packages/frontend/project/page/common.tsx
src/packages/frontend/project/page/file-tab.tsx
src/packages/frontend/project/page/flyouts/body.tsx
src/packages/frontend/project/page/flyouts/components.tsx
src/packages/frontend/project/page/flyouts/files.tsx
src/packages/frontend/project/page/flyouts/header.tsx
src/packages/frontend/project/page/flyouts/log.tsx
src/packages/frontend/project/page/flyouts/new.tsx
src/packages/frontend/project/page/home-page/recent-files.tsx
src/packages/frontend/project/page/page.tsx
src/packages/frontend/project/page/tabs.tsx
src/packages/frontend/project/search/body.tsx
src/packages/util/db-schema/accounts.ts

-  make the entire file item area clickable, but prevent the dropdown menu from triggering a click
- instead of caret sign, make background like hover. border's don't work well.
- load "full log" button
- keyboard scroll support for files in log entry + opening via return key
- get rid of popovers + remove associated account "other setting"
- fix opening file from log entries (re-using existing function)
- search: 
- compact settings, use help icon for additional info
- nested scrollbars if necessary
- do not copy if text is selected, also add a small copy button
- flyout vs. tasks: remove key handler when focused
- however, the focus never flipped back to tasks. how does chat do this? I had to change some code in `task-editor/list.tsx` **this is the only change outside flyouts, and it …

flyout: 5th round of improvements

---

src/packages/frontend/project/history/log-entry.tsx
src/packages/frontend/project/history/types.ts

Just a small detail after yesterday. Marking the "time" as optional in the type. It doesn't help when packed into the TypedMap, but at least the situation in general is written down somewhere.

frontend/log: mark EventRecord.time as optional

---

src/packages/frontend/project/explorer/explorer.tsx
src/packages/frontend/project/trial-banner.tsx
src/packages/frontend/project/warnings/course-project.tsx
src/packages/frontend/projects/actions.ts

- tried testing upgrades, but ended up debugging student pay. there is a test, only setting account_id and email only if both are known. [the corresponding test is an or](https://github.com/sagemathinc/cocalc/blob/08e186f36aeddee8a8476bd5b1ac62f17acb40c2/src/packages/frontend/projects/store.ts#L162).
- also saw odd margins with the trial banner, something must have changed slightly. in any case, now there is a link to buy upgrades.

Fix student pay and banner

---

src/packages/frontend/antd-bootstrap.tsx
src/packages/frontend/project/page/flyouts/components.tsx
src/packages/frontend/project/page/flyouts/files-bottom.tsx
src/packages/frontend/project/page/flyouts/files.tsx

this makes file selection a modal mode, which can be triggered in various ways (click on icon, explicit button, shift/ctrl key clicks). otherwise it opens the file. also, adding details like closing an active editor with a middle mouse click.

frontend/flyout/files: modal file selection

---

src/packages/frontend/assistant/body.cjsx
src/packages/frontend/assistant/dialog.cjsx
src/packages/frontend/assistant/footer.cjsx
src/packages/frontend/assistant/header.cjsx

the Space→Gap renaming was incomplete, and this also tweaks the header a little bit.

frontend/sagews/examples: fix Space/Gap renaming and broken header

---

src/packages/frontend/project/page/flyouts/components.tsx
src/packages/frontend/project/page/flyouts/files.tsx
src/packages/frontend/project/page/flyouts/log.tsx

- log entries can't be selected: fixes #6821
- mitigate stuck hover checkboxes by only showing one at a time
- log: trigger click on file icon, since it can't be selected
- flex-expand file item label, such that close and published icons are on the right hand side
- log/file entry: middle mouse click closes, just like with a files/file entry

frontend/flyout: 5th round of fixes

---

src/packages/frontend/project/page/file-tab.tsx
src/packages/frontend/project/page/flyouts/body.tsx
src/packages/frontend/project/page/flyouts/components.tsx
src/packages/frontend/project/page/flyouts/consts.ts
src/packages/frontend/project/page/flyouts/files.tsx
src/packages/frontend/project/page/flyouts/log.tsx
src/packages/util/misc.ts

- this depends on https://github.com/sagemathinc/cocalc/pull/6824 ... which must be merged first
- if flyout expands, show file attribute columns
upon expanding, show 2 or 3 columns:
and columns depend a little bit on sort column, i.e. you can see the values the sort ordering is based on

frontend/flyout: file attributes in files list

---

src/packages/database/postgres/user-tracking.ts
src/packages/frontend/project/page/flyouts/log.tsx
src/packages/util/db-schema/tracking.ts

- add col and set expire to 30 days on user_tracking entries
- add flyout/log open file tracking

User tracking expire

---

src/packages/frontend/account/other-settings.tsx
src/packages/frontend/index.sass
src/packages/frontend/project/explorer/explorer.tsx
src/packages/frontend/project/explorer/path-navigator.tsx
src/packages/frontend/project/explorer/path-segment-link.tsx
src/packages/frontend/project/page/file-tab.tsx
src/packages/frontend/project/page/flyouts/files.tsx
src/packages/frontend/project/page/flyouts/header.tsx
src/packages/frontend/project/page/flyouts/log.tsx
src/packages/frontend/project/page/tabs.tsx
src/packages/frontend/project/page/vbar.tsx
src/packages/frontend/project_actions.ts

-  fix not recording browser history when switching directories, this also fixes this for clicking on the breadcrumb path selector
- larger mini breadcrumb dot
- sync file-filter and log-filter search state + debouncing
- close icon is the same as for tabs
- account level option to change vertical bar layout: both, flyout or pages ... and adding a select menu to the bar to surface this

Flyout enhancements #7

---

src/packages/frontend/course/export/export-assignment.ts
src/packages/frontend/jupyter/nbconvert.tsx
src/packages/frontend/project/websocket/api.ts
src/packages/jupyter/kernel/kernel.ts

- increase nbconvert timeout to 60s (saw a timeout for a user)
- fix 2x antd deprecation in nbconvert modal dialog

nbconvert: double timeout to 60s

---

src/packages/frontend/index.sass
src/packages/frontend/project/page/tabs.tsx

frontend/flyout: make hover/active tabs more visible in pure flyout mode

---

src/packages/frontend/collaborators/add-collaborators.tsx
src/packages/frontend/project/page/flyouts/files-bottom.tsx
src/packages/frontend/project/trial-banner.tsx

- Select's "showArrow" is default and will be removed
- a `Collapse.Panel` → `items`
- Alert's closeText is closeIcon now

fixing a couple  antd deprecations

---

src/packages/database/postgres/site-license/hook.test.ts
src/packages/database/postgres/site-license/hook.ts
src/packages/frontend/site-licenses/rules.tsx

Under PayGo, a dedicated disk, and other special licenses like ext_rw and patches should stay active. Any other license should be disabled. The logic is in `disallowUnderPAYGO`. I also tried to add a test, but it didn't work – I'll leave the code as a comment to complete this later.  Hence this fixes https://github.com/sagemathinc/cocalc/issues/6881
Additionally, I added an explanation that regular/boost are ineffective under PayGo and clarified dedicated disks a little bit.
paygo active:
paygo inactive:

Mix dedicated disk with paygo

---

src/packages/frontend/projects/projects-nav.tsx
src/packages/frontend/projects/projects-page.tsx

- indicator icon for no internet (red globe, re-using the wifi icon in any way is too confusing, because it appears on the right of the tab when connecting)
- also a red warning text in hover box
- only shows up when running and the purchase aspect only in kucalc mode
---

frontend/project-tab: if there is no internet, add an indicator icon to the project tab

---

src/packages/frontend/project/settings/has-internet-access-hook.ts
src/packages/frontend/projects/projects-nav.tsx

This should fix the indicator icon. This actually fixes the more fundamental `useProjectHasInternetAccess` hook, which assumes there is always internet access in non-kubernetes deployments
this is the "yes" case for cocalc.com, showing the banner as well
no indicator even though network is false, the docker "kucalc==no" case
and on-prem, similar to production but without the banner

frontend/no internet hook: assume internet access for non-kubernetes deployments and show tooltip if project tab popover is disabled

---

src/cocalc.code-workspace
src/packages/frontend/components/icon.tsx
src/packages/frontend/project/settings/quota-editor/pay-as-you-go.tsx
src/packages/next/components/store/index.tsx
src/packages/next/components/store/overview.tsx
src/packages/next/lib/styles/layouts.tsx
src/packages/next/pages/pricing/onprem.tsx

This adds on-prem, vouchers and pay as you go more prominently on the store page ... with links and a short explanation text.

next/store: tweak overview page

---

src/packages/frontend/file-associations.ts

Added support for `.cu` files via alias to `.c` syntax highlighting.
See below screenshot:

#6916: Added text editor support for `.cu` file extension (for CUDA C files)

---

src/packages/next/components/misc/date-range.tsx
src/packages/next/components/store/usage-and-duration.tsx

This pull request only partially addresses #6920; I'm quite sure how to spoof invoices to test changes, but I did get the timezone name sorted out for license start/end dates:

#6920: Added time zone label to license start/stop times.

---

src/packages/frontend/custom-software/selector.tsx

This tells the user that standard software environments are changeable, while custom ones aren't. but they can copy files.

frontend/new project: tell the user standard software environments are changeable

---

src/packages/frontend/project/settings/datastore.tsx

I think I understand the issue and this should fix #6946 – I wasn't able to reproduce this in testing, though.

frontend/datastore: break form apart to avoid re-rendering flicker

---

src/packages/frontend/antd-bootstrap.tsx
src/packages/frontend/customize.tsx
src/packages/frontend/project/settings/body.tsx
src/packages/frontend/project/settings/quota-editor/pay-as-you-go.tsx
src/packages/frontend/project/warnings/no-network.tsx
src/packages/frontend/project/warnings/non-member.tsx
src/packages/frontend/project/warnings/util.ts
src/packages/util/theme.ts

- only show quota warnings in project settings, if those are really not set – based on run quota
- refactor some parts of the paygo upgrade panel
- emphasize more clearly when an upgrade schema is configured – I got confused and well, a  highlighted button and an explanation text would have helped me
- also, I tweaked the default schema to be a small one, but with internet and member hosting. there is now a new "budget" variant, which removes member hosting and which isn't the default (and it also does not show up, when the paygo quotas are cleared)

tweaks around paygo and missing quota warnings

---

src/packages/frontend/components/search-input.tsx
src/packages/frontend/project/explorer/explorer.tsx
src/packages/frontend/project/explorer/file-listing/no-files.tsx
src/packages/frontend/project/explorer/search-bar.tsx
src/packages/frontend/project/page/flyouts/files-header.tsx

if a search in files (explorer or flyout) finds nothing, shift+return creates it. just return leads to accidentally created jupyter notebooks (default file type).

frontend/files: shift+return to create file/folder

---

src/packages/frontend/components/time-ago.tsx
src/packages/frontend/project/page/flyouts/body.tsx
src/packages/frontend/project/page/flyouts/components.tsx
src/packages/frontend/project/page/flyouts/files.tsx
src/packages/frontend/project/page/page.tsx

- don't show flyout in fullpage
- tweak some margins/padding
- possibly fix #6918
- when clicking on the timestamp of a file to open it, do not show the timestamp toggle. maybe that should never show up if someone clicks there.

flyout fixes: fullpage and maybe the file listing click

---

src/packages/frontend/purchases/purchases-page.tsx
src/packages/frontend/purchases/purchases.tsx

The running balance now shows as a new column in the `PurchasesTable` component, and a new field is shown at the bottom with the user's current balance:
Addresses #6928 and #6919.

#6928, #6919: Added current and running balance to `PurchasesTable` component

---

src/packages/frontend/project/explorer/compute-file-masks.ts
src/packages/frontend/project/history/utils.ts
src/packages/frontend/project/page/flyouts/file-list-item.tsx
src/packages/frontend/project/page/flyouts/files-bottom.tsx
src/packages/frontend/project/page/flyouts/files-terminal.tsx
src/packages/frontend/project/page/flyouts/files.tsx
src/packages/frontend/project/page/flyouts/header.tsx
src/packages/frontend/project/page/flyouts/log.tsx
src/packages/frontend/project/settings/run-quota/run-quota.tsx
src/packages/frontend/site-licenses/site-license-public-info-component.tsx
src/packages/next/components/landing/executables-table.tsx
src/packages/util/misc.ts

- don't popup fullpage tooltip by default, only highlight
- not flyout: remove some padding in the next/software/execs table to make it more compact
- context menu PoC: selects file (if none are selected) for single file operations and download/view – or opens multi-file operations. see below.
- fix too much focusing in files mini terminal
- fix #6977

Flyout tweaks #4

---

src/packages/database/postgres/stats.test.ts
src/packages/database/postgres/stats.ts
src/packages/next/components/statistics/opened-files.tsx
src/packages/util/db-schema/stats.ts

- adding tracking for *.slides files
- showing them on the stats page
- also some type-related cleanup and testing the generated stats query

next/utils: adding tracking and stats for *.slides files

---

src/packages/frontend/purchases/api.ts
src/packages/frontend/purchases/purchases.tsx
src/packages/next/pages/api/v2/purchases/get-balance-admin.ts

...to support querying user balance as admin. Updated `getBalance` function in frontend to fetch account-specific balance when `account_id` is provided. Decoupled purchases query and balance/total computation.
Fixes #6974 .
See below screenshot:

#6974: Added `/v2/api/purchases/get-balance-admin` API endpoint 

---

src/packages/project/named-servers/control.ts

Obviously wrong shebang for command.sh
(just found debugging why «failed to load VS Code» on my setup)

obviously wrong shebang for command.sh

---

src/packages/frontend/codemirror/mode/python.js

Fixes #6580.
Before:
After:
(file copied from https://github.com/codemirror/codemirror5/blob/659df46b1f53cd94952058e23687f9e58e1b997e/mode/python/python.js)

#6580: Updated `python.js` CodeMirror mode.

---

src/packages/database/postgres-base.coffee
src/packages/database/postgres-server-queries.coffee
src/packages/database/postgres/pii.test.ts
src/packages/server/jupyter/execute.ts
src/packages/server/projects/control/kucalc.test.ts
src/packages/server/projects/control/kucalc.ts
src/packages/util/db-schema/copy-paths.ts
src/packages/util/db-schema/file-access-log.ts
src/packages/util/db-schema/jupyter.ts

* db/file_access_log: introduce "expire" column, with either the PII retention or 1 year as fallback
* add test for all possible pii expiration values, since we parse them
* db/central_log: expire after 1 year, unless it's a special case
* db/copy_paths: add an expiration for that kucalc related table
* with the additional detail, that scheduled copy events are postponed 1 month after the scheduled time, at least
* also added a new test for `control/kucalc.ts`
* db/jupyter_api_cache and jupyter_api_log: expire after 1 month (log is used for abuse, and only looks at 1 hour ago … 1 month is enough data to still have enough insight)
---
Test: I went through the tables in our kucalc test environment, including checking the copy event and the API call for scheduled copies

expire more table data

---

src/packages/frontend/app/context.tsx
src/packages/frontend/compute/compute-server.tsx
src/packages/frontend/package.json
src/packages/next/package.json
src/packages/pnpm-lock.yaml

- in my chrome (and not firefox) I had this weird issue with a stuck div in the background, when closing the compute server edit modal. it's weird, because all other modals I tried worked.
- I figured out what setting causes it: the disabled animation in the antd configuration! So, this is kind of a bug, caused by a race condition in antd, and could be triggered randomly. maybe because that modal is more complex than others.
- In any case, I found out, there is a newer way how to disable animations, and that's what this switches to
- I've also extracted that modal dialog into its own small component – can't hurt
- :warning:  the  **most impactful** change is to update to the newest antd version.

fix compute server edit modal

---

src/packages/frontend/project/page/flyouts/active-tabs.tsx
src/packages/frontend/project/page/flyouts/active-top.tsx
src/packages/frontend/project/page/flyouts/active.tsx
src/packages/frontend/project/page/flyouts/files-header.tsx
src/packages/frontend/project/page/flyouts/filter-warning.tsx
src/packages/frontend/project/page/flyouts/state.ts

- make two rows at the tops for the controls
- refactor filter warning, just like with the explorer flyout
- sort open tabs by custom or alphabetical order (I know about #7080 and recent usage, but that's for later)
- close all with popconfirm

Flyout active tweaks #3

---

src/packages/frontend/jupyter/chatgpt/split-cells.ts
src/packages/frontend/jupyter/insert-cell/ai-cell-generator.tsx
src/packages/frontend/project/page/home-page/ai-generate-jupyter.tsx

This fixes #7095 ... the basic idea is that inserting a single cell is treated just like creating a new notebook and inserting all cells. Hence it uses the same code to parse the output. The behavior is, such an extra output at the bottom is just another markdown cell. The screenshot below shows such a case, where I first inserted a single cell (no extra text happened), but then it did this in a follow up question. (the "2" and "3" in the adjacent cells are just there to confirm it really inserts all of that)

frontend/jupyter: improve how ai generated cells are inserted

---

src/packages/frontend/compute/ephemeral.tsx

An attempt to actually provide alternative wording instead of just criticizing the existing one! The idea is to provide description of what is actually happening when this option is selected, both before opening Help and when it is opened.

Rephrase ephemeral disk help and headings

---

src/packages/frontend/package.json
src/packages/pnpm-lock.yaml

There was a security issue with an outdated package, which is solved by updating jest. It's just a development dependency and version 2.4.3 has no actual change in the code itself. Hence this PR should not cause any issues. ~~Only thing left to do is to somehow test it.~~ OK, just changing flyouts or an editor tiling causes changes to local storage and it reads the config in when refreshing the page. So, all fine.

npm: update @cocalc/local-storage-lru to latest version 2.4.3

---

src/packages/frontend/frame-editors/chatgpt/model-switch.tsx
src/packages/frontend/frame-editors/chatgpt/title-bar-button.tsx

- fixes #7143 by making the button text and tooltip generated by the same function
- also slightly adjusts how the title looks like, only for the title button bar modal:
- testing: this doesn't change anything substantial about how this component is used.

frontend/llm model selector: generalize how button/tooltip is rendered

---

src/packages/database/package.json
src/packages/frontend/package.json
src/packages/hub/package.json
src/packages/pnpm-lock.yaml
src/packages/project/package.json
src/packages/server/auth/sso/passport-login.ts
src/packages/server/hub/auth.ts
src/packages/server/package.json
src/packages/sync/package.json
src/packages/terminal/package.json
src/packages/util/package.json

Updates the lodash types and gets rid of `saml2js`, which references an outdated lodash version. Bottom line, this PR has no change in the actual code.

lodash and @types/lodash

---

src/package.json
src/packages/frontend/purchases/purchases.tsx
src/packages/hub/package.json

Also added `express` to `package.json` to allow `pnpm run c` out of the box, along with support for attaching v8 debugger to `hub` when running in development mode.
Click the "Refresh" button in the `PurchasesTable` component at http://localhost:5000/settings/purchases. Verify that the balance is refreshed.

7150: Added balance refresh to `PurchasesTable` refresh handler.

---

src/packages/next/pages/api/v2/purchases/cancel-subscription.ts
src/packages/server/purchases/cancel-subscription.ts
src/packages/server/purchases/edit-license.ts
src/packages/server/purchases/maintain-subscriptions.ts
src/packages/server/purchases/resume-subscription.test.ts
src/packages/util/consts/billing.ts
src/packages/util/licenses/purchase/compute-cost.ts
src/packages/util/purchases/cost-to-edit-license.ts
src/packages/util/purchases/current-license-value.ts

This pull request reconciles the cost to cancel or resume an existing subscription. In particular, this pull request now computes the cost to resume a subscription based on the stored hourly rate of the subscription. There is still some follow-up work to do, so this is _not_ ready for merge, but these changes are ready for feedback. The items yet to be addressed are:
1) There is a discrepancy of precisely $0.02, which is introduced [here](https://github.com/schrodingersket/cocalc/blob/e78b23b3e07a5f0703d9c184266addbc1b7ab437/src/packages/util/purchases/cost-to-edit-license.ts#L177); the `modifiedPrice.discounted_cost` field is set to $0.02 when a refund is issued for an existing subscription license. It's not yet clear whether this should be removed when issuing a subscription.
2) Upon …

#7161: Fixed subscription cancel/resume logic when computing cost to resume or cancel an existing subscription.

---

src/packages/frontend/project/page/flyouts/consts.ts
src/packages/frontend/project/page/flyouts/files-bottom.tsx
src/packages/frontend/project/page/flyouts/files-controls.tsx
src/packages/frontend/project/page/flyouts/files-header.tsx
src/packages/frontend/project/page/flyouts/files-select-extra.tsx
src/packages/frontend/project/page/flyouts/files.tsx
src/packages/frontend/project/page/flyouts/utils.ts

for better or worse, this adds an "action bar" row at the top. other online file explorers alternate between the navigation/filter bar and the action buttons to safe space. We could try that in a follow up modification.

frontend/flyout/files: duplicate controls at the top

---

src/packages/frontend/project/page/flyouts/files-controls.tsx
src/packages/frontend/project/page/flyouts/files-select-extra.tsx

This is a silly bugfix: only show the action buttons if at least one file is selected. otherwise those clicks end up in a confusing void...

frontend/flyout/files: show top buttons when file is selected

---

src/packages/frontend/project/page/flyouts/file-list-item.tsx
src/packages/frontend/project/page/flyouts/files-controls.tsx
src/packages/frontend/project/page/flyouts/files-select-extra.tsx
src/packages/frontend/project/page/flyouts/files.tsx
src/packages/frontend/project/page/flyouts/log.tsx

* :warning: #7200 must be merged first
* ref: #7187 
* I assume this should also be removed for the log
* for me it's clearly more effective to have the X to close the file right there, speeds up opening and closing. But I also see how it ambiguous.

frontend/flyout: close button

---

src/packages/frontend/components/copy-to-clipboard.tsx
src/packages/frontend/share/config.tsx
src/packages/frontend/share/configure-name.tsx

When working on today's flyout PRs, I saw some odd details in the share dialog. e.g. on wider screens the options are no longer vertical, some text is to the side, and when the parent is shared, the access level is no longer visible, etc. Also, by introducing antd components for the layout and unifying or removing custom styles, it looks more consistent. I only made very small changes to the text and nothing regarding the actual functionality.

share dialog: various layout improvements

---

src/packages/next/components/store/checkout.tsx
src/packages/next/components/store/index.tsx
src/packages/next/components/store/menu.tsx
src/packages/next/components/store/vouchers.tsx
src/packages/next/lib/balance.ts

This pull request adds the user's balance to the top-right of the navbar in the Store. When not logged in, no balance is shown. The balance is refreshed when either a voucher or shopping cart purchase is completed or fails (the refresh is triggered in the corresponding `finally` blocks).
Screenshot (see top-right):
This PR is in draft until a couple UX questions are answered, namely:
1) Given that a) there are only two operations in the store that can change the balance, and b) we don't have any sort of event triggers that fire on the frontend when the balance is changed anyway, does it make sense to add a button to refresh the balance manually?
2) Is the `Account Balance: $20.00` text in the above screenshot still necessary, given that the account balance is displayed? Or is it still …

#6919: Added user balance to store navbar when user is logged in.

---

src/packages/frontend/course/configuration/actions.ts
src/packages/frontend/course/students/actions.ts
src/packages/frontend/frame-editors/code-editor/actions.ts
src/packages/frontend/frame-editors/x11-editor/actions.ts
src/packages/frontend/frame-editors/x11-editor/xpra-client.ts
src/packages/frontend/frame-editors/x11-editor/xpra-server.ts
src/packages/project/lean/lean.ts
src/packages/project/sync/project-status.ts

see title, also binding all other wrapped method calls, just to avoid surprises … in any case, with that I can run X11 apps in my dev project, format code, etc.

frontend/x11: fix fallout of using our own reuseInFlight

---

src/packages/frontend/project/new/file-type-selector.tsx
src/packages/frontend/project/new/new-file-dropdown.tsx
src/packages/frontend/project/page/flyouts/new.tsx
src/packages/frontend/project/utils.ts

This changes the overall behavior, hopefully to the better. It combines the single click auto-generated filename of the large new page with the explicit type dropdown from the explorer's new dropdown + entering a name. other changes involve how manually setting an extension via the filename works fine now, prioritizing some extensions in the dropdown, help info, and some cosmetic changes

frontend/flyout/new: different algorithm

---

src/packages/next/components/store/menu.tsx
src/packages/next/pages/vouchers/index.tsx

Store navbar is also now responsive.
**Feedback Request**
This PR implements the behavior exactly as suggested [in this comment](https://github.com/sagemathinc/cocalc/issues/7250#issuecomment-1930476991). Another possibility would be to slightly rename the existing menu option to be consistent with the updated Voucher Center link, and then to simply add an extra link in the store view to the Voucher Center:
This has the advantage of consistent rendering for menu options in the Store, preserves existing behavior, and adds the Voucher Center as its own hyperlink.
Happy to go either way.

#7250: `Vouchers` link in store now routes to `/vouchers` instead of `/store/vouchers`.

---

src/packages/server/support/create-ticket.ts

Once again, I saw there is no contact info in a ticket. This gets rid of calling "users.createOrUpdate" and instead just set the requester directly.
Ref: https://developer.zendesk.com/documentation/ticketing/managing-tickets/creating-and-updating-tickets/#creating-a-ticket-with-a-new-requester

server/zendesk: fix name+email

---

src/packages/frontend/codemirror/extensions/ai-formula.tsx
src/packages/frontend/codemirror/extensions/edit-selection.ts
src/packages/frontend/codemirror/extensions/insert-image.tsx
src/packages/frontend/frame-editors/code-editor/actions.ts
src/packages/frontend/frame-editors/frame-tree/commands/format-commands.tsx
src/packages/frontend/frame-editors/generic/codemirror-plugins.ts
src/packages/frontend/frame-editors/latex-editor/editor.ts

Ref #7265 for latex. This also works in Markdown, and hence also in Rmd. I don't know if this menu entry appears elsewhere, though.
[2024.02.09-ai-formula-2.webm](https://github.com/sagemathinc/cocalc/assets/207405/93026d0d-e609-4a02-8ad5-bdf765fe1b53)
If this is tied with a keyboard shortcut, it's almost magical. (and it only does the immediate query, if it is a free model)
[2024.02.09-ai-formula.webm](https://github.com/sagemathinc/cocalc/assets/207405/20c5c77b-743b-4fa8-8c13-a22d27f090bc)

frontend/latex+md: AI text -> formula button

---

src/packages/next/components/store/dedicated.tsx

adds a note to the vm purchase page about the startup delay right after the purchase

store/dedicated/vm: add note about startup delay

---

src/packages/next/components/landing/content.tsx

…to increase visibility of compute server banner (as discussed in chat).
Old:
New:

Moved landing page sign in/sign up buttons up and to the left

---

src/packages/frontend/compute/compute-servers-alert.tsx
src/packages/frontend/compute/compute-servers.tsx
src/packages/frontend/compute/google-cloud-config.tsx
src/packages/frontend/project/new/file-type-selector.tsx
src/packages/frontend/site-licenses/purchase/quota-editor.tsx
src/packages/next/components/store/overview.tsx
src/packages/next/components/store/payg-info.tsx
src/packages/next/components/store/quota-config.tsx
src/packages/next/pages/features/compute-server.tsx
src/packages/next/pages/pricing/products.tsx
src/packages/server/compute/cloud/google-cloud/validate-configuration.ts
src/packages/util/compute/cloud/google-cloud/compute-cost.ts
src/packages/util/db-schema/accounts.ts
src/packages/util/upgrades/quota.ts

Just a quick grammar fix changing:
- `GPU's` -> `GPUs`
- `CPU's` -> `CPUs`

Changed all instances of "GPU's" to "GPUs" (resp. "CPU's")

---

src/packages/next/components/store/quota-config-presets.tsx
src/packages/next/components/store/quota-config.tsx
src/packages/next/components/store/site-license.tsx

This pull request fixes #7301 and consists of three changes to the site license page in the CoCalc Store:
1) Member hosting and idle timeout are now hidden behind expert configuration.
2) License configuration is now matched against pre-existing presets.
3) When a license configuration is set via editing a license from the shopping cart, the `Expert configuration` tab is now opened by default. 
1) Navigate to the `/store/site-license` page and configure any preset license. Click `Expert configuration`, modify some values, and verify that a warning message is shown which details specific fields that differ from the selected preset.
2) Refresh the page, and verify the warning message is still there.
3) Select any preset (including the currently selected one) and refresh the page. Verify …

#7301: [Site license page] 

---

src/package.json

…which causes a dependency issue when developing on CoCalc itself.
@williamstein - I removed the `pnpm` dependency which I erroneously added to the `devDependencies` block in `src/package.json` a while back. Could you verify that everything runs/builds okay in your environment, and that the `pnpm` does what it's supposed to (i.e., that it's no longer looking for a missing local package) before merging this?

Removed extraneous `pnpm` dev dependency

---

src/packages/next/components/store/quota-config-presets.tsx
src/packages/next/components/store/quota-config.tsx
src/packages/next/components/store/site-license.tsx

…to consistently render presets view by default. Updated presets to explicitly include member hosting (before, they included it implicitly). Preset diff text is now a bit clearer.

#7531: [Site license page] Updated site license page 

---

src/packages/frontend/purchases/pay-as-you-go/cost.tsx
src/packages/frontend/purchases/pay-as-you-go/modal.tsx

properly check the type of service by using by using `isLanguageModelService` + some renaming

frontend/paygo/llm: fix mistral price schema display

---

src/packages/frontend/editors/slate/format/commands.ts
src/packages/frontend/editors/slate/format/insert-ai-formula.ts
src/packages/frontend/editors/slate/types.ts
src/packages/frontend/frame-editors/markdown-editor/actions.ts

I discovered that the slate editors AI formula menu needs a different code. This adds the same popup component, and also some extra lines to surface the `project_id`.
So, with that, I can insert a formula – the only thing that it does not do is to convert the markdown `$..$` string to the formula. You have to press space once to get it. I don't know how to do this, but in any case, at least the dialog shows up and it does insert something.
… and after insert formula → refocus cursor → space:

frontend/md/slate: integrate AI formula

---

src/packages/backend/data.ts
src/packages/database/postgres-base.coffee

…to function exports instead of arrow function const exports. Postgres config now destructures upon import into `postgres-base.coffee`.
Possibly addresses #7381. To test, verify that CoCalc connects to dev/prod databases.

#7381: Changed `sslConfigToPsqlEnv` and `sslConfigFromCoCalcEnv` 

---

src/packages/frontend/project/settings/environment.tsx
src/packages/project/project-setup.ts

should fix #7404 by retaining the existing `$PATH` entries in some way or another.

project: take extra care when tweaking $PATH 

---

src/packages/next/components/landing/footer.tsx
src/packages/next/components/landing/social-media-icon-list.tsx

On cocalc.com:
On prem (or local):

#7412: Added social media links to landing page footer when deployed to cocalc.com

---

src/packages/util/news.ts

To test:
1) Begin to create a news item.
2) Click the "Cancel" button.
3) Verify the user is redirected to `/news`.

Fixes 7397. "Cancel" button when creating news item now correctly redirects back to the main news page.

---

src/packages/next/components/landing/footer.tsx

Fixes 7412. Social media footer now displays below CoCalc logo.

---

src/packages/next/components/news/news.tsx

Also updated news item footer to be a bit more ergonomic and mobile-friendly:

Fixes 7347. Added LinkedIn share button to news items.

---

src/packages/package.json
src/packages/pnpm-lock.yaml

Slightly update undici, which seems to be a qdrant-js dependency

npm: override undici min version

---

src/packages/comm/project-configuration.ts
src/packages/frontend/course/configuration/customize-student-project-functionality.tsx
src/packages/frontend/project/named-server-panel.tsx
src/packages/frontend/project/new/types.ts
src/packages/frontend/project/page/flyouts/servers.tsx
src/packages/frontend/project/servers/project-servers.tsx
src/packages/frontend/project/settings/project-capabilites.tsx
src/packages/frontend/project_configuration.ts
src/packages/hub/projects.coffee
src/packages/hub/proxy/handle-upgrade.ts
src/packages/hub/proxy/target.ts
src/packages/project/configuration.ts
src/packages/project/named-servers/control.ts
src/packages/project/named-servers/list.ts
src/packages/util/db-schema/projects.ts
src/packages/util/types/servers.ts

~~Unfortunately I'm stuck. For whatever reason, such a named port does not work.~~
Interestingly, it is impossible to run this in a dev environment.
Deployment: hub first (for the proxy magic), then static, and then project (only when the configuration detects rserver, it will show it in the frontend)

Supporting Rstudio Server

---

src/packages/pnpm-lock.yaml
src/packages/project/package.json
src/packages/project/upload.ts

- newer formidable, only used here
- getting rid of a promise/callback wrapper
- updating how the chunks are processed (several subtle changes)
- cleanup code
:warning: unrelated: this updates the lock file to the newer version of pnpm@9
This is certainly non-trivial. I tested this locally, uploading a large file and several smaller ones. No problems, though …

npm/project: update formidable 

---

src/packages/frontend/markdown/index.ts
src/packages/next/components/news/news.tsx
src/packages/next/pages/news/[id].tsx

This pull requests adds a slew of `meta` tags to each news item. Here's an example of what those look like:
```html
<head>
...
<meta property="og:type" content="article"/>
<meta property="og:title" content="Another News Test"/>
<meta property="og:url" content="https://localhost/news/another-news-test-8"/>
<meta property="og:image" content="https://picsum.photos/536/354"/>
<meta property="article:published_time" content="2024-04-14T02:46:27.000Z"/>
<meta property="article:modified_time" content="2024-04-28T22:13:25.000Z"/>
...
</head>
```
...and LinkedIn's Post Inspector seems to pick up these tags as expected:
If you're developing on a publicly-available server, you can simply click the LinkedIn "share" link on a news item with an embedded image. Otherwise, you'll probably need to use …

7473: Added `meta` tags to support the Open Graph protocol when sharing news links.

---

src/packages/database/settings/customize.ts
src/packages/frontend/frame-editors/llm/title-bar-button-tour.tsx
src/packages/next/components/landing/cocalc-com-features.tsx
src/packages/next/pages/features/ai.tsx
src/packages/util/consts/ui.ts

* switch to the ai.html page for docs
* mention all enabled AI models on AI feature page
* some minor tweaks, like, accurately defining the "Customize" type and getting rid of a few too specific "ChatGPT" mentions.

frontend/next: change all doc chatgpt.html links + feature page tweaks

---

src/packages/next/components/store/quota-config-presets.tsx
src/packages/next/components/store/quota-config.tsx
src/packages/next/components/store/site-license.tsx

This is a quick idea I had. The license configurator will explicitly warn about maybe a bad experience with a low memory choice, and also warn about picking a compute server or VM instead of a high memory or cpu cores choice. This gives immediate feedback very early, right where the choice happens. It's also conditional on the action of the user, hence due to being dynamic it is more visible.
… and of course, params and the text in detail could be adjusted.

next/store: warnings for low/high cpu/mem and tweaking profiles

---

src/packages/frontend/frame-editors/llm/context.tsx
src/packages/frontend/frame-editors/llm/create-chat.ts
src/packages/frontend/frame-editors/llm/title-bar-button.tsx

fixing  #7539 by pre-selecting the first prompt template + some cleanups. also not showing "no context" if there is no derived `input`.

frontend/llm assistant: pre-select the first preset and process input

---

src/packages/database/jest.config.js
src/packages/database/package.json
src/packages/jupyter/jest.config.js
src/packages/jupyter/package.json
src/packages/next/package.json
src/packages/project/jest.config.js
src/packages/project/package.json
src/packages/static/jest.config.js
src/packages/static/package.json
src/packages/sync/jest.config.js
src/packages/sync/package.json
src/packages/terminal/jest.config.js
src/packages/terminal/package.json
src/packages/util/jest.config.js
src/packages/util/package.json

These tests all pass on my machine (from the `src` directory, I ran `pnpm clean && pnpm make-dev && pnpm test`), but I'd recommend waiting for a successful GitHub build before merging just in case there are breaking differences between dev/build servers.
Note that `src/packages/hub` cannot be migrated until that module no longer mixes CoffeeScript and TypeScript.

7474: Migrated `src/packages/{database,jupyter,project,static,sync,terminal,util}` test scripts to use TypeScript.

---

src/packages/next/components/landing/footer.tsx
src/packages/next/components/landing/header.tsx
src/packages/next/lib/customize.ts
src/packages/next/lib/with-customize.ts

I'm opening this as a draft for now so that we can go over the business logic that dictates which page links should appear when. Once the business logic is satisfactory, this PR is ready to merge.
The link rendering logic has been consolidated to a single source of truth so that business logic is all in one place; see https://github.com/sagemathinc/cocalc/compare/master...schrodingersket:ux/7429?expand=1#diff-53c6b656252dc3b6591f8121477a8c83492b50363c59fc139ed2619d04c0d135R78 for the current configuration, which mirrors the existing logic as much as possible.
Fixes #7532.

ux/7532: Extracted landing page link rendering logic to a single source of truth.

---

src/packages/frontend/frame-editors/llm/title-bar-button.tsx
src/packages/frontend/project/page/home-page/ai-generate-document.tsx

- this certainly helps parsing rmarkdown with code, but it's still sometimes odd. somehow the behavior is slightly different, where content is wrapped in backticks, although it shouldn't be. very weird. I'll have to iterate on the prompt a bit more.
- typo
- I'm stuck with that example dropdown … oh ok, I'm editing the wrong file. lol.

frontend/ai: fixing some of the issues of the recent PRs

---

src/packages/util/db-schema/site-settings-extras.ts

This is rather trivial. If the datatype is expected to be a json of a dict, make the default an empty dict. Then, there are no special cases necessary if it isn't defined.
deployment: not necessary to do anything

db-schema/server-settings: fix fallback for custom LLM configs

---

src/packages/next/components/path/path.tsx
src/packages/next/lib/share/get-public-path-info.ts
src/packages/next/pages/share/public_paths/[...id].tsx

This PR updates the corresponding `meta` tags on public share pages to handle null `created`/`last_edited` timestamps, since the database schema allows those columns to be null.
(follow-up to https://github.com/sagemathinc/cocalc/pull/7582).

#7503: Added check for nullish `created`/`last_edited` timestamps on public share records.

---

src/packages/next/components/path/path.tsx
src/packages/next/pages/share/public_paths/[...id].tsx

Follow-up PR to https://github.com/sagemathinc/cocalc/pull/7593.

#7503: `ogImage` and `ogUrl` are now both processed server-side before being passed to the client in publicly shared paths.

---

src/packages/frontend/components/icon.tsx
src/packages/frontend/frame-editors/frame-tree/commands/editor-menus.ts
src/packages/frontend/frame-editors/frame-tree/commands/manage.tsx
src/packages/frontend/frame-editors/frame-tree/commands/types.ts
src/packages/frontend/frame-editors/jupyter-editor/editor.ts
src/packages/frontend/jupyter/cell-buttonbar.tsx
src/packages/frontend/jupyter/commands.ts
src/packages/frontend/jupyter/consts.ts
src/packages/frontend/jupyter/keyboard-shortcuts.tsx
src/packages/frontend/jupyter/llm/cell-tool.tsx

- this adds a small dropdown to get quick access for running all cells above or below
- I'm also changing the icons, because they are not telling much, or even point in the wrong direction
- this also adds support for rotated menu icons

frontend/jupyter: run all cells above/below dropdown button in cell toolbar

---

src/packages/database/settings/customize.ts
src/packages/database/settings/get-sso-strategies.ts
src/packages/next/components/account/config/account/sso.tsx
src/packages/next/components/auth/sso.tsx
src/packages/next/components/landing/cocalc-com-features.tsx
src/packages/next/components/landing/sign-in.tsx
src/packages/next/components/videos.tsx
src/packages/next/lib/customize.ts
src/packages/next/lib/with-customize.ts
src/packages/next/pages/index.tsx

- ref: #7557
- if that "allow email signup" server setting is false, and hence no traditional email/password sign in/up is allowed, list all SSO options on the home page.
- no other changes
- also some header cleanups and type clarifications

"allow email signup" = false → list all SSO options on home page

---

src/packages/frontend/components/language-model-icon.tsx
src/packages/frontend/editors/markdown-input/mentionable-users.tsx
src/packages/frontend/frame-editors/llm/components.tsx
src/packages/frontend/frame-editors/llm/llm-query-dropdown.tsx
src/packages/frontend/frame-editors/llm/llm-selector.tsx
src/packages/frontend/frame-editors/llm/use-llm-menu-options.tsx
src/packages/frontend/projects/store.ts
src/packages/server/llm/index.ts
src/packages/util/db-schema/llm-utils.ts
src/packages/util/db-schema/site-defaults.ts
src/packages/util/db-schema/site-settings-extras.ts

There is code that's not general enough or simply wrong. That causes the "openai" setting to interfere with the "custom openai" configuration. The goal is to clean this up, name the categories of the custom LLM integrations in a better way, consolide both custom LLM endpoint options under a common category, etc. This also finishes the support for custom icons of these custom LLM endpoints.
PS: there is no need to deploy this, since there is no change for prod.

frontend/llm: refactor and fix OpenAI vs Custom OpenAI

---

src/packages/frontend/jupyter/cell-output-time.tsx

This avoid briefly flashing this time ago string. Instead, it shows a gray dot like the one to indicate it queued to run, and moves that time ago info in the tooltip.
now

frontend/jupyter/cell-bar: show dot when queued to run, instead of time

---

src/packages/frontend/custom-software/selector.tsx
src/packages/frontend/project/settings/compute-image-selector.tsx
src/packages/server/software-envs.ts
src/packages/util/sanitize-software-envs.ts

this is just a small UX change for on-prem, to match a bit more closely how this works with jupyter hub

on-prem: software environment selector more similar to jupyter hub

---

src/packages/frontend/account/other-settings.tsx
src/packages/frontend/customize.tsx
src/packages/frontend/project/context.tsx

This is just a silly bugfix. Once again, only the openai setting was used, when actually activating *any* of the LLM services should show that panel in the user settings - plus related details.

frontend/llm: only hide account/llm settings if all are disabled

---

src/packages/util/db-schema/llm-utils.test.ts
src/packages/util/db-schema/llm-utils.ts

* disable gpt 3.5 and 3.5 16k
* bulk of this is actually tweaking the function to get a model, especially in the case when you've configured a disabled model and it should fall back to the default. for that, a handful of tests check it's behavior.
* chat gpt on next pages works like before

llm: remove deprecated/old models

---

src/packages/next/components/landing/cocalc-com-features.tsx

- Add a (not very noticeable) link to "Why CoCalc?" doc page from the landing page
- Tweak on prem wording since we no longer have 3 options listed, but 2
- "Everyone's code" is a bit two generic, clarify "You and your collaborators"

Link Why CoCalc from a landing page and clean up on premises wording

---

src/packages/frontend/frame-editors/whiteboard-editor/delete-page.tsx
src/packages/frontend/frame-editors/whiteboard-editor/new-page.tsx
src/packages/frontend/frame-editors/whiteboard-editor/overview.tsx
src/packages/frontend/frame-editors/whiteboard-editor/pages.tsx

* buttons in page overview due to antd 5.18.3

frontend/slides: fix wrongly aligned icons 

---

src/packages/frontend/compute/cloud-filesystem/bucket.tsx
src/packages/frontend/compute/cloud-filesystem/create.tsx

Recommendations had inconsistent usage of "use": "use/Use/and nothing" - I made it uniform "Recommendation: Default"
The block size explanation is only about "the bigger the merrier" while the last sentence made sense in the code, with variables, but not rendered, where different variables had the same value. The meaning was still "the bigger the merrier", so I just deleted it. If somebody understands why smaller is better in a particular case, there is the flexibility to adjust it.

Tweak UI help text for creating Cloud Filesystems

---

src/packages/frontend/purchases/edit-license.tsx
src/packages/frontend/site-licenses/purchase/purchase.tsx
src/packages/frontend/site-licenses/purchase/quota-editor.tsx
src/packages/frontend/site-licenses/site-license-public-info.tsx
src/packages/next/components/store/quota-config-presets.tsx
src/packages/next/pages/pricing/subscriptions.tsx
src/packages/server/prices.test.ts
src/packages/server/purchases/purchase-shopping-cart-item.test.ts
src/packages/server/vouchers/charge-for-unpaid-vouchers.ts
src/packages/util/licenses/purchase/compute-cost.test.ts
src/packages/util/licenses/purchase/compute-cost.ts
src/packages/util/licenses/purchase/consts.ts
src/packages/util/licenses/purchase/cost-versions.ts
src/packages/util/licenses/purchase/purchase-info.ts
src/packages/util/licenses/purchase/types.ts
src/packages/util/licenses/store/compute-cost.ts
src/packages/util/purchases/cost-to-edit-license.ts

- this is just the first step in util; to really use this, we need to also make it so the version number is encoded in PurchaseInfo when the purchase is made.
- need to write some unit tests -- this is exactly the sort of thing where they are easy and useful
@haraldschilly I bet if you glance at [src/packages/util/licenses/purchase/cost-versions.ts](https://github.com/sagemathinc/cocalc/pull/7675/files#diff-59a01e8b2aab719f945c91b357cdf18af457ef18f590a1a601fba2d991bd69c3) you'll have ideas about how we might want to update those parameters for a new v2 pricing, which we could switch to.

add a version number to the cost parameters for licenses

---

src/README.md
src/packages/next/lib/api/schema/compute/compute-server-action.ts
src/packages/next/lib/api/schema/exec.ts
src/packages/next/pages/api/v2/exec.ts

Example request on left and corresponding response on the right:

OpenAPI docs: Added schema for `/api/v2/exec` endpoint for arbitrary project command execution.

---

src/packages/backend/execute-code.test.ts
src/packages/backend/execute-code.ts
src/packages/next/lib/api/schema/exec.ts
src/packages/next/pages/api/v2/exec.ts
src/packages/project/exec_shell_code.test.ts
src/packages/project/exec_shell_code.ts
src/packages/util/aggregate.d.ts
src/packages/util/aggregate.ts
src/packages/util/message.js
src/packages/util/types/execute-code.ts

* implementing #7666 for the project itself
* adding more details to the v2 API (some were missing)
* more tests
* typescript aggregate.js
* my main confusion was this new openapi validation, which is not working as I assumed, when there are more options for the input object. In any case, I think the code I wrote goes into the correct direction.
* the only real change for existing calls is adding a new `{type: "blocking"}` indicator to the response. I can't think of any reason why this is could become a problem.

async project exec

---

src/packages/frontend/account/editor-settings/checkboxes.tsx
src/packages/frontend/components/icon.tsx
src/packages/frontend/frame-editors/code-editor/actions.ts
src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx
src/packages/frontend/frame-editors/latex-editor/editor.ts
src/packages/frontend/frame-editors/qmd-editor/actions.ts
src/packages/frontend/frame-editors/qmd-editor/editor.ts
src/packages/frontend/frame-editors/rmd-editor/actions.ts
src/packages/frontend/frame-editors/rmd-editor/editor.ts

This surfaces the `build_on_save` account/editor setting. This certainly fixes https://github.com/sagemathinc/cocalc/issues/4821 and maybe there is a related one for latex as well.

tex/rmd/qmd: "build on save" toggle button

---

src/packages/next/pages/policies/terms.tsx

- drop some details about upgrading/downgrading
- explicitly state that CoCalc Credit is nonrefundable
- PAYG services may be terminated as soon as zero balance is hit

Update Refunds section in ToS

---

src/packages/frontend/antd-bootstrap.tsx
src/packages/frontend/project/ask-filename.tsx
src/packages/frontend/project/explorer/search-bar.tsx

A baby step towards getting rid of bootstrap.
(and error "X" makes it still dismissable)

frontend/explorer/search: get rid of react-bootstrap Alert

---

src/packages/next/pages/api/v2/projects/copy-path.ts
src/packages/next/pages/api/v2/projects/copy-url.ts
src/packages/next/pages/api/v2/projects/start.ts
src/packages/next/pages/api/v2/projects/stop.ts
src/packages/next/pages/api/v2/projects/touch.ts
src/packages/server/jupyter/execute.ts
src/packages/server/jupyter/kernels.ts

Added `await` call to enforce collaborator permissions check for {copy-path,copy-url,start,stop,touch} project operations.

Fix Project Collaborator Permission Check

---

src/packages/hub/hub.ts
src/packages/hub/servers/app/next.ts
src/packages/hub/servers/express-app.ts
src/packages/next/components/path/path.tsx
src/packages/next/components/share/file-contents.tsx
src/packages/next/components/share/path-contents.tsx
src/packages/next/lib/share/handle-raw.ts
src/packages/next/lib/share/virtual-hosts.ts

This renders a PDF on the share server embedded in an iframe. This is fine, because PDFs are sandboxed and isolated by all browsers anyways.
This also fixes a slight issue with using a cache and organizes imports.

next/share: embed PDF

---

src/packages/frontend/project/new/new-file-page.tsx

Fixes #7385
https://github.com/user-attachments/assets/4d3ebaa7-fefa-4f76-8735-473bb69ebbe7
https://github.com/user-attachments/assets/d682b446-1d13-48b4-93e2-1022b8b7c342

use filename when creating file via extension dropdown

---

src/packages/frontend/course/students/students-panel.tsx

Fixes #7843 
Shows email address in parenthesis alongside the name when adding students by email. If there's no name, in which case the email address is already shown, we don't show it.

show email address when adding students by email

---

src/packages/frontend/frame-editors/latex-editor/gutters.tsx

Down the tree, help me fix contains internationalization, but it is somehow rendered outside the root, where the context provider is defined.
So, this adds another context, just with the english defaults, to avoid that bug. It would be great if this is rendered in the same overall context ...
Error: 
```
Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry. 
```

frontend/latex: fix "help me fix" in gutter

---

src/packages/frontend/chat/chat-log.tsx
src/packages/frontend/chat/filter-messages.ts
src/packages/frontend/chat/filter.tsx
src/packages/frontend/chat/message.tsx
src/packages/frontend/client/console.ts
src/packages/frontend/frame-editors/chat-editor/editor.ts
src/packages/frontend/frame-editors/chat-editor/search.tsx
src/packages/frontend/frame-editors/chat-editor/use-search-index.ts
src/packages/frontend/frame-editors/code-editor/actions.ts
src/packages/frontend/frame-editors/frame-tree/editor.tsx
src/packages/frontend/frame-editors/frame-tree/frame-tree-drag-bar.tsx
src/packages/frontend/frame-editors/frame-tree/register.ts
src/packages/frontend/frame-editors/frame-tree/types.ts
src/packages/frontend/package.json
src/packages/pnpm-lock.yaml
src/packages/static/package.json
src/packages/static/src/plugins/define-constants.ts
src/scripts/g.sh

Do a minimal proof of concept of what search for chat using https://orama.com/ is like.
If this works well, extend it to other file types, including whiteboards, tasks, jupyter notebooks, pdf, etc.,
and also extend it to support indexes on multiple files (?).

chat search -- quick proof of concept

---

src/packages/frontend/package.json
src/packages/hub/package.json
src/packages/next/package.json
src/packages/pnpm-lock.yaml
src/packages/project/package.json
src/packages/server/package.json

- this does not attempt to update to [express 5](https://expressjs.com/en/guide/migrating-5.html) … we should probably wait a bit, but this is something to keep an eye on. This release already includes [backports](https://github.com/expressjs/express/releases/tag/4.21.1), though.
- small update to express-session to update its "cookie" dependency

npm: express/+session and microlink/react-json-view

---

src/packages/pnpm-lock.yaml
src/packages/static/package.json
src/packages/static/src/module-rules.ts

Goal is to get rid of html-minify-loader to fix #7945
In the end, this PR just gets rid of the minify loader. I don't know enough about webpack and all of this any more, though. It looks like there is a lot of opportunity to enhance this, but just regarding that loader, it only deals with existing html files – not generating them via plugin or whatever. 
So, all possibly affected assets are:
```
...$ git ls-files HEAD '**/*.html'
frontend/account.html
frontend/console.html
frontend/editor.html
frontend/jupyter.html
frontend/sagews/3d.html
frontend/sagews/d3.html
frontend/sagews/interact.html
```
and surely, they are either small already or will go away anyways.
My understanding is that with this change, the html file is just copied over. There are ways to add a plugin for minifying html …

static/webpack/npm: get rid of html-minify-loader

---

src/packages/next/components/landing/pricing-item.tsx
src/packages/next/components/landing/pricing.module.css
src/packages/next/components/store/quota-config-presets.tsx
src/packages/next/components/store/quota-config.tsx
src/packages/next/components/store/site-license.tsx
src/packages/next/components/store/usage-and-duration.tsx
src/packages/next/lib/api/schema/licenses/common.ts
src/packages/next/pages/pricing/subscriptions.tsx

This was more work than I thought – also, because I wanted to fix this for narrower mobile screens, because then the 3 columns are really bad.
**testing**:  :warning:  ~~I'm stuck with this, because~~ I can't add a selected license to the cart. It throws an API validation error. → I made a fix to the api definition. I know the checks can be disabled, but for dev at least something basic like adding a license to the cart should work. I wonder if this ever worked? The changes I made should just be cosmetic, no change to the actual query. Commit: 55b47c2ff41840d25e7a123a15c90e95b013a2de
just a list of options with a description, and below is more info.
* description is a bit modified
* quotas are easier to compare
* the "expectations" are new. They're derived from the previous text that has …

next/store: make all license presets selectable columns

---

src/packages/frontend/package.json
src/packages/pnpm-lock.yaml

Version 10 had [a security issue in its dependencies](https://github.com/cure53/DOMPurify/security/advisories/GHSA-mmhx-hmjr-r674) and well, why not update to version 11.
e.g. version 11 knows how to draw [bidirectional arrows](https://mermaid.js.org/syntax/sequenceDiagram.html#messages):

frontend: update mermaid to version 11

---

src/packages/frontend/project/page/flyouts/files-terminal.tsx

I keep seeing findDOMNode deprecated warnings. This PR is a baby step towards removing it. Test: the flyout mini terminal shows up just like before, so, this small change is fine.
Ticket #7976 is more general, in particular it references the upstream ticket of the dependency, which is actually triggering that warning I keep seeing.

frontend/flyout/terminal: get rid of deprecated ReactDOM.findDOMNode

---

src/packages/database/index.ts
src/packages/database/postgres/account-queries.ts
src/packages/database/postgres/types.ts
src/packages/next/lib/api/assert-trusted.ts
src/packages/next/lib/api/schema/accounts/sign-up.ts
src/packages/next/lib/types/sign-up.ts
src/packages/next/pages/api/v2/auth/sign-up.ts
src/packages/server/accounts/create-account.ts
src/packages/server/projects/control/kucalc.ts
src/packages/server/projects/control/util.ts

* follow up of 433f4b3bcb56688c3edd9271c12f9cbb4c11c753: for onprem, require admin group:
* When a regular user wants to create a user: `{'issues': {'api': "Error: Only users in the group 'admin' are allowed to create new users."}}`
* When an admin wants to create a user, works fine (account_id returned)
* I also typed that db database object, and had to deal with the fallout. No change in functionality, just many small typing details.
* OpenAPI spec, also documenting that issues object upon failure.

API: create account tweaks for onprem

---

src/packages/next/components/landing/info.tsx

I saw a warning in the logs … and this adds a  `key={index}`, that's all

next: add a missing key={} to an <A>

---

src/packages/database/postgres-base.coffee
src/packages/frontend/purchases/admin-refund.tsx
src/packages/frontend/purchases/purchases.tsx
src/packages/frontend/site-licenses/site-license-public-info-component.tsx
src/packages/server/billing/get-invoices-and-receipts.ts
src/packages/server/compute/maintenance/purchases/low-balance.ts
src/packages/server/messages/get.ts
src/packages/server/messages/maintenance.ts
src/packages/server/projects/control/kubernetes.ts
src/packages/server/purchases/create-refund.ts
src/packages/server/purchases/edit-license.ts
src/packages/server/shopping/cart/get.ts

Make it so admins can fully refund any license edit (e.g., extending subscription by a month), and also credit card payment (both normal *AND* automatic balance increases) through the UI, and improve the UI regarding show what has happened:
and
Everything is already done EXCEPT the backend part of actually refunding the license creating/changes.

Improve Admin Refunds

---

src/packages/next/components/landing/software-libraries.tsx
src/packages/next/lib/landing/landing.test.ts
src/packages/next/lib/landing/software-data.ts
src/packages/next/lib/landing/software-specs.ts
src/packages/next/pages/software/index.tsx
src/packages/next/software-inventory/setup.sh
src/packages/util/consts/software-envs.ts

also, download inventory files in parallel
code works, but the content of the inventory file is wrong → hence blocked for now

next/software: include ubuntu 24.04 inventory

---

src/packages/frontend/purchases/service.tsx
src/packages/util/db-schema/purchase-quotas.ts

this is for #8074 although the real problem is in `server/purchases/get-purchases.ts`
I checked that this works in my dev project, by explicitly setting `x[0].service = null;` in the frontend, in purchases.tsx, where the data comes in from `api.getPurchases`

ServiceTag: bandaid for #8074

---

src/packages/database/postgres-base.coffee
src/packages/database/postgres/record-connect-error.ts

This is related to https://github.com/sagemathinc/cocalc/issues/5997 … i.e. this records the case where there is no connection to the database, to eventually cause the health check to fail. This is more general than the "forgot the database password"-problem, because it should cause a health check failure in all cases, when it is not possible to establish a connection to the database.
test: I haven't tested this, but I think it should be fine. In the end, the `misc.retry_until_success` will call this `@_connect` again and again and the health checks last disconnect timestamp will be set once and kept at the point in time when this failure happened for the first time. 
---
This really needed more work. The weird part is, when there is a "disconnect" event, it should be emitted and received …

database: if all clients fail to connect, emit "disconnect" event

---

src/packages/frontend/app/nav-tab.tsx
src/packages/frontend/app/page.tsx
src/packages/frontend/app/top-nav-consts.ts
src/packages/frontend/i18n/common.ts
src/packages/frontend/i18n/trans/ar_EG.json
src/packages/frontend/i18n/trans/de_DE.json
src/packages/frontend/i18n/trans/es_ES.json
src/packages/frontend/i18n/trans/fr_FR.json
src/packages/frontend/i18n/trans/he_IL.json
src/packages/frontend/i18n/trans/hi_IN.json
src/packages/frontend/i18n/trans/hu_HU.json
src/packages/frontend/i18n/trans/it_IT.json
src/packages/frontend/i18n/trans/ja_JP.json
src/packages/frontend/i18n/trans/ko_KR.json
src/packages/frontend/i18n/trans/nl_NL.json
src/packages/frontend/i18n/trans/pl_PL.json
src/packages/frontend/i18n/trans/pt_PT.json
src/packages/frontend/i18n/trans/ru_RU.json
src/packages/frontend/i18n/trans/tr_TR.json
src/packages/frontend/i18n/trans/zh_CN.json
src/packages/frontend/purchases/balance-button.tsx

* hide if not commercial
* style like the other top bar buttons
* no change to the other balance button use in account settings, just refactoring
in the screenshot I'm hovering over the balance nav tab

frontend/topBar/balance: hide for non-commercial and style it uniformly like the others

---

src/packages/frontend/cspell.json
src/packages/frontend/project/explorer/action-box.tsx
src/packages/frontend/project/settings/run-quota/hooks.tsx
src/packages/frontend/project/settings/run-quota/run-quota.tsx
src/packages/frontend/project/settings/upgrade-usage.tsx
src/packages/frontend/share/config.tsx

see #8170
Uses (maybe stale) run_quota information to determine if project has the internet upgrade
Below are two situations for kucalc=yes - either no license and no internet, hence banner and no sharing – or a license, upgrades are there, no upgrade banner, and user can share. The root bug for this is assuming the basis-license has no upgrades at all, which is not necessarily true.

frontend/share: fix share dialog restriction

---

src/packages/frontend/client/purchases.ts
src/packages/frontend/project/explorer/action-box.tsx
src/packages/frontend/purchases/all-quotas-config.tsx
src/packages/frontend/purchases/quota-config.tsx

* lower preset values for LLMs
* instead of showing the preset tags everywhere, this is now a dropdown selector. editing the value works just like before.
* I also attempted to change this for the modal, but I couldn't figure out how to show the modal. I'm somehow assuming that modal is deprecated.

frontend/quota: change presets to a dropdown and special-case for LLM models

---

src/packages/frontend/cspell.json
src/packages/util/compute-images.ts

Reduce offered software environments.

software envs: remove old, only keep one "stable", and weed out many others

---

src/packages/frontend/frame-editors/qmd-editor/actions.ts
src/packages/frontend/project/new/consts.ts
src/packages/frontend/project/new/file-type-selector.tsx
src/packages/frontend/project/new/new-file-page.tsx

* new file button was creating an rmd file, not qmd. misleading.
* example content
* fixing some typos
* better typing of a map for icon names, because qmd icon was missing

quarto fixes

---

src/packages/frontend/project/new/new-file-page.tsx
src/packages/frontend/project/page/home-page/button.tsx

when the project UI is in flyout-only mode, the home page button shows the homepage and closing the new page opens the homepage as well. no changes for those other modes.

frontend/flyout: reinstate homepage

---

src/packages/next/lib/landing/landing.test.ts
src/packages/next/lib/landing/software-data.ts
src/packages/next/pages/software/index.tsx
src/packages/next/software-inventory/setup.sh
src/packages/util/compute-images.ts
src/packages/util/consts/software-envs.ts

The frontend relevant change is already in master. This is for removing the related next packages. No need to deploy any of that with urgency, there are already fallbacks in place.
regarding #8266:
Although, there might be similar issues with other elements.

compute env: remove Ubuntu 18.04

---

src/cocalc.code-workspace
src/packages/frontend/account/user-defined-llm.tsx
src/packages/frontend/chat/actions.ts
src/packages/frontend/cspell.json
src/packages/package.json
src/packages/pnpm-lock.yaml
src/packages/server/llm/client.ts
src/packages/server/llm/custom-openai.ts
src/packages/server/llm/index.ts
src/packages/server/llm/ollama.ts
src/packages/server/llm/test/00.test.ts
src/packages/server/llm/user-defined.ts
src/packages/server/package.json
src/packages/util/db-schema/llm-utils.ts
src/packages/util/db-schema/purchase-quotas.ts

This continues to fix some of the small details I saw, more refactoring in the future in small steps.
However, what this does is adding openai **4.1** and **4.1 mini**. I suggest to set 4.1 mini as the default.
4.1 mini is a bit more expensive, but still fine to offer for free and tests put it above o1-mini. See https://openai.com/index/gpt-4-1/ (4.1 family intelligence graph in the middle)
Related, since the list is getting long, we could disable GPT-4 and -turbo … or I just get rid of them in a future PR.

LLM housekeeping

---

src/packages/frontend/cspell.json
src/packages/frontend/customize.tsx
src/packages/frontend/purchases/all-quotas-config.tsx
src/packages/server/purchases/is-purchase-allowed.test.ts
src/packages/server/purchases/is-purchase-allowed.ts
src/packages/server/purchases/purchase-quotas.ts
src/packages/util/db-schema/purchase-quotas.ts
src/packages/util/db-schema/site-defaults.ts

I think this works, although I'm not 100% what to test and if there are negative side effects. So, a bit of caution …
For my local status see  the screenshot below. It shows the DB table for the quotas and how it looks in the UI. I can use the language models and do not get any warning messages. Except for Mistral Large, because there I set the quota to 0. "Budget Alert: Mistral AI Large"
My only remaining concern is to break quotas for other services.
This PR also switches a test, to use "compute-server" and not a language model … and adds a bit related to the default quota.
Finally, this also adds a `llm_default_quota` server settings with default 10.

raise LLM quota limit

---

src/packages/next/components/landing/header.tsx
src/packages/next/pages/policies/index.tsx

* ref: issue #8290
* add top nav link
* rephrase policies/index trust entry
* position trust on 2nd place in index
* make top nav links slightly denser, since there is now one more link
this is on dev, slightly different from prod, but as far as I understand the policies page should appear as well

next/policies: tweak where and how policies are shown

---

src/packages/server/auth/sso/types.ts
src/packages/server/hub/auth.ts

follow up of e879895d3ecc … and here are now types to avoid modifying an object that should stay intact

sso/auth: fix silly mistake in e879895d3ecc

---

src/packages/frontend/project/page/file-tab.tsx

Just as I suspected, a negative margin to is used as an offset on top of a padding. This halves the padding on the side from 16px to 8px and hence it works fine now.

frontend/file tabs: fix compact design

---

src/packages/frontend/chat/chatroom.tsx

This has some chances to fix the font size issue, but I haven't tested it yet.
fallout of #8323

frontend/chat: rename fontSize back to font_size 

---

src/packages/project/kucalc.ts

This removes a space character. Newer prometheus versions are more picky... 
… and no need to make an update just for that.

project/metrics: remove space character

---

src/packages/frontend/course/configuration/upgrades.tsx

They will be filled in using defaults in the store.

Drop most parameters for course license buy link

---

src/packages/conat/core/server.ts
src/packages/conat/monitor/usage.ts
src/packages/conat/types.ts
src/packages/server/conat/socketio/health.ts
src/packages/server/conat/socketio/metrics.ts
src/packages/server/conat/socketio/server.ts

Ok, well, I'm not sure how to test this or what metrics to even expose. The idea is to start very simple:
1. a "vitals" http server is created in the "server.ts" and then metrics and health return their data if path and method match.
2. on conat's side, some metrics are stored in a map "metrics" to avoid a dependency on prometheus (it needs node.js).
3. periodically, that values are grabbed by the server and exposed in prometheus.

conat/server: add prometheus metrics

---

src/packages/frontend/_projects.sass
src/packages/frontend/project/explorer/path-navigator.tsx

* this is mode == files only
* by spelling out "Home", next to the icon
* and adding an "up" arrow button (more could be done, but I wanted to start simple)

frontend/explorer: enhance breadcrumb nav

---

src/CLAUDE.md
src/packages/frontend/cspell.json
src/packages/next/lib/api/schema/projects/set-admin-quotas.ts
src/packages/next/pages/api/v2/projects/set-admin-quotas.ts
src/packages/server/conat/api/projects.ts

This helps admins for onprem setups to adjust specific project quotas.
What I tested:
* only admin API keys work, otherwise you get `{'error': 'only admins can set project quotas'}`
* adjusting the quotas
without settings, the effective `run_quota` is 
{`"network": false, "cpu_limit": 1, "cpu_request": 0.02, "member_host": false, "idle_timeout": 1800, "memory_limit": 1000, "always_running": false, "memory_request": 200, ...}`
Then, after this call and stopping/starting the project explicitly ...
```
{  "project_id": "...",
"always_running": True,
"internet": True,
"cpu_limit": 2,
"cpu_request": 1.5,
"memory_limit": 10000,
"memory_request": 5555,
"idle_timeout": 60000,
}
```
... the `run_quota` changed:
`{"network": true, "cpu_limit": 2, "cpu_request": 1.5, "idle_timeout": 60000, …

next/api/v2: add set-admin-quotas endpoint

---

src/CLAUDE.md
src/packages/comm/project-status/utils.ts
src/packages/project/project-info/server.ts
src/packages/project/project-status/server.ts

This PR implements comprehensive cgroup v2 support for CoCalc project monitoring, ensuring accurate resource usage reporting across different deployment environments (containers vs development setups).
- **Added cgroup v2 detection and parsing** with automatic fallback to v1, by checking if a file for v2 exists
- **Process-specific cgroup path resolution** via `/proc/self/cgroup` parsing to handle systemd user slices. This is relevant, if a the project runs as sub-process, with a slice of resources of the parent cgroup (or something like that, I'm not 100% sure)
- e.g.  if I run the cocalc project server via `systemd-run --uid=$USER --unit=cocalc --scope -p MemoryMax=10G -p CPUQuota=200%`, the cgroup slice has a path: `0::/system.slice/cocalc.scope`, and quotas are specific to this group. …

project/info: cgroup v2 compatibility

---

src/packages/frontend/compute/google-cloud-config.tsx
src/packages/util/db-schema/compute-servers.ts

fixes #8519
The idea is to extract the `getMachineTypeArchitecture` heuristic (something based on name) from the utils package → then use that check for filtering the `machineType` name (not the config)
screenshots or didn't happen:
arm has them
but x84 don't

frontend/compute-servers: filter out arm64 based on name

---

src/packages/frontend/frame-editors/latex-editor/pdf-watcher.ts

silly bug, assumes it resolves relative linux directories

frontend/latex/pdf-watcher: wrong directory fallback for $HOME

---

src/packages/next/pages/policies/privacy.tsx

Novel HR data use should be opt-in, not opt-out.

Clarify HR data use as requested by DPF
