- salvus/page/top_navbar.html
The icon to contract the navbar depicted the "extend" action, and vice-versa. 
I also made the bell icon the same size as the other icons. I think they are maybe a few pixels too small and I should all make them bigger. What do you think?
> Navbar details

- salvus/page/buttonbar.coffee
LaTeX needs r" (raw strings) to properly escape \ tokens.
> Add raw string to "Text" help

- src/smc-webapp/landing_page.cjsx
There is no space between the "restrict you." and "Upload" in the rendered html.  It seems that if there is not an explicit space (not just a newline) between the period and the `<strong>` tag, the space is deleted in the rendered html.  Reformatting the paragraph ensures that the newline falls in normal text, which seems to not have the problem (evidenced by other paragraphs).
> Insert space after period on landing page

- src/smc-hub/hub-version.coffee
- src/smc-hub/hub.coffee
that's my take for the version check. before, there was just a "require"-load, and not the -reload version ... which did cancel out the `if not ...` check that was always true.
> hub/version: fixing logic when updated version is detected

- src/smc-webapp/project_store.coffee
> Allow files starting with '-' in root directory to be copied

- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_store.coffee
- src/smc-webapp/r_misc.cjsx
Mostly matches the behavior for hitting enter while in the file listing tab with the following exceptions:
- Does not open up any newly created files
- Does not navigate to any newly created folders
- Does nothing when there are files displayed even if the search bar is non-empty
I have considered to cause it to create the file anyways even if there are search results. Sort of as a "force file creation". However, this might just confuse users since it would default to a sage worksheet without any indication. This probably falls under power user functionality though?
> Add functionality for ctrl+enter in file listing tab

- src/smc-build/build.py
Remove duplicates (last occurrence) in
- SAGE_PIP_PACKAGES: astropy, nose, patsy, seaborn
- R_PACKAGES: Matrix, forecast
- SAGE_OPTIONAL_PACKAGES: topcom
> Remove duplicates in Sage and R package lists

- src/wizard/input/python/intro.yaml
I am trying to push towards using the python3 print syntax in sage. Let us try to prepare the ground.
> Change python wizard print examples to use python3 function (do NOT merge until Python3 printing is the default in Sage worksheets)

- src/webapp-lib/index.jade
- src/webpack.config.coffee
this patch hardcodes the global smc_base_url and hence saves one round trip to the hub. it also makes sure, that in the case of the production website, the "/" is actually ending up as an empty string, such that `smc_base_url + '/some/abs/path'` in the webapp codebase does work.
> webpack/webapp+hub: hardcode BASE_URL during compilation

- src/smc-webapp/editor_chat.cjsx
No other chat program I know of scrolls to the bottom on entering text. All of them do it on submit. The current behavior makes it impossible to view an old message and type a response at the same time.
> Make autoscroll happen on submit and not keydown

- .gitignore
- src/k8s/smc-webapp-static/control.py
- src/k8s/smc-webapp-static/image/Dockerfile
- src/smc-util-node/misc_node.coffee
- src/smc-webapp/account.coffee
- src/smc-webapp/misc_page.coffee
- src/smc-webapp/project.coffee
- src/smc-webapp/project_store.coffee
- src/smc-webapp/redux_account.coffee
- src/smc-webapp/top_navbar.coffee
- src/webapp-lib/index.jade
- src/webpack.config.coffee
this patch leads to a webapp codebase, where our analytics token is no longer hardcoded. if a file data/config/google_analytics is present and stores the token, it is inserted in the template -- otherwise no reporting. 
also, in case of errors (script is blocked on a DNS level, etc.) it doesn't cause exceptions in the webapp.
I've also added some handling for dealing with the dockerimages. not sure what the best way would be, this below is at least a working one. I've created the image `analytics-token-cc288f` and deployed it on test.* ... where I verified that it is really there and reporting.
PS: don't mix this up with a similarly looking image name from the commit before that -- and what's the proper way to delete an image?
> Analytics token in configuration file

- src/smc-webapp/landing_page.cjsx
For discussion on whether or not this is a good idea.
I argue that FB does it and our sign up is based on theirs. Also since the sign-up area is so large, a new user is less likely need help finding it. 
On my sample size of 3, autofocusing the email bar makes it immediately obvious where to sign in. Otherwise it is not.
I could be totally wrong. 
- @timothyclemansinsea Wants to merge the two forms. 
- I think that's more confusing.
> Autofocus email in sign-in form always

- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_store.coffee
Staging here: https://cloud.sagemath.com/7552f6e3-0f4f-4476-8954-38b9f14c6069/port/57488/
No UI changes occur except to show output and to warn user.
To use, begin a search with `/` followed by a miniterm command.
> Enable search bar to behave like mini terminal.

- src/smc-webapp/projects.cjsx
I just created a new project and clicked "Create Project Without Upgrades".  This **still** applied the members only and networking upgrades.  This makes absolutely no sense (i.e., it is a clear bug).  Please fix.
> [MAJOR BUG!] create project without upgrades

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
- wrap second import from sage.repl.attach, in sage_salvus.py with try/except
- if either import from sage.repl.attach fails, change attach() function to print warning to worksheet stderr; the import exception messages only go to sage_server.log
> Attach import repl fix

- src/smc_sagews/smc_sagews/sage_parsing.py
Fixes these two cases from #295 in sage worksheet:
```
abc = [1,2,3]
-- new cell --
for a in ab[tab]
3 * ab[tab]
```
These examples have been added to test file for #701 at https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/SAGEWS/issue701.sagews - all tests pass
> introspection fix for #295

- src/smc-webapp/buttonbar.coffee
- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
Ref #722.
sage worksheet buttonbar:
- **Help > Magic mode commands** renamed to **Help > Mode commands** and inserts `print('\n'.join(modes()))`
- **Help > Jupyter kernels** inserts `print(jupyter.available_kernels())`
- **Modes > Jupyter bridge** inserts
```
a3 = jupyter("anaconda3")
```
sage worksheet inline:
- get rid of the dummy argument to the magics function, so %magics doesn’t work
- make it modes rather than magics
> Sjmode upstream #722

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
Upstream issue is [#2](https://github.com/sagemathinc/smc/issues/2)
Please review. Not sure this is the best way to deal with problem:
- Is it ok to insert functions and classes into `__main__`?
- Problem still occurs if user calls pickle or cPickle dump methods directly.
Test worksheet here:
https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/SAGEWS/issue0002.sagews
Parent module of worksheet appears to be `__builtin__`, but defined functions and classes at top level do not show up in namespace for `__builtin__`. Problem notes here:
https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/SAGEWS/issue0002.md
> [ready for review] monkey patch save - upstream #2

- src/smc-webapp/editor_chat.cjsx
#733 
I could also format it in markdown if we wanted to have automated docs in the future.
> Add docs to chat message format

- src/smc-webapp/editor_chat.cjsx
chat edits properly tell you when the message is updated. (No longer says the message is updated when the message is not updated)
issue #731
> Chat properly tells you when it's updated

- src/smc-webapp/misc_page.coffee
- src/smc_sagews/smc_sagews/sage_parsing.py
Reference #734.
The following now allow tab completion:
- `*_factors[tab]`
- `*le_pr*[tab]`
- `list.re*e[tab]`
There is a test file at https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/tabs734.sagews, but misc_page.coffee as well as sage_parsing.py will need to be updated for examples to work.
This follows the precedent in command-line sage in which a get-completions expression is treated as a wildcard expression if it contains one or more embedded asterisks. See [IPython/core/inputtransformer.py](https://github.com/ipython/ipython/blob/8b766e65c15d3f07e05ee6228d60256a5451df0d/IPython/core/inputtransformer.py#L211)
> [ready for review] allow tab completion on glob expressions upstream #734

- src/smc-webapp/editor_chat.cjsx
Fixes issue #766 . Added 1 input limit, fixed a bug where if someone deletes a message it says "last edited time ago by user" instead of "message is deleted"
> going to another tab saves chat edits

- src/smc-webapp/last.coffee
This is related to #61 and will still be there when the file area is a dropzone -- with a different info text, of course.
> webapp: preventing accidental file drops outside the drop area

- src/smc_sagews/smc_sagews/sage_parsing.py
Fix for: #70 
I tested several python segments with lines beginning with a literal and was not able to cause an error with this code change, but could be missing a case where the comparison `code[i][:2] == '%('` at line 219 in the original is needed.
> [ready for review] Issue70 indent

- src/smc-webapp/projects.cjsx
If you go into the list of projects, and begin to search for something that is not found in any project of the descriptions, the system correctly displays none of your projects.
However, the warning is not very large and not very bold. This might panic a user, who incorrectly imagines that their projects have all vanished. In fact, this very thing happened on August 4th, at MathFest 2016, to James Quinlan of the University of New England, and it panicked him visibly. 
This talk was essentially a demo of SageMathCloud, and it left the impression that SageMathCloud is non-trivial to use---precisely the antithesis of the talk's objective and purpose.
p.s. This issue ticket was requested by William on August 8th, in an email.
> The warning, when searching for projects, is not large/bold enough.

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
Ref: #757 
IPython pager did not sent output to BufferedOutputStream, even after adding encoding attribute, unless TERM environment variable was temporarily set to 'dumb'. Instead of going doing that, here's another monkey patch.
Note: With default limits, calling license() from sagews truncates output with error message  
_WARNING: Output: 70068 truncated by MAX_STDOUT_SIZE to 40000.  Type 'smc?' to learn how to raise the output limit._  
Rather than modifying limits, I added a reminder in the docstring that the sage `license()` command (which invokes a pager) is available in a terminal session.
> [ready for review] Issue757 license() for sagews

- src/smc_sagews/smc_sagews/sage_server.py
Proposed fix for #399 is to override `Salvus.execute()` argument `preparse` if `preparser(False)` has been called.
Test cases are in https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/SAGEWS/issue399test.sagews. That project is running the proposed modification.
> [ready for review] allow sage.repl.interpreter._do_preparse to override preparse argument

- src/smc_sagews/smc_sagews/sage_parsing.py
Ref #819 
Block parser was substituting comments (as well as strings) with %(Lxx) labels and removing them later. Code that substituted the comments is taken out.
Internal testing at https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/SAGEWS/issue819test.sagews - requires code change to be in place.
> [ready for review] issue819 block parser skip comments

- src/smc-project/print_to_pdf.coffee
useful for further fine-tuning and of course debugging -- fixes #854, touches #81
> sagews2pdf: fix keeping subdirectory of temporary latex files

- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_store.coffee
Users are constantly making big files, clearing up space by deleting them, then running out of space because they didn't "empty their trash", since it's not obvious how/where to do so.   But why bother?  We have snapshots every few minutes, so the trash can serves no purpose.  Let's just get rid of it.
> Get rid of the trash -- we have snapshots to solve the same problem.

- src/smc-webapp/_console.sass
- src/smc-webapp/console.coffee
this addresses #860 and also adds a bit of room for lines to avoid overwriting "_" by the next line.
I also bet that this is browser/OS specific, so maybe it always worked for @williamstein but never for me? My hope is, that my fix here errs on the lower side, such that the terminal is in all cases narrower than before.
> webapp/console: fixing col width and more room for line height

- src/smc-webapp/editor_chat.cjsx
You currently can't type messages into the main chatrooms in SMC on mobile chrome (on iOS / Android).  It works fie on mobile safari.
> fix mobile chat on android (and iphone chrome)

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
- src/smc_sagews/smc_sagews/tests/test_sagews_x.py
See #898 
~~Use `find|grep`, not `git grep`, for search_src.~~
Fix path for `git grep` command used by search_src. Add pytest cases.
> fix search_src after SMC upgrade to sage-7.3

- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server_command_line.py
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
- src/smc_sagews/smc_sagews/tests/test_sagews_timing.py
%sh mode revised to use jupyter bash kernel
- keep state (shell variables, working directory) between %sh cells
- auto completion
- color output for example from `ls`
__warning related to capture__
- jupyter bash kernel does not separate stdout and stderr as cell is running. it only returns `ok` or `error` depending on exit status of last command in the cell. So all cell output captured goes to stdout or stderr depending on last command
__sage_server_command_line__ modified to kill stuck client processes. I suspect these arise more often during testing than normal use. I added this change while testing %sh mode. For details, see https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/TEST_SAGEWS/test_processes.md section _Reliably creating stuck child process of …
> sagews %sh mode using jupyter kernel

- src/dev/docker/README.md
- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/sage_server.py
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_graphics.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
- src/smc_sagews/smc_sagews/tests/test_sagews_timing.py
- src/smc_sagews/smc_sagews/tests/test_sagews_x.py
Ref. #920 
This PR fixes autocomplete for direct and default %sh mode and adds pytest for those.
Test with
```
python -m pytest test_sagews_modes.py::TestShMode
```
Not fixed in this PR: %capture with %default_mode sh.
> sagews %sh autocomplete

- src/smc-webapp/project_files.cjsx
I needed to copy a directory of files from one project to another project, and I wanted my directory to reside in the home directory of the new project. 
The copy button was grayed out. 
Then @hsy and I chose an arbitrary destination directory, and it successfully copied it there. This means I had to move it from its arbitrary destination into the home directory of the new project.
Yet, surely, it should be possible to copy something into a new project's home directory.
> When copying a directory to another project's home directory, the copy button was grayed out

- src/smc-webapp/projects.cjsx
fixes issue #814 
the line deleted gives errors since @refs.projects_search is undefined there.
> fixed cancel filter so it removes hashtags

- src/smc_pyutil/smc_pyutil/smc_compute.py
Sometimes /projects/[project_id] doesn't have group/owner equal to that of the project.  Add a check or something in src/smc_pyutil/smc_pyutil/smc_compute.py to ensure it does whenever starting the project.
(Don't just chown the whole tree though, since that can take a very long time and is usually wasteful.)
> sometimes a project's home directory is owned by root (so wrong permissions)

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Second part of #920.
- fix %capture with %default_mode sh
- fix %capture with %default_mode r
- add pytest cases for above and simple computation in r
To run pytest cases for this issue:
```
python -m pytest test_sagews_modes.py
```
> fix capture for default modes for sh and r, add pytest cases

- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Fixes #890, sagews pytest updated.
to test:
```
python -m pytest test_sagews_modes.py::TestShMode
```
> filter deprecation warnings when starting jupyter kernel

- src/smc-webapp/editor_chat.cjsx
Fixes issue #669 
Changed auto focus to false on ios since we don't want to auto focus most forms on mobile. Changing auto focus to false on android messes up the input, so auto focus is set to true and it works.
> Iphone and android chrome input fixes

- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
- src/smc_sagews/smc_sagews/tests/README.md
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_graphics.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
- src/smc_sagews/smc_sagews/tests/test_sagews_timing.py
Issue/bug #355.
- %octave mode uses jupyter kernel (this will hide sage octave())
- add pytest for calculation, plot, capture in default mode octave
- omit output count numbers "[1] xxx" etc. from jupyter kernel outputs
- more pytest refactoring
```
python -m pytest test_sagews_modes.py::TestOctaveMode
python -m pytest test_sagews_modes.py::TestOctaveDefaultMode
python -m pytest test_graphics.py::TestOctavePlot
```
> Issue355octave

- src/smc-webapp/editor.coffee
this is essentially using it in an iframe.
for testing with smc-in-smc, the nested project url doesn't work. there is a commented src link in the code to try it with a real path.
> use nbviewer.jupyter.org to preview publicly accessible ipynb files

- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_00_timing.py
- src/smc_sagews/smc_sagews/tests/test_graphics.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Reference: #862.
Added pytest cases for
- #862 
- anaconda3 jupyter bridge
- julia jupyter bridge
- sagemath jupyter bridge
Put sage & sage_server timing tests at start of default test run because they are most robust about initial state of sage_server.
To run just the new tests:
```
python -m pytest test_sagews_modes.py::TestJupyterModes
```
> fix newlines with jupyter bridge #862

- src/smc-webapp/profile.cjsx
This would address editors like chat where line numbers make no sense
> don't show line number if line = 1 in users viewing document

- src/smc-util/misc.coffee
- src/smc-webapp/markdown.coffee
- src/smc-webapp/sagews.coffee
also covering cases where formulas are enclosed in _italic_, etc.
strings for testing markdown, the new case is a formula in markdown or bold, while also handling pre-tag escaping:
1. **Lemma 4.** _There is an $n_0 > 0$ such that $a_n < 2^n$ for all $n > n_0$._
1. **Lemma 4.** <i>There is an $n_0 > 0$ such that $a_n < 2^n$ for all $n > n_0$.</i>
1. **foo** bar _italic start $a^b$ **this bold `not $9`** $a_b$_ end of italic
1. bar **foo _abc $9^3$ `foo $9` $a^b$_ end** xyz
1. bar **foo _abc $9^3$ ```foo $9``` $a^b$_ end** xyzt
1. **foo $x^` y$ bar**
1. _foo $x`y$ bar_
1. `foo **$9` $a^b$ **bar**
old cases:
$a^b$
`Payment of $499`
abc `text $ 123` abc
abc `$a^b$` test
<pre>
$a^b$
</pre>
```
asdf $a^b$ asdf
asdf
```
<pre>
$ cd ~
$ mkdir apps
</pre>
```
$ nosetests pandas$
..........
OK …
```
> webapp/markdown+mathjax: second attempt at fixing #112

- src/smc_pyutil/smc_pyutil/sagews2pdf.py
this enhances special-case handling of sagews2pdf in a straightforward way and  fixes #575
here are two sagews cells for testing:
%md
0 &lt; &le; = &ne; &ge; &gt; 11
foo $1 \lt \le  = \neq \ge \gt 2$ bar
and 
%html
<div>0 &lt; &le; = &ne; &ge; &gt; 1</div>
<div>foo $1 \lt \le = \neq \ge \gt 2$ bar</div>
> handling relational html signs like &lt; &gt; and corresponding mathjax commands like \lt and \gt

- src/smc-project/raw_server.coffee
- src/smc-webapp/project.coffee
fixes #982
testing:
* try it with a pdf or svg file
* webapp recompilation
* restart the project to pick up the modified `smc-project/raw_server.coffee` file
> webapp+raw_server: tell browsers to always download a file if it should be downloaded

- src/smc-webapp/project.coffee
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_store.coffee
This is a simple solution for all issues related to #328 
Note, that it also support right-click and "copy url", since it is in the href of an anchor.
What I haven't done is to think much about the styling (we could add a hover text), nor if this also shows up for public file listing (would it work there?). Still, I like it, it's very minimal and it doesn't add much clutter.
It also definitely conflicts with my recent PR #983 since it moves that raw URL creation into a separate function ... merging is trivial, though.
> webapp/file listing: add download buttons that also support right-click → copy url

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_00_timing.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
Reference: #63 
Fix was tricky because
- I was only able to set sage.misc.session.state_at_init after first code block has executed
- sage.misc.session.init() is not called until first invocation of show_identifiers()
- need to set sage.misc.session.state_at_init before first user cell executes or risk missing variable assignments in that cell
- worksheet server adds 'smc', 'salvus', 'require', and sometimes other identifiers to session namespace - I made the requirements choice of removing these before returning show_identifiers() because user can't shadow them anyway.
Pytest cases have been added for show_identifiers(), reset(), save_session(), load_session(). To run just the new tests:
```
python -m pytest test_sagews.py::TestIdentifiers
```
> show_identifiers() #63

- src/smc-webapp/sagews.coffee
see #1012 ... not sure if this is a fix at all, it does at least handle all the corner cases and finishes fixing [this change from a while ago](https://github.com/sagemathinc/smc/commit/5215886c8352504f199e00cc402960dff7269518#diff-9d796ba4eb777e83c8f17a2169b073dbL2416)
So, the point is, this PR should go in asap, but I'm not sure if the story behind why #1012 came up in the first place is fixed by that.
> webapp/sagews: discarding empty strings when deserializing cell output -- related to #1012

- src/smc-webapp/project_store.coffee
fixes issue #995
for testing:
```
mkdir -- '- bbb'
echo "xxxxx" > '- aaa'
echo "xxxxx" > '- bbb/xyz'
```
and then "find"-search for "xxxxx" with or without clicking the "include subdirs" checkbox.
> webapp: fix grepping through files and subdirs starting with a dash

- src/smc-webapp/editor.coffee
- src/smc-webapp/editor_latex.coffee
Fixes #1065. 
This is *not* clean and does *not* fit into the current framework snugly. No idea if this is acceptable or not since our next strategic plan is to redo the LaTeX editor in React anyways.
> Fix Rebuilding LaTeX Document on Save

- src/smc-webapp/index.sass
The "buttons" e.g. in the "files", "new", ... and open editors row aren't changing the mouse cursor to a pointer (only the text inside of them). this changes this for all anchors with the role "button".
> webapp/css: <a role="button"> mouse should be a pointer, not arrow

- src/smc_sagews/smc_sagews/sage_salvus.py
see issue #89. also dealing with empty string corner case.
Test this via
```
typeset_mode(True)
rows = [['a', 'bäßbb', 'cö'],[100,2,3], [4,5,60]]
table(rows, header_row=True)
```
> sagews: Sage's table command produces a latex text environment, which can't be processed by mathjax

- src/smc-webapp/package.json
- src/smc-webapp/syncdoc.coffee
- src/smc-webapp/tasks.coffee
Fixes #1067 
Timeago would wait until next update to change the text. Added 2 lines to just make sure that we show timeago if there is a relevant date.
> Fix correctly displaying timeago on render

- src/smc-webapp/billing.cjsx
Fixes #1088 Now correctly on the same line.
> Fix add credit card date UI

- src/smc-webapp/course/assignments_panel.cjsx
- src/smc-webapp/course/handouts_panel.cjsx
- src/smc-webapp/course/main.cjsx
- src/smc-webapp/course/students_panel.cjsx
Persist the expansion state of assignments in the course management. 
Implemented with an `immutable.Set`. Does not propagate to other clients.
Without this change, expansion state of assignments is loss between unmounts which makes things like grading a lot slower.
> Fix assignment expansion state

- src/smc-webapp/desktop_app.cjsx
- src/smc-webapp/init_app.coffee
- src/smc-webapp/landing_page.cjsx
Changes `Account` button in top nav menu to be a `Sign in` button when not logged in.
Clicking `Sign in` also tries to log in if you're on the
landing page. Thus any confusion caused by the text
on the screen is a moot point.
An open public file:
On the landing page with an open public file:
View after clicking the `Sign in` on the top nav:
> Change Account button to Sign in when not logged in

- src/smc-webapp/project_store.coffee
Fixes #1093. File activity notification was setting state using old saved state data. Mistakes were made.
> Remove setting store to old data

- src/smc-webapp/course/students_panel.cjsx
- src/smc-webapp/project_settings.cjsx
issue #1117 
how to test:
1. search for a new collaborator and if there is just one name as a result, clicking on "add user" is enough (not clicking on the name to actually select it)
2. the same in the student panel of a course, i.e. search for a name and if there is just one result, clicking on the button is also enough
> one-click adding for single search result when adding a collaborator or student

- src/smc-webapp/init_app.coffee
- src/smc-webapp/projects.cjsx
- src/smc-webapp/projects_nav.cjsx
Fixes #1106 
If fetching the title times out, the browser tab will default to "SageMathCloud".
If the title is blank, the browser tab will read "Untitled Project  - SageMathCloud".
While fetching a public title, the browser tab will read "Loading Project - SageMathCloud"
> Fix browser tab title on project refresh

- src/smc-webapp/desktop_app.cjsx
Fixes #1085 
As @williamstein points out, this is consistent with behavior found in browser tabs.
> Make project tabs just pile up next to each other

- src/smc-webapp/projects_nav.cjsx
Ensure updating the browser tab title whenever the active app tab title changes.
Fixes #1123
Also fix up scope of data passed to project tabs.
> Fix more title consistency issues

- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
- Use atexit and sage cleaner to kill jupyter client and kernel processes and subprocesses when sage client exits.
- Also fixes bug with ansi colors in stderr output seen with anaconda3. Test case added.
- Fix a couple typos.
> Jupyter cleanup

- src/smc-hub/compute-server.coffee
I think it's a sane move to limit this map a little bit, e.g. after restart or during high load. of course, if it takes longer than two minutes, we're in in any case in a gameover situation.
> compute server: limit the number of parallel state updates

- src/smc-util/client.coffee
- src/smc-util/synctable.coffee
- src/webapp-lib.coffee
see issue #1098
I've tested this on a test course with 200 students. There, the 'disconnected' event alone has 411 listeners. Hence that new limit of 3000 is well above this.
> webapp/client: increasing max number of listeners of Client to 3000

- src/smc_pyutil/smc_pyutil/sagews2pdf.py
issue #100
I also tested, if it converts some other sagews with images and that worked, too. seems to be a pretty safe fix.
> sagews2pdf: no newline when inserting a graphic, then the latex is valid when there is an image inside an \href

- src/smc-util/syncstring.coffee
- src/smc-webapp/project_file.cjsx
- src/smc-webapp/syncdoc.coffee
issue #591
this patch indirectly prefixes the filename for SyncDoc (and derived) objects with the symlink to the root directory in .smc
I think that's not the whole deal, since that sha1 sum comes up at more places, but at least `open /tmp/text.md` works.
> sync: dealing with file paths not inside the project

- src/smc-webapp/course/main.cjsx
- src/smc-webapp/course/settings_panel.cjsx
- src/smc-webapp/projects.cjsx
- src/smc-webapp/smc-react.coffee
- src/smc-webapp/users.cjsx
Edit:
Removed `wait until` madness.  
Now tries for 5 minutes to keep all projects running or closed. 
Clicking the other option while this happens removes the timeout and interval of the previous action.
> Improve start/stop all student projects UI feedback

- src/smc-webapp/editor.html
- src/smc-webapp/editor_latex.coffee
this fixes this by reverting this and instead removes the buttonbar via jquery from the latex editor pdf previewer
> webapp: commit ac759ba062b5f erroneously removed the buttonbar from the embedded pdf viewer

- src/smc-webapp/billing.cjsx
- src/smc-webapp/browser.coffee
- src/smc-webapp/client_browser.coffee
- src/smc-webapp/console.coffee
- src/smc-webapp/d3.coffee
- src/smc-webapp/editor.coffee
- src/smc-webapp/editor_codemirror.cjsx
- src/smc-webapp/editor_git.cjsx
- src/smc-webapp/editor_history.coffee
- src/smc-webapp/editor_jupyter.coffee
- src/smc-webapp/feature.coffee
- src/smc-webapp/last.coffee
- src/smc-webapp/misc_page.coffee
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_log.cjsx
- src/smc-webapp/render.coffee
- src/smc-webapp/sagews-eval.coffee
- src/smc-webapp/sagews.coffee
- src/smc-webapp/salvus_client.coffee
- src/smc-webapp/smc-react.coffee
- src/smc-webapp/syncdoc.coffee
- src/webpack.config.coffee
This patch exposes `smc.*` objects iff webpack's injected `DEBUG` variable is true.
The range of areas it touches are the idle timeout, syncdoc, history editor, jupyter and billing.
Most importantly, transferring the "Connection" object from the client_browser to the salvus_client is done via a function call and not the global smc.client object.
Additionally, creating the statically rendered files also needs to be checked.
> webapp: only expose smc.client and related objects for testing

- src/smc_sagews/smc_sagews/sage_salvus.py
Add docstrings for the new jupyter versions of these modes. There was a [posting on sage-devel](https://groups.google.com/d/msg/sage-devel/QaBdHSNJuKg/yXwZ-MIiBAAJ) looking for doc on the new `r` in smc.
> docstrings for %octave and %r using jupyter

- src/smc-webapp/app_shared.cjsx
Fixes #1180 
Now above all normal components. Placed below temporary warnings and popovers.
> Change version warning z-index

- src/smc-webapp/account_page.cjsx
- src/smc-webapp/billing.cjsx
> Add confirmation message to payment card

- src/smc-webapp/sagews.coffee
- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/sage_salvus.py
issue #1192
This is actually really weird. When the output renders, the image is drawn (at least) two times. The first time around it is all fine, the naturalWidth is like it should be, scaling works. It should just stop there!
But immediately afterwards, probably triggered by some sync mechanism, the output is rendered again, the naturalWidth is unfortunately 0 (I assume, the image is removed from the DOM but not loaded) and the calculated width is zero. Therefore, here in this code, there is this addition to do the calculation after it has been loaded the second time around.
> jupyter/sagews: using image scaling factor to resize it in sagews

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/tests/test_graphics.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Ref: #1202 
Recent config changes for octave in jupyter kernel already changed plot file format from svg to png. All that was needed is scale factor; 0.66 looks good.
Server-side pytests updated. `71 passed in 114.32 seconds`
> 1202octavepng

- src/smc-webapp/_editor.sass
- src/smc-webapp/sagews.coffee
this little change makes it easier to select multiline output. my test-case is to copy paste the whole output of `random_matrix(GF(2), 10, 10)`. works much better than it does right now.
I also checked it in firefox, and well, all other output types like images and md aren't touched by that. I also tested to switch to other codemirror themes...
> webapp/sagews: display output spans as blocks, span-wrap images and improve multiline-selections of text output

- src/smc-build/smc-ansible/all-install.yaml
- src/smc_pyutil/setup.py
this reverts 2f6bf61a9f5f and fixes #1213 
for reviewing: my test was to temporarily tell the setup.py to always change the executable (i.e. `if True: # ...`)  and then to see what it produces in my `~/.local` and that my local `smc-status` works.
`/usr/loca/bin/python2-nosite` is [this globally installed wrapper](https://github.com/sagemathinc/smc/blob/master/src/smc-build/smc-ansible/files/python2-nosite)
> smc_pyutil: using python2-nosite to avoid interferences with ~/.local

- src/smc-webapp/interact.coffee
This also fixes
```
%prun
1+1
```
It's really strange, since that spelling error has been there since 2013? how is that possible?
> webapp/interact: parse_width spelling error -- #1212

- src/smc-hub/compute-client.coffee
how to test:
1. `mkdir -- -test`
2. share `-test` publicly
3. sign out
4. open the `-test` subdirectory in the public listing
one could philosophy about where in the layers to actually fix this. I opted for this place, since it makes no sense to deal with it in the front end code and I don't want to change the python parser (just by looking at the passed arguments, it is usually too late to disambiguate. the place where it is called needs to be fixed)
> hub/compute: public listing of directories with leading dashes -- #1221

- src/smc-webapp/init_app.coffee
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/projects.cjsx
Fixes #1247 
- Allows highlighting text without opening the file
- Applied to projects in the projects listing as well.
- Opens the file if you click on it
- Nothing is highlighted when you check multiple rows with `shift + click`
> Allow copying file and folder names from the files listing

- src/smc_sagews/smc_sagews/sage_parsing.py
- src/smc_sagews/smc_sagews/tests/README.md
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
Fix for #1251 so smc_sagews pytests can be run from any directory. Added fixture to set directory for read-only data files.
I updated the README.md to reflect where I usually run the tests. But tests now also work if you invoke them per the previous instructions, i.e.
```
cd smc/src/smc_sagews/smc_sagews
python -m pytest tests
```
> 1251testdir

- src/smc-webapp/init_app.coffee
Fixes all known replication cases of #1271. 
App was trying to close tabs which didn't exist on every store change.
> Do nothing on closing a project if it's not open

- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Ref: bug #1279 
- show ansi color codes in scala text output properly
- add `%scala211` built-in jupyter bridge mode and alias `%scala`
- add pytest for the two new modes
- remove commented-out `%r` mode code
```
~/smc/src/smc_sagews/smc_sagews/tests$ python -m pytest
...= 114 passed in 152.96 seconds =
```
> 1279scala ansi

- src/smc-webapp/_editor.sass
- src/smc-webapp/editor.coffee
solution to #1337 by showing it when the buttons are initialized. also, changing the style to be similar to with the other buttons.
> webapp/editor/mode: showing mode button for sagews editor -- #1337

- src/smc-webapp/interact.coffee
I don't know why this was broken, but wrapping again in jquery fixes #1354
> webapp/interact: wrapping options of selectors in jquery -- fixes #1354

- src/smc_sagews/smc_sagews/sage_server.py
Ref: #1349 
How does this look? I didn't add pytest cases yet because I'm not sure the test is specific enough.
Example:
```
def f():
a = [0]
a[0]
---
Error in lines 3-3
Traceback (most recent call last):
File "/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/.local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 977, in execute
exec compile(block+'\n', '', 'single') in namespace, locals
File "", line 1, in <module>
NameError: name 'a' is not defined
*** WARNING: Code contains non-ascii characters ***
```
> warn about non-ascii characters in code if there is an error #1349

- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_log.cjsx
- src/smc-webapp/project_miniterm.cjsx
- src/smc-webapp/project_page.cjsx
- src/smc-webapp/project_store.coffee
- src/smc-webapp/projects.cjsx
- src/smc-webapp/r_misc.cjsx
- src/smc-webapp/r_upgrades.cjsx
Fixes #1326. 
In my opinion, this isn't the prettiest solution, but a better solution (I would rather all folder paths end with `/`) is *much* more involved with a *lot* more testing. #1330 proposes this change.
> Fix opening copied directories from log

- src/smc-webapp/_editor.sass
- src/smc-webapp/editor.coffee
- src/smc-webapp/feature.coffee
This is the best I came up with for #1347. The root problem is, that setting the innerHTML in an iframe doesn't trigger any javascript to run. Maybe that's a security measure, I don't know (even a `console.log` in a script tag doesn't work) and therefore no mathjax.
However, setting the srcdoc works in almost all browsers and this falls back to jquery's `html(...)` for the other ones.
Besides that: It removes a margin which make no sense.
> webapp: set public html iframe srcdoc when supported -- #1347

- src/smc_sagews/smc_sagews/tests/test_sagews.py
Add pytest cases for
- #1350 warn about non-ascii characters in code
- four linear algebra examples in sage, based on tutorial at http://www.dm.ufrpe.br/sagemath
> 1350pytests

- src/smc-webapp/r_account.cjsx
- src/smc-webapp/redux_account.coffee
Turns out I broke forced refresh in the react rewrite. 
Currently if you have this option checked
and you sign out, failing tell the page to reload will allow anyone to **log onto your account with their own credentials**.
> Force refresh on logout

- src/smc-webapp/r_misc.cjsx
Fixes #1329 in all markdown renderers which use the `r_misc.Markdown` component.
> Always render \$ as $.

- src/smc_sagews/smc_sagews/tests/test_graphics.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Unique test function names will make it easier to work with the `sagews-test-report.json` test results report.
> make test function names unique, fix typo

- src/smc-hub/email.coffee
- src/smc-hub/hub.coffee
- src/smc-hub/package.json
- src/smc-util/client.coffee
- src/smc-util/message.coffee
- src/smc-webapp/course/main.cjsx
- src/smc-webapp/project_settings.cjsx
- src/smc-webapp/projects.cjsx
(unless email_address is undefined, then it falls back) and updating the sendgrid API to v3. -- issue #1316
for testing: update the sendgrid npm package, then send an invitation email and a course invite. in both cases, the normal "reply" in the email will be the actual user, not help@sagemath.com. also, in gmail, when clicking on "show original" in the email's drop down, SPF and DKIM both pass.
> webapp/hub: setting reply-to in emails such that recipients automatically contact the correct one

- src/smc-webapp/_misc_page.sass
- src/smc-webapp/client_browser.coffee
based on http://stackoverflow.com/a/17490775/54236 -- and I also added a second event listener and also check for touch movements.
@timothyclemansinsea please test if this helps with safari and chrome/WKWebView ... and well, it should preferably not break the existing behavior
> safari mobile: make idle notification have a pointer cursor #1415

- src/smc-webapp/project_files.cjsx
see  issue #1414
this is a proposal for how to deal with that situation. it basically checks, if the path is an absolute directory (when opening that directory mentioned in #1414, `readlink -f` shows that it is really a root directory)
"logical" would be to get rid of the home "house" icon, but I don't like doing that. therefore, it adds a bit of extra space to distance it.
> webapp/files: fix path for root directories

- src/smc-webapp/r_misc.cjsx
this deals with issue #1296 by getting rid of unnecessary code duplication
more importantly, it fixes the broken "rename" action (which would have also been broken for "duplicate", because there is no `get_basename` function)
testing: open a sagews and go through all the options in the blue info dropdown.
> webapp/file info dropdown: deriving actions from file_action_buttons and fixing missing "get_basename" function for set_file_action

- src/smc-webapp/editor-html-md/editor-html-md.coffee
- src/smc-webapp/editor.coffee
- src/smc_pyutil/setup.py
- src/smc_pyutil/smc_pyutil/rmd2html.py
Ref: #1424
Initial version, allows you to open a .Rmd file and see it recompiled in real time.
Adds `rmd2html.py` (committed in `smc_pyutil`) which must be in command path.
Features possibly to be added after this:
- view pdf
- view md
- clear knitr cache
- buttonbar
- add `r` code chunk
- menu of code chunk options
> issue/1424 Rmd edit mode 

- src/smc-webapp/editor-html-md/editor-html-md.coffee
- src/smc_pyutil/smc_pyutil/rmd2html.py
@DrXyzzy  this patch does two things
1. it switches to the directory where the files is -- before `smc-rmd2html` is even called. hence, all relative files will be relative to it, etc.
2. there is a variable `warnings` collecting the `stderr` output. The only problem is, in `@to_html` this warnings variable from the callback is not used at all. Therefore, I wasn't able to see any issues but now I could.
what I don't understand is what is going on with saving the file.
> webapp/rmd: showing errors when back-end fails to run and switching path for subdirectories

- src/smc-webapp/project_files.cjsx
Fixes a bug where `file_creation_error` wasn't hooked up to the store.
**Edit**: Fixes #1481
Should look like this.
Test:
1. Go to file page
2. Make sure the search bar is *empty*
2. Click the down arrow of `Create`
3. Click on one of the file types.
4. You should see a notice.
This is currently broken on live. Who knows how long it's been broken for.
> Make file creation errors show again

- src/smc-webapp/project_files.cjsx
Addresses #1480 
Looks like:
To test:
1. Open files listing tab in a project
2. Have enough files for a second page to be necessary.
3. Observe a missing `Add Collaborators` button and no top pager.
> Remove some files listing clutter

- src/smc_pyutil/setup.py
- src/smc_pyutil/smc_pyutil/ipynb2sagews.py
- src/smc_pyutil/smc_pyutil/lib/__init__.py
- src/smc_pyutil/smc_pyutil/lib/sagews_cell.py
- src/smc_pyutil/smc_pyutil/m2sagews.py
Patterned after `smc-ipynb2sagews`, this PR adds a utility to take one or more `.m` files on the command line and make a `.sagews` file for each one, with a header cell setting the default mode and a single body cell containing the file contents.
Input file foo.m:
```
x = eye(5)
```
After running `smc-m2sagews foo.m`, get output file `foo.sagews`:
```
%auto
%default_mode octave
--- 
x = eye(5)
```
> add smc-m2sagews utility

- src/smc-webapp/misc_page.coffee
- src/smc-webapp/project_files.cjsx
I think there is not ticket, but this is something very simple we should have done long time ago. If in "commercial" mode and inside the sharing file dialog with a published file, it shows facebook, g+ and twitter action buttons. They point to sharing URLs and hence there are no additional dependencies.
testing: select a file and share it. 3 sharing buttons should appear after clicking on "make item public".
> webapp: sharing to social media buttons if shared file is public

- src/smc-webapp/project_page.cjsx
small consistency fix: prior to this, e.g. the icon for dockerfile or makefile do not show up in the tab when it is opened in an editor. (same issue in `project_files` is already fixed: eae52f0637687 )
how to test: `touch Makefile` and open it. the tab should show the gears icon and not the default `code-o` icon.
> webapp/file tabs: this makes the tab icon for files consistent with the actual definition

- src/smc-webapp/editor.coffee
- src/smc-webapp/editor.html
- src/smc-webapp/editor_latex.coffee
- src/smc-webapp/project_store.coffee
see issue #19
testing:
* click and drag in a latex preview, double click should still do the inverse search.
* make sure it doesn't behave strangely when going outside the viewport or outside the browser window (i.e. it might get stuck in the mouse-down state, etc.)
* it even works on my laptop's touch screen, but I haven't tested it with an actual tablet
> webapp/latex: drag preview with mouse, renaming output to pages

- src/smc-util/misc.coffee
- src/smc-util/test/misc-test.coffee
- src/smc-webapp/project_page.cjsx
- src/smc-webapp/project_store.coffee
Fixes #1561. 
Saves scroll position for any editor that doesn't maintain internal scroll state.
Implements tests for `tab_to_path` and `path_to_tab`
Testing:
1. Create a course
2. Add some assignments
3. Toggle open some assignments to produce a scroll bar
4. Open an assignment folder.
5. Return to the course to find yourself in the same position
6. Open any other page/tab in SMC and return to the course.
Do the same for students but this time open the student project.
Do the above steps again but with chat open
> Save Scroll State on Courses

- src/smc-webapp/course/common.cjsx
- src/smc-webapp/course/main.cjsx
- src/smc-webapp/course/students_panel.cjsx
Things **not** in this PR:
- Custom ordering
- Changing default ordering
Also adjusts some spacing across tabs.
Account settings:
1. Create students in a course
2. Clicking on any of the headers should sort by that column.
3. Clicking on the same header again should reverse the order.
4. Clicking on a different header should start with the arrow pointed down.
5. Any columns not being sorted by should not have any arrow next to the name
6. The arrow should initially appear next to `Last Name`
7. Arrow down should mean a -> z (caps ignored) for names and emails.
8. Arrow down for `Last Active` should mean most recent to never used
9. Arrow down for `Hosting Type` should put members before free servers.
> Add Student Sorting to Courses

- src/scripts/postgresql/cool-queries.md
- src/smc-webapp/editor-html-md/editor-html-md.coffee
- src/smc-webapp/misc_page.coffee
right now, in the preview of md files, relative and absolute links inside SMC open a new tab .This fixes this. It also ports the enhancements from the now removed image and object source rewriter to this plugin.
testing: check that relative urls open inside smc inside the md preview. since the jquery plugin is touched, also check that images in `%md` cells pointing relatively to smc still work.
> markdown external links

- src/smc-webapp/_editor.sass
I don't know what's happening. There has been a tiny change in the css and this patch here at least makes them blocks and hence there is a perceived line break. What was the problem (or what was fixed by the change) before? /cc @williamstein
> webapp/sagews: hotfix for line breaks in stdout

- src/smc-webapp/misc_page.coffee
- src/smc-webapp/package.json
See #1658
This is about codefolding in latex, i.e. test that
```
\section{asdf}
asdf
\subsection{asdfasdf}
fdas
\subsection{asdfasdf}
```
closing the first subsection still shows the second one, etc.
I'm against using that shim for IE, just adds some baggage and long term we'll transition to lodash anyways. (<strike>Regarding size, that  just adds that one function, not the whole deal</strike> we already ship lodash anyways ...)
> webapp: using lodash.trimstart instead of String.prototype.trimLeft

- src/smc-webapp/editor_latex.coffee
Looks like a simple race condition in the callback. This should prevent that exception:
```
id           | f0ad8861-2387-4053-8f80-abafc4d5423c
name         | TypeError
message      | Cannot read property 'spellcheck_highlight' of undefined
comment      | 
stacktrace   | TypeError: Cannot read property 'spellcheck_highlight' of undefined                                                                                                                                                                                              
|     at Object.preview.pdflatex.spell_check.cb (https://cloud.sagemath.com/static/smc-a16074d1e62237848769.js?a16074d1e62237848769:225:12272) 
|     at Object.disable.e.lang._exec.cb (https://cloud.sagemath.com/static/smc-a16074d1e62237848769.js?a16074d1e62237848769:29 …
```
> webapp/latex: safeguarding against error f0ad8861-2387-4053-8f80-abafc4d5423c

- src/smc-webapp/editor.coffee
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_new.cjsx
That's based on these new error reports. I actually don't know how to trigger the error, which is weird. This change at least uses the functions from the editor to derive the icon and there are also small changes to make sure that there is always an icon defined.
> webapp/files: this fixes "icon undefined" errors of new file dropdown lists, in NewFileDropdown and ProjectFilesNew

- src/smc-webapp/file_use.cjsx
Per bug found by HSY webapp error reporter!
Would throw an error when someone with no file use notifications tried to submit a search inside the file use widget.
> Fix rare file use bug

- src/smc-webapp/editor.coffee
Only concerns tex files, and this fix is based on exceptions like
```
stacktrace   | TypeError: Cannot read property 'offset' of undefined                                                                                                +
|     at n.scroll_into_view (https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:30:3131)                               +
|     at n.scroll_into_view (https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:28:4965)                               +
|     at n.zoom (https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:30:1896)                                           +
|     at n.zoom (https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:28:49 …
```
> webapp/errors: scroll_into_view -> offset undefined

- src/smc-webapp/editor.coffee
the no. 1 reported error is like
```
TypeError: Cannot read property 'getViewport' of undefined
|     at n._set (https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:29:9926)
|     at n.<anonymous> (https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:28:4965)
|     at n._set (https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:28:4965)
|     at Object.cb (https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:168:8473)
|     at https://cloud.sagemath.com/static/smc-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:160:15271
|     at function.e._wrapper.e._wrapper (https://cloud.sagemath.com/static/lib-cd251bc36c45dc61b87c.js?cd251bc36c45dc61b87c:131:3934)
|     at …
```
> webapp/errors: "getViewport" property is undefined

- src/smc-webapp/3d.coffee
That's a trivial one, see https://github.com/mrdoob/three.js/blob/master/examples/js/controls/OrbitControls.js#L962
```
message      | THREE.OrbitControls: .noKeys has been deprecated. Use .enableKeys instead.
comment      | 
stacktrace   | <generated>                                                                                                                                 +
| Error                                                                                                                                       +
|     at i (https://cloud.sagemath.com/static/lib-a16074d1e62237848769.js?a16074d1e62237848769:131:6199)                                      +
|     at d (https://cloud.sagemath.com/static/lib-a16074d1e62237848769.js?a16074d1e62237848769:131:8765) …
```
> webapp/3d: noKeys deprecated

- src/smc-webapp/editor_latex.coffee
yet another case where codemirror is gone
```
message      | Cannot read property '_smc_inline_errors' of undefined
comment      | 
stacktrace   | TypeError: Cannot read property '_smc_inline_errors' of undefined                                                                                 +
|     at f.exports.LatexEditor.f._render_inline_error (https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:225:29730)+
|     at f._render_inline_error (https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:225:9455)                       +
|     at f.exports.LatexEditor.f.render_error_message (https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:225:31879)+
|     at f.render_error_message …
```
> webapp/latex: fixing "_smc_inline_errors" undefined

- src/smc-webapp/editor_latex.coffee
on firefox, the `@preview_emebd` is disabled, because it triggers PDF downloads.
this patch takes care of that when it isn't defined
stacktrace:
```
stacktrace   | exports.LatexEditor</f.prototype.remove@https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:225:19052                                     +
| b/<@https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:225:9453                                                                          +
| Le/<@https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:28:4963                                                                          +
| exports.register_nonreact_editor/<.remove@https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c …
```
> webapp/latex: on firefox, the embedded preview is disabled

- src/smc-webapp/editor.coffee
stacktrace:
```
stacktrace   | TypeError: Cannot read property 'getCursor' of undefined                                                                           +
|     at https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:29:16675                                 +
|     at l (https://cloud.sagemath.com/static/smc-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:15:4341)                              +
|     at function.e._wrapper.e._wrapper (https://cloud.sagemath.com/static/lib-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:131:3934)+
|     at https://cloud.sagemath.com/static/lib-d3fe692e11c3c55d6e10.js?d3fe692e11c3c55d6e10:131:5448
```
is very vague. I've looked up line 29, column 16675  in the minified source:
```
[...] var t,n;return …
```
> webapp/editor: Cannot read property getCursor of undefined

- src/smc-webapp/misc_page.coffee
- src/smc-webapp/package.json
- src/webapp-lib/latex/latex-log-parser.coffee
see #1567 
test: 
1. create a faulty latex file "with spaces.tex" and check that errors reference that file fine.
2. create a `latex.tex` that references `with space.xyz` inside of it via `\input{"with space.xyz"}`. given "with space.xyz" contains an latex error,  the error message in "latex.tex" shows and references the full "with space.xyz" filename -- and clicking on the button opens the file correctly.
check: "normal" file names still work fine.
> latex error log parsing for files with spaces in their name

- src/smc-webapp/project_page.cjsx
How I tested:
Create a course, require fee, add user to it, go to that user and see course fee warning but not the little warning banner at top
Also create a new project with no upgrades, should see little warning banner
> For #1601: remove little warning banner if course fee required

- src/smc-webapp/app_shared.cjsx
- src/smc-webapp/desktop_app.cjsx
- src/smc-webapp/mobile_app.cjsx
issue #1191
this doesn't do much, but still more than no visual clue at all:
> webapp/notification bell: simple background highlighting when active

- src/smc-webapp/r_account.cjsx
Re: #1597
To reviewer: please check this. I'm unable to delete a test account in smc-in-smc, even before changing any code. But with code change in this PR, the `Confirm Account Deletion` button highlights properly when first name or last name is blank.
> allow for blank first name or last name when deleting account

- src/smc-util/misc.coffee
- src/smc-util/test/misc-test.coffee
see issue #1795 for testing chat and sagews `%md`
> misc/mathjax: fixing off-by-one parser error and adding some tests

- src/smc-webapp/r_misc.cjsx
Tiny thing that has annoyed me.
Also fixes the spinner "wobbling" up and down as much as I could.
> Fix clipping of activity spinner

- src/smc_sagews/smc_sagews/sage_jupyter.py
Ref:#1489
To test manually:
- Apply the patch in this PR.
- In a sagews file, run this code:
```
%octave
z = input("what is z? ","s")
```
A text box should pop up in the cell output. Type in some text and hit Enter or click the checkmark at right of the text.
- The text box will be doubled. This is a known issue not related to octave or the jupyter bridge, #358 
- The value of z is echoed as `z = your_text`. You can verify this with another cell:
```
%octave
z
```
- In another cell, run this code:
```
%octave
pause
3 + 4
```
- You will see a prompt, `Paused, enter any value to continue`. Press enter. Again, input is doubled, then you will see `ans =   100`
> support input() and pause in octave jupyter bridge

- src/smc-webapp/project_files.cjsx
- src/smc-webapp/projects.cjsx
Changes in projects to match project files more closely.
- If you open a project `enter`, clear the project search
- Allow `ctrl + enter` to open a project without switching to it
- Do not clear the project search in the latter case.
Changes in project files to match projects more closely
- `ctrl + click` on a listing when searching should not clear the search.
Also remove some inappropriate usage of redux.getActions
> Clean up some differences between projects and files search behavior

- src/smc-webapp/misc_page.coffee
this deals with issue #1778 
process: capture the special case of absolute URLs, extract the project_id and path, and reconstruct the "raw" URL.
test: you're a collab on projects A and B. Given in project A is a "plot.png" file, reference it from project B via `https:// ... /projects/project_A/file/.../plot.png` in a chat message or a MD file.
time: 20 min
> webapp: fix absolute image URLs *between* two projects

- src/smc-webapp/editor.coffee
- src/smc-webapp/editor_latex.coffee
fixes #1809
test: check that editors and some features like saving/restoring font size still works
process: just following the idea to pull up the `@cms` from the latex editor into the `CodeMirrorEditor` class and using it in the latex editor and various other places.
time: 20 min
> webapp: pull up of latex editor's @cms to CodeMirrorEditor::codemirrors and some cleanup

- src/smc-webapp/editor_latex.coffee
see issue #1814
process: this is a simple defensive solution, the real question is what's going on with `@_get()`
time: 5 min
> webapp/latex: content sometimes undefined

- src/smc-webapp/project_files.cjsx
issue #1812
process: the comment was referring to encoding the whole string, but it's ok to use the already encoded link to the path. simple error in reasoning.
test: create a crazily named file `file with spä¢→al-¢ħæ¶ſ.md` and share it via the file listing. when clicking on email, an encoded url shows up. copy/paste it back into your web-browser to see if it opens up fine.
time: 10 min
> webapp: email share the url encoded link, while not url encoding the whole url

- src/smc-webapp/course/assignments_panel.cjsx
- src/smc-webapp/course/common.cjsx
- src/smc-webapp/course/handouts_panel.cjsx
- src/smc-webapp/course/main.cjsx
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_search.cjsx
- src/smc-webapp/project_settings.cjsx
- src/smc-webapp/project_store.coffee
- src/smc-webapp/projects.cjsx
- src/smc-webapp/r_misc.cjsx
- src/smc-webapp/support.cjsx
Cleans up what I think are the final holes for SearchInput.
- Removes extraneous markup and unifies search inputs fixing various small bugs.
- For example the project search icon now correctly becomes orange when non-empty 
- Opening a directory now clears the search input since in most cases, you are not looking for something with the same name as the directory you searched for.
- Allows `↓` to trigger selection highlighting in project files.
- Improve readability of selected_file_index manipulations.
> Clean up SearchInput and extra markup

- src/smc-util/misc.coffee
- src/smc-util/test/misc-test.coffee
see #1822 
test: with that fix, even monstrosities like the following are rendered properly in a `*.md` file.
```
\begin{CD}
(0,0) @         >1/2>>       (1,0) @>1/3>>           (2,0) @.                  @.                  @.                  @.                 \\
@V 1/2 VV                    @V2/3 VV                @V1 VV              @.                  @.                  @.            @.   \\
(1,1) @         >2/3>>       (2,1) @>1/2>>           (3,1) @.                  @.                  @.                  @.                 \\
@V 1/3 VV                    @V1/2 VV                @V1 VV              @.                  @.                  @.            @.   \\
(2,2) @         > 1 >>       (3,2) @>1/2>>           (4,2) @>1/2>>        (5,2)@>1/3>>        (6,2)@.                  @. …
```
> misc/mathjax: detecting all mathjax environments -- fixes #1822

- src/smc-webapp/buttonbar.coffee
- src/smc-webapp/editor.coffee
- src/smc-webapp/misc_page.coffee
- src/smc_sagews/smc_sagews/sage_salvus.py
issue #1565
This isn't pretty, but it hides the undefined latex buttons. There are also new features like font size, and also striking through text. That in turn needs the `sout` package. Hence my question: @DrXyzzy do you know if the line `...latex.add_package_to_preamble_if_available('soul')` in `smc_sagews/sage_salvus.py` makes sense? It works for my dev project, so I'm quite sure it is at least heading into the right direction.
process: untangling the labyrinth of buttonbar commands, their special cases and fallbacks, reading what CodeMirror's `edit_selection` in misc_page does and adding more code to handle more latex commands.
test: in a sagews, make a `%latex` cell and click all the buttons. bonus feature: in debug mode, `edit_selection` will give a warning if it doesn't know what …
> webapp/sagews: making the %latex buttonbar a bit smarter and some enhancements

- src/smc-webapp/printing.coffee
Updated url per #1845.
Tested by introducing deliberate typo in the MathJax CDN URL and confirming that clicking print button at upper right for a sage worksheet did not produce LaTeX output, fixing the typo and seeing correct LaTeX in the HTML produced by clicking print.
time: 30 minutes
> change url for mathjax CDN #1845

- src/smc_sagews/smc_sagews/sage_server.py
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
see issue #1835
This is one way how how to deal with this. Part of this is to come up with a list of code-strings to test:
* `sage_server?` → docstring
* `x = random?   # bar` → docstring for random
* `x = random?   # plot?` → still docstring for random, not plot
* `x = 1 # plot?` → no docstring, x is 1
* `x="random?" # plot?` → assign x, no docstring for plot
* ```
x = """
salvus?
"""
``` 
x is this multiline string, no help for salvus.
@DrXyzzy apart from the obvious fact that this is in the need for proper test cases, please check if I have missed something. I am also not sure if it doesn't break something else. I.e. note that the `sage_parsing.introspect` do get `b` now, and no longer the `block`. That's necessary, because otherwise it doesn't introspect correctly.
process: …
> sagews: use a lexer to parse codeblocks for stripping comments and "understanding" strings

- src/smc-util/syncstring.coffee
issue #1855 
process: simple fix. if it returns undefined, instead of an exception the string "undefined" will be  shown.
time: 5 min
> util/sync: taking care of @get_doc returning undefined

- src/smc_sagews/smc_sagews/sage_parsing.py
issue #1780
process: key insight was to find out there is an ignored exception, and that it is `'ascii' codec can't decode byte 0xc3 in position 3719: ordinal not in range(128)`
also, line 467 should probably be `args = list(x.args) if x.args else []` (but I have no idea, just looks wrong)
test: `parametric_plot3d?` and similar ones aren't broken.
time: 50 min
> sagews: workaround for code from the pre-utf8 time

- src/smc-webapp/course/main.cjsx
- src/smc-webapp/course/students_panel.cjsx
Addresses #1669.
Works just like first and last name forms. 
- `Tab` to next input works. 
- `Enter` on any field submits the form. 
- `Esc` on any input cancels all changes. 
- The save button is disabled unless changes have been made
Does **not** display the student's prior or actual email.
> Allow course emails to be edited by instructors

- src/smc-webapp/desktop_app.cjsx
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_new.cjsx
- src/smc-webapp/r_misc.cjsx
Fixes #1478, #1237. 
Provides stepping stone to #1238 and #935 by creating an initial wrapper component that directly uses Dropzone.js. It is basically a slightly altered coffeescript rewrite of `react-dropzone-component` that is still used on the +New page.
List of other changes below
- Dragging non-files (like icon links) across the page now does nothing instead of giving the user an error.
- Dragging a file onto a non-drop-enabled area now says "File Rejected" instead of "File Drop Disabled"
- Dragging a file onto the files area now works automatically without having to hit some specific dropzone that gets rendered.
- Also works on a directory with no files.
- Clicking Upload on the Files page now opens a file upload dialogue.
- Upload status on the Files page is now only as big as it …
> Fix file drop notification

- src/smc_sagews/setup.py
- src/smc_sagews/smc_sagews/sage_server.py
This fixes https://github.com/sagemathinc/smc/pull/1849 by using `ushlex`.
I made https://github.com/sagemathinc/smc/issues/1859 without really knowing how to actually test this. In particular I'm wondering if there are any utf8 strings in that test suite.
> sagews: fixing shlex by using ushlex

- src/smc-webapp/project_page.cjsx
- src/smc-webapp/projects_nav.cjsx
Fixes case for #1738 for which I could reproduce.
Reproduce case: Drag on the space near a file or project tab and you get the error. 
Fix: Dragging on that space no longer triggers react-sortable.
> Only sort tabs when dragging a sortable item

- src/smc_sagews/smc_sagews/tests/test_sagews.py
ref: #1859 
No changes to production code.
Adds 4 tests, class TestUnicode.
To test, check out the patch and do (assuming your smc repo is at ~/smc):
```
python -m pytest test_sagews.py::TestUnicode
```
Note: Other tests in src/smc_sagews/smc_sagews/tests are broken. Out of scope for this PR.
> add TestUnicode and skip TestLex

- src/smc-webapp/project_files.cjsx
see issue #1885
with that change it looks ok for me in chrome, someone should give safari a try, too.
also, I've no idea what did trigger this, hence that's just a patch to fix this in a sane way without knowing a deeper cause. maybe it just waited to be triggered ...
> webapp/files/create new file dropdown: instead of hardcoding a width, tell it to not do any linebreaks

- src/smc-webapp/project_store.coffee
Ref: #1908.
Tested in smc-in-smc.
> check name, not full path, for invalid chars in latex file name

- src/smc-webapp/video-chat.cjsx
see #1899
test: (i.e. what I checked in chrome and firefox) open video chat, indicator is "1", close the window, ~1 sec later the indicator is "0".
process: testing some approaches, in the end http://stackoverflow.com/questions/3291712/is-it-possible-to-open-a-popup-with-javascript-and-then-detect-when-the-user-clo was most helpful.
time: 25 min
> webapp/video-chat: workaround for #1899

- src/smc-webapp/jupyter/_jupyter.sass
e.g. `data.frame(list(x=c(1,2,4), y = c(9,8,2)))`
> jupyter2: tablewidth auto, otherwise it looks ridiculous for some R dataframes

- src/smc-webapp/last.coffee
this sets the output to common html (which is the suggested default and where they're focusing their efforts) and enables rendering of unknown macros or broken formulas in red (better than showing a dumb generic error)
process: reading docs, some iterations to make the style look nice, tested in chrome and firefox in .md and jupyter
time: 20 min
> webapp: be graceful with mathjax errors

- src/smc-webapp/course/assignments_panel.cjsx
- src/smc-webapp/course/course_funcs.coffee
- src/smc-webapp/course/main.cjsx
- src/smc-webapp/course/students_panel.cjsx
Takes whatever sort order the student listing is in and applies it to the list of students for an assignment.
Sort of fixes #1635?
Also sets Due Date as default sorting for Assignments.
**Last Name**
**Email**
- Toggle open an assignment, change the student sort, then going back to the assignment should result in the new sort order displayed
- Due Date should be the default sort.
> Mirror student list sort inside assignments

- src/smc-webapp/r_misc.cjsx
Ref: #1939 
This simple change appears to fix the reported bug, but please review because
1. Other parts of SMC than clicking on log entries might use the code that is changed and depend on relative paths only.
1. There is one thing that is hard to test in smc-in-smc. If you have a file at an absolute path open in the browser and click refresh, smc-in-smc will try to open a file at the corresponding relative path, but it's not clear that regular smc will have the same problem.
More info on the second item. I think it relates to this line in salvus.coffee: https://github.com/sagemathinc/smc/blob/master/src/smc-webapp/salvus_client.coffee#L33
because:
1. Open an absolute path, e.g. `open /projects/sage/sage/README.md`
1. Copy the link from the browser location bar, e.g. …
> allow absolute paths when clicking on log link

- src/smc_sagews/smc_sagews/sage_server.py
See #1948 
Verified that pytests for %attach still work.
> move annoying attach/reload message from cell output to log

- src/smc_pyutil/smc_pyutil/smc_compute.py
ref: #1941 
Tested by creating a directory with bad file names, checking that directory contents did not list correctly with smc_compute.py's `Project().directory_listing()`, then changing code and getting a correct list (with only the JSON-able filenames). Test code is in this (non-public) notebook: 
https://cocalc.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/TEST_SAGEWS/issue-1941.ipynb
> issue #1941 skip non-jsonable file names

- src/smc-webapp/project_store.coffee
Simple fix for #1641.
Within 5 seconds, it will re-adjust your tabs unless you close the current tab.
> Add clearing ghost tabs on timeout

- src/smc-webapp/init_app.coffee
Fixes #1729 
When a student switches to a course project, automatically tries to add members hosting and network access.
> Automatically add default upgrades when required by course

- src/smc-webapp/video-chat.cjsx
Notice how the file tab floats above the editor.
Shrinking the video button a little bit fixes this.
> Fix vertical spacing when chat is open

- src/smc-util/message.coffee
This introduces a version 2 as `message2`.
The way I tested this is minimal, in `coffee`:
```
coffee> m = require('./message')
coffee> m.query(query: "test")
{ query: 'test', multi_response: false, event: 'query' }
coffee> m.documentation
{ query:
{ description: 'This queries directly the database (sort of Facebook\'s GraphQL)',
fields:
{ id: 'A unique UUID for the query',
query: 'The actual query (required)',
changes: '',
multi_response: ' (default: false)',
options: '' } } }
coffee> m.examples
{ query: [ [ [Object], [Object] ], [ [Object], [Object] ] ] }
```
> documentation and examples for message protocol as data

- src/smc-webapp/editor_latex.coffee
Ref: #2001 
To test
1. install the PR
1. create a new .tex file and wait for preview to appear in right pane.
1. before doing any edits, click "zoom out a little". Preview should shrink to show black margins at sides
1. save and reload the .tex file and confirm preview size is remembered
1. create another new .tex file and confirm that "zoom in a little" works as expected before any edits are done
> zoom width for preview was uninitialized in latex editor #2001

- src/webapp-lib/cocalc-icons-font/style.css
- src/webpack.config.coffee
For some reasons, webpack did create small one-line wrapper scripts disguised as font files. Of course, that's not going to work out well, if the content type of e.g. a *.ttf file is binary but contains a small js script. 
This here changes the configuration and well, the most important aspect is to test it. I.e. when webpack-production compiles, that there are no errors about unknown file types (that happens, when e.g. the regex `\.ttf(\?[a-z0-9\.-=]+)?$` doesn't match and it falls back to a default). The second aspect to test is that when the page loads the newer font-icons for the symbols show up. (right at the moment when I wrote this, https://test.cocalc.com/ works with that newer config)
> font files and webpack

- src/smc-hub/test/api/account.coffee
Adds 1 API test file only for get_usernames and create_account.
> mocha tests for API get_usernames and create_account

- src/smc-hub/hub_http_server.coffee
- src/smc-hub/postgres-base.coffee
- src/smc-hub/postgres-server-queries.coffee
- src/smc-hub/test/get_stats.coffee
- src/smc-util/db-schema.coffee
- src/webapp-lib/index.coffee
This adds some stats about files on the landing page. Most importantly, it requires a schema update!
There is also some compactification of the code for those stats tasks in the hub; and in case the query looks scary, it isn't so bad as it looks.
Test:
* calling `/stats` should still contain the old entries and of course, doesn't cause exceptions in the hub.
* The landing page should shows more data in the stats table.
> Hub stats opened files

- src/smc-hub/test/api/account.coffee
- src/smc-hub/test/api/messages.coffee
- src/smc-util/message.coffee
Ref: #1987 
This PR includes src/smc-hub/test/api/messsages.coffee, a file which has been useful when defining message docs. I'm not sure the team will want it in the src tree, though.
Mainly, this PR adds 'API message2' docs for more events.
> add API message docs

- src/smc-hub/hub_http_server.coffee
- src/smc-webapp/init_app.coffee
- src/smc-webapp/misc_page.coffee
- src/smc-webapp/webapp_client.coffee
Ref #2028 -- this introduces a query parameter `?fullscreen` to toggle it on.
process: mainly finding my way around how various redirects work and how `smc_target` is used, etc.
test and edge cases:
* `/app?fullscreen`
* `/projects/ ... /files/dir/name.ipynb?fullscreen` → opens up that ipynb file in fullscreen (and does not stupidly add the `?...` part to the filename)
* all normal paths still work, i.e. `/projects`, `/`, `/projects/.../files/...`, etc. (e.g. that when opening a file, `*.ipynb` isn't mangled into `*.ipyn` or so)
deployment: don't miss that it also touches the hub
time: 1 hour 10 min
> fullscreen query parameter

- src/smc-webapp/course/assignments_panel.cjsx
- src/smc-webapp/course/delete_students.cjsx
- src/smc-webapp/course/help_box.cjsx
- src/smc-webapp/course/main.cjsx
- src/smc-webapp/course/settings_panel.cjsx
- src/smc-webapp/course/students_panel.cjsx
- src/smc-webapp/course/styles.coffee
**Before**
**After**
**Before**
**After**
- Also refactors part of the settings panel.
- Delete all student projects works
> Fix some visual edge cases in courses

- src/smc-hub/test/api/advanced.coffee
- src/smc-util/message.coffee
Ref: #1987 #1988 #2057 
Document `project_exec`, remove `save_project` and `email_address_availability` API messages, other minor edits.
Adds file `src/smc-hub/test/api/advanced.coffee` which will accumulate most of the remaining API tests.
test run of `~/cocalc/src/smc-hub$ mocha test/api/`: 61 passing (16s)
> API doc & test 'project_exec' and other fixes

- src/smc-webapp/billing.cjsx
- src/smc-webapp/course/help_box.cjsx
- src/smc-webapp/landing_page.cjsx
- src/smc-webapp/r_help.cjsx
- src/webapp-lib/index.pug
pointing to https://tutorial.cocalc.com/ now
this is some bulk editing to get to the correct landing page. we should fine adjust where to point once the fate of the tutorial is clear and we know the names of relevant individual pages.
> consolidating links to the "croucher smc tutorial"

- src/smc-webapp/course/assignments_panel.cjsx
- src/smc-webapp/entry-point.coffee
- src/smc-webapp/r_misc.cjsx
- src/smc-webapp/smc-react.coffee
- src/smc-webapp/widget-markdown-input/actions.coffee
- src/smc-webapp/widget-markdown-input/info.coffee
- src/smc-webapp/widget-markdown-input/main.cjsx
- src/smc-webapp/widget-markdown-input/store.coffee
- Fixes #1546.
- Moves save/cancel buttons to the bottom of the markdown input
- Allows MarkdownInputs to be "attached" to stores instead of having to write the saving code in stores/actions for every possible location. 
TODO:
- Toggle edit mode, change the value, hit cancel, then hit edit. The edit value should be what the display value was.
- Toggle edit mode, navigate away, come back, editing should remain.
- Toggle edit mode, change the value, close the file, reopen the file, edit state should be lost
- Open multiple MarkdownInputs, each one should maintain their state independently of each other.
> Persist Markdown Inputs

- src/smc-webapp/public/editor_md.cjsx
See #2077 
Hard to test public view of a project from cc-in-cc due to cookies (needed to access the project, but don't want for public view). I tested the change using live update of html using browser tools page editor (Inspect with Chrome and Firefox).
Before the change:
After:
> add left and right margins for public view of .md files

- src/smc-webapp/project_store.coffee
- src/smc-webapp/smc-react.coffee
Stores should clean up after themselves
Neither needs to know they are within a `ReduxApp`
Actions should not have any state or listeners to destroy
- Search codebase for any relevant uses of `destroy` that I may have missed
- Confirm that MarkdownInputs still work.
> Clean up smc-react Stores/Actions abstraction a little

- src/smc-webapp/editor_latex.coffee
see #1313 for some history on that. besides the screenshot, I also checked that it updates when I change some input. yes, it does refresh as expected...
> webapp: re-enable firefox embedded pdf viewer

- src/smc-hub/test/api/account.coffee
- src/smc-util/message.coffee
Ref: #1987 #1988 
Doc & mocha test for
- invite_collaborator
- invite_noncloud_collaborators
- remove_collaborator
Test for `invite_noncloud_collaborators` is skipped in `account.coffee` for now due to callback issue. To be fixed in a later PR.
Result of test run on api:
```
~/smc/src/smc-hub$ mocha test/api
...
76 passing (16s)
1 pending
```
> Issue/1987f API collaborator message doc

- src/smc-webapp/editor.coffee
- src/smc-webapp/editor_latex.coffee
issue #1621
test: latex editor with many png preview pages and switching tabs works as advertised
process: I was on the wrong track for quite some time, because I thought some reactification-related resets happen, then I tried to figure out how sagews files keep their position, etc. in the end, it turns out the dom elements are there, but only invisible and all I had to figure out is when exactly to record and when to restore the position. The whole reason why it scrolls up seems to be related to making elements invisible. Then, they have a scroll height (or overall height) of zero and that's why showing them again restores them at the top position.
time: 1 hour
> webapp/latex: restore png pdf preview scroll location when switching tabs

- src/smc-webapp/editor.coffee
- src/webpack.config.coffee
I tested this with webpack-production and I don't see any issues. Still, there are two additional points in the code where require.ensure is added. So, this warrants for some caution.
With that configuration, I see two chunks now:
```
1.1M Jun 15 13:16 static/0-172927f1c2224e5fb061.cacheme.js
49K Jun 15 13:16 static/1-172927f1c2224e5fb061.cacheme.js
```
That's not much, but once we have a better refactored code base, this could pay off much more. E.g. right now when reloading, chunk "1" is loaded initially anyways, and I think "0" when I opened a sagews.
> webpack: allowing for more chunks, and two points where it is introduced in the webapp code

- src/smc-webapp/project_files.cjsx
ProjectsStore::get_total_project_quotas could return undefined and `not quotas?` is hence true, even if `member_host` isn't even known.
see issue #1226, this is a second attempt
> webapp/projects: do not show payment info if quotas are not even known

- src/smc-util/misc.coffee
- src/smc-util/test/misc-test.coffee
- src/smc-webapp/process-links.coffee
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_store.coffee
- src/smc-webapp/side_chat.cjsx
- src/smc-webapp/test-client/project.coffee
Fixes a portion of #2103 
Also fixes `setState(...)` warnings of Side chat
Things with chats should have their chats be moved/renamed with them
Be aware of #2119.
Do each of the following with with hidden files and visible files
Do each of the following with files in the home directory and a subdirectory
Do the same from a subfolder to the home folder
1. Test moving 1 file without a chat into subfolder
2. Test moving 2 files without chats into a subfolder
3. Test moving 1 file with a chat into a subfolder
4. Test moving 2 files with chats in to a subfolder
5. Test moving 2 files into a subfolder where one has a chat and the other does not.
6. Test renaming a file without a chat
7. Test renaming a file that has a chat
Additionally, trying to copy associated chat files with their files …
> Rename/move Side Chat files with the source files.

- src/smc-webapp/account.coffee
- src/smc-webapp/project_store.coffee
- src/smc-webapp/redux_account.coffee
see issue #2150
This still contains debug lines, so please someone has to clean this up a bit afterwards. I've also no idea if my contraption is any good, or if there is a much better fix. I also didn't catch how and where the problem was actually introduced.
Open question: why is `redux_account.coffee`  opening up the projects list? this could interfere with other callbacks reacting to "sigend_in". I've commented the line, maybe erroneously ...
> webapp: attempted fix for target paths not opening files properly

- src/smc-webapp/copy-paste-buffer.coffee
adding this line here, because it's quite odd to me to not write to the clipboard
> webapp: let copy operation write to clipboard (if allowed)

- src/smc-hub/hub.coffee
- src/smc-hub/hub_http_server.coffee
- src/smc-hub/postgres-server-queries.coffee
Since our hubs started to run longer and are more stable, we have this problem of outdated stats (or, when dispatched randomly across hubs, significant jitter). Root cause is the very long ttl time, which causes a hub to think its local data is still valid although it's not. 
The changes I made address a couple of things:
1. what if there is no data? don't do anything, but give a warning
2. when  a hub is explicitly being told to not update, always live with the best known information
3. related to that, even when that information is outdated, do not query the DB each time a hub is being asked (e.g. consider the case where the cronjob task is no longer updating). that's the reason for a 30 secs db query ttl.
4. The TTL time is now set to 5 minutes (it was 2 minutes). I think that's good …
> hub: fixing problems with updating stats based on ttl and also being explicit about disabling calculating them

- src/scripts/mocha_clean.sh
Ref: #2162
sample use:
```
~/cocalc/src/smc-hub$ mocha test/api
...
90 passing (35s)
1 pending
~/cocalc/src/smc-hub$ mocha_clean.sh
process count 28 -> 8
memory use 966MB -> 393MB
```
> add mocha_clean.sh for after mocha api run

- src/smc-hub/package.json
- src/smc-hub/postgres-server-queries.coffee
- src/smc-hub/test/postgres/postgres-user-queries-changefeeds-2.coffee
also: calling mocha_clean.sh after each test invocation.
issue #2173
> hub/tests: being explicit about not using cached results in testing stats changefeeds

- src/smc-hub/test/api/messages.coffee
- src/smc-util/message.coffee
Ref: #1987.
Added mocha tests for message2 formatting only. No tests were added that go through the database.
> API doc: create and get support tickets

- src/smc-webapp/smc-dropzone.cjsx
- src/smc-webapp/smc_chat.cjsx
First version of dragging items onto the chat text area.
Images will embed as `<img ...>` tags with width='60%'. This can be made smarter later.
Files will embed as `[file_name.ext](file_name.ext)`, making a link which opens as a new file tab.
Text is inserted where the cursor is at the time of dropping. 
If you have highlighted text, it will replace that text.
Items get uploaded to the current directory of the `project_store`. Right now this is always the directory of the open file (in this case, chat).
**Not** implemented for side chats yet.
Needs testing on more platforms
> Drag n drop chat images

- src/smc_sagews/smc_sagews/sage_server.py
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_00_timing.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Ref: #2236.
These changes, plus @hsy fix hiding sage binary for python3 so that sage_server uses /usr/bin/python3, allow sage worksheets to run with sage-8.0.
```
~/cocalc/src/smc_sagews/smc_sagews/tests
python -m pytest
...
== 137 passed, 5 skipped in 195.90 seconds ==
...
== 137 passed, 5 skipped in 207.19 seconds ==
== 137 passed, 5 skipped in 210.55 seconds ==
```
> Issue/2236 sage_server with sage-8.0

- src/smc_sagews/smc_sagews/sage_salvus.py
Ref: #2240.
To test:
1. Install the patch (1 file changed, sage_salvus.py).
1. Try any 3d plot with `frame=False` and notice that a frame is not drawn, for example:
```
sphere(frame=False)
line3d([(0,0,0),(1,1,1)],frame=False)
```
1. Try other options that were ignored before this fix:
```
icosahedron(frame={'color':'darkgreen','fontsize':20,'thickness':5})
cube(viewer='tachyon')
```
> process frame and other extra kwds in threed()

- src/smc-webapp/app_shared.cjsx
- src/smc-webapp/chat-indicator.cjsx
- src/smc-webapp/desktop_app.cjsx
- src/smc-webapp/init_app.coffee
- src/smc-webapp/mobile_app.cjsx
- src/smc-webapp/project_page.cjsx
see issue #2234
Test: kiosk-mode is triggered in two ways
* append `?fullscreen=kiosk` to the URL
* shift-click on fullscreen
* no regressions: i.e. appending `?fullscreen` still shows the toggle button
> webapp: introduce ?fullscreen=kiosk mode, as a no-way-back to normal fullscreen state

- src/smc-webapp/project_new.cjsx
this is trivial bug bugs me for weeks. new file button in project/new for markdown and switching from excel to latex for the tex icon.
> webapp: markdown button in project/new and changing tex file icon to the one for latex (instead of excel?)

- src/smc-webapp/project_files.cjsx
Hi @johnjeng ... thank you for reviewing the last one, but your little change reverted a problem I'm usually seeing in my files listing. The upload button wraps into the next line, hence the nowrap style.
This fix reverts it, and to show you what I mean, here are before/after screenshots:
vs.
> webapp: fix newline wrapping of upload button in files listing

- src/smc-webapp/session.coffee
there is another detail I just saw while testing: the local session info is shared with the main site and hence there are interferences when doing cc-in-cc dev. this patch prefixes they key with the app base url. it doesn't change the already existing key.
> webapp: prefix local session with app base url

- src/smc-webapp/process-links.coffee
- src/smc-webapp/projects.cjsx
This is a small detail for queries like session=local in the URL. When someone copies that link into a file for internal linking, the `?session=local` part should be ignored. 
Test: external links should still work as they are. Example, create a test.md file:
```
open [new.ipynb](new.ipynb?session=local)
open [external](https://www.google.at/search?q=cocalc)
```
There is still a design question open, namely if this logic should be in the `ProjectsActions::load_target` function instead.
> webapp: ignore query strings like "?session=local" in internal links

- src/smc-webapp/project_files.cjsx
here is another approach to clean this up. related to #2266 and the button objections ...
unfortunately, the more I look at this, the more problems I see. Regarding this patch, I've tested it in chrome and firefox, at different window sizes and with and without zoom (also, using myself as a second user to see the active-heads area). It's mostly ok, and #2266 didn't happen for me, but I think we have to redo this using flexbox css and rethink this a bit.
> webapp: files action button row, switching path to breadcrumb and some fine tuning

- src/smc-webapp/project_page.cjsx
- src/smc-webapp/project_settings.cjsx
Shows up when disk space used is within 5mb of the quota limit.
- No `x` to remove the warning. Delete files, increase quota, or suffer the warning.
- Disappears automatically when quota is adjusted
I tested on smc-in-smc by using admin edit to reduce a project quota to under 5mb since "usage" is always undefined/zero.
> Space warning

- src/smc-webapp/_projects.sass
- src/smc-webapp/project_files.cjsx
I got angry with that stupid line break.
process: less is more (getting rid of a div) for more control and the wrapping itself can only be dealt with dynamically reassigning flex layout to the element. I think under the hood some element-juggling-magic happens ... 
also, removing an erroneously set bsSize argument.
tested in Chrome and FF, no impact on the other parts of this horizontal row.
> webapp/files: no newline wrap for create-dropdown button when narrow

- src/smc-project/sage_session.coffee
SAGE_SERVER_MAX_STARTUP_TIME_S from 30 → 60
Tested by adding 35 sec delay to `src/smc_sagews/smc_sagews/sage_server.py:run_server()` and verifying that worksheet startup timed out before the change and did not timeout after the change.
> longer sage_server startup timeout for kucalc & sage-8.0

- src/smc-project/local_hub.coffee
- src/smc-project/package.json
This is part of the Kucalc efforts. The project's local hub kills itself if it can access information that's supposed to be firewalled (server is the same as DNS, etc.)
> project: optional deadman switch if internal GCE network is accessible

- src/smc-webapp/r_upgrades.cjsx
Implements #2289
How many students before this becomes unusable? ~100 projects takes a few seconds.
Note that this 100 is the number of projects you've upgraded, not total number you're on.
> Remove all upgrades from all projects

- src/smc-webapp/project_settings.cjsx
Tell user who is about to add an ssh key for a project that it's possible to add key for all projects using account settings.
> project ssh key note about account key

- src/smc-webapp/course/actions.coffee
see #1547
test: assign handouts and immediately refresh the site. that causes you to show these stale distribute buttons. with that patch, clicking on cancel at least let's you to get out of this stuck state. (in the future we can figure out how to properly sync this, but that's out of the scope here)
process: at some point, `status_map` must have been renamed to `status`. that causes the code to exit the function because the status is always undefined.
time: 30 min
> webapp/course: a rename of status_map to status seems to be the culprit for 1547

- src/smc-util/message.coffee
fix typo in api doc for query to set project upgrades, reported by minerva
> add missing quote in docs

- src/smc-hub/package.json
- src/smc-hub/support.coffee
- src/smc-hub/test/misc/support.coffee
(this ticket also enabled hub/misc tests!)
This is mainly to help us with support, and I gave it a brief dry run and added some tests (4 postgres tests fail for me, though, so that's why `npm run testmisc` is all there is for this)
> support: replace or add ?session=support to the support requests or included URLs in the body

- src/smc_pyutil/smc_pyutil/smc_compute.py
Please review. I am have confirmed that this 1-character change fixes the problem in #2348, e.g.
```
~/cocalc/src/smc-hub$ mocha --opts test/mocha.opts test/api/text_files.coffee
==>
12 passing (6s)
```
If I understand the change to `nargs` correctly, it _should_ be benign for other cases, e.g. kucalc testing, but it should be reviewed.
> change nargs for `public_get_text_file` mocha test

- src/smc-webapp/jupyter/actions.coffee
- src/smc-webapp/jupyter/parsing.coffee
se issue #2233
process: the main feature of prolog is to answer questions about some believes. in calisto, these questions end with a questionmark. this jupyter implementation triggers introspection when the code line ends with a questionmark regardless of which programming language we deal with ... that's not going to work. (https://github.com/Calysto/calysto_prolog)
test:
* `has(a, b).`
* `has(a, b)?` → true
> jupyter2: special case regarding processing ?/?? help for the language "prolog"

- src/smc-util/misc.coffee
- src/smc-webapp/project_new.cjsx
- src/smc-webapp/project_store.coffee
Fixes #2322. 
Shows no warning since the text already offers URLs as a valid option to enter. You hit enter or create and you'll be redirected to the project files page and a `downloading [url]...` notification in the upper right.
> Don't show extension warning for urls in new file

- src/smc-hub/postgres-server-queries.coffee
Ref: #2370.
All api mocha tests pass with this change. There is something odd, though. Please see second item.
1. The change at line 1564, `listing.files = []`, looks ok to me, but...
1. After adding the above change, but without the change at line 1563, another test fails that should pass. If the public path requested exists and contains a file, the value of listing just before line 1563 is (correctly) displayed by console.log as
```
{"files":[{"size":11,"name":"doc1.txt","mtime":1505195811}]}
```
but the test for `if not misc.is_array(listing?.files?)` succeeds, causing the API call to return an empty files list. This problem is eliminated by the change to line 1563, `if not listing?.files?[0]?`.
> fix for empty files list

- src/smc-webapp/latex/document.coffee
this is the idea for #2379 I had some time ago to avoid this.
test: open same tex file in two tabs, next to each other, and you'll should able to trigger timeout errors. edit the latex compile command by adding `sleep 5; <latex command>; sleep 5` to slow it down!
process: to understand what's going on, run this line in two terminals at the same time: `(flock -E 99 -x -o -w 5 9 || exit 1; echo "a"; sleep 10; echo "c") 9> l1` and check the exit code via `echo $?`.
> webapp/latex: exclusive lock to avoid concurrent latex operations

- src/webapp-lib/_base.pug
- src/webapp-lib/index.pug
this replaces the static image with the mark quinn intro video. Adds credits and dynamically scales. This scaling should be tested in browsers. (I'll do it later, still setting it to review ... we should only merge if we're sure the landing page isn't too distorted by that in a common browser)
> landing page: embed mark quinn video with dynamic sizing

- src/smc-hub/package.json
- src/smc-hub/test/mocha.opts
Ref #2415.
Note: most tests in src/smc-hub/test/api hang after the tests pass. That is a separate issue independent of #2415
> eliminate deprecation for mocha test on compiler option

- src/smc-webapp/desktop_app.cjsx
this is quick idea how to make it clear that this is for the account settings, while keeping the ui personalized.
> webapp/top bar: show avatar and account instead of name

- src/smc-webapp/project_page.cjsx
- src/smc-webapp/project_settings.cjsx
- src/smc-webapp/project_store.coffee
- src/smc-webapp/projects.cjsx
- src/smc-webapp/r_misc.cjsx
The purpose of this is to make "free users" aware of the current load and the impact on running any calculations. It shows an estimate about how much longer a computation takes compared to having no elevated load or cpu core limits.
The problem is, I'm sure what I coded is at the wrong spot and can be done much better. I think what I wrote is at least safe to do.
I've assigned j3 because I think he knows exactly how to properly trigger this upon project startup.
> webapp/project: calculate a "slowdown" estimate depending on quotas.core and normalized load 5

- src/smc-hub/stripe/connect.coffee
Based on my testing of our Stripe calls, this [changelog](https://stripe.com/docs/upgrades?since=2015-07-07#api-changelog), and their api [docs](https://stripe.com/docs/api).
How to tell the new version is running? The way I did it was using `subscriptions.list`
>You can now view canceled subscriptions by specifying status=canceled or status=all when listing subscriptions. In addition, you can now retrieve a canceled subscription by its ID
> Update client stripe version

- src/smc-hub/share/listing.coffee
- src/smc-hub/share/raw.coffee
rather trivial, i.e. in my cc-in-cc 
`https://cocalc.com/UUID/port/56754/raw/UUID` → `https://cocalc.com/UUID/port/56754/raw/UUID/`
and I can see a directory listing there. I also added a filter for hidden files ... I understand they will not show up in production, but in general I think this is a good precaution to exclude them from any listings.
> hub/raw server: redirect directories, filter hidden files

- src/smc-webapp/jupyter/actions.coffee
issue #2495
* I haven't tested this at all
* I'm not sure what the general meaning is, i.e. it tests if there is output and if not that `exec_count` of the cell is defined? or > 0 ?
> webapp/jupyter2: cell is clearly not defined, this should fix it

- src/smc_sagews/smc_sagews/sage_server.py
- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_unicode.py
- 5(1+2) generates TypeError, not SyntaxError; do you want to catch these?
- another case added to end of pytest test_unicode.py
- unrelated, but found during testing: increase sagews pytest timeout because of slow scala launch
> Sagews warn quotes

- src/smc-webapp/init_app.coffee
- src/smc-webapp/project_store.coffee
- src/smc-webapp/smc-react.coffee
Addresses #2518
Warns you if you're accessing state that isn't declared or if you're setting state that isn't declared.
Let's you use it anyways. 
Inside project actions or page actions, call `@setState` with a property not defined in stateTypes.
Use that property in a component with reduxProps. See both warnings and that passing down the prop still works.
> Fix state types

- src/smc-hub/share/mathjax-support.coffee
- src/smc-util/mathjax-config.coffee
- src/smc-webapp/last.coffee
- src/smc-webapp/printing.coffee
This reuses the existing webapp mathjax configuration for the static renderer in shared.Not all settings can be used, though ,and well, no idea how to fix all the remaining erroneous attempts to render a formula in the codemirror boxes.
screenshot for the QQbar macro:
> webapp and hub/share: same config for macros, etc.

- src/smc-util/db-schema.coffee
- src/smc-webapp/r_account.cjsx
- src/smc-webapp/r_misc.cjsx
- src/smc-webapp/share/public-paths-browser.cjsx
This bugged me for a while, too.
However, I'm wondering if there is a better way than this redux-double-wrapping of the element?
> webapp: switch TimeAgo to alternatively show absolute times

- src/smc-webapp/r_help.cjsx
- src/smc-webapp/redux_server_stats.coffee
I'm not even sure what I'm doing here. This is an ugly proof of concept for loading the "stats" data from the dedicated /stats http-endpoint.
> webapp: load stats from the /stats endpoint

- src/s
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/r_misc.cjsx
- Removes `Share` button from listing entries
- Improves sharing workflow
- Rename `Close` to `Cancel` for consistency
- Rename `Stop sharing item publicly` to `Make item private`
Only see the link after sharing. 
List of items is less important at this point (esp since you can't share more than one item yet).
> Sharing improvements

- src/smc_sagews/smc_sagews/sage_server.py
> sagews: ignore string literals for implicit multiplication

- src/smc-util/package.json
- src/smc-util/test/misc-test.coffee
Fixes #2577
`new Error("test")` stringifies to `{}`??? I tested it in my browser.
Changed the test to use a string. Should probably change the logging behavior?
Ensure NODE_ENV is set to something other than 'production' when running tests.
> Fix util test issues

- src/smc-hub/share/render-public-path.cjsx
- src/smc-webapp/share/page.cjsx
- src/smc-webapp/share/public-path.cjsx
- src/smc-webapp/share/public-paths-browser.cjsx
>[ws] A concern I just had. All editors in normal Cocalc assume they are in a fixed height div with flex column layout. That's basically why the share server is that way -- so they can keep that assumpion. Just a thought.
I think this is mostly for scroll position reasons. But on the share server, the whole page scrolls. Anyways, for the implemented editors so far it doesn't seem to be an issue.
> Simplify share rendering

- src/smc-webapp/misc_page.coffee
- src/smc-webapp/project/plain-jupyter-server.cjsx
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/support.cjsx
- src/smc-webapp/video-chat.cjsx
- src/smc-webapp/widgets-misc/link-retry.cjsx
this is a fix for #2599
background: for example, my chrome browser blocks all javascript actions that attempt to open a new tab by default. I have whitelist some pages like cocalc to be allowed to do this, but new users don't have cocalc whitelisted. the result is, that the `window.open` function returns `undefined` or something like that.
this patch takes care of #2599 and also wraps other instances of `window.open` with that function. I've also modified the popup=true case to match  with the config of the video chat. 
test: popup blocking is again active in a private browsing session of my chrome browser. then, these red information bubbles appear and show a link.
> webapp: sanitize all window.open commands against popup blockers

- src/smc-webapp/latex/document.coffee
reason: the pdf file could be huge and this eats up /tmp (memory) quickly
test: 
* PDF previews work
*  there shouldn't be any PDFs in `ls -l /tmp/latex-preview/*` (maybe briefly, but that's all)
> webapp/latex: immediately remove temporary pdf after creating preview images

- src/smc-hub/client.coffee
- src/smc-util/upgrade-spec.coffee
- src/smc-util/upgrades.coffee
- src/smc-webapp/billing.cjsx
- src/smc-webapp/course/settings_panel.cjsx
- src/smc-webapp/redux_account.coffee
- src/smc-webapp/support.cjsx
UI Changes:
- Change the course plan names to Basic/Standard
- Add a section `Basic or Standard?` in the plan explanation section
- List the Standard plan on the first row instead of the second
Bug Fixes:
- Change grammar of the confirmation to say "lasts a year" instead "lasts year"
- Fix highlighting bug where an annual course subscription panel would not highlight upon selection.
Misc:
- Change code to use `subscription` instead of `membership`
> Change course subscription names

- src/smc-webapp/account_page.cjsx
- src/smc-webapp/billing.cjsx
This might make it look in some way awkward, but well, in the end, courses are not really subscriptions. I think this makes it easier to find where to actually purchase these course packages.
and well, the general reason for this is that I saw at least two recent support requests, where I sensed some sort of confusion about where to buy what.
> webapp: explicitly adding "course package" to all payment related mentions of subscriptions

- src/smc-webapp/project_log.cjsx
- src/smc-webapp/projects.cjsx
this isn't finished, but could still be merged right now. it only logs the *requests* to stop/restart a project. more work needs to be done to then actually log the "stop" by the backend. the only tiny complication is that the backend has no `account_id`. hence, the front-end part needs to deal with that, too.
> webapp: log project stop/restart requests by a user

- src/smc-hub/package.json
- src/smc-hub/test/README.md
- src/smc-project/jupyter/test/supported-kernels.coffee
- src/smc-project/package.json
- src/smc-util-node/package.json
- src/smc-util/package.json
- src/smc-webapp/package.json
- src/smc-webapp/smc-react.coffee
- export `_internals` from src/smc-webapp/smc-react.coffee for use by smc-react-test.coffee
- increase timeouts in src/smc-project/jupyter/test/supported-kernels.coffee for slow-starting kernels (some of these run much faster on second test run immediately after first test)
- modify package.json for easier debugging
- following precedent in smc-hub, split multi-directory tests in smc-project and smc-webapp
- more use of --reporter ${REPORTER:-progress}
- add ${BAIL} to a couple tests; allow `BAIL=-b npm run testapi` etc
> mocha mods

- src/smc-webapp/latex/document.coffee
- src/smc-webapp/latex/editor.coffee
- src/smc-webapp/latex/png_preview.coffee
see issue #2534, this did bug me again and again when testing in the past few days.
In the end, all this does is delay the update rendering by 1 second after the syncdoc says that it is connected. I suspect this bug started when opening files was speeded up. I am also aware that this is not a perfect fix, but let's postpone this after a rewrite...
Testing: I checked with a normal document and upon Rnw documents.
Here is a document with a couple of pages for testing. The way to reproduce the problem in prod is to open it, wait until compiled, close the tab, wait a few secs, then open the tab again. The .tex file is saved while closed and there is no need to re-render it when opening. And without that additional rendering, it is somehow not properly initialized. That's why it's a …
> webapp/latex: timing issue when opening a tex file that does not need to be compiled again

- src/smc-hub/test/api/messages.coffee
- src/smc-util/message.coffee
See: #2672
- update api.html for get_available_upgrades
- add syntax check for get_available_upgrades message2 def
I didn't add a mocha test for get_available_upgrades at this time because I didn't want to get into mocking the stripe interface.
> api doc for get_available_upgrades

- src/smc-util/message.coffee
use `APi message[2]` for api endpoints, omit `API` for internal messages
> available_upgrades is api response, not a query

- src/smc-webapp/course/actions.coffee
The mentioned mismatch is with [set_pay_method](https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/course/actions.coffee#L224)
> webapp/courses: mismatching keys when checking payment config choices

- src/smc-webapp/course/common.cjsx
This fixes stale information of the "grade comment" for a student in an assignment.
Test: open the same course assignment twice in two tabs and edit a comment of a student grade. After saving in on of them, the changes should show up in the other instance, too.
> webapp/course: update state of form box upon changes in supplied props data

- src/smc-webapp/billing.cjsx
Mimic other coupon adders as suggested.
In particular, 
- The button now says `Apply`
- The button is closer to the coupon text. 
- It lights up when you put anything in the box
- It submits onBlur
> Mimic other coupon-promo adders

- src/smc-webapp/project_warnings.cjsx
This simply adjusts the memory warning, see #2736
We should check what the memory usage of freshly started jupyter kernels is. python 3 ~80M, while sagemath ~200m? maybe a @DrXyzzy task?
Also, being to sensitive and telling users non-stop in a red banner to upgrade memory would be yet another annoyance :roll_eyes:
> project: more sensitive memory warning and pointing to out-of-memory wiki page

- src/smc-webapp/project_store.coffee
See #2728 
testing is easy: copy one or more files to a directory vs. duplicating a file.
> webapp: special case for logging duplicating files as a copy operation

- src/smc-webapp/project_page.cjsx
There is a second scrollbar for editor content, see screenshot. This simply makes it show up only when necessary …
> webapp/ui: remove duplicate (disabled) scrollbar when viewing an editor content

- src/smc-webapp/course/actions.coffee
- src/smc-webapp/course/assignments_panel.cjsx
- src/smc-webapp/course/common.cjsx
- src/smc-webapp/course/progress.cjsx
- src/smc-webapp/course/store.coffee
- src/smc-webapp/package-lock.json
Fixes #2432 and #2714 
Also improves UI involved with Skipped Steps.
- Don't show errors involved in skipped steps
- Display `Skipped`
- If step is skipped, show all UI for next step even if previous step has errors
> Fix #2432 and #2714

- src/smc-webapp/project_page.cjsx
see #2780
This fix does work for #2780, but it is something I don't really want to go with (because of jquery) … but it is at least a proof of concept how to address this.
(or, we do this as a hotfix for now and update the ticket with a good idea how to do this)
> project page: fixing scrollTop restoration after using smc-vfill flex  layout for the "editor_inner_container" element 

- src/smc-webapp/syncdoc.coffee
This is hopefully harmless until this is fixed properly
> syncdoc: skip undefined codemirrors in close

- src/smc-webapp/code-editor/actions.coffee
idea for #2778
but I'm not sure if I understand this correctly ... and there is similar code for the tasks editor, which might need a similar check.
> code-editor: safeguard save_editor_state against called after close

- src/smc-webapp/course/students_panel.cjsx
This simply adds a button to the "student add" form to add all students in one go (if none are selected).
Test: make a course and add `student+1000@cocalc.com, student+1001@cocalc.com, student+1002@cocalc.com` into the input box and search.
> course: adding all students button (small usability aspect)

- src/smc-webapp/latex/document.coffee
This is a "hotfix". I realized only now that longer lasting operations in the latex editor do timeout with these post calls (they're webapp client "exec" calls).
This patch adds a couple of `allow_post:false`.
Below is a screenshot how it looks with a  lengthy document containing a couple of sage commands.
Same document compiled in my cc-in-cc dev project...
> webapp/latex: some commands take longer and hence tell "exec" to not use post messages

- src/webpack.config.coffee
I remembered to polyfill es2015+ but not transpile it. Oops.
> Use babel-loader for .js and .jsx

- src/webapp-lib/app.pug
Replace `Something bad must have happened.` message with text that
- identifies CoCalc as source of the message
- offers information on the nature of the error
@haraldschilly  please review for correctness. Also, can you suggest a quick way to simulate the error in testing?
If merged, also update [this wiki entry](https://github.com/sagemathinc/cocalc/wiki/Troubleshooting#load-timeout)
> make "something bad" message more useful

- src/smc-webapp/process-links.coffee
issue #2725
Testing: upload a small webm video and do this in a chat or a jupyter markdown textarea:
```
<video controls src="video.webm" style="width:50%">
</video>
<video controls style="width:50%">
<source src="video.webm" >
</video>
```
Of course, other image tags shouldn't break.
There is also similar code buried inside the `sagews/sagews.coffee` file. I tried to fix this in a similar way but then it all broke. That should better be fixed as part of the upcoming rewrite.
> webapp: process links should also fix <video> tags

- src/smc-webapp/smc_chat.cjsx
No clipping either.
Side-effect: Send and preview buttons are now smaller on desktop version. I think this is fine.
> Fix hidden send button on thin screens

- src/smc-webapp/assistant/actions.coffee
- src/smc-webapp/assistant/legacy.cjsx
- src/smc-webapp/assistant/main.coffee
- src/smc-webapp/assistant/store.coffee
- src/smc-webapp/project_log.cjsx
This is a short follow-up for the assistant. This adds entries to the project log in the form of
```
event: {"lang": "python", "path": "empty.ipynb", "entry": ["NumPy", "Indexing", "Get shape of array"], "event": "assistant", "action": "insert"}
event: {"lang": "sage", "path": "empty.sagews", "entry": ["Extras", "Files", "Read CSV data"], "event": "assistant", "action": "insert"}
[...]
```
> webapp/assistant: log inserts in project log

- src/smc-util/misc.coffee
straight forward fix for #2823
testing: the following minimal code for testing causes `this` to be undefined after the second attribute. I have no idea why, it just "happens".
```
<iframe
id="abc"
src="javascript:void(0)"
width="123"
>
</iframe>
```
> webapp/misc: html sanitization stumbles over undefined "this"

- src/smc-webapp/editor.coffee
I saw `Error connecting to console server -- [object Object]` in an error box and well, that's not very informative. This attempts to convert this to a string.
> webapp: improve error message display

- src/smc-webapp/sagews/sagews.coffee
this is a one-line fix for #2830
although I'm wondering why this is can even happen at all.
> sagews: skip init_hide_show_gutter for undefined codemirrors

- src/smc-webapp/buttonbar.coffee
- src/smc-webapp/code-editor/frame-title-bar.cjsx
- src/smc-webapp/editor.coffee
- src/smc-webapp/editor.html
In sagews, a `%md` block, I noticed that there are 3 undefined icons. Sometimes, this split-view icon was also empty, hence I added a fallback in case `@_layout` isn't defined. (heisenbuggy)
The "#" sign for comments in code is also broken.
Finally, the "magic" icon is used by the assistant and it might not be great to use that icon for code formatting as well. Using "indent" seems like a fine choice to me.
> webapp: fix/adjust new icon set for sagews %md

- src/smc-webapp/sagews/sagews.coffee
this is a hotfix for #2860, but only what's in the initial comment. I was able to confirm it by running it through the webpack production build (broken before, fixed after)
> sagews: disable require.ensure for d3 (plotting graphs)

- src/smc_sagews/smc_sagews/sage_parsing.py
- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
Ref: #2868
Add support for python's __future__ statements along with a utility function python_future_feature(feature=None, enable=None) to enable, disable, and query the state of 'future features' like "division" and "print_function".
> Enable support for "from __future__ import ..." in sage worksheets

- src/smc-webapp/collaborators/add-to-project.cjsx
- src/smc-webapp/course/students_panel.cjsx
This should fix #2873 unless I am missing an "invite" somewhere, but my very-quick grep search found one other instance in billing here: https://github.com/sagemathinc/cocalc/blob/invite_to_add/src/smc-webapp/billing.cjsx#L1212
```
You can also invite collaborators to work with you inside a project
```
I thought this was an ok use for the word "invite" so I left it, but maybe for consistency it might be better to switch it also.
> change 'invite' to 'add' in text

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/sage_server.py
This is work in progress, but right now it is at least in state where sagews worksheets produce some output in ubuntu 18.04 again.
The background is that matplotlib config files or env variables might set the backend of matplotlib to one of such a type, where it tries to open a graphical window. e.g. configs like that
```
$ grep ^backend /etc/matplotlibrc
backend      : TkAgg
```
This change here makes this robust against that and selects "Agg" regardless of what the configuration says.
Loading speed? Since in that file pylab is getting imported globally, and also some other parts of matplotlib, I can't imagine how this can have any impact.
Testing: ~~what's missing is to double check with the current ubuntu 16.04 environment.~~ ok, this works in the current software environment, too (no …
> matplotlib backend selection in salvus server

- src/smc-webapp/index.sass
see issue #2892
This isn't fixing katex, but at least the formulas brackets aren't mixed up.
> webapp: simple workaround to unmangle katex formulas in RTL contexts

- src/smc-util/misc.coffee
- src/smc-util/test/misc-test.coffee
- src/smc-webapp/jupyter/status.cjsx
This PR changes the error message for a jupyter notebook with unknown kernel to a message that suggests an existing kernel and allows a user to click and for that kernel to be automatically selected.
I changed the wording of the message to include the word "click" to emphasize that it is actionable.
The suggested kernel is determined by the `closest_kernel_match` function. It basically looks at kernels which have the longest matching prefix with the given kernel. The results are sorted using a custom string comparison that makes things like "sage8.10" bigger than "sage8.9". This way, given the string "sage", this function should usually recommend the latest version of the Sage kernel.
> kernel selection suggestion for jupyter notebooks

- src/webapp-lib/index.pug
This adds a red box warning about firefox (and only for firefox). The text sounds a bit weird, but I think it gets the point across.
> static/landingpage: show warning to firefox users about issue #2875

- src/smc-webapp/jupyter/cell-output-message.cjsx
Ref: #2889.
Here is what is displayed with the new code. Ugly ansi codes no longer appear, and foreground color seems to match the output of JuliaBox.
CoCalc with Julia 0.6.2 kernel:
JuliaBox with Julia 0.6.2 kernel:
> handle ansi codes in stderr

- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_00_timing.py
- src/smc_sagews/smc_sagews/tests/test_graphics.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
- src/smc_sagews/smc_sagews/tests/test_unicode.py
- explicit use of encode()/decode()/chr() when going between bytes and strings
- dict.items() instead of dict.iteritems()
- allow more time for some tests to complete
to test, apply this patch, then
```
cd ~/cocalc/src/smc_sagews/smc_sagews/tests
python -m pytest
==>
== 167 passed, 5 skipped in 332.97 seconds ==
```
> make sagews pytest suite work with python 3.5

- src/smc-webapp/frame-editors/latex-editor/actions.ts
- src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
- src/smc-webapp/frame-editors/latex-editor/gutters.tsx
- src/smc-webapp/frame-editors/latex-editor/knitr.ts
- src/smc-webapp/frame-editors/latex-editor/latex-log-parser.ts
This patch accomplishes a few details regarding Knitr processing of Rnw files.
* do not continue to compile any latex if there is a knitr problem
* parse the knitr output and try to generate appropriate error and warning messages (there isn't much information to get, but it's still helpful)
* if there are no knitr errors but latex errors, these latex errors are on top
* pure latex processing is not affected.
below are screenshots for various scenarios (R syntax, missing R variable, latex error)
> Dealing with Knitr errors

- src/smc-webapp/frame-editors/latex-editor/knitr.ts
this is just a small detail I wasn't thinking about. instead of bash and pipe, it just runs the expression via `-e`. this should make all this robust against funny file names, too.
> webapp/latex/knitr: do not use bash

- src/smc-webapp/app_shared.cjsx
- src/smc-webapp/desktop_app.cjsx
- src/smc-webapp/r_account.cjsx
- src/smc-webapp/redux_account.coffee
I'm trying to make this work again. There is a comment I don't understand, though
> We need to delete this function and instead do like in the _init of actions, i.e.,
>    set derived state based on changes to account store in AccountActions.  -- william
When I add a `_init` function to the account actions, it isn't called at all. Is such a call supposed to happen by the framework? Is this documented anywhere? If so, I haven't found it in the app-framework examples. 
So, what I ended up doing is just calling it right where it is created, in order to make it do anything.
> webapp/global banner: reactivate for K2 announcement

- src/smc-webapp/r_profile_image.tsx
This makes it so that the cropping tool is always a square. Fixes #2971.
> set initial aspect ratio/crop after image is loaded

- src/smc-util/db-schema.coffee
This is just for adding a row like `compute_image` to the projects table. It's a general purpose configuration for "academic" aspects, e.g. additional software, special product keys (for env variables), and whatever we come up in the future. First step is to have a place to store this in a project specific datastructure.
I was also thinking about using the quota system for this, but I fear that's getting too complex.
The associated branch for kucalc is `proj-edu`.
> db: add "addons" row to project table

- src/smc-hub/postgres-server-queries.coffee
- src/smc-util/db-schema.coffee
- src/smc-webapp/admin/users/user-search.tsx
did three test searches directly on the db in prod, which all were below 3 ms.
> db user search: search all users, not just active ones -- #2991

- src/smc-webapp/frame-editors/code-editor/actions.ts
- src/smc-webapp/frame-editors/code-editor/spell-check.ts
- src/smc-webapp/frame-editors/latex-editor/actions.ts
- src/smc-webapp/frame-editors/latex-editor/register.ts
- src/smc-webapp/frame-editors/latex-editor/util.ts
**depends on #3031** ← review that one first
ref: #3026 
test: create a file `test.Rtex` with content, e.g.
```
cat <<EOF > test.Rtex
\documentclass{scrartcl}
\begin{document}
tesst
%% a chunk with default options
%% begin.rcode
% 1+1
%
% x=rnorm(5); t(t(x))
%% end.rcode
ookk
\end{document}
EOF
```
immediately after opening it, the misspelled words should show up with underlines and no  error as depicted in #3026 appears.
> spellcheck special cases for rtex/rnw files

- src/smc-webapp/project_actions.ts
see #3046
test: 
1. setup the paths: `mkdir test; mkdir test/dirA; mkdir test/dirAB; touch test/dirA/a; touch test/dirAB/b; open test/dirA/a`
2. then first go into `dirAB`, and then up and into `dirA`.
> webapp file breakcrumb history: fix erroneous detection of subdirectory if dir names are similar

- src/smc-webapp/billing.cjsx
Now looks like this:
After selecting a subscription
Updating information...
Selected and payment method added. User can still scroll up and change their selection.
> Show add subscription for first time customers

- src/smc-webapp/app_shared.cjsx
- src/smc-webapp/desktop_app.cjsx
This is a detail bothering me from day to day. Usually, my project nav bar looks like that:
which makes it hard to read what's there.
The goal of this here is to hide the labels of some elements when there are more than 6 projects.
> webapp: hide labels of some tabs when there are many open projects

- src/smc-webapp/project_settings.cjsx
when I looked at the changes to the project image selector, I noticed a funny line below:
This PR removes this, there is already a box for the ssh info and there is also no host information (it was still hard coding `...sagemath.com`)
... or is this being used somewhere, e.g. in docker? even there, it wouldn't make much sense as it is, due to hardcoding the DNS.
> remove host info from project settings

- src/smc-project/jupyter/execute-code.ts
- src/smc-webapp/jupyter/output-handler.ts
- src/smc-webapp/jupyter/project-actions.ts
ref:  #3092
root cause: look closely at the changed lines in execute-code: `msg_type` was always undefined, because earlier the `mesg` object was already stripped of the `header` dict.
I also added types in another file I sifted through via debugging, I hope that's fine.
test:
```
from IPython.display import clear_output
from time import sleep
for i in range(10):
clear_output(wait=True)
print('.' * i)
sleep(.1)
```
which should just show 10 dots in the end.
> jupyter2/project:

- src/globals.d.ts
- src/smc-project/globals.d.ts
- src/smc-project/package.json
- src/smc-webapp/jupyter/actions.ts
- src/smc-webapp/jupyter/cell-input.tsx
- src/smc-webapp/jupyter/cell-list.tsx
- src/smc-webapp/jupyter/cell-output-message.tsx
- src/smc-webapp/jupyter/server-urls.ts
- src/smc-webapp/jupyter/store.ts
quick attempt to add declarations for `$`, `window` and so on.
ideas from here: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
interestingly, this doesn't work for `window.app_base_url` in `jupyter/server-urls.ts`. So, despite that I can start the hub in my dev project, maybe all this isn't working at all.
> adding custom global type defs for cocalc

- src/smc-project/browser-websocket/api.ts
- src/smc-project/prettier.ts
- src/smc-project/python-format.ts
- src/smc-project/r-format.ts
- src/smc-webapp/frame-editors/code-editor/actions.ts
- src/smc-webapp/frame-editors/code-editor/editor.ts
- src/smc-webapp/frame-editors/codemirror/cm-options.ts
- src/smc-webapp/frame-editors/frame-tree/editor.tsx
- src/smc-webapp/frame-editors/frame-tree/util.ts
- src/smc-webapp/frame-editors/generic/client.ts
"formatR" with useful defaults and reporting python formatting errors (last line) if possible. also a bit of tweaking for the error message.
obligatory screenshots: messy R code, syntax error, formatted
> formatting *.r code and better display of error messages about syntax problems for python and R

- src/smc-project/package.json
- src/smc-webapp/frame-editors/code-editor/actions.ts
- src/smc-webapp/frame-editors/code-editor/editor.ts
- src/smc-webapp/frame-editors/code-editor/spell-check.ts
- src/smc-webapp/frame-editors/frame-tree/util.ts
- src/smc-webapp/frame-editors/generic/misc.ts
this looks small and easy to merge, but it's not. take your time to review!
> prettier yaml formatting

- src/smc-webapp/frame-editors/code-editor/actions.ts
- src/smc-webapp/frame-editors/frame-tree/editor.tsx
- src/smc-webapp/frame-editors/frame-tree/types.ts
this makes it so that normal error messages have proportional width and all format errors are monospaced. to refine this for each formatter, it would just require to set a flag-variable  in the switch/case block in `code-editor/actions → format()` when running the formatter.
I triggered that one below by stopping the hub
yaml syntax error
> webapp/frame editor: more than one type of error styling

- src/smc-webapp/misc_page.coffee
ref: #3141
I am not sure how to test this, because when I open up normal markdown files or a chat box, and enter a  an image with a normal http-url, it still doesn't append a random number. (with or without that patch). I don't know how and where to look to check it properly.
the code itself is a no-brainer
> do not randomize data image urls

- src/smc-webapp/codemirror/mode/lean.ts
this changes a few details and introduces support for block comments. the order matters a lot, that's where I struggled most. I also need to find a good lean code example for testing … here is the screenshot how block comments look like with that patch
> lean editor: block comment syntax

- src/webapp-lib/index.pug
there is already a version-specific warning when the webapp starts and since FF 62 was released, there is IMHO no longer a reason any more to show this unconditional warning.
test: to build the static pages run `env CC_STATICPAGES=true NODE_ENV=development webpack --debug --output-pathinfo --progress --colors` in the `src` directory.
> static/landingpage: we no longer need that FF extra warning

- src/smc-webapp/jupyter/cell-output-message.tsx
because of
```
2018-09-08T17:09:46.145Z - debug: init_share_server: initializing share server at  /14eed217-2d3c-4975-a381-b69edcb40e0e/port/56754/share
loading jsdom...
loading jQuery...
ensure the global variable window.CodeMirror is defined....
jsdom support loaded
2018-09-08T17:10:02.811Z - debug: BUG ****************************************************************************
2018-09-08T17:10:02.812Z - debug: Uncaught exception: TSError: ⨯ Unable to compile TypeScript:
../smc-webapp/jupyter/cell-output-message.tsx(225,21): error TS2304: Cannot find name '$'.
2018-09-08T17:10:02.814Z - debug: TSError: ⨯ Unable to compile TypeScript:
../smc-webapp/jupyter/cell-output-message.tsx(225,21): error TS2304: Cannot find name '$'.
at createTSError …
```
> hub: fix startup which requires $ to be declared, but is not

- src/smc-webapp/frame-editors/latex-editor/actions.ts
ref: #3159
well, pretty clear fix, type info was misleading
obligatory bonus screenshot featuring build command `latexmk -pdf -f -g -bibtex -synctex=1 -interaction=nonstopmode issue-3159.tex; pythontex3 issue-3159.tex; latexmk -pdf -f -g -bibtex -synctex=1 -interaction=nonstopmode issue-3159.tex`
> latex: fix customizing build command 

- src/smc-project/browser-websocket/api.ts
- src/smc-project/clang-format.ts
- src/smc-project/prettier.ts
- src/smc-webapp/frame-editors/code-editor/actions.ts
- src/smc-webapp/frame-editors/code-editor/editor.ts
- src/smc-webapp/frame-editors/codemirror/cm-options.ts
- src/smc-webapp/frame-editors/frame-tree/util.ts
This should be straight forward to review. For testing, paste a c, cc, h or c++ file and use the format button. 
before
after
> webapp/project: format c, c++ files

- src/smc-webapp/client_browser.coffee
- src/smc-webapp/jupyter/complete.tsx
- src/webapp-lib/preflight-checks.ts
because that's the only one in version 60 that works, and remove that little alert box from the browser client
rationale behind this is explained here https://github.com/sagemathinc/cocalc/issues/2875#issuecomment-420682930
testing: so far I haven't …  and compiling it suddenly causes
```
2018-09-12T15:39:55.992Z - debug: Uncaught exception: TSError: ⨯ Unable to compile TypeScript:
../smc-webapp/jupyter/complete.tsx(32,5): error TS2304: Cannot find name '$'.
```
well, added another commit, now it compiles, and works locally for me. we should check if existing warnings for FF 60 and 61 still show up.
plan to finish: check if my dev project loads find in my chrome and ff 60.2 esr, while the warning appears for an older firefox.
> preflight check: test explicitly for FF 60.2 ESR

- src/smc-webapp/frame-editors/pdf-editor/actions.ts
ref #3182
I'm not sure if this makes really sense, but just from testing it (see referenced ticket) it works.
Below you can see the `reload={...}` property with a value, which appears in the PDFJS (unnamed, though) component after opening it. Without that patch, there is no such property because `props.reload` is `undefined`.
> pdf viewer: initialize loading the viewer with a "reload"  value right from the start

- src/webapp-lib/_base.pug
- src/webapp-lib/index.pug
#3170 
changes: 
* presentation 2nd after intro presentation video. it fits to have both of them there
* moved the text about starting free vs. upgrading to be above two places where the create account button is. added the clarification that this is a unlimited trial. this should make it much more explicit about what to expect with creating an account
> static landing page: adding William's Harvard presentation 

- src/smc-webapp/sagews/sagews.coffee
Ref: #2757
not the prettiest thing, and it's also not a "fix", but existing worksheets do at least load up without showing control characters and a user learns about the problem
> webapp/sagews: hotfix to bypass #2757

- src/smc-webapp/frame-editors/latex-editor/actions.ts
- src/smc-webapp/frame-editors/latex-editor/build.tsx
- src/smc-webapp/frame-editors/latex-editor/clean.ts
- src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
- src/smc-webapp/frame-editors/latex-editor/pythontex.ts
- src/smc-webapp/project_store.ts
ref: #3160
* main goal: editing a pythontex latex document works
* in case of errors, pythontex stdout is parsed and an error indicator added to the gutter
* example document added to https://github.com/sagemathinc/cocalc-example-files/tree/master/latex/pythontex
* pdf preview isn't updated during a build run with an intermediate sagetex or pythontex step
testing: the example document in the cocalc examples mentioned above showcases code, formulas, sympy blocks and error handling
> support pythontex 

- src/smc-webapp/codemirror/custom-modes.coffee
- src/smc-webapp/file-associations.coffee
ref #3047
test: rnw and rtex default files look ok (latex still highlighted). nothing else is touched.
what's actually a bit sad is the overall R syntax highlighting (i.e. no constants,etc.) → [made this pr](https://github.com/codemirror/CodeMirror/pull/5586) upstream.
obligatory screenshots
> syntax highlight R code in rnw and rtex files 

- src/smc-hub/postgres-server-queries.coffee
- src/smc-util/client.coffee
this looks trivial, but I have to add that I haven't tested it so do not merge it without a check
* I indirectly noticed #3171 today because searching for a 2 year dormant user via email didn't give any results in the admin interface
* and well, then noticing  how the default is set, this makes it clear why #3171 is still an issue
* setting `{active:undefined or null}` for admin doesn't work, because the string as a default overwrites it ... hence I added the clause to the if  in the hub. (which requires a restart)
> webapp/hub: increase default for user_search to 13 months and ignore "last active" for admins

- src/smc-webapp/frame-editors/lean-editor/lean-messages.tsx
otherwise scrollbar looks odd
before
after
> weabpp/lean: padding instead of margin around messages 

- src/webapp-lib/webapp-error-reporter.coffee
this fix is based on that below. the whole point is to report an exception `e` as `e`, and not `e.reason`.
---
chrome: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36`
smc_git_rev: 9dde507f765bbe78bafc6d00b22375271ebd1c16
Date: 2018-09-28 13:34:51.692758
`{"0":"misc.defaults -- TypeError: property 'message' must be specified: "}`
```
<generated>
Error
at s (https://cocalc.com/static/smc-2bee88b0c9d7755adaa4.cacheme.js?2bee88b0c9d7755adaa4:5:854984)
at h (https://cocalc.com/static/smc-2bee88b0c9d7755adaa4.cacheme.js?2bee88b0c9d7755adaa4:5:857629)
at console.<anonymous> (https://cocalc.com/static/smc-2bee88b0c9d7755adaa4.cacheme.js?2bee88b0c9d7755adaa4:5:857843)
at console.e.(anonymous function) [as warn] …
```
> webapp errors: fix unhandledrejection error reporting

- src/smc-webapp/project_store.ts
ref #3229
the overall goal is to have `pythontex-files-pytex-1` grayed out in the files listing:
> webapp/latex: improve masking of pythontex cache dir 

- src/smc-webapp/frame-editors/latex-editor/clean.ts
#3228 
Test: cleaning up aux latex files for a file named `x y.tex` using pythontex, also the directory `pythontex-files-x-y` is removed
> latex/cleanup pylatex cache dir 

- src/smc-webapp/history.coffee
- src/smc-webapp/init_app.coffee
Forward/back browser navigation is currently broken. You can go back one action but can't go back anymore. Additionally forward is not possible.
The issue is that every `set_active_tab` call at the page level pushes onto the browser history stack.
This change adds an option for `load_target` and page level `set_active_tab` to not push onto browser history.
Changed `window.onpopstate` to pass `change_history=false` to `load_target` so that forward and back don't alter the history stack.
1. Go to account settings
1. Go to Projects 
1. Open a project
1. Use forward and back on your browser to navigate the previous 3 actions.
Couldn't find an issue.
> Fix browser forward/back navigation

- src/smc-util/misc.coffee
- src/smc-util/test/misc-test.coffee
This extends the `seconds2hms` utility function to also account for days if it is more than one day.
test: in `src/smc-util`, all tests for misc should pass: `export NODE_ENV=mocha-test && SMC_TEST=true node_modules/.bin/mocha --reporter ${REPORTER:-progress} test/misc-test.coffee`
> webapp: project uptime also in day resolution

- src/smc-webapp/codemirror/mode/ada.ts
- src/smc-webapp/codemirror/modes.coffee
- src/smc-webapp/file-associations.coffee
well, when we install the compiler, we should also support file formatting. this is closely modeled after the lean file. good enough for the very basics.
> webapp: support adb ada files

- src/smc-webapp/course/actions.ts
My hypothesis is that `student_account_id` becomes undefined for some reason (which is why a non-user invite is sent) and then the project checks if account ids on the student project are valid. Since `student_account_id` is undefined, all course-collabs (teacher, TAs, etc) will remain but anyone else, including the student, will be removed from the student course.
> Don't remove anyone if student id unknown

- src/smc-webapp/frame-editors/latex-editor/actions.ts
see issue #3262
I don't know how to reproduce this, must be some sort of race condition.
#3262
> webapp/latex: build_logs could be undefined

- src/webapp-lib/webapp-error-reporter.coffee
Since d1100d5931c2080039388778115ab8ae062aaa1e, which includes an earlier fix about handling these type of intercepted problems, "reason" messages of unhandledrejection errors are reported as `unhandledrejection: [object Object]`. The goal of this patch is to get more info about that object.
> webapp: handle objects occurring as unhandledrejection reasons

- src/smc-webapp/course/configuration_panel.tsx
1. grade and comment an assignment with `"` quotes
1. import in excel (I only have libreoffice, though)
* #3249
> webapp/course: export double quotes in comments and grades to csv properly escaped

- src/smc-webapp/package.json
- src/webapp-smc.coffee
see issue #1872, the referenced upstream ticket is closed and someone reported that bootstrap removal as the solution.
basically this is a double-bootstrapping problem.
I did very little testing, just confirmed that #1872 is fixed. My fear is there could be unrelated problems. However, I'm pretty sure importing `react-bootstrap` does also introduce some code and css in such a way, that it might be fine just the way it is.
> webapp: remove bootstrap, in favor of just using react-bootstrap

- src/smc-webapp/course/main.tsx
- src/smc-webapp/course/store.ts
The default was set incorrectly. I'm actually not sure how the check box was showing the incorrect value though. It works now as far as I can tell though.
1. Create a new course file. The Allow arbitrary collaborators box should be unchecked.
1. Add a someone not on the course project to a student project
1. Re-open the course file
1. The extra person should be removed from the student project now
> Fix default allow_collabs value

- src/smc-webapp/project/file-tab.cjsx
- src/smc-webapp/projects_nav.cjsx
middle mouse click to close editor and project tabs. this is then consistent with many other tab-based applications.
1. middle mouse click on an editor tab → closes it
1. middle mouse click on a project tab → closes it
> webapp: middle mouse click to close editor and project tabs

- src/smc-webapp/frame-editors/terminal-editor/terminal.tsx
This adjust the padding of the terminal panel, such that the scrollbar doesn't look like it is floating free. In the screenshots, I switched to a dark background to make the difference clearly visible.
> Terminal scrollbar padding

- src/smc-webapp/billing.cjsx
easy to reproduce problem: subscription → select $14 plan → click on close
do the above, but reset state
#3295
> Issue/3295: fix props.on_close is not a function

- src/smc-webapp/file-associations.coffee
- src/smc-webapp/frame-editors/code-editor/actions.ts
- src/smc-webapp/frame-editors/code-editor/editor.ts
- src/smc-webapp/frame-editors/codemirror/cm-options.ts
- src/smc-webapp/frame-editors/frame-tree/util.ts
This patch tells cocalc to use the XML editor for kml and cml files.
* https://en.wikipedia.org/wiki/Keyhole_Markup_Language … for GIS
* http://www.xml-cml.org/ ... chemistry, e.g. used by https://avogadro.cc/
There isn't much to test.
1. files ending in cml or kml open with the xml editor (syntax highlighting)
2. clicking the format button formats using xml
Example content: see the wikipedia page for kml and the other one for files like
```
<molecule xmlns='http://www.xml-cml.org/schema'>
<atom>
<bond>
<molecule />
</bond>
</atom>
</molecule>
```
it's just xml though.
> webapp/project: enable XML editor for kml and cml and also formatting

- src/smc-project/formatters/bib-format.ts
- src/smc-project/formatters/prettier.ts
- src/smc-webapp/frame-editors/code-editor/actions.ts
- src/smc-webapp/frame-editors/code-editor/editor.ts
- src/smc-webapp/frame-editors/codemirror/cm-options.ts
- src/smc-webapp/frame-editors/frame-tree/util.ts
this is modeled after the xml formatter, which we streamlined to use cocalc's execute function.
1. this only concerns a `.bib` file, which should have a format button.
issue #3315
> format bib files via biber

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/tests/test_00_timing.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Ready for review
~~Marked "work in progress" until new compute image is deployed (see below).~~
update sagews pytest suite for compute image updates
- julia 1.x
- sage 8.3 or 8.4
- singular 41xx
- add simple test for %latex mode
1. select *experimental* compute image if before Monday, Oct 29
1. cd ~/cocalc/src/smc_sagews/smc_sagews/tests
1. python -m pytest
#3302 for %latex
- [NA] Screenshots if relevant.
> Pytest update for 2018-10-29

- src/smc-webapp/frame-editors/html-editor/iframe-html.tsx
- src/smc-webapp/frame-editors/rmd-editor/actions.ts
RMarkdown has a mode, where it generates "notebook html" files. They contain rmd itself, and some extras. This patch basically fixes the iframe viewer in rmd mode in such a way, that it picks the correct file to show. See screenshot
1. see ticket #3317, screenshot also shows a dataframe with a pager.
#3317
> support rmarkdown notebook html files

- src/webapp-lib/_base.pug
- src/webapp-lib/doc/features.pug
- src/webapp-lib/doc/latex-editor.pug
- src/webapp-lib/doc/software.pug
The main aspect of this patch is to introduce a "Features" page pointing to the special latex, R and jupyter notebook pages. I think the wording needs to be fixed a little bit.
The pages should still compile. It did work fine for me...
> Static landing pages improvements

- src/smc-webapp/r_profile_image.tsx
The core of all this is to not show buttons in avatar accounts settings, when the email address isn't defined. Root change is `email_address: string | undefined;` in `ProfileImageSelectorProps` and then making typescript happy.
1. Maybe by deleting one's email address from the DB? What I did is to negate these IFs, to see how it renders if it isn't set.
#3320
> webapp: sanitize avatar settings based on email_address when it does not exist

- src/smc-webapp/editor.coffee
1. I honestly don't know, but the stacktrace in  #3321 supports this fix
#3321
> webapp/editor: safeguard undefined codemirror in programmatical_goto_line

- src/smc-webapp/frame-editors/latex-editor/actions.ts
- src/smc-webapp/frame-editors/latex-editor/gutters.tsx
I tried to come up with a solution mentioned in #3230 but all that doesn't work. Instead, just show an error message.
Along the way I also saw a stacktrace for gutters.
1. filename.tex with no spaces works
1. `file na me.tex` works as well
1. `file  name.tex` or even `file          name.tex` shows an error.
#3230
> Latex spaces in filename

- src/smc-webapp/frame-editors/terminal-editor/connected-terminal.ts
use browser settings for "monospace" generic font family[1] in terminal (just like it is used in the text editor, too)
[1] https://developer.mozilla.org/de/docs/Web/CSS/font-family
1. change font settings in your browser, terminal font changes accordingly -- i.e. not using any web-fonts, but your actual settings
* follow up to #3304
Front end:
> terminal: use browser's generic monospace font

- src/smc-webapp/file-associations.coffee
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_new.cjsx
This just adds RMarkdown to the create/new dialogs. 
1. files → create → dropdown → click RMarkdown
2. +new → RMardown button
Front end:
> webapp: make "RMarkdown" support more visible in new/create files

- src/smc-webapp/billing.cjsx
Remove incorrect callback which set `continue_first_subscription` to false.
1. Open an account that has no prior credit card entered.
1. Click `Account` > `Subscriptions/Course Packages`.
1. Select $14/mo Standard Plan.
1. Enter valid credit card and click "Add Credit Card".
1. After a wait, no weirdness should happen.
#3363
Front end:
> Fix setting continue_first_subscription incorrectly

- src/smc-webapp/tasks/hashtag-bar.cjsx
On production, notice the whitespace below the hashtags:
Fixed with this PR:
Example of many hash tags:
1. Open a tasks file
1. Make some hashtags
1. Click on some
1. It should not produce extra whitespace below the bar
1. Add a lot of hashtags
1. They should all render
Front end:
> Fix hash-bar bottom-margin

- src/smc-webapp/frame-editors/terminal-editor/actions.ts
- src/smc-webapp/frame-editors/terminal-editor/connected-terminal.ts
- src/smc-webapp/frame-editors/terminal-editor/terminal-manager.ts
- src/smc-webapp/frame-editors/terminal-editor/terminal.tsx
- src/smc-webapp/index.sass
This brings the div with the scrollbar in front of the other one: #3389
There is also some artifact left from exposing the render type … but it's no good to have that context menu even in dom mode.
I tested this with a bright (black on white) and a dark theme, in chrome and firefox, and also when I've both opened at the same time. Didn't notice any Problems.
#3389
Front end:
> webapp/terminal: fixing hidden scrollbar

- src/smc-webapp/frame-editors/x11-editor/launcher.tsx
more x11 buttons
1. this is easy to test. click through the new buttons ...
Front end:
> x11: more apps and space around buttons

- src/smc-webapp/frame-editors/x11-editor/launcher.tsx
quick follow up of https://github.com/sagemathinc/cocalc/pull/3395
different sorting algo:
1. it compiles, travis will check this
1. those two new buttons for calibre and evince open up the apps
Front end:
> webapp/x11: sort launcher by labels and add two more

- src/smc-webapp/frame-editors/code-editor/actions.ts
- src/smc-webapp/frame-editors/latex-editor/actions.ts
- src/smc-webapp/frame-editors/terminal-editor/actions.ts
This is rather trivial, and changes to use the popup-blocker aware tab opener
1. x11 help → as usual
2. latex help → opens new page, as usual
3. terminal help → new page
Front end:
> webapp: fix terminal help url

- src/smc-webapp/desktop_app.cjsx
The gap we have makes me uneasy each time I look at it. This patch moves it up … and makes that navbar width a global variable.
1. open in a browser
2. mobile shouldn't be affected
Front end:
> webapp/desktop: basically fixing the new files notification box

- src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
1.  deployed this on test and the in prod, opening the file causing this did work
2. I made a follow up commit, which seems to also work but it needs review. I didn't really understand what's going on actually …
Front end:
> webapp/latex: fix #3413

- src/webapp-lib/preflight-checks.ts
Firefox 65 beta4 exhibits similar symptoms as #2875 
To see it, install FF 65 beta4 and try to connect:
1. Well, to properly test this, we would have to deploy this branch on "test". I'm confident about the code, though …
Front end:
> firefox connection issue: 65 beta4 exhibits symptoms similar to #2875

- .travis-test.sh
- src/smc-hub/package.json
- src/smc-hub/test/api/copy_between_projects.coffee
Fixes error reported by @haraldschilly, `Error: Cannot find module './failing-to-save'`, for the case of `smc-hub$ npm run testapi`
Should not affect production. The only changes are to devDependencies and scripts in package.json and test timeouts in the hub api mocha suite.
1. Install this PR patch.
1. Restart project.
1. In one .term:
```     
cd ~/cocalc/src
. smc-env 
npm run clean
time npm run make
dev/project/start_postgres.py
```
1. In another .term:
```
cd ~/cocalc/src
. smc-env
. dev/project/postgres-env
cd smc-hub
time BAIL=-b npm run testapi 2>&1 | grep -v debug
../scripts/mocha_clean.sh
```
Front end: N/A
> add ts support to hub api mocha test

- src/package.json
- src/smc-project/package.json
Compare with
```
$ /usr/bin/prettier --version
1.15.3
```
... and the entry in the global package.json is because as some dependency, a version 1.11 would be installed. this makes sure all of them are the same.
1. I tested formatting an Rmd file and a cell in a python3 jupyter notebook.
Front end:
> update prettier to be in sync with system-wide version

- src/smc-webapp/frame-editors/x11-editor/launcher.tsx
Add button to X11 launchers for QGIS and DS9. Should be deployed after the next software update. Enable Octave.
Also adds some typing, because I made a typo (`descr` instead of `desc`) and there was no error...
1. ~~run "experimental"~~ recently started project
2. qgis opens up
3. ds9 opens up
4. octave opens up
5. maxima still opens up
6. xcas is also there
7. System Monitor opens up
Front end:
> webapp/x11: QGIS, DS9, Octave, Maxima, Xcas and System Monitor

- src/smc-webapp/project_log.cjsx
This is a quite weird one, but I am able to reproduce #3465 in my dev project, and well, with that patch applied it looks like in the screenshot at the end (compared to the ticket).  There must be something  going on with timestamps which I don't understand. I'm also using lodash as a dependency because of #3466. I tried to sort that "log" array in the js-console, and it simply doesn't get sorted despite it should. What's also interesting, it only works when calling `lodash.sortBy( ... , <function>)`, and not by calling `lodash.sortBy(... , [ <function> ])`. The second one is [mentioned in the doc's example](https://lodash.com/docs/4.17.11#sortBy) but the arguments allow a plain function. Also, using `<date>.getTime()` didn't help either, which is even more obscure.
Still, this is an easy …
> webapp/project log: fix sorting of log entries, especially when searching

- src/smc-util/compute-images.coffee
Since the semester starts and our latest "stable" snapshot is from a while ago, this adds a new one around the beginning of the next semester.
in my cc-in-cc dev project, which runs as kucalc=yes, here are the corresponding DB entry changes:
```
smc=# select compute_image from projects where project_id = 'bc6f81b3-25ad-4d58-ae4a-65649fae4fa5';
-[ RECORD 1 ]-+--------
compute_image | default
smc=# select compute_image from projects where project_id = 'bc6f81b3-25ad-4d58-ae4a-65649fae4fa5';
-[ RECORD 1 ]-+------------------
compute_image | stable-2019-01-12
```
and the image server:
```
root@image-server-m5hwp:/storage# ls -l stable-*
lrwxrwxrwx 1 root root 15 Aug 27 17:32 stable-2018-08-27 -> 2018-08-21_1804
lrwxrwxrwx 1 root root 18 Jan 14 09:55 stable-2019-01-12 -> 2019-01-12_1804_ro
``` …
> software: adding stable-2019-01-12 and tweaking descriptions a little bit

- src/smc-webapp/frame-editors/latex-editor/pdfjs-page.tsx
Fix the gap between pages in pdfjs, such that the page number shows up again.
1. look at the pdf preview of a latex document with more than 1 page.
Front end:
> webapp/pdfjs: show page number between pages again

- src/smc-webapp/frame-editors/latex-editor/latexmk.ts
Pushes latexmk timeout to 4 minutes.
1. does latexmk still compile? (I don't see why not…)
Front end:
> webapp/latex: 4 min timeout latexmk

- src/package.json
- src/smc-project/package.json
The next software update will push prettier to 1.16.0. This just makes sure they're at the same version.
1. formatting an md file
Front end:
> npm: update prettier

- src/smc-util/message.coffee
Minor edit to API docs so that difference between `projects_all` and `projects` calls to the `query` command is explained. 
1. Check out the patch. 
2. mocha test to verify `smc-util/messages.coffee` still works with api calls
```
cd ~/cocalc/src
. smc-env
npm run clean
npm run make
dev/project/start_postgres.py
cd ~/cocalc/src
. smc-env
. dev/project/postgres-env
cd smc-hub
npm run testapi
SMC_DB_RESET=true SMC_TEST=true node_modules/.bin/ts-mocha -p ../tsconfig.json test/api/messages.coffee
```
3. build the doc & view it
```
cd cocalc/src
npm run webpack-static
open static/doc/api.html
```
Relates to #3496.
Front end:
> have projects_all example query in api doc

- src/smc-webapp/landing_page.cjsx
well, click the link
Front end:
> webapp/landing: doc page is more informative than landing page

- src/smc-webapp/project_actions.ts
- src/smc-webapp/project_files.cjsx
This is basically an issue, where an optional field resets an existing value in the DB. I fixed this in such a way, that it not only works for that "unlisted" boolean, but also for the "description"  field. Additionally, I think there was an inaccuracy when checking a defined field: `x || default` picks the default if x is defined but has the value "false". I made this more explicit.
In my cc-in-cc dev project, I ran `psql`, switched via `\x` to see this better, and then picked out the share in my dev project like that:
```
select * from public_paths where project_id = 'bc6f81b3-25ad-4d58-ae4a-65649fae4fa5' and path ILIKE 'latex/one%';
```
change the project id and the path prefix to match with what you have in your project.
* #3485
* #2885
Front end:
> webapp/share: fix updating info about listing & description

- src/smc-webapp/misc_page.coffee
This fixes some oddities, but there are more "window.open" calls with "noopener". So, as of writing this it isn't done.
Regarding `open_new_tab`, it does indeed disconnect the new tab from the old one. `window.openenr` isn't defined, and cocalc's webapp also has no connection any more. 
1. open video chat → new window popup, and `window.opener` is null
1. share a file, and then click on the button to open the shared file. it openes a new tab (not window!) and again, `window.opener` isn't defined.
#3504
Front end:
> open_new_tab emulates rel=noopener by removing the opener attribute

- src/smc-webapp/editor_jupyter.coffee
I remember vaguely there is a ticket, but didn't find it. However, here are before and after screenshots:
1. check title offset
Front end:
> webapp/jupyter classical: fix title offset

- src/smc-webapp/misc_page.coffee
Easy fix, see #3509 for motivation, and no need to `focus()` …
1. open a sagews and click on "help" → "overview" in the buttonbar. tab opens up, no exception.
#3509
Front end:
> webapp: codemirror "edit_selection" use open_new_tab function

- src/smc-project/kucalc.coffee
I looked up what https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt has to say, and it seems like we don't have to add huge pages. "rss: #of bytes of anonymous and swap cache memory (includes		transparent hugepages).". Makes no difference, because it's 0 in our case (at least, I've never seen any other value. `total_cache` for consistency.
1.
1.
1.
Front end:
> project/memory calc: no need to add rss_huge, and total_cache.

- src/smc-hub/package.json
- src/smc-hub/test/api/text_files.coffee
- src/smc_sagews/smc_sagews/tests/test_sagews.py
- update sage version in **sagews pytest** to 8.6
- backout ts workaround (no longer works) & increase timeouts for text file tests in **api mocha tests**
1. check out patch for this PR
1. in a .term:
```
cd cocalc/src/smc_sagews/smc_sagews/tests
python -m pytest
```
1. check out patch for this PR
1. in one .term:
```
cd ~/cocalc/src
npm run clean
npm run make
. smc-env
dev/project/start_postgres.py
```
3. in another .term:
```
cd ~/cocalc/src
. smc-env
. dev/project/postgres-env
cd smc-hub
npm run testapi
```
4. There may be timeouts on the first testapi run. If that happens, repeat the last step, `npm run testapi`.
No changes to production code.
Front end:
> minor updates to sagews pytest and api mocha

- src/smc-webapp/project_files.cjsx
This small change of the little help text above the files listing is mainly motivated by support questions. 
1. there isn't much to test at all, just the wording
Front end:
> webapp: improve info text for select-file actions

- src/smc-webapp/app_shared.cjsx
- src/smc-webapp/chat-indicator.cjsx
- src/smc-webapp/project/file-tab.cjsx
- src/smc-webapp/project_actions.ts
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/projects/create-project.tsx
- src/smc-webapp/projects/project-row.tsx
- src/smc-webapp/projects_nav.cjsx
- src/smc-webapp/tracker/index.ts
Add more Google analytics events so that the events view becomes more useful.
1. Not sure. Is there a way to get a dev Google analytics in a test env?
Front end:
> Track various user interactions via Google Analytics

- src/smc-webapp/misc/__test__/local-storage.test.tsx
- src/smc-webapp/misc/local-storage.ts
This fixes https://github.com/sagemathinc/cocalc/issues/3515, adds an `exists` function, and fixes a bug.
1. I tried to write a test, but I wasn't able to make it work. With a bit of hardcoding it does, though. 
2. My actual test was to expose this temporarily by inserting
```
import * as tls from "./misc/local-storage";
window.smc.tls = tls;
```
somewhere and checking it in the js console.
Front end:
> webapp: remove local storage warning and add exists function

- src/smc-webapp/frame-editors/codemirror/cm-options.ts
I think #3539 is pretty straight forward to fix.
1. see ticket: tex file → cursor in source → Ctrl-p
Front end:
> weabpp/frame editor: codemirror Ctrl-P does not pass down frame ID 

- src/smc-webapp/course/students_panel.tsx
See #3430 and a bit of cleanup. Shouldn't cause any troubles …
1. enter something into the search box and then press shift-return. (no newline is inserted, but searching happens)
2. return still works
3. while searching there is a spinner on the button
Front end:
> webapp/course: search student via shift return

- src/smc-hub/test/api/messages.coffee
- src/smc-util/message.js
1. Main reason for this PR is broken links under "Additional References" to `db_schema.coffee` and `message.coffee` in [api doc page](https://cocalc.com/doc/api.html).
1. Also `smc-hub` api test was requiring `message.coffee` instead of `message.js`.
1. Other `.coffee` mentions in comments were updated to `.js`.
No executable production code is changed. 
1. API test (basically a syntax check)
```
cd cocalc/src
. smc-env
npm run clean
npm run make
cd cocalc/src/smc-hub
node_modules/.bin/mocha test/api/messages.coffee
==>
13 passing (22ms)
```
2. Build API docs (assumes previous steps done). After the build, verify links under "Additional References" resolve to `db_schema.js` and `message.js`.
```
cd cocalc/src
npm run webpack-static
open static/doc/api.html
```
Front end:
> Message coffee comments

- src/smc-webapp/frame-editors/x11-editor/actions.ts
- src/smc-webapp/project_log.cjsx
This records x11 button launches in the project log. I don't know how to record the same for terminal commands, but this is still better than nothing.
Technically, the entry looks like this:
```
smc=# select * from project_log where event ->> 'event' = 'x11' order by time desc limit 3;
-[ RECORD 1 ]--------------------------------------------------------------------------
id         | edf5ca80-9222-4f18-9a72-39b8a3eb5fd7
project_id | bc6f81b3-25ad-4d58-ae4a-65649fae4fa5
time       | 2019-02-06 22:27:50.866
account_id | be11b57a-40f7-4751-8841-9e40dfba5638
event      | {"path": "x11.x11", "event": "x11", "action": "launch", "command": "idle"}
```
and shows up like that
1. x11: click a button and see if it shows up in the log
Front end:
> x11: log launch button

- src/smc-util/client.coffee
- src/smc-webapp/client_browser.coffee
- src/smc-webapp/init_app.coffee
- src/smc-webapp/project_log.cjsx
- src/smc-webapp/share/extensions.coffee
This makes sure the search box is focused, such that arrow keys and so on do work.
0. open log with more than one page of entries
1. click somewhere, and type in
2. similarly, up/down keys still work
3. clicking on a link opens the file as usual
4. also works after clicking on "next page"
#3549
Front end:
> webapp/project log: focus search box when clicks bubble up -- 

- src/smc-project/jupyter/jupyter.ts
Only set the environment of a kernel, if it is a sage kernel. (starting with `sage...`).
The result of this is, that a kernel config file for a python kernel containing
```
{
[...]
"env": {    "CUSTOM_VAR": "123"  }
}
```
will end up as 
There isn't much to test, since it doesn't change anything for sage kernels and fixes all other cases.
Front end:
> project/jupyter: set environment only for sage kernels

- src/smc_sagews/smc_sagews/sage_salvus.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
This depends on this weekends software update.
I tested by running `j11 = jupyter("julia-1.1")` … which worked fine.
Front end:
> sagews: %julia 1.1

- src/smc-webapp/editor.coffee
I don't know the original intention, but the lowercase version of the file extension is available as `@ext`.
high priority, because inserting anything at all is broken
also, moving that line down lowers any impact of errors
1. insert example in a sagews file
* #3564
Front end:
> webapp/sagews: fix misc.get_extension is not a function

- src/smc-webapp/side_chat.cjsx
trivial fix for  #3566
1. open chat next to e.g. sagews file → no longer stacktrace. 
*  #3566
Front end:
> webapp/side_chat: analytics_event was undefined

- src/smc-webapp/jupyter/cell-input.tsx
I hit that error after a clean rebuild of everything (npm update)
```
ensure the global variable window.CodeMirror is defined....
jsdom support loaded
2019-02-16T12:55:23.337Z - debug: BUG ****************************************************************************
2019-02-16T12:55:23.338Z - debug: Uncaught exception: TSError: ⨯ Unable to compile TypeScript:
../smc-webapp/jupyter/cell-input.tsx(48,9): error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery` and then add `jquery` to the types field in your tsconfig.
../smc-webapp/jupyter/cell-input.tsx(55,7): error TS2581: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery` and then add `jquery` to the types field in your tsconfig. …
```
> hub startup: fix yet another error TS2581: Cannot find name "$".

- src/smc-util/sync/jest.config.js
This allows for running `npx jest` from inside of `src/smc-util/sync`.
Originally I borrowed from the jest config a few levels deep then realized I could trim out more config.
1. Have dev environment set up
1. `cd src/smc-util/sync`
1. `npx jest`
Extracting sync into a new separate library -- #3582
> configure sync's jest setup to run solo

- src/smc-webapp/browser.coffee
- src/smc-webapp/file-use/init.ts
With that change I can see the `(<number>) <title>` in the titlebar for notifications again.
1. chat with yourself across two accounts
Front end:
> webapp: fix title notification count in (..)

- src/smc-webapp/sign-up.tsx
Simply removes the component from being rendered.
Back to a simpler UI.
1. Create a new account
1. Check that sign up intents is empty in the database
Front end:
> Disable sign up intents

- src/install.py
- src/package.json
- src/scripts/smc-install-all
This removes all of "our" (in the cocalc codebase) package-lock files, upon running a full installation or cleaning up.  That way, we can eliminate certain side effects of  these files lying around after a previous build.
My motivation is my previous PR about updating pdfjs, because even after changing back to my master branch (with an older pdfjs), npm installed the newer version.
and well, also install.py, that's what kucalc uses
There isn't much to test, because the overall install behavior just getting closer to a "fresh" install
Front end:
> webapp build: cleanup all of "our" package-lock files

- src/smc-webapp/frame-editors/latex-editor/pdfjs-annotation.tsx
- src/smc-webapp/frame-editors/latex-editor/pdfjs-nonloaded-page.tsx
- src/smc-webapp/frame-editors/latex-editor/pdfjs-page.tsx
- src/smc-webapp/frame-editors/latex-editor/pdfjs.tsx
- src/smc-webapp/package.json
Instead of a larger npm package update, this is just one part by itself. Less to worry.
The only substancial change here is this slight API change (a getter), e.g. https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L918
what I tested:
1. latex preview as pdfjs, including forward inverse search, and clicking around, dragging, etc.
2. opening the pdf in the stand alone viewer
Front end:
> webapp/latex: update pdfjs 2.0.943

- src/smc-webapp/frame-editors/latex-editor/actions.ts
- src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
- src/smc-webapp/frame-editors/latex-editor/sagetex.ts
Since I made this already for pythontex and knitr, I knew what to tweak to also make sagetex errors show up. I haven't tested it well, but I'm leaving this here for now. This doesn't solve #3609 though, because there is no line info.
Additionally, I made the headers smaller if the message group has nothing to say. That way, it's less easy to overlook those which have errors -- this could be tweaked in a future ticket a bit more, I guess ...
make errors, check what's showing up, and check that they go away when the problem is resolved.
* #3609
Front end:
> webapp/latex: showing errors of sagetex

- src/install.py
- src/package.json
- src/scripts/smc-install-all
reverting #3616, and adding two targets to get some control over these lock files for further debugging of that problem
1.
1.
1.
Front end:
> webapp: reverting #3616 and adding two npm targets for removing or resetting all lock files

- src/smc-project/x11/server.ts
problem, my dev project never started. always:
```
TSError: ⨯ Unable to compile TypeScript:
home/user/cocalc/src/smc-project/x11/server.ts(9,18): error TS6133: 'SpawnOptions' is declared but its value is never read.
home/user/cocalc/src/smc-project/x11/server.ts(130,40): error TS2345: Argument of type '{ cwd: string; env: any; detached: boolean; stdio: string; }' is not assignable to parameter of type 'SpawnOptions | undefined'.
Type '{ cwd: string; env: any; detached: boolean; stdio: string; }' is not assignable to type 'SpawnOptions'.
Types of property 'stdio' are incompatible.
Type 'string' is not assignable to type '"ignore" | "pipe" | "inherit" | (number | Stream | "ignore" | "pipe" | "inherit" | "ipc" | null |...'.
```
I tried all sorts of ideas. cleaning via that npm run task, …
> proj/x11 server: type spawn options

- src/smc-webapp/support.cjsx
1. Build cc-in-cc
1. Log into test project
1. Open help button and test all 5 links, make sure they point to new pages in doc.cocalc.com
Front end:
> help button links moved to user manual

- src/smc_pyutil/smc_pyutil/smc_compute.py
foudn by lgtm : https://lgtm.com/projects/g/sagemathinc/cocalc/alerts/?mode=list&lang=python
remove the line setting filename which was then not used anywhere in the method
1.
1.
1.
Front end:
> remove one useless line

- src/smc-project/package-lock.json
- src/smc-project/package.json
- src/smc-util-node/memory.coffee
- src/smc-util-node/package-lock.json
- src/smc-util-node/package.json
This whole exercise here is to make projects work with node 10. One package needs updating, another one is no longer maintained (3y old) and has a newer fork. I've also checked in the lock files, because they are short and easy to understand.
1. a clean build in kucalc (using node 8) works.
2. dev projects (in node 8) work (we can't test node 10 dev projects yet)
Front end:
> make projects nodejs 8 and 10 compatible

- src/webapp-lib/_inc_analytics.pug
This is what I suggested on monday, but I haven't seen any changes yet. [see documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/pages)
the goal is that a url like `/app?query=123` is only reported as `/app`.
my only real issue is that I haven't figured out how to confirm this by testing it. inspecting the network traffic didn't help me.
Front end:
> static: do not report query params to GA

- src/smc-webapp/project_miniterm.tsx
This restricts the max width of the miniterm output area. 
I created a long line by running `echo foobar{1..100} | tr -d ' '`
Front end:
> webapp/miniterm: restrict max width to avoid being off screen

- src/smc-webapp/video-chat.cjsx
This should deal with that
* #3648 
Front end:
> webapp/video chat: there could be no video window

- .gitignore
- src/scripts/export-api-doc.ts
no need to review, this is just a helper to get the data from point A to B without having to depend on the entire repository
> doc: little extractor to get a serialized representation of the api doc

- src/smc-webapp/smc_chat.tsx
Clicking the send button works again.
Also fixed some css.
Front end:
> Fix width styling and send button

- src/smc-util/message.js
this is only about api docstrings. @DrXyzzy maybe you should review it to see what changes were necessary.
1.
1.
1.
Front end:
> api: fixing docstrings for usage in doc.cocalc.com

- src/smc_pyutil/smc_pyutil/templates/linux/default.tex
The URL changed, that's all
1.
1.
1.
Front end:
> pyutil: fix link to sagetex help

- src/smc-webapp/side_chat.cjsx
- src/smc-webapp/smc_chat.tsx
Fix pasting in images.
1. Type some text
1. Paste in an image at the beginning, middle, and end locations of input text.
#3670
Front end:
> Fix pasting in an image and refocus

- src/smc-webapp/frame-editors/latex-editor/build-command.tsx
- src/smc-webapp/frame-editors/latex-editor/clean.ts
- src/smc-webapp/frame-editors/latex-editor/latexmk.ts
- src/smc-webapp/project_store.ts
This is adding an escape hatch for #3676, despite whatever we decide with that ticket. A picture says more than words:
**bonus** also mask / clean those gnuplot files
1. run a gnuplot example, with or without the shell-escape enabled engine
2. check the files listing and click the latex build clean button
3. make sure those other selectable engine commands do not add the pdflatex specific option
#3676
Front end:
> Latex shell escape

- src/smc-webapp/jupyter/codemirror.tsx
Trying to fix #3680 
1.
1.
1.
Front end:
> webapp+share: fix rendering of jupyter notebooks

- src/smc-util/theme.js
- src/webapp-lib/_base.pug
- src/webapp-lib/doc/api.coffee
- src/webapp-lib/doc/api.pug
- src/webapp-lib/doc/features.pug
This links to more specific pages in the documentation (they're sufficient stable now), without disturbing the SEO pages. It  also links to the documentation directly from the top navbar, which should drive much more traffic over there. The old API page is left as a redirect to the new location.
well, easy, because if static pages build you just have to look at the features page.
Front end:
> static: link to documentation pages from enhanced features page and the top level navbar

- src/smc-webapp/chat/actions.coffee
- src/smc-webapp/chat/input.tsx
- src/smc-webapp/chat/store.ts
- src/smc-webapp/editor_chat.cjsx
- src/smc-webapp/package.json
- src/smc-webapp/side_chat.cjsx
- src/smc-webapp/smc-dropzone.cjsx
- src/smc-webapp/smc_chat.tsx
Add a simple memoization method so that mentions data is only recomputed when users on the project changes or when the entire chatroom is rendered.
The latter could be removed but it turns out my store memoization method is broken. Sooo I'm going to look into that after this.
In any case, this memoization method is really easy to follow.
Also fixes #3678
1. Open a project with 2 users
1. Have one user invite additional users while the other uses mentions. The list should update.
1. Check that styling hasn't regressed
#3678
Front end:
> Fix #3678 and memoize user data computation

- src/smc-webapp/smc_chat.tsx
Long single line message:
Long vertical message:
1. Type a long one line message into a chatroom without any spaces
1. Create a chat message with a lot of line breaks to have long 
Front end:
> Fix message length problems in chat rooms

- src/smc-webapp/project_page.cjsx
The goal if this here is to point to the new trial project page, but I discovered that displaying it depends on the project log -- which isn't loaded any more. Well, this restores it in all cases, i.e. in particular at the beginning of using a project as a smaller basic banner, and then grows with project usage. The remaining question is if the project log should be loaded in any case. My idea is to check there in the banner logic if it is a paid project (etc.). If not and the project log is empty, it loads it once (maybe with a bit of delay). I didn't code that, because I'm not sure about the actual performance implications.
1. new project, no upgrades, banner shows up (before that patch, it wouldn't)
2. after the project log is loaded and actually filled with a couple of entries and the …
> New trial project page

- src/smc-webapp/package.json
- src/smc-webapp/project/file-listing/directory-row.tsx
- src/smc-webapp/project/file-listing/file-checkbox.tsx
- src/smc-webapp/project/file-listing/file-listing.tsx
- src/smc-webapp/project/file-listing/file-row.tsx
- src/smc-webapp/project/file-listing/no-files.tsx
- src/smc-webapp/project_actions.ts
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/project_store.ts
- src/smc-webapp/projects.cjsx
- src/smc-webapp/projects/project-row.tsx
Uses `react-virtualized` to make file listing much more performant. Try it with a 1000 files! 10000 files even!
https://youtu.be/-vSZnKwhu5A
Implements a few performance improvements mostly involving lists in project listing and file listing.
Testing file listing changes
1. Make a lot of files
1. Make a lot more files
1. Set your file per page to a big number
1. Test checking files
1. Shift check multiple files
1. Use file actions
1. Use up and down arrow keys to change the "selected file"
1. Use down arrow keys until it should scroll. Then watch it scroll with your selection.
Testing scroll save
1. Scroll down
1. Navigate away
1. Come back to the same spot
1. Use the arrow keys while your cursor is in the search box
1. Navigating away and back should result in the selection being visible …
> Performance

- src/smc-webapp/project/ask-filename.tsx
- src/smc-webapp/project_files.cjsx
- src/smc-webapp/r_misc/index.cjsx
that's an implementation for my idea in #2919, in particular to overcome step 2&3 in the user story. basically instead of an error, show an explicit request for a filename in a panel. it's also less friction than before, because a timestamped-filename is inserted by default and return or one additional click is enough to get the file.
in "files" for each, do click "+new" dropdown → e.g. latex or jupyter
1. press return → new file
1. press esc → back to square one
1. type some chars → uses that filename
1. no filename: create not active, and return shows a specific error
#2919
Front end:
> ask explicitly about filename, after selecting the type

- src/smc-webapp/file-associations.ts
- src/smc-webapp/frame-editors/markdown-editor/register.ts
boring PR, see #3723 
open
1. `.md` file
1. `.markdown` file
Front end:
> associate .markdown files with markdown editor -- #3723

- src/smc-webapp/frame-editors/x11-editor/xpra-server.ts
This is a leftover branch from when I thought xrpa 2.5 breaks cocalc's x11. The only change is an additional parameter that disables some dynamic dns lookup. I think it's ok to merge this, but worth a second pair of eyes.
```
--mdns=yes|no       Publish the session information via mDNS. Default:  yes.
```
also, as of right now, I think it doesn't work in the containerized network environment.
```
~/cocalc/src/smc-webapp/frame-editors$ xpra --version
xpra v2.5-r22135
~/cocalc/src/smc-webapp/frame-editors$ xpra list-mdns
failed to connect to the system dbus: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
either start a dbus session or disable mdns support
Looking for xpra services via mdns
Traceback (most …
```
> x11: disable mDNS, xpra 2.5

- src/smc-webapp/editor-data/generic.tsx
do not open jar files as text
well, this doesn't really require testing
Front end:
> webapp: do not open jar files

- src/test/selenium/.gitignore
- src/test/selenium/README.md
- src/test/selenium/tests/conftest.py
- src/test/selenium/tests/test_landing.py
See `cocalc/src/test/selenium/README.md`.
This is a tiny start.
Nothing changes to production code.
1. Apply the patch.
1. Create `~/cocalc/src/test/selenium/mysite.yaml` per README.md. Use IP address if testing cocalc.com or test.cocalc.com.
1. Do
cd ~/cocalc/src/test/selenium/tests
python3 -m pytest --site=../mysite.yaml
\# expect output:
...
== 4 passed in 28.83 seconds ==
Front end:
> start of selenium tests for CoCalc

- src/smc-webapp/editor-data/generic.tsx
there is a link to the documentation of that file type and a note about unzipping it
this is what I did
1.  `wget http://dl.google.com/developers/maps/buffetthawaiitour.kmz`
1. opening that file → info banner, that's it
1. terminal `unzip buffetthawaiitour.kmz` → deflated files
1. opening `doc.kml` (the main file there) opens up as an xml file, which is fine, because it is xml :100: 
Front end:
> kmz files are binary

- src/smc_sagews/smc_sagews/tests/README.md
- src/smc_sagews/smc_sagews/tests/runtests.sh
- src/smc_sagews/smc_sagews/tests/test_doctests.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
- Update sagews pytest for sage-8.7. (trivial)
- Also add initial doctest integration, to see if doctests for a few sagemath files run as expected in sagews environment.
- Tested in experimental software environment (sage-8.7) and default software environment (sage-8.6)
- No changes to code that runs in production.
1. Note in README.md, test invocation has `runtests.sh` wrapper now.
1. Apply the patch.
1. `cd ~/cocalc/src/smc_sagews/smc_sagews/tests`
1. `./runtests.sh -x`. Expected result:
```
collected 190 items                                                                                                             
test_00_timing.py ....                                                                               [  2%]
test_doctests.py ... …
```
> sagews pytest: sage-8.7, sagemath doctest

- src/scripts/bup_migrate_all.py
> remove usunsed import

- src/smc-webapp/jupyter/cell-input.tsx
- src/smc-webapp/jupyter/cell-list.tsx
- src/smc-webapp/jupyter/cell.tsx
Related to that recent question about edit/delete protection, I noticed that during rewriting the jupyter notebook the icon indicator got broken and cell input wasn't updated properly.
1. set metadata `{deletable:false}` or toggle it in the edit menu. just like with editable, an icon appears with a hover explanation.
Front end:
> webapp/jupyter: fix deletable icon indicator

- src/smc-webapp/landing_page.cjsx
- src/smc-webapp/redux_account.coffee
Since this comes up in support at least once a week, I've enhanced the error message if there is a connection issue. It points to the connection debugging page and suggests to refresh the tab. There is also some style tweaking, because those shorter messages would be squeezed to the far right with line breaks.
1. To test this, I've made my email address wrong (by adding  `+'x'`) in the redux account `webapp_client.sign_in` call, and explicitly set `error = 'no conn...'` in the callback. Below are two screenshots.
Front end:
> enhance user-facing error msg when there is a sign in issue

- src/smc-webapp/users.cjsx
Broken mentions (and anywhere User is used) now have text that will read more correctly.
1. Create a mention
1. In the hosting env, edit the database to remove the source column
eg.
```
update mentions
set source = null
```
1. Refresh the page.
1. You should see **Unknown User** instead of the person's name
Front end:
> Change message for malformed account id

- src/smc-hub/api/handler.coffee
- src/smc-hub/auth.coffee
- src/smc-hub/test/api/apikey.coffee
- src/smc-hub/test/api/apitest.coffee
- src/smc-hub/test/api/auth-token.coffee
* if an api key is associated with a banned account, block access
* expiring lru cache, instead of piling up timeouts
* more tests, i.e. the apikey test is a stub to nail down failure behavior
* this is live in prod, hence merging it to avoid confusion
1.
1.
1.
Front end:
> hub: ban api access for banned user account

- src/smc-webapp/share/extensions.coffee
- src/smc-webapp/share/public-path.cjsx
this was missing when support for audiofiles was added.
1. `touch test.wav`, and it should show up via an audio tag
Front end:
> share: add audio file support

- src/smc-webapp/misc/local-storage.ts
- src/smc-webapp/session.ts
Issue #3629
that's how I (successfully) tested this
1. in my cc-in-cc, be in the "master" branch (old code)
1. have a session with two projects and a file each
1. refresh while on master to check that projects and files restore.
1. switch to this branch, refresh browser
1. session should restore as before, double check `session.ts` file's source code to contain e.g. `_local_storage_name: LS.CustomKey` to be sure to really run the new code.
1. open/create yet another file, and refresh
Front end:
> wrap local storage for session save/restore

- src/package.json
- src/smc-webapp/frame-editors/frame-tree/print.ts
- src/smc-webapp/package.json
- src/smc-webapp/share/page.cjsx
- src/webapp-lib/_inc_head.pug
updating katex to exactly 0.10.2
The trick to remember is to also update these security has tokens :champagne:  
I also noticed, there is `latex-editor/experimental/latexjs.jsx:23:import { parse } from "latex.js";` which has an old version of katex as a dependency. Is this used?  Maybe comment out everything related to latexjs and remove the package?
There are new features, e.g. a special bracket. i.e. `$\lBrace 1+2 \rBrace_{\infty}$` doesn't work in prod, but here is a screenshot after the update:
Front end:
> update katex 0.10.2

- src/smc-project/formatters/bib-format.ts
- src/smc-project/formatters/clang-format.ts
- src/smc-project/formatters/gofmt.ts
- src/smc-project/formatters/html-format.ts
- src/smc-project/formatters/latex-format.ts
- src/smc-project/formatters/python-format.ts
- src/smc-project/formatters/r-format.ts
- src/smc-project/formatters/xml-format.ts
The `fs.unlink` api changed in node 10. Instead of using unlinkSync, I just added a pointless function. That's all. This patch also adds some missing temp file cleanup calls!
1. well, all those formatters which were changed should work now
#3832
Front end:
> project/formatter: node 10 fallout regarding fs.unlink

- src/smc-hub/client/create-account.ts
- src/smc-hub/postgres-server-queries.coffee
- src/smc-util/misc2.ts
- src/smc-util/test/misc-test.coffee
- src/smc-webapp/landing-page/sign-up.tsx
This is admittedly a bit simple, but I think it is sufficient. This
* adds a test for a valid username, with a test
* adds this as a precondition for creating an account
* fixes error reporting in the sign up form (otherwise, the screenshot below wouldn't have a red error message)
1. creating an account with a normal first and last name still works
1. trying to create an account where the first or last name contains `https://` or so throws an error
Front end:
> Block URLs in names

- src/smc-util/db-schema.js
- src/smc-webapp/chat/actions.coffee
- src/smc-webapp/chat/input.tsx
- src/smc-webapp/r_account.cjsx
- src/smc-webapp/side_chat.cjsx
- src/smc-webapp/smc_chat.tsx
Add an option in account settings to disable sending mentions.
1. Toggle mentions off in account settings
1. Create a project with collaborators
1. Create a chat room 
1. The help text should not say `@name`
1. Type `@`. Nothing special should happen
1. Sending messages should still work
1. Pasting images should still work
1. Test the above with side chats as well.
Front end:
> Add disable mentions account option

- src/smc-hub/postgres-server-queries.coffee
- src/smc-hub/postgres/syncdoc-history.ts
- src/smc-util-node/misc2_node.ts
- src/smc-util-node/package-lock.json
- src/smc-util-node/package.json
- src/smc-util-node/test/misc_node-test.coffee
- src/smc-util/misc2.ts
- src/smc-util/package-lock.json
- src/smc-util/package.json
- src/smc-util/test/misc-test.coffee
- src/smc-webapp/frame-editors/settings/__tests__/__snapshots__/editor.test.tsx.snap
- src/smc-webapp/frame-editors/settings/__tests__/editor.test.tsx
basically: moving function from  smc-util → smc-util-node
1. `npm run test` in smc-util-node
1. I'll deploy in test namespace.
#3850
Front end:
> fix edge 18 incompatibiltiy in url-regex lib

- src/scripts/postgresql/cool-queries.md
- src/smc-webapp/assistant/body.cjsx
- src/smc-webapp/assistant/dialog.cjsx
- src/smc-webapp/assistant/footer.cjsx
- src/smc-webapp/assistant/header.cjsx
- src/smc-webapp/assistant/legacy.cjsx
- src/smc-webapp/assistant/main.coffee
- src/smc-webapp/editor.coffee
- src/smc-webapp/editor.html
- src/smc-webapp/frame-editors/sagews-editor/editor.ts
- src/smc-webapp/jupyter/browser-actions.ts
- src/smc-webapp/jupyter/commands.ts
- src/smc-webapp/jupyter/main.tsx
- src/smc-webapp/jupyter/register.ts
- src/smc-webapp/jupyter/store.ts
- src/smc-webapp/jupyter/top-buttonbar.tsx
Except for the subdirectory itself, this renames occurrences of "assistant" to "snippets". 
1. sagews: button exists, it opens the dialog, and you can insert code
2. jupyter: same as above
Front end:
> webapp: rename assistant to snippets

- .gitmodules
* sage 3d plots, more 2d plots, renaming
* point the submodule to the renamed github repo
1. sagews: snippets → 3D
2. I also copied over the cython class example
for example, here is the icosahedron plot
Front end:
> update snippets (sage 3d plots, more 2d plots, renaming)

- src/smc-webapp/project_files.cjsx
In my cc-in-cc environment, I made a project for a normal user "A", created a project. Then, as my usual admin user, I opened that project. With that patch, the listing is always there or it attempts to load it. To actually see the project's state, open settings → project control.
#3863
Front end:
> webapp/file listing: for admins, always assume project is running 

- src/smc-webapp/project_files.cjsx
See stacktrace in #3872. There is only one `get` call, and it just happend that there is no configuration yet available.
This is a trivial fix.
#3872
Front end:
> webapp/new files: if no project config is available, fallback to offer all file extensions

- src/smc-util/message.js
Add explanation of get_api_key.
No change to executable code. I checked syntax by building cc-in-cc and logging into the dev instance.
When this PR is merged, I can commit the new `api.json` file to the [cocalc-doc](https://github.com/sagemathinc/cocalc-doc) repo to make the new content show up in the user manual.
Screenshot of the new content:
> Doc get api key

- src/smc-webapp/jupyter/actions.ts
- src/smc-webapp/jupyter/cm_options.ts
There are conflicting modes, and a substition like there are already others helps.
check if e.g. `putStr "abc"` is highlighted in a juypter notebook
#3887
Front end:
> webapp/jupyter: ihaskell → haskell substition for codemirror mode

- src/smc-util/message.js
No change to executable code.
Adds 1 line to API docs pointing out that multi_response API query is not supported, as per [src/smc-hub/api/handler.coffee](https://github.com/sagemathinc/cocalc/blob/3f4b15e6e7b9588f9297f493861352e6ead3cf8f/src/smc-hub/api/handler.coffee#L56)
1.
1.
1.
Front end:
> multi_response query not supported by api

- src/smc-webapp/codemirror/codemirror.coffee
- src/smc-webapp/frame-editors/codemirror/cm-options.ts
- src/smc-webapp/r_account.cjsx
... and also adding a simple fallback if the theme is not known
1.
1.
1.
Front end:
> webapp/code editor: no syntax highlighting for ambience mobile

- src/smc-webapp/projects.cjsx
the idea is simple: init all keys with zero, then sum up, etc. 
testing is tricky. all fields are set in the dev project. so, in order to trigger this, I crippled the "settings" field and removed the user upgrades. e.g. `update projects set settings = '{"project_id": "...", "member_host": 0, "memory_request": 0}'::JSONB where project_id = ...` and so on. Below are screenshot from "master" and with that patch.
Front end:
> webapp/quotas: make sure all quotas exist in the dict of upgrades to avoid NaN vals

- src/smc-webapp/frame-editors/settings/editor.tsx
Fix for a stacktrace like that:
firefox: `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0`
smc_git_rev: d7f6b8c903205aa3d32de047d8fad290e93d3c56
Date: 2019-06-18 15:39:47.842917
`e.props.available_features is undefined`
```
l</t.prototype.render_settings/<@https://cocalc.com/static/smc-cee5077c3cc91ca45d70.cacheme.js?cee5077c3cc91ca45d70:5:456076
e.exports</Be.prototype.__iterate/<@https://cocalc.com/static/0-cee5077c3cc91ca45d70.cacheme.js?cee5077c3cc91ca45d70:6:301470
e.exports</Ge.prototype.iterate@https://cocalc.com/static/0-cee5077c3cc91ca45d70.cacheme.js?cee5077c3cc91ca45d70:6:307221
e.exports</Be.prototype.__iterate@https://cocalc.com/static/0-cee5077c3cc91ca45d70.cacheme.js?cee5077c3cc91ca45d70:6:301428 …
```
> webapp/editor: available features could be undefined

- src/smc-hub/client.coffee
This is my attempt to fix #3916 --- I've not tested this, because I'm not sure about all moving parts and stop here. However, all changes are definitely related to inconsistencies, etc. I've also got rid of one step in `mesg_get_available_upgrades`, because `stripe_get_customer` is already querying the stripe ID.
1. see ticket, i.e. for stripe setup, querying available upgrades for an account with a stripe ID and without one (!) should return. In the second case, it is an error to explain the user that there is no customer info (guessing from the code, it's probably `"no customer_id set yet"`)
Front end:
> hub/api: attempt to fix #3916 (not tested)

- src/smc-hub/client.coffee
- src/smc-hub/package.json
- src/smc-hub/stripe/client.ts
- src/smc-webapp/account_page.cjsx
- src/smc-webapp/billing.cjsx
- src/smc-webapp/r_upgrades.cjsx
Some initial testing suggests this works.  I need to test it more carefully from scratch with a new user,  **test coupons**, test the api, and test various edge cases.  This code is motivated by https://github.com/sagemathinc/cocalc/pull/3917 -- namely how hearing about and seeing this old code I wrote disgusted me (!).   Also, this rewrite probably fixes many subtle bugs that we might not have noticed, since it's just far easier to write async/await typescript code that is correct, than long callback-hell chains in scope-hell coffeescript.
> Refactor all backend stripe api code out of smc-hub/client.coffee; rewrite in Typescript with async/await

- src/smc-webapp/project_files.cjsx
this is a way how #3904 is fixed for me, tested in chrome and firefox. from trial/error I discovered, that the 100% height style in conjunction with the vertical flex directives are causing the problem. my idea is to split this up into two divs, where the bottom one expands and holds the files.
I marked this as careful, because if this fix works for me it doesn't mean I'm breaking it for others.
I tested this for chrome 76.0.3809.36 and Firefox  67.0.3 
1. +new button shows the dialog
1. library shows up
1. uploading a file creates that area showing the upload process
1. file listing shows up, and if there are more files than your page limit, you have these buttons at the bottom
Front end:
> files listing: split flex divs to avoid #3904

- src/smc_sagews/smc_sagews/tests/conftest.py
- src/smc_sagews/smc_sagews/tests/test_graphics.py
- src/smc_sagews/smc_sagews/tests/test_sagews.py
Update to sagews pytest suite for sage-8.8. Also extends graphics tests to allow multiple image file types.
No changes to production code. Tested with sage-8.6, 8.7, 8.8.
1. check out this patch
1. run this code
```
cd cocalc/src/smc_sagews/smc_sagews/tests
python -m pytest -x
==>
=== 178 passed, 10 skipped in 297.92 seconds ===
```
Front end:
> sagews pytest 2019 07

- src/dev/project/README.md
No executable code changed.
Changes to src/dev/projectREADME.md:
1. Document URL needed to connect to cc-in-cc from parent project, e.g. for API testing.
1. Mention `scripts/make-user-admin`.
1.
1.
1.
Front end:
> URL for cc-in-cc from project

- src/smc-webapp/billing.cjsx
Add a section under **Basic or Standard?** on pricing page inviting customers to email with custom requirements.
No changes outside of html in the pricing page.
1.
1.
1.
Front end:
> announce options for custom plans

- src/smc-webapp/billing.cjsx
Replace ask for a free trial with ask about customized plans.
1.
1.
1.
Front end:
> invite customization from subscriptions page

- src/webapp-lib/_base.pug
- src/webapp-lib/_inc_head.pug
- src/webapp-lib/doc/_terminal.pug
- src/webapp-lib/doc/jupyter-notebook.pug
- src/webapp-lib/doc/latex-editor.pug
- src/webapp-lib/doc/linux.pug
- src/webapp-lib/doc/python.pug
- src/webapp-lib/doc/r-statistical-software.pug
- src/webapp-lib/doc/teaching.pug
- src/webapp-lib/index.coffee
- src/webapp-lib/index.pug
This should speed up the page load time.
1. scrolling down on all landing pages and the images show up
Front end:
> static/landing: lazy loading all those images

- src/smc-webapp/billing.cjsx
Restore wording at top of Account > Subscriptions... page inviting free trial. No other changes.
1.
1.
1.
Front end:
> restore invitation to free trial

- src/smc-webapp/billing.cjsx
Per Harald's suggestion, turn "Contact us" into an email link at the top of the Subscriptions tab. The link text broke across lines between the two words in my testing. I inserted a UTF-8 NO-BREAK SPACE.
1.
1.
1.
Front end:
> "contact us" email link

- src/smc_sagews/smc_sagews/sage_jupyter.py
- src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
1. Drop anaconda3 from sagews and its pytests. 
1. Update jupyter bridge code to handle any kernel name starting with 'anaconda'.
1. Update pytest to test for anaconda5 and anaconda2019.
1. Compute image must support anaconda2019. Just now, I tested with `experimental`.
1. Load the patch for this PR.
1. Run tests:
```
cd ~/cocalc/src/smc_sagews/smc_sagews/tests
python -m pytest
==>
== 178 passed, 10 skipped in 373.82 seconds ==
```
Front end:
> sagews a5 a2019

- src/smc-util/message.js
Add an index entry for sphinx docs to message.js. This is a test with one change before adding others.
- only change is inside a string parameter
- cc-in-cc builds & runs ok (projects start, ipynb widgets run)
- test build of docs shows the two new index entries
1.
1.
1.
Front end:
> doc index entry for api user_auth

- src/smc-webapp/jupyter/cm_options.ts
make codemirror indentUnit and tabSize more robust against missing or bad values coming from the editor settings
I'm not sure how to test. What I saw at an account setting was a missing `indent_unit` entry in the settings dictionary. I wasn't able to replicate the problem, but this should help.
Front end:
> jupyter: make codemirror indentUnit and tabSize more robust 

- src/smc-hub/client.coffee
SendGrid unsubscribe group ID for invites is now set in theme.js 
A variable representing the INVITE group ID had already been defined (as 699) in `theme.js`, but didn't seem to be used anywhere -- unlike the variable for the NEWSLETTER group ID, which is being used in `smc-hub/email`
With the `SENDGRID_ASM_INVITE` variable appearing in `smc-util/theme.js`, it gives the false impression that the INVITE group ID would be updated by changing this parameter. After all, that is also where one sets the SendGrid template ID and NEWSLETTER group ID. 
1. Create a _new_ SendGrid template (**legacy**, not one of the "new" dynamic ones) and note its ID
1. Create _new_ SendGrid unsubscribe groups for "Invites" and "Newsletters" (names actually unimportant) and note their IDs
1. Copy the new group IDs …
> SendGrid invite group ID uses variable instead of hardcode

- src/smc-hub/client.coffee
- src/smc-util/message.js
This adds an API endpoint to query the status of a previous copy operation. 
Well, I am not sure if this is a suitable implementation. What I did is to insert an artificial DB entry in my dev project's copy path table:
```
-[ RECORD 2 ]-----+-------------------------------------
id                | 6f3439af-3716-4217-b116-cf34b27ef946
time              | 2019-07-31 12:59:53.616663
source_project_id | bc6f81b3-25ad-4d58-ae4a-65649fae4fa5
source_path       | 
target_project_id | e24ba30d-edcd-479f-8a26-bbe81f38296c
target_path       | 
overwrite_newer   | 
delete_missing    | 
backup            | t
bwlimit           | 
timeout           | 
started           | 
finished          | 
error             | no error
```
Then this works:
```
$ curl -X POST -u sk_[...]: -d …
```
> api: query status of copy path operation

- src/smc-hub/postgres-server-queries.coffee
- src/smc-hub/stripe/client.ts
- src/smc-hub/stripe/sync.coffee
- src/smc-webapp/billing.cjsx
* Updates to a user's email address should propagate to stripe. See #3453
* `sync_stripe`
- syncs the name to the `name` field in stripe (sounds like a good idea), if name or description changed. it also updates the description field.
- of course, it also syncs over the email address
- I saw the comment about rate limiting, that's why I added a short 10ms delay
* while testing and fiddling around with stripe directly, I ended up with exceptions about missing data on  fields. That's why I also added some purely defensive code to `billing.cjsx`.
everything I tested is for cc-in-cc against my own stripe API test token
1. running `hub --stripe_sync`
2. changing email address, checking stripe
3. changing name, running `stripe_sync`, checking if name changed
4. new user, creating stripe …
> hub/stripe: propagate email changes from our DB to stripe 

- src/smc-util/db-schema.js
This is just an additional column for scheduled copy operations. To avoid duplication, using the `started` field should be sufficient.
1.
1.
1.
Front end:
> db: add a "scheduled" field to copy_path for future tasks

- src/smc-hub/hub_http_server.coffee
Fixes #3894 / #3987 
1. Open up a cocalc file link without parameters eg. the url ends with `a.md`
1. This should NOT open up `a.mdnull`
Front end:
> Catch the null case for params

- src/dev/project/start_hub.py
- src/smc-hub/client.coffee
- src/smc-hub/compute-client.coffee
- src/smc-hub/kucalc/compute-client.coffee
- src/smc-hub/test/api/copy-api.sh
- src/smc-util/message.js
The terminal session below is from my local computer hitting the test namespace. I've updated *all* hubs for that (but I think just the api hub is enough ... )
What's new is
*  `copy_path_between_projects` gets a switch `-d wait_until_done=false`
* `copy_path_status` with `-d copy_path_id=[copy_path_id]`
```
hsy@x1:~/d/cocalc/test$ curl -s -X POST -u `cat test_api`: -d src_project_id=`cat p1` -d target_project_id=`cat p2` -d wait_until_done=false -d src_path=x.md https://test.cocalc.com/api/v1/copy_path_between_projects | jq
{
"event": "copy_path_between_projects_response",
"id": "354f6977-47e0-435f-80c2-ccb3593f1217",
"copy_path_id": "b83f8dbf-8c0c-49ab-913a-24a20d862792",
"note": "Query copy_path_status with the copy_path_id to learn if the copy operation was successful."
}
```
``` …
```
> Kucalc: API copy status, Take 2

- src/smc-hub/hub.coffee
report/monitor unhandledRejection errors. Not tested, I've not even restarted my hub. This is just the core idea how to make this work.
Node 10 doc: https://nodejs.org/docs/latest-v10.x/api/process.html#process_event_unhandledrejection
1.
1.
1.
Front end:
> hub: handle unhandledRejection events and report them

- src/smc-webapp/history2.ts
- src/smc-webapp/init_app.coffee
- src/smc-webapp/test/history2.test.ts
Fix #3994 
The default page was account which would briefly load before being set correctly later to `window.smc_target`. This change sets the page appropriately if `window.smc_target` is defined. Defaults to the original behavior if not defined.
1. Load a URL pointed to a file. You should NOT see account settings.
1. Load other pages. Those should still work.
Front end:
> Load directly into target if possible

- src/smc-project/formatters/python-format.ts
- src/smc-webapp/frame-editors/frame-tree/editor.tsx
* show last lines of error, instead of only the last line
* change CSS to fix indentation:
instead of
it's now
1. py file with syntax error → see the line number somewhere
2. still formats if there is no syntax error
#3992
Front end:
> show more of python formatter errors

- src/smc-webapp/frame-editors/_style.sass
- src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
I thought #4000 is easy, but it's not. With this change it behaves as before in firefox, while it overlaps in chrome. The overlapping is at least in such a way, that the right hand controls are always accessible.
chrome beta:
firefox
1.  I tested the latex editor in chromium (stable), chrome beta and firefox
#4000
Front end:
> webapp/frame editor: fix overlapping buttons 

- src/smc-webapp/jupyter/main.tsx
- src/smc-webapp/r_misc/error-display.tsx
well, similar to https://github.com/sagemathinc/cocalc/pull/3995 ... something similar for jupyter. 
here are before/after screenshots
Front end:
> webapp/jupyter: display errors in such a way that pre-formatted text works

- src/smc-util/db-schema.js
searching for scheduled rows means to look for all older ones which aren't finished. this avoid scanning an ever increasing pile.
1.
1.
1.
Front end:
> improve copy paths indexing

- src/smc-hub/postgres-base.coffee
- src/smc-util/db-schema.js
second take for PR #4005, trivial fix. 
1.
1.
1.
Front end:
> hub: create index expressions must be in in parenthesis 

- src/smc-webapp/frame-editors/_style.sass
- src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
#4000
I tested this in my beta-chrome, chromium stable and firefox. works as before and the menu shows up properly.
Front end:
> webapp/frame editor: fix overlapping buttons v2

- src/smc-webapp/custom-software/init.ts
- src/smc-webapp/entry-point.coffee
- src/smc-webapp/fullscreen.ts
- src/smc-webapp/init_app.coffee
- src/smc-webapp/misc_page2.ts
- src/smc-webapp/projects.cjsx
- src/smc-webapp/prom-client.coffee
- src/smc-webapp/redux_server_stats.coffee
- src/smc-webapp/system_notifications.coffee
- src/smc-webapp/users.cjsx
simple idea: when started in kiosk mode, the variable `COCALC_MINIMAL`  causes some aspects to not initialize. the effect is less network traffic and overhead, but I'm not sure if this really helps significantly or is just a drop on a hot stone. This is maybe just a first step.
1. I refreshed various pages, in particular a jupyter notebook. All seem to work fine.
1. normal pages and `fullscreen=default` do not trigger this mode, hence they work just like before.
Front end:
> initialize less when in kiosk mode

- src/webapp-lib/_base.pug
- src/webapp-lib/_base.sass
- src/webapp-lib/index.coffee
I tested this in chrome and FF
Front end:
> static: reinstate fixed navbar via flex

- src/smc-hub/package.json
this updates http-proxy to 1.17. I've deployed this in "test" and ...
overall frontend, cocalc's jupyter notebook, terminal, x11, and the jupyter lab+classic server work. 
Front end:
> hub/proxy: update http-proxy to 1.17

- src/smc-webapp/projects.cjsx
this is an attempt to fix #4054. I wasn't able to fix the nested layout in such a way, that the windowed list works and also the custom software dialog can be scrolled. This simplifies all this.
I tested this on chrome 77 and firefox 68, for narrower windows, and also in cases where it has a smaller height (i.e. the scrollbars become necessary). both behave fine and in the same way.
#4054
Front end:
> webapp/projects listing: fix scrolling for custom software (on small screens)

- src/smc-webapp/course/assignments_panel.tsx
- src/smc-webapp/course/handouts_panel.tsx
- src/smc-webapp/course/main.tsx
- src/smc-webapp/jupyter/cell-list.tsx
- src/smc-webapp/smc_chat.tsx
removing a couple of margins and paddings, such that scrollbars which should be on the right hand side are actually on the right hand side. there was also a case where an inactive bar is shown (and the active one is nested inside right next to it)
* chat window
* course: assignments + handouts, and config is scrollable
* jupyter cell list
Front end:
> Fix scroll margins

- src/webapp-lib/preflight-checks.ts
see #4056
I'm building this in  "test", otherwise I have no way to check it → deployed and it does block Edge as expected
Front end:
> preflight check: block all Edge until #4056 is solved
