salvus/sage_salvus.py, salvus/static/policies/index.html
Just fixing (I hope) a few small typos that I noticed while familiarizing myself with your code base.
=> Correct some typos in magics docstrings, etc.

src/smc-webapp/editor_chat.cjsx
Pulls own messages to the right and other messages to the left. This is inline with the vast majority of chat systems if not all of them.
Own chat messages are also now shaded blue for even easier reading.
=> Implements various chat improvements

src/smc-webapp/projects.cjsx
Change projects page to not include Deleted and Hidden buttons if not applicable.
=> Simplify projects page for new users

src/smc-webapp/editor_course.cjsx
https://github.com/sagemathinc/smc/issues/367
=> Change to say assign homework

INSTALL.md
I'm looking to do SMC development. I was at the Develop for SMC talk and think it's easier to follow along then INSTALL.md so I added a link to it in INSTALL.md
=> add link to "How to Develop SageMathCloud"

src/smc-webapp/project_files.cjsx, src/smc-webapp/project_new.cjsx
Add children to fileTypeSelector
=> Add chatroom to file creation on file listing

src/smc-webapp/editor.html
=> Add a help button for sage worksheets

src/smc_sagews/smc_sagews/sage_server.py
changes towards python3, about print, except and has_key
=> some python3 changes in sage_server

src/smc_sagews/smc_sagews/sage_salvus.py
* changed the syntax of except clauses to use "except Error as msg"
* changed the syntax of raise to use "raise Error("txt")"
* changed most of the print to python2 and python3 compatible syntax
=> some changes towards python3

src/smc_pyutil/smc_pyutil/git_ls.py
=> has_key is not allowed in py3

src/smc-webapp/_project.sass, src/smc-webapp/project.coffee, src/smc-webapp/project.html, src/smc-webapp/top_navbar.coffee, src/webpack.config.coffee
I wasn't able to find a better way, how to update it dynamically when quotas change ... already spent too much time on finding out & testing this way.
What's definitely up for review is the language. I aimed for a short and concise wording, and when clicked  on it, it switches to the settings to show the full explanation messages (matching background colors, etc.). That's also a way to temporarily hide it...
=> webapp: small always visible warning banner when free server or no internet

src/smc-webapp/editor_chat.cjsx
Moves timeago into each individual chat area.
=> fix issue #661

src/smc-webapp/editor_chat.cjsx
Fixing #663. Also made buttons into a group.
=> Change chat scroll down button to default color

src/smc-webapp/editor_chat.cjsx
=> Chat: Scroll to new messages when scrolled to bottom

src/smc-webapp/_project.sass, src/smc-webapp/project.coffee
simple upgrade with expandable text, more links, and dismissable for the entire session.
=> webapp/project banner upgrade warning: version 2

src/smc-webapp/course/settings_panel.cjsx
=> Course: Clarify student upgrade description

src/smc_sagews/smc_sagews/sage_jupyter.py, src/smc_sagews/smc_sagews/sage_server.py
- sage_jupyter.py: add wiki link, eliminate big_output, other minor cleanup
- sage_server.py: make output truncation messages more informative, no other changes to this file
=> Sagews jupyter2

src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/sage_server.py
attach, passes tests at https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/SAGEWS/issue290test.sagews
also cleaned up truncate_text_warn docstring in sage_server.py
=> Sagews hws3

src/smc_sagews/smc_sagews/sage_parsing.py
- one-liner fix, add 'try' to possible parent code blocks of 'else'
- not sure we need to look for 'elif' but I left it there
- decided against any() with list comp because list comp. doesn't short circuit; generator would be overkill
=> issue 694 merge else code block with previous try

src/smc-util/syncdb.coffee, src/smc-webapp/editor_chat.cjsx, src/smc-webapp/smc-react.coffee
In staging: https://cloud.sagemath.com/7552f6e3-0f4f-4476-8954-38b9f14c6069/port/57488/
Log in with one of:
- 1@test.com 
- 2@test.com 
- 3@test.com 
pass: tester
=> Chat: Allow editing of old messages

src/smc-webapp/editor_chat.cjsx
Fixes #704. Was sanitizing before storage. We just need to sanitize on render which happens.
=> Fix issue 704

src/smc-webapp/projects.cjsx, src/smc-webapp/r_account.cjsx
=> Require typing first and last name to delete account

src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/sage_server.py
This reverts commit dafb4b204fc79843c9b71a0136fae563c471c292, reversing
changes made to b4ea2f72690eeaaad3d966d0ec1de3e82e71df7e.
Reverting code in PR for #2 because it added complexity with no value.
=> Revert "Merge pull request #715 from DrXyzzy/pickle-sagews-002"

src/smc-webapp/editor_chat.cjsx
=> fixed issue 746

README.md
=> src - > smc/src

src/smc-webapp/sagews.coffee
This is for #735 
Call to start_line() was, in some cases, causing line renumbering and cursor movement. See issue for more info.
=> [ready for review] Issue735 tab top

src/smc-webapp/editor_chat.cjsx
issue #771 . When you edit a chat and then open other chat edit, the message sends, if it is not edit, it will close the chat edit.
=> when chat edit closes by opening another chat edit, message sends if edited

src/smc-webapp/editor_chat.cjsx
issue #796 Chat preview is no off by default. When you start typing, a eye icon will pop up. When you click it, a preview of the message will appear. You can also close the preview by clicking the X.
=> Updated chat preview.

src/smc-webapp/editor_chat.cjsx
issue #804 fixed issue where the sentences in message history and chat preview breaking in middle of words instead of wrapping.
=> issue 804: changed wordBreak to wordWrap

src/smc-webapp/editor_chat.cjsx
issue #801 changed the eye preview button to a info style button right above the send button.
=> updating preview button

src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/sage_server.py
This code is for the `search_doc` part of #724 .
Tests in sample worksheet in project with feature installed here:
https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/SAGEWS/search_doc_724_test.sagews
=> [merge conflict] add search_doc()

src/smc_sagews/smc_sagews/sage_salvus.py
Ref: #825 
Test file https://cloud.sagemath.com/projects/ccd4d4a4-29a8-4c39-85c2-a630cb1e9b6c/files/SAGEWS/issue825_test.sagews
Project is on smc branch for test code at this time.
=> [ready for review] smc issue #825 sage_eval in sagews

src/smc-webapp/course/students_panel.cjsx, src/smc-webapp/project_settings.cjsx, src/smc-webapp/r_misc.cjsx
=> Issue/851 -- in course when searching for student already in the course, say "student already in course" rather than "student not found"

src/smc-webapp/profile.cjsx, src/smc-webapp/projects.cjsx
On the page listing projects this would show anyone who collaborates on any project the user is a collaborator on that has viewed any file in the last six minutes. Clicking on the icon would take the user to the project page.
=> Make realtime avatars for page listing projects

src/smc_sagews/smc_sagews/sage_server.py, src/smc_sagews/smc_sagews/tests/README.md, src/smc_sagews/smc_sagews/tests/conftest.py, src/smc_sagews/smc_sagews/tests/test_sage_server.py, src/smc_sagews/smc_sagews/tests/test_sagews.py, src/smc_sagews/smc_sagews/tests/test_sagews_x.py
This PR adds files under smc/src/smc_sagews/smc_sagews/tests:
- README.md
- conftest.py
- test_sagews.py
- test_sagews_x.py
This is a start at a regression suite to make it easy to add Sage worksheet test cases as issues are fixed.
=> [review requested] Sage server pytest

src/smc_sagews/smc_sagews/tests/README.md, src/smc_sagews/smc_sagews/tests/conftest.py, src/smc_sagews/smc_sagews/tests/test_sagews.py, src/smc_sagews/smc_sagews/tests/test_sagews_modes.py, src/smc_sagews/smc_sagews/tests/test_sagews_timing.py
add tests to pytest suite for sage worksheets, including
- sh mode tests for checking work with #738 
- startup latency for sage_server
no changes to production SMC code, only to pytest suite under `src/smc_sagews/smc_sagews/tests`
=> [review requested] sagews pytest2

src/dev/docker/README.md
A PR updating the readme as suggested in email.
=> Notes for fixed port assignment and detach

src/smc-webapp/project_store.coffee
I think that's the problem with the directory listings, but I can't test it since everything fails in my dev environment.
=> webapp: fixing directory listing sort and hidden arguments

src/smc-webapp/_account.sass, src/smc-webapp/landing_page.cjsx, src/smc-webapp/redux_account.coffee
Fixes issue #189 
- Added a bold red "check your spam folder"
- moved the dialog to below the input box. I think that makes more sense than being above it.
- made the input box auto focus when you click "forgot password?".
- noticed a bug while fixing this when you click reset password with an empty input box it just gives you the same dialog with an empty email. I think that it should just say "Please enter an email address". So I made it so it says that if you try to reset password with an empty email address. It also focuses the input again if that happens.
=> added a "check your spam folder" and fixed other things in the modal.

src/smc-webapp/profile.cjsx
=> avatars - need to truncate long names in avatar hover text. (e.g., in chatroom)

src/smc-webapp/project_settings.cjsx, src/smc-webapp/r_misc.cjsx
"Warning: this project does not have full internet access..."
See the top and bottom of this image for the inconsistency.
Fixing this will be an easy one-line change some react code.
=> Generated text about network access in warning message in project settings is incorrect

src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Workaround for issue/bug #945, with pytest case added.
=> add workaround for %sh command not found and pytest case

src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/tests/conftest.py, src/smc_sagews/smc_sagews/tests/test_graphics.py, src/smc_sagews/smc_sagews/tests/test_sagews.py
- Made change to docstring per #476
- Added pytest case `tests/test_sagews.py::TestBasic::test_show_doc`, first test case for `code` response from front end.
=> issues 476 and 594 with pytest case

src/smc-webapp/editor_chat.cjsx
=> removed clear input on escape

src/smc-build/anaconda.md, src/smc-build/build.py, src/smc-build/compute-integration-tests.py, src/smc-build/smc-ansible/all-install.yaml, src/smc-build/smc-ansible/compute-extra.yaml, src/smc-project/client.coffee, src/smc-project/sage_session.coffee, src/smc-util/syncstring.coffee, src/smc-webapp/course/settings_panel.cjsx, src/smc-webapp/editor.coffee, src/smc-webapp/editor_chat.cjsx, src/smc-webapp/project_files.cjsx, src/smc-webapp/project_settings.cjsx, src/smc-webapp/project_store.coffee
issue #483 
The default file sort under user settings now sorts the file listing by the selected option.
=> fixed file sort to work with default file sort

src/smc-webapp/editor_chat.cjsx, src/smc-webapp/sagews.coffee
issue #986 cm is undefined when clicking cancel or x, changed it to @codemirror and works.
=> fixed cancel and x buttons in mobile new cell sagews modal

src/smc-webapp/projects.cjsx
I think the problem is it includes probably everything that has ever been upgraded and then downgraded too.  Fixing this is probably nearly trivial -- just recognizing 0 versus undefined...
=> the "Upgrades you have applied to projects" in https://cloud.sagemath.com/settings/upgrades includes entries with no upgrades applied to them

src/smc-webapp/course/common.cjsx
Fixes #835 
Tested in Chrome, Firefox, and Edge on Windows 10
=> Course: Fix self closing assignment/folder adder

src/smc-util/client.coffee
see #361 for details
fix works for me in smc-in-smc
=> fix for #361

src/smc-webapp/smc_chat.cjsx
Moved changes tim made in #997 to the new chat rewrite.
=> Timothyclemansinsea upstream issue 997

src/smc-webapp/editor_chat.cjsx
I tried to edit a message on mobile only to discover I couldn't do so because mobile doesn't have shift-enter.
=> chatrooms: on mobile have a submit button below message when message is being edited

src/smc_sagews/smc_sagews/sage_salvus.py
food for testing, issue #195 
```
rows = [['a', 'bäßbb', 'cö'],[100,2,3], [4,5,60]]
html.table(rows, header=True)
import numpy as np
html.table(np.random.rand(5,5))
m = matrix([[1,2.2,3], [2,3,1]])
html.table(m)
```
=> sagews: implementing html.table (issue #195)

src/smc-webapp/desktop_app.cjsx
This fixes the name change propagation issue. #1057 
It's not elegant. I plan to change Stores so that functions are computed as necessary and stored as values which are then accessed by React so that all computed values always update automatically.
=> Fix name change auto propagation

src/smc-webapp/editor_chat.cjsx, src/smc-webapp/side_chat.cjsx, src/smc-webapp/smc_chat.cjsx
cleans up history and preview rendering #1074
=> fix history and preview rendering

src/smc_sagews/smc_sagews/sage_jupyter.py, src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/sage_server.py, src/smc_sagews/smc_sagews/tests/conftest.py, src/smc_sagews/smc_sagews/tests/test_graphics.py, src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Re: #240 and #976.
Much of old %r supporting code is commented out in sage_salvus.py starting around line 2035. I wasn't sure we want to get rid of all of it.
I don't think it's worth fighting with R and Jupyter to make plots come out in .svg. Suggest referring users to the usual R workaround of saving plot to a file if non-png format is desired.
=> %r with jupyter kernel

src/smc-webapp/profile.cjsx
issue #964 
fixed the avatar count to show the right number of people
=> fixed avatar count

src/smc-webapp/misc_page.coffee, src/smc-webapp/sagews.coffee
=> Change all found instances of load_target to correct call

src/smc-webapp/project_settings.cjsx, src/smc-webapp/projects.cjsx, src/smc-webapp/r_misc.cjsx
Testing here: https://cloud.sagemath.com/7552f6e3-0f4f-4476-8954-38b9f14c6069/port/46161/
Fixes #1048
=> Fix and refactor adjust quota contributions

src/smc-webapp/project_page.cjsx
Fixes #1031 Again another problem with showing stale data since the func pointer itself won't update. 
Issue made for the general problem #1084.
=> Fix free project warning to update automatically.

src/smc-webapp/_projects.sass, src/smc-webapp/editor_history.coffee, src/smc-webapp/project_page.cjsx, src/smc-webapp/redux_account.coffee
issue #1108
@johnjeng please review, in particular I don't know if there is a `className` for `SortableNav` (there is just a helper class?) -- hence I left this as an ID.
=> webapp: moving injected CSS from project_page to _projects.sass

src/smc-webapp/_projects.sass, src/smc-webapp/_projects_nav.sass, src/smc-webapp/desktop_app.cjsx, src/smc-webapp/index.sass, src/smc-webapp/project_page.cjsx, src/smc-webapp/projects_nav.cjsx
Following up on #1113 for the rest of the app.
Tested in Chrome and Firefox on Linux.
=> Change more style strings to sass files

src/smc-webapp/project_store.coffee
Whenever the path changes, update the URL
Fixes #1105
=> Update url on path change

src/smc-webapp/project_page.cjsx
Literally unusable without this fix.
/s
=> Fix file tab height discrepancies

src/smc-webapp/editor.coffee
=> webapp: prevent event bubbling up when toggling html/md preview

src/smc-webapp/project_files.cjsx, src/smc-webapp/project_miniterm.cjsx, src/smc-webapp/project_store.coffee, src/smc-webapp/r_misc.cjsx
Take 2 on this guy. Also incidentally fixes hidden browser history bugs.
=> Fix some fragility with project actions

src/smc-webapp/course/settings_panel.cjsx
Live:
Fixed: 
Also minor changes to accessing actions and type checking immutable maps.
=> Re-align checkbox for requiring students to pay

src/smc-webapp/course/handouts_panel.cjsx
Fixes #1144 
**Was:**
**Now:**
=> Course: Fix long handout names

src/smc-webapp/billing.cjsx
=> Add empty values to add payment FormControl

src/smc-webapp/sagews.coffee, src/smc-webapp/side_chat.cjsx
issue #1184 -- @DrXyzzy please check if this is really fixing what you meant (and not breaking other cases)
=> webapp/sagews: when fixing the src of an image in some html, make sure to deal with absolute paths and images from the blobstore

src/smc-webapp/editor.coffee, src/smc-webapp/editor.html
issue #193
example file: https://cloud.sagemath.com/14eed217-2d3c-4975-a381-b69edcb40e0e/raw/scratch/animation.webm
=> sagews: show videos like webm or mp4, e.g. animations created with matplotlib

src/smc_sagews/smc_sagews/sage_jupyter.py, src/smc_sagews/smc_sagews/tests/a.html, src/smc_sagews/smc_sagews/tests/a.py, src/smc_sagews/smc_sagews/tests/a.sage, src/smc_sagews/smc_sagews/tests/conftest.py, src/smc_sagews/smc_sagews/tests/test_sagews.py
- remove redundant `continue` statements reported in #1217.
- add test cases for sage worksheet
=> sagews cleanup

src/smc-webapp/project_settings.cjsx
=> webapp: fixing project id when creating ssh authorized keys file

src/smc-webapp/buttonbar.coffee, src/smc-webapp/misc_page.coffee
also keep focus after inserting and do not move cursor back to the original position
issue #1201
how to test:
* empty sagews or in a new cell, inserting %md mode, no newline above, but cursor below and ready to do markdown
* in sage/python mode, in a new line, inserting an if-else control structure starts at the same line and the cursor is then at the end and ready for evaluation
* also in sage/python, but the cursor is inside the line (not column zero), inserting if-else inserts a newline and hence starts a proper block of code. that way, most of the cases do not end up in broken code (e.g. in "data", inserting all the constructors one after the other)
=> webapp/buttonbar: avoid inserting empty lines if cursor is at the start of a line.

src/dev/laptop/README.md
FIxed a typo in the laptop instructions
=> Fixed a typo

src/smc_sagews/smc_sagews/sage_parsing.py, src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/tests/conftest.py, src/smc_sagews/smc_sagews/tests/test_sagews.py, src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
- Fix for #1225 plus regressions on #295 and #701.
- Add test cases for #295, #701, #734 and #1225 (all autocomplete)
- Add introspection test fixture.
=> 1225autocomplete

src/smc_pyutil/smc_pyutil/sagews2pdf.py
I'm still contemplating about this, but my test file works for all cases. So, this is rather to let anyone else know that I've tackled both...
=> sagews printing: fixing octave printing #1254 and too wide plots #1255

src/smc-webapp/project_files.cjsx, src/smc-webapp/project_store.coffee
Resolved on smc-in-smc *with* minify turned on per script by @haraldschilly
=> Hotfix public files before computed values is fixed

src/smc-util/misc.coffee, src/smc-util/test/misc-test.coffee, src/smc-webapp/project_files.cjsx, src/smc-webapp/project_settings.cjsx, src/smc-webapp/project_store.coffee, src/smc-webapp/smc-react.coffee, src/smc-webapp/test/smc-react-test.coffee
Redo computed values so that they don't need some crazy minification scheme. 
Tests updated to reflect these changes.
=> Computed values

src/smc-webapp/project_store.coffee
Fixes #1285 
Also prevent other unseen fallout from converting project_store.
=> Fix shift-click on files

src/smc-webapp/project_store.coffee
=> Fix updating current directory url

src/smc-webapp/editor.coffee, src/smc-webapp/editor.html
Attention, merging this branch removes the sagews2html beta testing easter egg and adds a new button for the current sagew2pdf printing.
=> webapp: remove sagews2html easter egg

src/smc-webapp/interact.coffee, src/smc-webapp/sagews.coffee
this is an attempt to fix #1332 
I ended up doing it this way after a lot of trial and error. Feels like the wrong way to do it and I hope there is a more elegant way. Also, those additional processing steps in between inside interact.coffee are probably not necessary.
=> webapp/sagews/interact: html-process descriptions to fix #1332

src/smc-webapp/project_log.cjsx
Got tired of this not existing.
It moves!
=> Add arrow key controls to project log

src/smc-webapp/landing_page.cjsx, src/smc-webapp/r_help.cjsx
=> Add stats to landing page

src/smc-webapp/project_files.cjsx
=> show an error if not collaborator

src/smc-webapp/_editor.sass
=> webapp: bringing timetravel slider's z-index down back to earth -- #1339

src/smc-webapp/_projects.sass, src/smc-webapp/billing.cjsx, src/smc-webapp/projects.cjsx, src/smc-webapp/r_misc.cjsx
Note: make sure you set commercial to yes in settings and set up stripe
For #1016
=> Simplify the create project component

src/smc-webapp/r_misc.cjsx
=> Export NoUpgrades component

src/smc-webapp/project_files.cjsx, src/smc-webapp/projects.cjsx, src/smc-webapp/r_misc.cjsx
Fix a bug that by luck hasn't shown up before.
=> Fix bug where project log search would not show

src/smc_sagews/smc_sagews/tests/README.md, src/smc_sagews/smc_sagews/tests/conftest.py, src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
- increase recv timeout
- add simple reporting of test failures and update README.md for that
- typo
=> pytestreport

src/smc-webapp/project_store.coffee
Fixes #1365. Includes a debug log upon error for #1359 which I have been failing to replicate on test.sagemath.com and on smc-in-smc. Replication on production servers also seems inconsistent.
=> Fix invisible error when opening hidden files

src/smc-hub/hub.coffee, src/smc-webapp/projects.cjsx, src/smc-webapp/r_account.cjsx
=> polish create project with hosting and network upgrades

src/smc-webapp/side_chat.cjsx
=> Fix viewing user name for side chat editor

src/smc-webapp/project_store.coffee
=> Remove looking at local chat storage for public files

src/smc-webapp/printing.coffee
error handling is missing. besides that a first working idea... I'll finish this another day.
=> sagews2html: embedding videos

src/smc-webapp/project_store.coffee
the way I did test it, is to reload the whole page while the url contains a full path to a file
=> webapp: dealing with file listing problems -- issue #1408

src/smc-webapp/account_page.cjsx, src/smc-webapp/landing_page.cjsx, src/smc-webapp/project_files.cjsx, src/smc-webapp/project_page.cjsx, src/smc-webapp/project_store.coffee, src/smc-webapp/projects.cjsx
=> Re-generate Editors if Client relationship to them changes

src/smc-webapp/smc_chat.cjsx, src/smc-webapp/video-chat.cjsx
the basic idea of this fix is, that the video chat button is a `<Button onClick={@click_video_button} ...`.
works for me in my FF, and of course chrome. No changes in the visual look ...
=> webapp/chat: fixing #1364 by making the VideoChatButton a real Button

src/smc-webapp/landing_page.cjsx
=> add Advantages wiki link to landing page

src/smc-webapp/app_shared.cjsx, src/smc-webapp/chat-indicator.cjsx, src/smc-webapp/index.sass, src/smc-webapp/smc-react.coffee
this deals with  issues #938 and #1422.
=> webapp: simple animations for notifications

src/smc-webapp/editor-html-md/editor-html-md.coffee, src/smc-webapp/editor.coffee, src/smc_pyutil/setup.py, src/smc_pyutil/smc_pyutil/java2html.py
I didn't want to write a bunch of code for this so I'm piggybacking off of the md file editor.
=> add a java file editor that shows output on the right

src/smc-webapp/editor.coffee, src/smc-webapp/editor_latex.coffee
This is a minimal implementation for supporting `*.Rnw` files.
=> webapp/latex: support for *.Rnw knitr files (like sagetex, but for R)

src/smc-webapp/course/settings_panel.cjsx
=> put members and network hosting checkboxes at top

src/smc-webapp/editor-html-md/editor-html-md.coffee, src/smc-webapp/editor.coffee, src/smc_pyutil/smc_pyutil/java2html.py
=> Make java preview work with subfolders and get rid of html file creation

src/smc-webapp/editor-html-md/editor-html-md.coffee
=> hide text input buttons for java files

src/smc-webapp/projects.cjsx
=> show create new project if no projects

src/smc-webapp/editor_latex.coffee
for Rnw files, this maps the line numbers of the latex errors to the lines of the Rnw file. Easy to test by opening a large Rnw file and breaking the latex code.
=> Rnw concordance for latex compile errors

src/smc-webapp/redux_account.coffee
so on sign in the projects page shows
=> For #1473: on sign out get rid of settings hashtag

src/smc-webapp/_console.sass
issue #1528
besides cleaning up the animation a bit, my only idea is to introduce a border. looks ok for me. I don't see a way to solve this in a more sophisticated way by working with the actual background color of the theme.
=> webapp/console: cleanup cursor blinking and introduce a border for improved visibility on dark backgrounds

src/smc-webapp/billing.cjsx, src/smc-webapp/project_files.cjsx
=> For #1558: add pay for course via project files page

src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/sage_server.py, src/smc_sagews/smc_sagews/tests/conftest.py, src/smc_sagews/smc_sagews/tests/test_00_timing.py, src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Ref: #1586 #1553  
also: increase sage_server acceptable start latency from 10 to 12 sec in pytest suite
=> issue/1586 sagews %singular_kernel mode and pytest cases

src/smc-webapp/init_app.coffee
It is used to suppress the warning after resume from standby
see issue #1320
The way I tested it, is to first reduce the interval_min to `.1` to deal with my impatience and then to just stop all chrome tasks with a SIGSTOP ... more than 10 secs later, resume them via SIGCONT. 
One subtlety is, that the timer sometimes fires two times at once, that's why it looks back 3 timestamps. That's why this obviously doesn't work when you resume after less than 3 minutes.
I also don't fully understand, why the message appears so easily after a resume. It's maybe because the disconnect event of the client is triggered several times and hence it looks like there were a lot of attempts. The fix here is independent of this, though, and hence should suppress it regardless if that theory is true or not.
=> webapp reconnection warning: this introduces a test "recent_wakeup_from_standby" based on a heartbeat

src/smc-webapp/billing.cjsx
(clearly, those who want to make more than one have to literally wait until this is done properly)
=> webapp/billing: dirty fix to prevent more than one subscription creation per minute

src/smc-webapp/projects.cjsx
This is just a slightly better logging and error message.
=> webapp/projects: be explicit about which project one is not a collaborator of

src/smc-webapp/project_new.cjsx
Test workflow:
no extension press enter, should see confirmation, and confirming should work
no extension press file, should see confirmation, and confirming should work
extension press enter, new file should be created
extension press file, new file should be created
no extension, click file extension dropdown select one, new file should be created
=> For #1595: fix file button bug

src/smc-webapp/project_file.cjsx, src/smc-webapp/project_new.cjsx
For #1668 and depends on #1602
=> For #1668 don't show warning for file associations starting with noext-

src/smc-webapp/sagews.coffee
as suggested in issue #1724, should be safe
=> webapp/sagews: _handle_input_hide_show_gutter_click check if there is a line

src/smc-hub/postgres-synctable.coffee, src/smc-util/db-schema.coffee
=> notes about backing changes data with a small table

src/smc_sagews/smc_sagews/sage_parsing.py, src/smc_sagews/smc_sagews/tests/test_sagews.py
issue #1735
besides review, @DrXyzzy, this maybe needs a test case?
=> sagews: also merge code blocks when there is more than one decorator

src/smc-webapp/buttonbar.coffee
1-line edit, tested in smc-in-smc
=> change default_mode buttonbar text into working code

src/smc-webapp/r_misc.cjsx
@williamstein few days ago you were asking about an `HTML` component. This patch creates such element, which is basically the already existing `Markdown` component except for the Markdown part.
I tested it by temporarily adding some code like this
<HTML value="<a href='http://www.latex-project.org/'>LaTeX</a> is a system ... " />
and indeed, the rendered link opens a new tab (automatically added `target="_blank"`), renders a formula, etc. Hence it does all the extras `Markdown` usually does. Maybe merge it into your jupyter branch first...
=> webapp: adding an react HTML component which is 90% of the already existing Markdown component

src/smc-util/misc.coffee
covers one case that came up while working on #1801
=> webapp/latex: bmatrix is also a valid environment

src/smc-webapp/3d.coffee, src/smc_sagews/smc_sagews/sage_salvus.py
Ref: #1836 
time: 2:45
mostly researching feasibility of transparency option
=> add viewer and background to docstring for show(), enable transparent bg for three.js

src/smc-webapp/smc_chat.cjsx
unexciting fix for #1802
process: see what happens when a message is displayed
time: 10 min
=> webapp/chat: simple fix for #1802

src/smc-webapp/3d.coffee, src/smc_sagews/smc_sagews/sage_salvus.py
=> set default foreground when background is transparent

src/webapp-lib.coffee
issue #1853
test: is smc still load up fine? checking with IE11 a plus :-)
process: most time spent in figuring out where in all the webapp node libs the error really is
time: 20 min
=> webapp/lib: Number.isNaN polyfill

src/smc-util/misc.coffee, src/smc-util/test/misc-test.coffee
see issue #1818
this is work in progress, but at least I've added tests and expanded what it does a bit. I haven't actually checked if it fixes #1818.
time: 30 min
=> util/misc: making "transform_get_url" smarter and adding tests

src/smc-webapp/course/main.cjsx, src/smc-webapp/course/settings_panel.cjsx, src/smc-webapp/project_files.cjsx, src/smc-webapp/smc-dropzone.cjsx
Fixes #1863 and #1864 for the cases below:
- Viewing directories in public view
- Viewing directories as an administrator
Also fixes minor `TextInput` bug in courses.
=> Add disable option to dropzones

src/webapp-lib.coffee
=> webapp/lib: polyfill for String.prototype.includes

src/smc-webapp/_project_page.sass, src/smc-webapp/_projects_nav.sass, src/smc-webapp/index.sass, src/smc-webapp/mobile_app.cjsx, src/smc-webapp/project_page.cjsx, src/smc-webapp/projects_nav.cjsx
=> Mobile fixes

src/smc-webapp/smc-dropzone.cjsx
see #1896 based on #1869
test: dropzone works in public view
process: no idea what's going on, seems like the previous changes to that did revert some earlier bugfixes -- or -- some code is missing and wasn't committed.
time: 30 min
=> webapp/dropzone: hotfix for #1896 based on #1869

src/smc_pyutil/smc_pyutil/sws2sagews.py
ref: #1587 
This patch converts 5 of the 6 .sws files from #1587 to usable .sagews files. It does not successfully convert `fclali34.sws` from `resageincalculus.zip`. The latter file is newer sws format (i.e., top level of the bzip2 archive is `sage_worksheet`). It has a several `<div class="math">` elements in html cells which are not converted correctly, as well a .css file in the archive. I think I'm at the point of diminishing returns and do not plan to fix conversion of `fclali34.sws` at this time.
To test:
1. Check out the patch and run sws2sagews.py from source repo:
```
~/smc/src/smc_pyutil/smc_pyutil/sws2sagews.py <filename.sws> ...
```
The script will create a `filename.sagews` file for each .sws file on the command line.
1. Test with any of the 5 old-format files in #1587.
1. …
=> Issue/1587 convert old-format sws files to sagews

src/scripts/update_stats, src/smc-hub/hub.coffee, src/smc-hub/postgres-server-queries.coffee
This basically creates a new hub-task, which I modeled after sync_stripe.
=> hub: update stats task

src/smc-hub/test/api/account.coffee, src/smc-util/message.coffee
Ref: #1987 
This PR uses `API message2` definitions and `desc` docstrings. More commits to follow on this issue.
=> document API

src/smc-webapp/course/actions.coffee
=> Remove all given upgrades when deleting a student

src/smc-util/immutable-types.coffee, src/smc-util/test/types.coffee
Some initial tests.
For some reason doing the same test with Lists was failing so I'll be investigating tomorrow.
=> Add inital testing of custom immutable types

src/smc-hub/test/api/account.coffee, src/smc-hub/test/api/text_files.coffee, src/smc-util/message.coffee
Ref: #1987 and #1988.
Doc and tests for API calls for private and public text files.
- write_text_file_to_project
- read_text_file_from_project
- public_get_directory_listing
- public_get_text_file
Note that the test for `write_text_file_to_project` can take up to 5 seconds.
=> Issue1987d

src/webapp-lib/term/term.js
I dusted off this old branch of mine, where I worked on fixing a couple of problems with term.js. 
Main "new" feature: you can open up htop and it understands mouse clicks (e.g. highlighting a line, etc.). 
The other part is just a note about an error, but that commented change introduces other problems, ...
=> Term.js bugfixes

src/smc-webapp/api-key.cjsx
=> link to api docs from account settings

src/smc-webapp/course/actions.coffee, src/smc-webapp/course/assignments_panel.cjsx, src/smc-webapp/course/handouts_panel.cjsx, src/smc-webapp/course/main.cjsx, src/smc-webapp/course/settings_panel.cjsx, src/smc-webapp/course/students_panel.cjsx
Actually apply the code required to fix #1546...
Also save the open state of the peer grading configuration dialogue
=> Enable persistence on all markdownInput widgets in course

src/smc-hub/auth-token.coffee, src/smc-hub/auth.coffee, src/smc-hub/client.coffee, src/smc-hub/postgres-server-queries.coffee, src/smc-hub/sign-in.coffee, src/smc-hub/test/api/account.coffee, src/smc-hub/test/api/auth-token.coffee, src/smc-util/client.coffee, src/smc-util/db-schema.coffee, src/smc-util/message.coffee, src/smc-webapp/client_browser.coffee, src/smc-webapp/init_app.coffee
=> add user auth message -- #2029

src/smc-hub/hub.coffee, src/smc-hub/hub_http_server.coffee, src/smc-hub/metrics-recorder.coffee
2nd round, I've simplified the initialization, saw that a function could throw an exception, there were also one or two typos, etc.
In my project, all tests pass and the project works. In case there is still something broken I need to know more about what's going on.
=> hub prometheus metrics -- pt. 2

src/smc-webapp/_editor.sass, src/smc-webapp/editor.html, src/smc-webapp/editor_latex.coffee
@DrXyzzy this is about documentation and fixing my language. It also addresses #1610 a little bit, at least I think so.
=> webapp/latex: adding help tab

src/smc-util/message.coffee, src/webapp-lib/_base.pug, src/webapp-lib/doc/api.pug, src/webapp-lib/index.pug
=> api doc enhancements

src/smc-util/message.coffee
=> expanded API intro doc section

src/smc-webapp/jupyter/actions.coffee
=> webapp/jupyter: fixing setting cursor locations without syncdb instance

src/smc-hub/client.coffee
=> SageMathCloud -> CoCalc in email invitation

src/smc-webapp/billing.cjsx, src/smc-webapp/buttonbar.coffee, src/smc-webapp/course/actions.coffee, src/smc-webapp/course/delete_students.cjsx, src/smc-webapp/course/help_box.cjsx, src/smc-webapp/course/settings_panel.cjsx, src/smc-webapp/course/shared_project_panel.cjsx, src/smc-webapp/course/students_panel.cjsx, src/smc-webapp/course/upgrades.cjsx, src/smc-webapp/desktop_app.cjsx, src/smc-webapp/editor_jupyter.coffee, src/smc-webapp/entry-point.coffee, src/smc-webapp/init_app.coffee, src/smc-webapp/jupyter/javascript-eval.coffee
issue #2111
process: replacing text and comments
time: 15 min
=> webapp: various smc → cocalc renamings and licensing code

src/smc-hub/client.coffee, src/smc-hub/test/api/text_files.coffee, src/smc-util/message.coffee, src/smc_pyutil/smc_pyutil/smc_compute.py
For #2053 
~~No production code was changed.~~
Added tests for making folder public and downloading zip ("PK") file.
=> add tests for making folder public and downloading

src/smc-util-node/sqlite.coffee
=> enable debug logging if SMC_DEBUG is set

src/smc-hub/test/api/copy_between_projects.coffee, src/smc-util/message.coffee, src/smc-webapp/_projects.sass, src/smc-webapp/project_page.cjsx
Ref: #1987 and #1988.
API calls `copy_path_between_projects` and `copy_public_path_between_projects`.
```
~/cocalc/src/smc-hub$ mocha test/api
... 
90 passing (32s)
1 pending
```
=> doc & test API copy between projects

src/smc-webapp/project_files.cjsx
=> webapp: in files, create+upload button wrap on narrow screens. does not look ok

src/smc-webapp/projects.cjsx
Pull request for copy menu bug
=> Copy menu update

src/smc-webapp/course/store.coffee, src/smc-webapp/course/sync.coffee
obviously, some refactoring leftovers are the cause for #2190 
time: 20 min
process: first I thought it is the template itself, but in the end it's the default text
=> webapp: fix course invitation template text

src/smc-webapp/project_page.cjsx
just cosmetics, see comment https://github.com/sagemathinc/cocalc/issues/2041#issuecomment-315155469
test: open sagews or ipynb file and append `?fullscreen` to the URL
time: 7 min
=> webapp: get rid of top padding iff in fullscreen mode

src/package.json, src/smc-webapp/billing.cjsx
(in particular around avoiding vendor lock-in)
=> webapp/billing: adding more details to the FAQ explaining aspects around project files and courses

src/smc-hub/client.coffee, src/smc-hub/test/api/account.coffee, src/smc-hub/test/api/copy_between_projects.coffee, src/smc-hub/test/api/log_client_error.coffee, src/smc-util/message.coffee
Ref: #1988
~~__WARNING__: I'm requesting a review of this test in relation to #2184, but this PR should probably not be merged until that issue is resolved.~~
Please see my last comment below. The code looks good, but I was not able to complete testing using cc-in-cc (details in the comments). If @haraldschilly can do the two suggested tests in a normal build, it should be good for a merge.
=> log_client_error test without `done` on logging step

src/smc-webapp/sagews.coffee
see issue #2245 and some cleanup
=> sagews: improve error message

src/smc_pyutil/MANIFEST.in, src/smc_pyutil/fastentrypoints.py, src/smc_pyutil/setup.py
see issue #2259
I should add that I haven't tested all the commands, but my compute0 test project seems to work well and I don't see a reason why there should be some failing while others work.
=> smc_pyutil: use fastentrypoints.py to speed up starting commands

src/smc-webapp/project_files.cjsx
minor aesthetic changes to make the files listing controls look better and more consistent
=> webapp/project-files: change links in files listing controls to buttons

src/smc-webapp/project_files.cjsx
... yet another approach, again, works for me in chrome and FF, this time I haven't seen any of the corner cases with overlapping elements. still, no idea what safari is capable of ;-)
=> Project files action bar flex layout

src/dev/docker/Dockerfile
I made some updates to the dockerfile
* python3-yaml
* locales-all (hence I think we do not have to generate any locale, at the bottom)
* some reformatting
tested: nope, I just edited it
=> dev/docker: some updates to the dockerfile

src/smc-project/jupyter/package.json, src/smc-project/jupyter/test/supported-kernels.coffee
in particular to get the fix for https://github.com/nteract/kernelspecs/issues/28
... I haven't tested it, this is more or less just a reminder that we need to update this.
=> project/jupyter: update nteract dependencies

src/smc-webapp/r_help.cjsx
=> add CoCalc API link

src/smc-hub/stripe/invoice.coffee, src/smc-util/theme.coffee
see attachment
[sagemathcloud-harald_schilly-receipt-2017-07-31-in_1AliifHUW2QmBRFouLMYT804.pdf](https://github.com/sagemathinc/cocalc/files/1233707/sagemathcloud-harald_schilly-receipt-2017-07-31-in_1AliifHUW2QmBRFouLMYT804.pdf)
=> hub/invoice: add address and taxid to the invoice/receipt

src/smc-webapp/billing.cjsx
Added it, and well, imho this also applies to wire transfers.
=> webapp/billing: paypal only above $50

src/smc-webapp/course/actions.coffee
Fixes #2323. @bryantpq Please test.
The problem may still occur on disconnects.
=> Close race condition hole in student creation

src/dev/project/README.md
added notes for getting cc-in-cc to start
=> clear out .npm, install forever

src/smc-project/kucalc.coffee
This simplifies this function and makes the project's memory info more accurate.
=> kucalc: only use sysfs memory.stat file to get rss, cache and total memory limits

src/smc-webapp/editor.html, src/smc-webapp/editor_history.coffee
Added html element and coffee code. Takes user to .snapshot directory where snapshots files are stored.
=> adding backups button to timetravel page

src/smc-project/directory-listing.coffee, src/smc-util/misc.coffee
hotfix for #2400
This needs a clear mind to think through this little change not causing other harm.
=> project: handling hash signs in URLs for directory listings

src/smc-util/misc.coffee, src/smc-webapp/project_settings.cjsx
this is one of the kucalc specific tasks, to expose more about project usage.
for testing, well, I hope the queries work and it needs to be run on ws1
=> webapp: expose uptime and total cpu usage in project settings

src/smc-webapp/course/actions.coffee
=> invitation from CoCalc, not SMC

src/smc-webapp/process-links.coffee
fixes issue #2437
since I saw it again, a 1 min fix
=> webapp: fix mailto link processing

src/smc-webapp/project_miniterm.cjsx
Fixes #2472 potentially? Should be safe anyways.
=> Stringify the error for miniterm

src/webapp-lib/doc/api.pug
Simple entry point list. Others may want to improve style.
=> list of entry points in api doc

src/smc-hub/share/listing.coffee, src/smc-hub/share/raw.coffee, src/smc-util/db-schema.coffee
this is more just for fun, and on top of the other PR earlier.
however, if we do this, we should add this index:
`CREATE INDEX IF NOT EXISTS project_id_2char ON public_paths (substring(project_id::text from 0 for 2));`
=> Hub raw dir index

src/smc-webapp/editor_archive.cjsx
one small step towards issue #1720
=> webapp: support for tgz archives and a hint in the error to use the terminal

src/smc-util/message.coffee
=> correction to api doc for updating project upgrades

src/smc-webapp/share/README.md, src/smc-webapp/share/page.cjsx, src/smc-webapp/share/public-paths-browser.cjsx, src/smc-webapp/share/top-bar.cjsx
Refactor TopBar
Make listing headers stay in place as you scroll down
=> Share Server Changes

src/smc-webapp/package.json, src/smc-webapp/project_files.cjsx, src/smc-webapp/r_misc.cjsx
Highlight when clicking on text
Copy to clip board when clicking on button
=> Make share link copy to clipboard

src/smc-hub/share/router.cjsx, src/smc-hub/share/util.coffee, src/smc-webapp/share/page.cjsx
this adds the "gtag" for google analytics to share pages. entirely optional ...
=> share: adding google analytics from the default location

src/smc-webapp/last.coffee
not sure what this does yet, but it breaks for iframe embedding.
=> webapp: hotfix for #2542

src/smc_sagews/smc_sagews/tests/test_unicode.py
=> add test cases for false positive implicit mult error

src/webapp-lib/doc/jupyter-notebook.pug
among other things, I didn't capitalize "notebook" unless it was in a heading or title
=> minor wording changes

src/webapp-lib/doc/software-executables.pug
=> static/software: add id attributes to h3 headers

src/smc-webapp/landing_page.cjsx
variable was picked from the wrong file
=> webapp: fix info link #2609

src/smc-hub/stripe/invoice.coffee
Makes room for an invoice description on receipts.
=> Add receipt description

src/smc-webapp/markdown.coffee
=> webapp: attempt at fixing #2619

src/smc-util/message.coffee
API doc update for #2627. And put in link to API tutorial on share server.
=> update doc for change_password, link to API tutorial

src/smc-webapp/course/assignments_panel.cjsx, src/smc-webapp/course/handouts_panel.cjsx, src/smc-webapp/course/store.coffee, src/smc-webapp/course/styles.coffee
The goal here is to make progress information about the assignment steps more visible to the teacher. The status string is similar to how it looks like for handout distributions and the button is green when all are done. The following screenshot shows assignment steps in various progress states.
=> course assignment progress indicators

src/smc-util/db-schema.coffee
This is a bare minimum step 1 for #2684 and would allow us to at least record any issues. It clearly doesn't resolve #2684 ...
=> db: add field for problems with a specific email address

src/smc-webapp/course/actions.coffee
The idea here is to write this due-date file only once when copying out an assignment. That's why there is a new `copy_assignment_create_due_date_file` and it is used in two places. Either for single student distributions, or when iterating over all students. It also checks if it was written correctly, which is motivated by #2694.
=> webapp/course: when assigning to students, create the due date file only once

src/smc-util/misc.coffee, src/smc-util/test/misc-test.coffee, src/smc-webapp/project_settings.cjsx
more cosmetics. 0.17 hours is really ugly.
=> webapp/project settings: render timeout quota more human readable

src/smc-webapp/project_files.cjsx
=> add wiki link to sharing text

src/smc-webapp/_projects_nav.sass, src/smc-webapp/projects.cjsx, src/smc-webapp/projects_nav.cjsx
Adjusts some styles so that the dropdown menu on mobile isn't totally broken.
=> Fix mobile ui

src/package-lock.json, src/package.json, src/webpack.config.coffee
fixing #2738 by removing that dependency.
=> webpack: removing copy-webpack-plugin

src/smc-webapp/projects.cjsx, src/smc-webapp/r_misc.cjsx, src/smc-webapp/r_upgrades.cjsx, src/smc-webapp/upgrade_restart_warning.cjsx
Add an in place adjustor to the Upgrades Page.
=> Add in place adjustor

src/smc-webapp/collaborators/add-to-project.cjsx
issue #2749
The main question for me is:
A. [ ] this is a parser error
B. [ ] never put comments next to control statements inside of nested ifs when cjsx is involved
=> fix syntax issue leading to leaking comment into cjsx 

src/smc-project/kucalc.coffee
This just exposes a small detail that could help detecting memory issues in a project.
=> kucalc/project: add oom kill count for project's cgroup

src/smc-webapp/package-lock.json, src/smc-webapp/r_upgrades.cjsx
Change as suggested. Click upgrades to edit.
=> Remove clutter

src/smc-hub/client.coffee
Fixes case when failed subscriptions would count against the user's coupon count.
@DrXyzzy can you test this?
=> Wait until success to update coupon use

src/smc-webapp/course/students_panel.cjsx
=> course: open new window when clicking on student email address

src/smc-webapp/billing.cjsx
=> Add coupon option to student pay

src/smc-webapp/course/common.cjsx, src/smc-webapp/course/common/FoldersToolBar.cjsx, src/smc-webapp/r_misc.cjsx
Don't show stale results if new search was submitted while waiting for the last search
Clean up some course code
Fixes #2797
=>  Fix search pending animation

src/smc-util/db-schema.coffee
=> db: add projects.compute_image field to specify which one to run in kucalc

src/dev/project/start_webpack.py, src/install.py, src/scripts/smc-install-all
I found 4 places, where it makes sense to strategically call git to initialize and update submodules.
=> webapp install: strategically calling git to initialize submodules

src/smc_pyutil/smc_pyutil/templates/linux/default.tex
=> Lua template

src/package.json, src/smc-hub/stripe/plans.coffee, src/smc-hub/stripe/sync.coffee, src/smc-util/upgrade-spec.coffee, src/smc-webapp/billing.cjsx, src/smc-webapp/r_upgrades.cjsx, src/w, src/webpack.config.coffee
=> add new workshop subscription/plan, which is 1 week

src/smc-webapp/customize.cjsx, src/smc-webapp/landing_page.cjsx
here is how it looks on my screen
=> webapp/landingpage: small changes to the trial info box

src/smc-webapp/collaborators/add-to-project.cjsx
Ref: #2873 
Tested in cc-in-cc build.
=> change collaborator button Invite -> Add

src/smc-hub/test/postgres/postgres-test.coffee
tiny fix for one postgres test. not entirely sure about the additional fields. I bet they were added during the last year, that's all.
=> hub/test: fixing one postgres test

src/smc-hub/email.coffee
Minor changes to the welcome email.
=> Change welcome email

src/smc-webapp/mobile_app.cjsx
=> use account icon if logged in, and center the labels next to the icons -- on mobile

src/smc-webapp/editor_jupyter.coffee
I haven't tested it, but I think it's save to merge.
=> classical jupyter: fix broken nbconvert command

src/smc_pyutil/smc_pyutil/ipynb2sagews.py
=> no jupyter bridge for sage kernels

src/smc-webapp/project_files.cjsx
=> disable move,compress,rename when inside snapshots directory

src/smc-webapp/project_files.cjsx
some style/rearrangements on saturday evening  … also motivates users to look for a thing called "library" :snake:
=> webapp/files: make first steps a subtle banner at the bottom

src/smc-webapp/frame-editors/latex-editor/actions.ts, src/smc-webapp/frame-editors/latex-editor/pdfjs-page.tsx
=> latex: force build triggers a force reload of the pdf preview 

src/smc-webapp/frame-editors/latex-editor/actions.ts
=> remove possibly misleading part of a latex error message

src/smc-webapp/frame-editors/latex-editor/build-command.tsx
=> use syncdb file and store correctly

src/smc-webapp/frame-editors/code-editor/spell-check.ts
ref #3030
...and prep for spellchecking knitr related file formats
=> webapp/code editor spellcheck: canonicalize filename extension to select correct mode

src/smc-util/misc.coffee, src/smc-webapp/project_actions.ts, src/smc-webapp/project_search.cjsx
=> initial fix

src/smc-webapp/jupyter/actions.ts
=> cache kernels by project, not globally in case of custom kernels

src/smc-webapp/jupyter/actions.ts
ref #3050, which also explains how to test
=> webapp/jupyter: fix completion after pressing a key

src/smc-webapp/course/actions.ts, src/smc-webapp/course/assignments_panel.tsx, src/smc-webapp/course/common.tsx, src/smc-webapp/course/main.tsx, src/smc-webapp/course/store.ts, src/smc-webapp/course/students_panel.tsx, src/smc-webapp/course/util.ts, src/smc-webapp/widget-markdown-input/main.tsx
Persist grading assignments and fix #3049.
=> Persist grading

src/smc-webapp/project_settings.cjsx
=> consistent icons

src/smc-webapp/app-framework/TypedMap.ts, src/smc-webapp/app-framework/examples/example_TypedMap.ts, src/smc-webapp/course/assignments_panel.tsx, src/smc-webapp/course/store.ts
Removes `__guard__` from `assignment_panel.tsx`. 
Also comes with a nice little update to TypedMap for convenience. See changes in `example_TypedMap.ts`
=> Course typing

src/smc-webapp/jupyter/cell-input.tsx, src/smc-webapp/jupyter/cell-list.tsx, src/smc-webapp/jupyter/cell-output-message.tsx
I have troubles starting my hub, which started a day ago when I worked on these nbgrading aspects. Today, it also fails when I'm on master. This here essentially introduces 3 lines (the rest is formatting).
The errors I always saw are below. Does this imply that hubs are broken right now? I've also no clear idea what did trigger this (I wished I had, it could be related to some changes how the compilation is conducted)
```
2018-08-16T11:08:28.856Z - debug: PostgreSQL.SyncTable(table='compute_servers')._init: "retry_until_success() -- success"
2018-08-16T11:08:28.856Z - debug: compute server created
2018-08-16T11:08:28.870Z - debug: initializing express http server
2018-08-16T11:08:28.870Z - debug: MATHJAX_URL =  /14eed217-2d3c-4975-a381-b69edcb40e0e/port/56754/static/mathjax-2.7.4/MathJax. …
```
=> jupyter/hub: add 3x `declare const $: any;` to make the hub start again

src/smc-util/compute-images.coffee
The real question for this PR is how to actually describe this.
=> project image: introduce new "stable" with fixed timestamp image

src/smc-webapp/project_settings.cjsx
with that, the project hide/del dialog looks like this:
=> webapp/projects: add explicit note about deleting/removing sensitive data

src/webapp-lib/doc/r-statistical-software.pug, src/webapp-lib/font-awesome
changes:
- remove superflous colon in R page
- delete a broken symlink
@DrXyzzy maybe you could review this and add any other changes you have on our mind?
=> small changes static R page

src/webapp-lib/doc/jupyter-notebook.pug
trivial addition, just like on the R page
=> add "start free" boilerplate text at the bottom

src/smc-project/lean/lean.ts, src/smc-project/lean/server.ts, src/smc-webapp/frame-editors/frame-tree/title-bar.tsx, src/smc-webapp/frame-editors/lean-editor/actions.ts, src/smc-webapp/frame-editors/lean-editor/editor.ts, src/smc-webapp/frame-editors/lean-editor/lean-messages.tsx
main complication so far: is that lean api somewhere documented?
=> webapp/lean: restart lean server instance via a button

src/smc-webapp/frame-editors/code-editor/codemirror-gutter-markers.tsx
=> webapp/frame: codemirror lineInfo for an unkown line gives null

src/smc-webapp/project_actions.ts
Ref #3223
The fix I made is based on pure speculation about what's going on…
=> webapp/file listing: special case where there is no error but also no file listing

src/smc-webapp/project_actions.ts
NaN === NaN does not evaluate to true.
we need to use Number.isNaN
=> fix NaN comparison

src/smc-webapp/course/actions.ts, src/smc-webapp/project_log.cjsx, src/smc-webapp/projects.cjsx
Logs removal of collaborators. 
1. Add a user to a project
1. Remove that user
1. See that the action was logged
None
=> Add removal of collaborators to project log

src/webapp-lib/policies/_sagemath_privacy_policy.html, src/webapp-lib/policies/privacy.pug
Update to our latest privacy policy without Privacy Shield.
1. Navigate to our privacy policy page ([base_url]/policies/privacy.html)
1. See that the date has been updated.
None
=> Update to pre-privacy-shield

src/smc-webapp/r_help.cjsx
Add blog link to "Core developers" text in i About page.
1. Build cc-in-cc
1. Login to test build
1. In dev project, make test account admin
1. In test build, use admin tab to enable business settings
1. View i About
1. Verify that link goes to blog posting about [core team](http://blog.sagemath.com/cocalc/2018/09/10/where-is-cocalc-from.html)
=> link to "meet the team" blog

src/smc-util/misc.coffee
* I don't know how to reproduce the problem
* issue #3254
Is this checklist for me or the reviewer?
=> webapp: fix strip_date by not specifying a locale at all

src/smc-webapp/r_account.cjsx
1. Open account settings
1. Click account deletion
Temporary prevention for #3243
=> Remove account deletion temporarily

src/webapp-lib/policies/terms.pug
=> policies: terms of service typos

src/smc-webapp/course/actions.ts, src/smc-webapp/course/main.tsx, src/smc-webapp/course/sync.ts
Decided to set the default to allow arbitrary collaboration.
Correctly moved initialization to sync.ts
Add comment about race condition
1. Create a new course. 
1. Go to the configuration panel
1. See that the check box is actually checked
=> Fix default course arbitrary collaborators setting

src/smc-webapp/frame-editors/code-editor/actions.ts, src/smc-webapp/frame-editors/frame-tree/frame-tree.tsx, src/smc-webapp/frame-editors/frame-tree/register.ts, src/smc-webapp/frame-editors/register.ts, src/smc-webapp/frame-editors/terminal-editor/register.ts, src/smc-webapp/frame-editors/x11-editor/actions.ts, src/smc-webapp/frame-editors/x11-editor/editor.ts, src/smc-webapp/frame-editors/x11-editor/register.ts, src/smc-webapp/frame-editors/x11-editor/window-tab.tsx, src/smc-webapp/frame-editors/x11-editor/x11.tsx, src/smc-webapp/frame-editors/x11-editor/xpra-client.ts, src/smc-webapp/package.json
=> working on xpra integration with cocalc

src/smc-util-node/execute-code.coffee, src/smc-util-node/test/misc_node-test.coffee
This is essentially a tiny bugfix and some tests to nail down the semantics. I have problems using that function, because `err_on_exit : false` swallows more general errors, like not being able to run the exec at all (e.g. when it doesn't exist). I think `err_on_exit` should only be concerned with the actual output of the executable, after it ran. Hence there is a change in semantics.
In the usage case of `tiny`, the main problem with the current function is that exit code 1 is fine in the usual (working) case, but it is also 1 when that tool doesn't exist. With that semantic change above it would become plain obvious that there is something wrong on a more general level.
=> misc node/execute code: add tests and change semantics of err_on_exit

src/smc-webapp/project/websocket/connect.ts
The goal of this here is improve the primus websocket initialization. It adds a check to what is downloaded, before it is globally executed. Another detail I figured out is that in my cc-in-cc dev project the situation of when the project did actually start up until the listing appears does improve. I think that's because of properly throwing errors (the ones in the global evaluation before aren't caught at all) and it also waits for the explicit global evaluation.
1. open at least two projects, to check if the listing are different -- bad timing could cause a reuse of the same primus socket across projects
2. do things like: stop project, refresh browser, start it and check what the console says. in the best case szenario, the attempt to connect works quickly and the listing appears …
=> project/websocket init: check what gets globally executed 

src/webapp-lib/policies/_sagemath_privacy_policy.html
This is the October 29th update for the privacy policy.
1. static pages build, although it's an 100% html-only change.
=> update privacy policy (version 2018-10-29)

src/smc-webapp/project_store.ts
this masks *.nb.html files derived from *.rdm files 
1. see https://github.com/sagemathinc/cocalc/pull/3318
=> webapp/rmd file listing: mask *.nb.html

src/smc-util/misc.js, src/smc-util/test/misc-test.coffee, src/smc-webapp/course/students_panel.tsx
The goal of this is to make it easier to copy/paste student email addresses from a spreadsheet. Here are a couple of screenshots to explain what I mean.
libreoffice calc on my desktop:
then paste this into the textarea form (it's possible to expand the area, by default it is 2 lines)
that's how it looks with a slightly smaller box and the parsed/queried addresses in the confirmation list
Regarding the code changes, the form is a bit different, because just changing the field type caused overlapping controls.
1. misc: `./src/smc-util$ export NODE_ENV=mocha-test && SMC_TEST=true node_modules/.bin/mocha --reporter ${REPORTER:-progress} test/misc-test.coffee`
I've noticed that two unrelated tests fail for `misc.map_limit`. Which is weird, because the code is clearly not doing what the tests …
=> course: add students as a multiline string

src/smc-project/index.js
just by browsing through lgtm I found this
https://lgtm.com/projects/g/sagemathinc/cocalc/snapshot/bb021b94cb910309f5cb4f6de38cd64e0fa11190/files/src/smc-project/index.js?sort=name&dir=ASC&mode=heatmap#x4883b628575f574e:1
probably dead code, though (but, it's referenced from the package.json file, as the main entry point)
1.
1.
1.
Front end:
=> lgtm found this

.travis-test.sh, .travis.yml
=> testing: tweaking travis

src/smc-webapp/r_account.cjsx
See #3379
I didn't test ... affects accounts without an email address.
#3379
Front end:
=> webapp: email_address not necessarily defined -- #3379

src/smc-webapp/file-associations.coffee
First step towards supporting Rust. I think the screenshot below tells it all ...
1. https://doc.rust-lang.org/stable/rust-by-example/hello.html
Front end:
=> webapp: rust .rs files + an icon that looks a bit like the rust logo

src/smc-webapp/projects/project-row.tsx
I don't know what this function is doing, but there are problems. See #3442.
Could we maybe add a few lines explaining what this is doing?
I don't know how to test this
#3442
Front end:
=> webapp: account for cleared state in ProjectRow

src/smc-webapp/tasks/actions.coffee
=> webapp/tasks: moving help page

src/webapp-lib/doc/r-statistical-software.pug
=> static/r: link movd to doc

src/smc-hub/email.coffee
=> doc: Troubleshooting page moved

src/smc-util/upgrade-spec.js
=> upgrades: add stubs for ephemeral_state and ephemeral_disk

src/package.json
this just checks in some changes npm does during an install step
there is nothing to test
Front end:
=> package.json: just formatting, npm modifies it

src/smc-webapp/project_warnings.cjsx
=> webapp/projects: memory/oom page moved

src/misc.py
* sha is deprecated in favour of hashlib
* socket was imported twice
1.
1.
1.
Front end:
=> fixing imports

src/smc_sagews/smc_sagews/sage_salvus.py
mainly imports, all found by lgtm
1.
1.
1.
Front end:
=> various fixes

src/smc-hub/email.coffee
use https for sagemath.org and jupyter
1.
1.
1.
Front end:
=> 3 more https links

src/scripts/zvol_storage.py
* remove unused import
* convert one print to py3
* replace __cmp__ by __eq__ and __ne__
* rmove one unused assignement
1.
1.
1.
Front end:
=> a few changes

src/smc-hub/client.coffee, src/smc-hub/local_hub_connection.coffee, src/smc-hub/postgres-server-queries.coffee, src/smc-hub/postgres/syncdoc-history.ts, src/smc-hub/postgres/types.ts, src/smc-project/client.coffee, src/smc-project/http-api/server.ts, src/smc-project/http-api/test.js, src/smc-project/local_hub.coffee, src/smc-project/package.json, src/smc-project/raw_server.coffee, src/smc-util/client.coffee, src/smc-util/message.js, src/smc-webapp/api-key.cjsx
=> Syncdoc history project API export

src/smc-webapp/r_misc/index.cjsx
=> one-letter typo

src/smc-webapp/project_warnings.cjsx
Shorten and simplify the out of memory message.
=> Simplyify OOM message

src/scripts/create_unix_user.py
and python3 print
1.
1.
1.
Front end:
=> remove unused import

src/scripts/gitinfo
plus use python3 prints
1.
1.
1.
Front end:
=> fix one syntax error

src/smc-webapp/frame-editors/x11-editor/launcher.tsx
I'm assuming positive review and I'll merge when it is available.
1.
1.
1.
Front end:
=> webapp/x11: add scilab button

src/dev/laptop/util.py, src/dev/project/info.py, src/dev/smc/start_postgres.py
=> pyflakes py3 fixes in dev/

.travis-test.sh, .travis.yml, src/install.py, src/smc-hub/scripts/hub, src/webapp-lib/term/color_themes.js, src/webapp-lib/term/compile
This fixes a little bit the test setup and since it updates to python 3, there are also a couple of compatibility fixes.
1.
1.
1.
Front end:
=> travis: pip-install missing python packages

src/smc-webapp/user-tracking.ts
this is just an extraneous line
1.
1.
1.
Front end:
=> webapp: comment out console line in user-tracking

src/smc-webapp/file-associations.ts
see screenshots, not much else to say
1.
1.
1.
Front end:
=> webapp: erlang files in codemirror

src/smc-hub/api/handler.coffee, src/smc-hub/test/api/apikey.coffee
This tightens the API endpoint.
The only test I made is to run
SMC_DB_RESET=true SMC_TEST=true node_modules/.bin/mocha --reporter progress test/api/apikey.coffee 
Front end:
=> hub/api: require valid api key and not-banned account for all calls

src/smc-util/misc2.ts, src/smc-util/package.json, src/smc-util/test/misc-test.coffee
this detects a wide variety of URLs
the changes are checked by additional tests
Front end:
=> misc/validate name: harden URL detection

src/webapp-lib/_base.pug, src/webapp-lib/doc/_style.sass, src/webapp-lib/doc/features.pug, src/webapp-lib/doc/index.pug, src/webapp-lib/doc/jupyter-notebook.pug, src/webapp-lib/doc/latex-editor.pug, src/webapp-lib/doc/linux-terminal.pug, src/webapp-lib/doc/python.pug, src/webapp-lib/doc/r-statistical-software.pug, src/webapp-lib/doc/software-executables.pug, src/webapp-lib/doc/x11.pug
work in progress to improve the static landing pages (add more, etc.)
below is how it looks in the mobile simulator
1.
1.
1.
Front end:
=> static page improvements

src/smc-util/message.js
No change to executable code.
1.
1.
1.
Front end:
=> example email address edited in comments

src/webapp-lib/doc/linux-terminal.pug
This expands a little bit about terminals. It also includes a screenshot for running a database, with a jupyter notebook side-by-side with a terminal :-)
https://storage.googleapis.com/cocalc-extra/terminal-jupyter-postgresql.png
1.
1.
1.
Front end:
=> landing: terminal content

src/smc_pyutil/smc_pyutil/templates/linux/default.tex
=> link to sagemath.org for SageTeX documentation

src/smc-webapp/project/file-listing/file-listing.tsx
Fixes #3928 
1. Open a project, make your browser window very thin, and refresh your browser and wait for the directory listing to appear.
2. Make your browser window wide again.
3. It looks normal after 80ms
Front end:
=> Clear computed size cache on window resize

src/smc-util/message.js
correct a 1-word typo in the comments for the API
1.
1.
1.
Front end:
=> api uses POST

src/webapp-lib/doc/latex-editor.pug
This mainly mentions the unlimited number of collaborators and some other minor tweaks.
1. latex page builds, that's all to check
Front end:
=> Landing page latex collaborators

src/smc-webapp/project_actions.ts, src/smc-webapp/project_log.cjsx, src/smc-webapp/smc-dropzone.cjsx
log file uploads, pretty straight forward
1. upload a file and see a clickable entry to open it
#3909
Front end:
=> webapp: log project uploads

src/webapp-lib/policies/_wcag_statement.html, src/webapp-lib/policies/accessibility.md, src/webapp-lib/policies/accessibility.pug
1. add `src/webapp-lib/policies/_wcag_statement.html`
1. increase heading level in `src/webapp-lib/policies/accessibility.md`
1. include WCAG statement before VPAT in `src/webapp-lib/policies/accessibility.pug`
1.
1.
1.
Front end:
=> prepend WCAG accessibility statement

src/smc-webapp/course/common.tsx
1-line change - link in course Assignments tab under "What happens when I assign again?" moved to point to docs.
1.
1.
1.
Front end:
=> move link from wiki to doc

src/smc-hub/mentions/handle.ts
Is this testable in a dev project? In any case, the TS compiles and the change is pretty minimal.
1. ?
Front end:
=> Add description to mentions email

src/smc-util/schema.js, src/smc-util/upgrade-spec.js, src/webapp-lib/policies/pricing.pug, src/webpack.config.js
=> a new premium course pricing plan

src/package.json, src/smc-webapp/app-framework.ts, src/smc-webapp/app-framework/TypedMap.ts, src/smc-webapp/app-framework/examples/example_stores.ts, src/smc-webapp/course/main.tsx, src/smc-webapp/frame-editors/code-editor/actions.ts, src/smc-webapp/frame-editors/terminal-editor/connected-terminal.ts, src/smc-webapp/frame-editors/terminal-editor/terminal-manager.ts, src/smc-webapp/landing-actions.ts, src/smc-webapp/notifications/mentions/init.ts, src/smc-webapp/project/file-listing/directory-row.tsx, src/smc-webapp/project/file-listing/file-row.tsx, src/smc-webapp/project_store.ts, src/smc-webapp/projects/project-row.tsx, src/smc-webapp/stopwatch/register.ts, src/smc-webapp/tracker/index.ts, src/smc-webapp/widget-markdown-input/main.tsx
Upgrades to TS 3.6
Some types lost type inference and became Unknown it seems. Explicitly calling the function seems to work.
1. Opened and edited a file
1. Changed account settings
Front end:
=> Upgrade typescript 3.6

src/webapp-lib/_base.pug, src/webapp-lib/policies/index.pug, src/webapp-lib/policies/thirdparties.pug
just moving policies/third parties from wiki page to policies page
I added more links and further explanations, though
1.
1.
1.
Front end:
=> moving policies/third parties from wiki page to policies page

src/scripts/cocalc-dirs.sh, src/scripts/smc-install-all
this runs some tasks for `npm run make` in parallel. 
1.
1.
1.
Front end:
=> npm run make: parallelize installation

src/install.py
This should fix docker-build.
Let's just wait until travis-ci finishes … well, travis is :green_heart: 
Front end:
=> install: fix executor to make cocalc-docker build

src/smc-webapp/frame-editors/latex-editor/actions.ts
well, see #4148
1.
1.
1.
#4148
Front end:
=> webapp/latex: do not set an output if there is none -- 

src/smc-webapp/frame-editors/generic/client.ts, src/smc-webapp/frame-editors/latex-editor/actions.ts, src/smc-webapp/frame-editors/latex-editor/bibtex.ts, src/smc-webapp/frame-editors/latex-editor/pythontex.ts, src/smc-webapp/frame-editors/latex-editor/sagetex.ts
=> webapp/latex: fix pythontex, sagetex and bibtex -- #4147

src/smc-webapp/course/configuration_panel.tsx
See #4143.
Only change is the descriptive text in course Configuration under the checkbox for Collaborator policy / Allow arbitrary collaborators.
Tested build in cc-in-cc. 
1.
1.
1.
Front end:
=> alter wording per issue 4143

src/smc-util/message.js
Add 1 line of doc to message.js.
Tested cc-in-cc build.
1.
1.
1.
Front end:
=> add index entry for get_api_key

src/smc_sagews/smc_sagews/sage_salvus.py, src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
simple update
1.
1.
1.
Front end:
=> sagews: update julia to 1.2

src/smc-webapp/course/assignments/actions.ts, src/smc-webapp/course/store.ts
this is just to make typescript happy
1.
1.
1.
Front end:
=> Fix 3 TS errors

src/.eslintrc.js, src/smc-hub/auth.coffee, src/smc-hub/client.coffee, src/smc-hub/client/create-account.ts, src/smc-hub/password.coffee, src/smc-hub/postgres-server-queries.coffee, src/smc-hub/postgres/account-queries.ts, src/smc-hub/sign-in.coffee, src/smc-util/client.coffee, src/smc-util/message.js, src/smc-util/theme.js, src/smc-webapp/account/actions.ts, src/smc-webapp/account/sign-out.tsx, src/smc-webapp/account/store.ts, src/smc-webapp/account/types.ts, src/smc-webapp/account_page.cjsx, src/smc-webapp/client_browser.coffee, src/smc-webapp/desktop_app.cjsx, src/smc-webapp/project_page.cjsx, src/smc-webapp/projects.cjsx, src/smc-webapp/projects_nav.cjsx, src/smc-webapp/r_account.cjsx, src/smc-webapp/share/top-bar.tsx, src/smc-webapp/support.cjsx, src/webapp-lib/_base.pug
something that can be released ASAP
=> Anonymous stable

src/.eslintrc.js, src/smc-hub/auth.coffee, src/smc-hub/client.coffee, src/smc-hub/client/create-account.ts, src/smc-hub/password.coffee, src/smc-hub/postgres-server-queries.coffee, src/smc-hub/postgres/account-queries.ts, src/smc-hub/sign-in.coffee, src/smc-util/client.coffee, src/smc-util/message.js, src/smc-util/theme.js, src/smc-webapp/account/actions.ts, src/smc-webapp/account/sign-out.tsx, src/smc-webapp/account/store.ts, src/smc-webapp/account/types.ts, src/smc-webapp/account_page.cjsx, src/smc-webapp/client_browser.coffee, src/smc-webapp/desktop_app.cjsx, src/smc-webapp/project_page.cjsx, src/smc-webapp/projects.cjsx, src/smc-webapp/r_account.cjsx, src/smc-webapp/support.cjsx, src/webapp-lib/_base.pug
Full support for anonymous accounts, which either get automatically deleted or transition to normal accounts.
=> Anonymous accounts.

src/smc-webapp/r_upgrades.cjsx
This is straight forward. I wonder what other duplications like that we have right now, though …
1.
1.
1.
Front end:
=> remove duplicated DedicatedVM entry

src/smc-webapp/share/config/config.tsx
One-word edit under "How it works" when "Share" is clicked after selecting a file in Files tab.
1.
1.
1.
Front end:
=> edit wording

src/smc-project/configuration.ts
trivial fix for https://github.com/sagemathinc/cocalc/issues/4364
1.
1.
1.
Front end:
=> project/config: set PATH var via env option

src/smc-webapp/_account-button.sass, src/smc-webapp/_antd_fix.sass, src/smc-webapp/account-button.tsx, src/smc-webapp/desktop_app.cjsx, src/smc-webapp/index.sass
=> Change account button to dropdown

src/webapp-lib/policies/_sagemath_privacy_policy.html, src/webapp-lib/policies/privacy.pug
- Uncomment references to Privacy Shield that were temporarily commented out for compliance reasons.
- Incorporate changes required by privacyshield.gov.
- Remove effective date from `src/webapp-lib/policies/privacy.pug` so updates only have to touch one file, namely `src/webapp-lib/policies/_sagemath_privacy_policy.html`.
Hal to notify privacyshield.gov when these changes are live.
1.
1.
1.
Front end:
=> Privacy shield 2020 02

src/webapp-lib/policies/thirdparties.pug
just to make that page match reality
1.
1.
1.
Front end:
=> mention backblaze in the list of third parties

src/smc_sagews/smc_sagews/sage_parsing.py
I used `partial_sieve_function?` for testing
Front end:
=> sagews: fix obj? introspection for 9.0 and some code cleanup

src/smc_pyutil/smc_pyutil/ipynb_to_pdf.py
see #4476
ipynb file with a space in the filename
Front end:
=> pyutil/cc-ipynb-to-pdf: make it work with spaces in filenames 

src/smc-hub/open-cocalc-server.ts, src/webapp-lib/_base.pug, src/webapp-lib/index.pug
basically, open the index.html page and check what's there with our without an account creation token
Front end:
=> index page: remove "open-source" and show anon button if there is no account creation token

src/smc-webapp/_misc_page.sass, src/smc-webapp/client_browser.coffee
theme the idle banner, make the text below white and say the site name
1.
1.
1.
Front end:
=> tweak idle banner

src/smc-webapp/project/trial-banner.tsx
* This tries to make the steps of (1) buying and (2) applying more explicit. 
* there is also a silly off-by-60 mistake :facepalm: 
1.
1.
1.
Front end:
=> Trial banner: be explicit about buying and upgrading

src/smc-webapp/account/account-page.tsx
little hotfix, that's all
1.
1.
1.
Front end:
=> webapp/account: put sign out button on top

src/smc-hub/postgres/site-license/search.ts
=> hotfix to make manage compile again

.travis-test.sh
fixes one set of tests, but the more general tests are not ok
nothing to test
Front end:
=> travis: build color scheme + primus

src/smc-webapp/account/account-page.tsx, src/smc-webapp/account/delete-account.tsx, src/smc-webapp/account/settings/account-settings.tsx, src/smc-webapp/account/sign-out.tsx
just cosmetics. 
1.
1.
1.
Front end:
=> remove red color from delete account and change sign out to use primary

.travis-test.sh, src/smc-webapp/package.json, src/smc-webapp/r_misc/__tests__/__snapshots__/error-display.test.tsx.snap, src/smc-webapp/r_misc/__tests__/__snapshots__/number-input.test.tsx.snap, src/smc-webapp/r_misc/__tests__/__snapshots__/uncommited-changes.test.tsx.snap, src/smc-webapp/r_misc/__tests__/number-input.test.tsx
some progress towards making tests work again -- or weed them out
what's I would wish to work is https://github.com/sagemathinc/cocalc/issues/4570 ... which looks like there was one small change that causes a chain of tests to fail.
1.
1.
1.
Front end:
=> fix travis testing

src/smc-hub/hub.coffee
this just moves the metrics initialization to a separate function to use it for the hub and for the landing setup
1.
1.
1.
Front end:
=> hub: instrument hub-landing

src/smc-project/gitconfig.ts
this is just a minor tweak, such that hidden files don't show up. makes more sense if you really want and entire project to be a git repo
1.
1.
1.
Front end:
=> project/gitconfig: remove hidden files and explain that users can edit the file

src/smc-webapp/desktop_app.cjsx
for anonymous usage, a bit more info about what cocalc is doing. only cosmetics.
1.
1.
1.
=> webapp/anon: this shows a short info about what is going on during loading

src/smc-util/compute-images.js, src/smc-webapp/project/settings/project-control.tsx
* more software environments
* don't show them in a random order
* project's drop down menu shows them
* 20.04 is starting up, but not working well yet
Front end:
=> project: more compute images

src/smc-webapp/admin/account-creation-token.tsx
type + wording
1.
1.
1.
Front end:
=>  last → least + wording

src/smc-hub/postgres-server-queries.coffee
if there is already a challenge token, keep it instead of creating a new one and hence invalidating the existing one
* creating an account creates a new token
* sending a verification email keeps the token as it is
Front end:
=> hub/verify email: keep existing token

src/smc-hub/email.ts
=> hub/email: fix broken link

src/smc-hub/analytics.ts, src/smc-hub/package-lock.json, src/smc-hub/package.json, src/smc-util/db-schema/site-defaults.ts
* if you do no set any DNS, this falls back to cocalc.com as a default (was an oversight!)
*  and it also takes care if you enter something that is not "ok" ... tweaking the types with questionsmarks makes this situation clear to TS
hub starts, I  did also delete my entry via `delete from server_settings where name = 'dns';`
none, but the stacktrace is
```
TypeError: Cannot read property 'domain' of null
at /cocalc/src/smc-hub/analytics.ts:269:49
at Layer.handle [as handle_request] (/cocalc/src/smc-hub/node_modules/express/lib/router/layer.js:95:5)
at next (/cocalc/src/smc-hub/node_modules/express/lib/router/route.js:137:13)
at cors (/cocalc/src/smc-hub/node_modules/cors/lib/index.js:188:7)
at /cocalc/src/smc-hub/node_modules/cors/lib/index.js:224:17
at origin …
```
=> hub/analytics: fix bad DNS

src/smc-webapp/frame-editors/latex-editor/build.tsx
this is a follow up. it deals with the case when there is an error, to open that log where there is an error. there is the case where you have an error, fix it (no error), switch tabs, and then make yet again an error. once again I think it's neat to open the tab with the error, because that's what you have to take action on. 
1.
1.
1.
Front end:
=> webapp/latex: fix changing log tabs when there is an error

src/smc-project/browser-websocket/api.ts, src/smc-project/sync/listings.ts
fixing broken imports
1.
1.
1.
Front end:
=> project: fix imports to make it compile again

src/smc-hub/client.coffee, src/smc-hub/postgres-server-queries.coffee, src/smc-hub/postgres/collab.ts, src/smc-hub/postgres/types.ts, src/smc-util/db-schema/project-invite-tokens.ts, src/smc-util/message.js, src/smc-webapp/account/settings/account-settings.tsx, src/smc-webapp/admin/registration-token.tsx, src/smc-webapp/app/page.tsx, src/smc-webapp/client/anonymous-setup.ts, src/smc-webapp/client/project-collaborators.ts, src/smc-webapp/collaborators/handle-project-invite.ts, src/smc-webapp/collaborators/new-collabs.tsx, src/smc-webapp/collaborators/project-invite-tokens.tsx, src/smc-webapp/project/page/file-tab.tsx, src/smc-webapp/projects/create-project.tsx, src/smc-webapp/projects/load-all.tsx, src/smc-webapp/projects/project-row.tsx, src/smc-webapp/projects/projects-page.tsx, src/smc-webapp/projects/token.tsx
This will be https://github.com/sagemathinc/cocalc/issues/885
=> Project invite token -- #885

src/package-lock.json, src/package.json, src/smc-webapp/package-lock.json, src/smc-webapp/package.json, src/webapp-lib/resources/package-lock.json, src/webapp-lib/resources/package.json
Reverts sagemathinc/cocalc#4740
=> Revert "katex 0.12.0"

src/package-lock.json, src/package.json, src/smc-hub/open-cocalc-server.ts, src/smc-webapp/misc/resource-links.ts, src/smc-webapp/package-lock.json, src/smc-webapp/package.json, src/webapp-lib/_inc_head.pug, src/webapp-lib/resources/package-lock.json, src/webapp-lib/resources/package.json, src/webapp-lib/resources/setup.py, src/webpack.config.js
=> Katex 0.12 Take 2

src/smc_pyutil/smc_pyutil/smc_compute.py
=> pyutil: fix uuid for python3

src/smc-webapp/jupyter/iframe.ts
This is a quick idea how to plot Altair. It detects altair plots and wraps them in an iframe. see #4468
1. I ran the altair code
1. There is a very slim chance that the heuristic also wraps/mangles other plots. In any case, I checked 3D plots in sage 8.9 (jmol) and 9.1 (that canvas thing).
#4468
Front end:
=> jupyter: wrap altair in an iframe

src/smc-hub/postgres-server-queries.coffee
=> hub/email verify: only reuse token if email address did  not change

src/smc-webapp/course/export/actions.ts
@williamstein I'll make this live 
1.
1.
1.
Front end:
=> course: fix #4825

src/smc-project/package-lock.json, src/smc-project/package.json
this is a generalization of https://github.com/sagemathinc/cocalc/pull/4829
jupyter notebook in my cc-in-cc runs, so, I guess this is all fine
Front end:
=> project: update better-sqlite3 & dependencies

src/smc-webapp/project/page/software-env-upgrade.tsx
well, this should help
1.
1.
1.
Front end:
=> webapp/software update: reorder some lines to avoid violating hook rules

src/smc_pyutil/smc_pyutil/ipynb_to_pdf.py
this should help with converting to pdf or give some useful feedback if chrome or chromium is missing
=> pyutil/ipynb2pdf: check for chrome or chromium

src/smc-webapp/billing/explain-resources.tsx, src/smc-webapp/billing/static-pricing-page.tsx
* some changes to the landing page part is already pushed and in master
=> pricing: do not show course packages (quick n dirty)

src/smc-hub/test/kucalc/quota.test.ts, src/smc-util/upgrades/quota.ts
fixes 25 broken tests (dedicated quotas are all NaN and overcommittment calculations are broken for deriving the defaults) … and no clue if site licenses are working
I added one test, but I have no idea if the results are actually what they should be.
deployment: updating manage – I'm building the first commit now, the second doesn't change anything.
=> quota function broken

src/smc-util/message.js
Add stubs for api docs for `add_license_to_project` and `remove_license_from_project`.
Built cc-in-cc and opened a project to check for syntax errors.
=> minimal docs for api license calls

src/smc-util/theme.js
I guess it's time to change it
=> change of address

src/smc-hub/hub.coffee, src/smc-hub/webapp-configuration.ts, src/smc-util/db-schema/site-defaults.ts, src/smc-webapp/account/licenses/about-licenses.tsx, src/smc-webapp/client/project.ts, src/smc-webapp/customize.tsx, src/smc-webapp/info/usage.tsx, src/smc-webapp/project/client-side-throttle.ts, src/smc-webapp/project/directory-listing.ts, src/smc-webapp/project/explorer/explorer.tsx, src/smc-webapp/project/page/page.tsx, src/smc-webapp/project/start-button.tsx, src/smc-webapp/project/trial-banner.tsx, src/smc-webapp/project/websocket/connect.ts, src/smc-webapp/project/websocket/listings.ts, src/smc-webapp/projects/actions.ts, src/smc-webapp/projects/store.ts, src/smc-webapp/server-stats.ts
=> Client side project limit

src/smc-webapp/editor-data/generic.tsx
this is pretty straight forward.
=> webapp: block opening p, pkl and pickle files

src/smc-hub/postgres-base.coffee
I'm undoing this "concurrently" for creating indices. it failed in production.
=> hub/db: creating indices concurrently caused them to be invalid

src/smc-hub/postgres/always-running.ts, src/smc-util/db-schema/projects.ts
this is a simple optimization and well, maybe there will be other queries asking for this set of projects in the future as well.
=> speed up the "always_running" query

src/smc-hub/postgres/site-license/manager.ts, src/smc-util/db-schema/site-licenses.ts, src/smc-webapp/admin/users/actions.ts, src/smc-webapp/admin/users/user.tsx, src/smc-webapp/frame-editors/generic/client.ts, src/smc-webapp/site-licenses/purchase-info-about-license.tsx, src/smc-webapp/site-licenses/site-license-public-info.tsx, src/smc-webapp/site-licenses/types.ts
Deployment requires restarting hub-websocket.
=> implement license manager add/remove by users

src/smc-webapp/project/info/project-info.tsx
fixing #4962
ok, this fixes this for me in dev
=> webapp/project info: avoid sticky modals in antd

src/smc-webapp/project/info/fcs.tsx, src/smc-webapp/project/info/project-info.tsx
this is a simple measure to prevent users from killing their own project hub, that's all
=> webapp/project info: block sending any signals to processes classified as "project" or "sshd"

src/smc-webapp/billing/license-examples.tsx
=> webapp/pricing: exemplary → typical

src/smc-project/jupyter/jupyter.ts, src/smc-project/nbgrader/jupyter-run.ts, src/smc-webapp/jupyter/project-interface.ts
Minimal code:
```
def sol():
import pandas as pd
x = pd.Series()
return x.size
```
test
```
from nose.tools import assert_true
assert_true(sol() == 0)
```
Well, the "problem" is that python warnings result in something that looks like an error. See json below:
```{json}
{
"cell_type": "code",
"execution_count": 6,
"metadata": {
"collapsed": false,
"nbgrader": {
"grade": true,
"grade_id": "fc7670",
"locked": true,
"points": 2,
"schema_version": 3,
"solution": false,
"task": false
}
},
"outputs": [
{
"name": "stderr",
"output_type": "stream",
"text": [
"<ipython-input-5-f1912baca5b3>:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.\n",
"  x = pd.Series()\n"
]
}
], …
```
=> jupyter/nbgrader: suppress all python warnings

src/smc-hub/client/create-account.ts, src/smc-util/message-types.ts
fixes #5040
test stats: building in "test"
=> fixing a bug preventing anon user sign ups

src/smc-hub/package-lock.json, src/smc-hub/package.json
small update for oauth2 and a major one for ldap. since we don't use ldap yet, this won't have an impact. as far as I can see those are the only available updates.
=> passport: update oauth2 (small change) and ldap 

src/smc-project/sync/listings.ts, src/smc-project/sync/usage-info.ts
this is a quick follow up for https://github.com/sagemathinc/cocalc/pull/5056
=> project: follow up of usage-info PR

src/dev/project/README.md
=> added `. smc-env` and changed `cocalc/cocalc` to `cocalc/src`

src/smc-webapp/editor-data/generic.tsx, src/smc-webapp/file-associations.ts
stop cocalc from mangling *.blend files
=> webapp: do not open blend files

src/smc-project/jupyter/jupyter.ts
see #5165
screenshots in python and R
=> jupyter: expose file path and kernel name as env variables 

src/smc_pyutil/setup.py
=> pyutil: nbformat should be listed as a dependency

src/smc-webapp/project_actions.ts
=> webapp: convert docx2md to gfm

src/smc-webapp/jupyter/select-kernel.tsx
fixing selector page, by using more of antd, fixing #5189. I also checked if this fixes the problem where a small list of kernels looks odd. I can't find the issue, though. My test was to just render the first kernel. I checked this in my chrome and fireofx. Here are two screenshot about this:
---
=> jupyter: redoing the kernel selector page, 

src/smc-project/autorenice.ts, src/smc-project/local_hub.coffee, src/smc-project/project-setup.ts, src/smc-project/project_setup.ts
If a project is "free", all processes are re-niced a lot. Also, a bit of refactoring of CS → TS.
test: I tested this, including custom env variables and deleting NVM related vars. ... no problems
deploy:  it's already running in production
=> lower priority of free projects processes

src/smc-webapp/project/info/project-info.tsx
This adds some info when the project info doesn't load.
=> project info: show alert info box pointing users to #5081

src/smc-hub/postgres-server-queries.coffee, src/smc-hub/postgres/delete-projects.ts
this unlinks projects marked as deleted
=> unlink old deleted projects

src/smc-webapp/frame-editors/settings/spell-check.tsx
See #5222 ... I have no idea if react bootstrap is fixable, but this replaced it with antd.
=> webapp: fix spellcheck dropdown

src/smc-webapp/file-associations.ts, src/smc-webapp/project/new/new-file-dropdown.tsx
well, this is just like the +new button in files. yes, it creates a file with the given extension. I also cleaned up the code.
=> webapp/new: fix that new file dropdown

src/smc-webapp/share/config/license.tsx
yet another broken dropdown ...
=> webapp: fix share/license dropdown

src/smc-webapp/course/sync.ts
=> fix initial/default datastore setting

src/smc-webapp/editors/unknown/editor.tsx
this is pretty simple. my test case: `echo abc > x.abc`. if I click on that file, it opens with the code editor. 
on the other hand, a png image `y.xxx` still opens that editor and offers no solution. doing something similar for images is for another ticket.
=> automatically associate plain text files and open them

src/smc-webapp/course/assignments/actions.ts, src/smc-webapp/frame-editors/generic/client.ts, src/smc-webapp/projects/actions.ts
This checks if the start action for a student project did actually start the project. If so, request a stop. #5278 should be merged first!
=> Nbgrader: stop project if it started it

src/smc-project/configuration.ts, src/smc-webapp/frame-editors/jupyter-editor/snippets/components.tsx, src/smc-webapp/frame-editors/jupyter-editor/snippets/main.tsx, src/smc-webapp/frame-editors/jupyter-editor/snippets/types.ts, src/smc-webapp/frame-editors/jupyter-editor/snippets/utils.ts, src/smc-webapp/jupyter/store.ts, src/smc-webapp/project_configuration.ts
This makes it possible to add custom snippets. It's not 100%, but good enough for a start. It's mainly webapp, but it also checks for `jq` in the project.
=> Custom Snippets

src/smc-webapp/jupyter/actions.ts, src/smc-webapp/jupyter/parsing.ts
ticket #5284
the only thing I noticed is that the format button doesn't always work. the menu entry does, though. I don't understand why. 
my test were just simple things like
```
%time 123
def ff(x):
pass
```
=> jupyter/formatter: support %magics 

src/smc-webapp/jupyter/parsing.ts
yes, #5290 has a good point. assuming those magics start with the line, this processes the lines individually. then, such % signs are excluded automatically. I also changed the marker to be `#%%%#` which is even more unusual than in the original code. the comment should be a bit better now as well.
=> jupyter/format magics: process each line individually 

src/smc-webapp/course/configuration/parallel.tsx, src/smc-webapp/course/store.ts
=> Copy ops tweaks

src/smc-hub/client.coffee, src/smc-hub/email.ts, src/smc-hub/package-lock.json, src/smc-hub/package.json, src/smc-hub/postgres-server-queries.coffee, src/smc-util/db-schema/types.ts, src/smc-webapp/course/store.ts, src/smc-webapp/course/student-projects/actions.ts
* issue #5282
* issue #4881
* a missing callback when inviting someone (I generalized the code, though)
* fixing replyTo attribute for nodemailer (also, updated it)
=> hub/email: fix invite email sender config

src/smc-webapp/frame-editors/frame-tree/editor.tsx, src/smc-webapp/frame-editors/frame-tree/frame-tree.tsx, src/smc-webapp/frame-editors/frame-tree/leaf.tsx, src/smc-webapp/frame-editors/html-editor/iframe-html.tsx, src/smc-webapp/project/page/content.tsx
There were a couple of subtle issues with iframes. e.g. the iframe is sometimes blank in firefox, or the scroll position is gone when you tab away. Interestingly, after converting this to a FC, it got worse, which helped debugging it. I tested this with html, rst and Rmd. What's left – and I'll try to fix with another PR – is this frequent re-compiling of Rmd and maybe other editors with a preview. That's also really annoying.
=> frame editor iframe: React.FC + fixing bugs

src/smc-webapp/account/editor-settings/checkboxes.tsx, src/smc-webapp/frame-editors/frame-tree/title-bar.tsx, src/smc-webapp/frame-editors/rmd-editor/actions.ts, src/smc-webapp/frame-editors/rmd-editor/rmd-converter.ts
* fix some details around how builds are deduplicated. I borrowed some lines from latex.
* make building optional, like latex
* only trigger builds once, because they could take a while to run
* #5314
=> webapp/rmd: improve automatic builds

src/smc-webapp/frame-editors/latex-editor/actions.ts, src/smc-webapp/frame-editors/latex-editor/latex-word-count.tsx
this is just a small change, works fine
=> webapp/latex/word_count: make this an FC, minor cleanups

src/smc-webapp/frame-editors/frame-tree/title-bar.tsx, src/smc-webapp/frame-editors/latex-editor/latex-log-parser.ts
see #5320
to test this call the main file `TEX.TEX` and reference e.g. `\include{file}` for `file.tex`
=> latex multifile support fixes

src/smc-webapp/frame-editors/html-editor/rendered-html.tsx
this is rather trivial, it's the "html preview" of the html editor.
=> webapp/html: react.fc the rendered html preview

src/smc-webapp/frame-editors/latex-editor/actions.ts
similar to #5318 but for latex
=> latex: do not rebuild on every save

src/smc-webapp/jupyter/cursors.tsx
I think this works, but in general, I'm not happy with the positioning of it. That's what I actually wanted to look into. 
So, either we merge this quickly and I'll try to fix the CSS for the positioning (but I'm not really sure how it should look) or I'll keep tinkering around.
~~OK, no, I think I messed up something with the Cursor class, when moving it's parts around. Will fix it.~~ nope, just confused.
I'll look into that cursor positioning another time…
=> make cursor classes FCs

src/smc-project/jupyter/jupyter-blobs-sqlite.ts
* see #5255 to trim large files 
* vacuum (without that, it never shrinks)
* properly use prepared statements
i'm not 100% sure how to test. that mocha test no longer works. I was able to do a few plots in a notebook in my cc-in-cc dev project, and then use time travel to also see older versions. Hence the basic functionality is fine. I tried to trigger the part about deleting old entries when it's getting large by setting the threshold very low. I think it's ok, but without an actual large db file quite impossible to test properly.
=> project/jupyter: improvements blobstore

src/smc-project/jupyter/jupyter-blobs-sqlite.ts
so, I believe the problem in 8a4a349f4ef4 was that those prepared statements need the table. makes sense. I refactored this a bit and made a comment.
=> project: fix 8a4a349f4ef4 and a bit of refactoring

src/smc-webapp/site-licenses/purchase/purchase.tsx
=> license: mention non-profit organizations as well

src/smc-project/kucalc.coffee
trivial, but didn't test it yet
=> project: missing async for prom metrics

src/smc-util/compute-images.ts
this is trivial, just an entry for a symlink
=> adding ubuntu2004-2021-05-31 reference

src/smc-webapp/course/configuration/datastore-config.tsx, src/smc-webapp/project/settings/datastore.tsx
this just changes strings, that's all
=> webapp: rename datastore to cloud store & remote file system

src/smc-project/project-setup.ts
re-introduced an env var, and getting rid of it after init.sh ran
=> project: rm PATH_COCALC

src/packages/hub/package-lock.json, src/packages/hub/package.json, src/packages/hub/postgres-server-queries.coffee, src/packages/util-node/package-lock.json, src/packages/util-node/package.json, src/packages/util-node/server-settings/customize.ts, src/packages/util-node/server-settings/server-settings.ts
=> hub: fix "sign up"

src/packages/frontend/project/info/components.tsx
This checks more carefully if a selected process still exists.
=> frontend/process info: if a selected process terminates, it no longer exists

src/packages/util/compute-images.ts
=> software env snapshot ubuntu2004-2021-08-13

src/packages/backend/data.ts, src/packages/database/pool/pool.ts, src/packages/database/postgres-base.coffee
follow up of https://github.com/sagemathinc/cocalc/pull/5560
=> db/backend: set database name via SMC_DB and PGDATABASE in "data" object

src/packages/database/postgres/pii.ts, src/packages/hub/package.json, src/packages/server/email/send-email.ts, src/packages/server/email/smtp.ts, src/packages/server/email/throttle.ts, src/packages/server/mentions/notify.ts, src/packages/server/settings/server-settings.ts, src/packages/util/db-schema/email-counter.ts
this is for gdpr compliance. I also added a few missing license headers.
=> Expire email count stats

src/packages/next/components/landing/head.tsx
such a double dash doesn't look good, long dash suits better
=> next/header: change double dash to long dash

src/packages/database/package-lock.json, src/packages/database/package.json
yesterday's type changes in https://github.com/sagemathinc/cocalc/pull/5590 don't have a new version. that updates this.
=> udpate database version

src/packages/database/package-lock.json, src/packages/database/package.json, src/packages/database/postgres/types.ts
=> database/postgres types: add order_by field to async_query options

src/packages/database/postgres/stats.ts
since it came up today, also check for these two file extensions
=> database/stats: also record julia .jl and matlab .m files

src/packages/util/compute-images.ts
since the current one was so long in use, it makes sense to add a pointer to it
=> util: add pointer to software environment 2021-10-10

src/packages/next/components/share/layout.tsx, src/packages/next/lib/customize.ts, src/packages/next/lib/project/info.ts, src/packages/next/lib/use-customize.ts, src/packages/next/lib/with-customize.ts, src/packages/server/settings/customize.ts
if something is unlisted, tell search engines to actually not index it
please look carefully at what I wrote, first time I looked at that code
=> next/share: tell search engines to "noindex" if unlisted

src/packages/frontend/project/settings/quota-console.tsx, src/packages/frontend/projects/store.ts, src/packages/util/upgrades/quota.ts
I think it works, but I don't have enough energy & time left to test properly... 💤
=> frontend/quota-console: fix displayed quotas

src/packages/frontend/file-use/info.tsx, src/packages/frontend/jupyter/cell-toolbar-tags.tsx, src/packages/frontend/project/explorer/file-listing/copy-button.tsx, src/packages/frontend/project/explorer/file-listing/file-checkbox.tsx, src/packages/frontend/project/explorer/file-listing/file-listing.tsx, src/packages/frontend/project/explorer/file-listing/listing-header.tsx, src/packages/frontend/project/explorer/file-listing/no-files.tsx, src/packages/frontend/project/explorer/file-listing/utils.ts, src/packages/frontend/project/settings/body.tsx, src/packages/frontend/project/settings/project-capabilites.tsx, src/packages/frontend/project/settings/project-control.tsx, src/packages/frontend/project_configuration.ts
this changes a couple of old components to be functional.
=> frontend: modernize more UI components

src/packages/frontend/admin/site-settings.tsx, src/packages/next/components/landing/contact.tsx, src/packages/next/components/landing/content.tsx, src/packages/next/components/landing/footer.tsx, src/packages/next/components/landing/header.tsx, src/packages/next/components/landing/sign-in.tsx, src/packages/next/components/landing/sub-nav.tsx, src/packages/next/components/misc/sanitized-markdown.tsx, src/packages/next/lib/customize.ts, src/packages/next/lib/with-customize.ts, src/packages/next/pages/index.tsx, src/packages/next/pages/policies/imprint.tsx, src/packages/next/pages/policies/index.tsx, src/packages/next/pages/policies/policies.tsx, src/packages/next/pages/policies/terms.tsx, src/packages/server/settings/customize.ts, src/packages/util/db-schema/site-defaults.ts
- Imprint and policies pages for on-prem setups, requiring that policy subnav to be more flexible
- also fixing https://github.com/sagemathinc/cocalc/issues/5625
- footer: linking to organization if `organizationUrl` is set
=> Imprint and policies

src/packages/frontend/project/settings/site-license.tsx, src/packages/frontend/site-licenses/site-license-public-info.tsx, src/packages/server/projects/control/base.ts
for project settings only, if a license key is added or removed, the project is automatically restarted. this also adds a bit of warning text and modifies the description of adding a license key.
during testing I discovered #5635 ... which is not part of this
=> License change restart

src/packages/frontend/admin/users/actions.ts, src/packages/frontend/collaborators/add-collaborators.tsx, src/packages/frontend/frame-editors/generic/client.ts, src/packages/frontend/site-licenses/site-license-public-info.tsx
* type of created and last_active changed in 63e8e9954dc51632cf
=> fix admin search

src/packages/frontend/frame-editors/frame-tree/frame-tree-drag-bar.tsx, src/packages/frontend/frame-editors/frame-tree/frame-tree.tsx, src/packages/frontend/frame-editors/terminal-editor/commands-guide.tsx, src/packages/frontend/frame-editors/terminal-editor/connected-terminal.ts, src/packages/frontend/frame-editors/terminal-editor/terminal.tsx, src/packages/frontend/misc/iframe.ts, src/packages/frontend/project/page/page.tsx, src/packages/frontend/project_actions.ts
- **follow up of #5686** ... hence merge the other one first, then this one is clearer
- there was some code duplication, with slightly inconsistent code. not sure why → now there is a separate component for both directions.
- the main issue to fix is that the vertical scrollbar quickly fades away, because the drag state is just set upon hover. with this here, it works better.
=> Frame editor: fix horizontal dragbar

src/packages/frontend/components/link-retry.tsx, src/packages/frontend/custom-software/info-bar.tsx, src/packages/frontend/custom-software/reset-bar.tsx, src/packages/frontend/project/explorer/action-bar.tsx
This fixes #5683 and also some general modernizations.
=> CSE styling

src/packages/frontend/frame-editors/x11-editor/apps.ts
=> frontend/x11: add TeXmaker app -- fixes #5685

src/packages/frontend/editors/archive/actions.ts, src/packages/frontend/editors/archive/component.tsx, src/packages/frontend/editors/archive/misc.ts
- this fixes #411
- also tar.gz
=> frontend/archive: support tar.bz2 and tbz2

src/packages/frontend/frame-editors/jupyter-editor/snippets/main.tsx, src/packages/frontend/frame-editors/jupyter-editor/snippets/utils.ts
- this fixes #5443
- also, to make #5443 work, language name must be lower case
- refactors some variable names and other details
=> Jupyter snippets stalled during loading

src/packages/frontend/course/configuration/upgrades.tsx
=> fix tiny typo

src/packages/next/components/billing/consts.ts, src/packages/next/components/billing/invoices-and-receipts.tsx, src/packages/next/components/billing/layout.tsx, src/packages/next/components/billing/menu.tsx, src/packages/next/components/billing/overview.tsx, src/packages/next/components/billing/payment-methods.tsx, src/packages/next/components/billing/subscriptions.tsx, src/packages/next/pages/billing/[[...page]].tsx
* see #5739
* first, this redirects broken pages, since there is no way to know if those two are all broken links
*  introduce a 404 error, otherwise there is an infinite number of pages. never a good idea.
* and I try to avoiding running into this in the future via a list & typing … no idea if there is a proper way of doing this
* what's puzzling me is to type `page: string;` in layout.tsx. I changed this to an array of strings, including undefined.
=> next: fix problematic billing pages 

src/packages/next/pages/404.tsx
=> next: custom 404 page

src/packages/frontend/components/text-input.tsx, src/packages/frontend/project/settings/about-box.tsx
=> course: project/settings name/descr readonly 

src/packages/next/components/landing/image.tsx
follow up of https://github.com/sagemathinc/cocalc/pull/5749
ok, with that `npm run build` works
=> next/image: missing type info

src/packages/frontend/account/avatar/users-viewing.tsx, src/packages/next/components/licenses/managed.tsx
There are two cases where scrollbars appear around avatars: #5399 and #5663 … which are fixed by small CSS changes
=> Fix avatar scrollbars

src/packages/next/components/licenses/how-used.tsx, src/packages/next/components/licenses/managed.tsx
two cosmetic changes, removing scrollbars and additional space on the page -- see #5664
=> Next license scrollbars 

src/packages/assets/README.md, src/packages/assets/misc/talk-20121004/index.html, src/packages/assets/term/term.js, src/packages/assets/threejs/r73/OrbitControls.js, src/packages/backend/execute-code.coffee, src/packages/backend/logger.ts, src/packages/backend/package-lock.json, src/packages/backend/test/misc_node-test.coffee, src/packages/database/postgres-base.coffee, src/packages/database/postgres-blobs.coffee, src/packages/database/postgres-ops.coffee, src/packages/database/postgres-server-queries.coffee, src/packages/database/postgres-user-queries.coffee, src/packages/database/postgres/collab.ts, src/packages/database/postgres/delete-projects.ts, src/packages/database/postgres/site-license/hook.ts, src/packages/database/postgres/site-license/search.ts, src/packages/database/postgres/site-license/usage-log.ts, src/packages/next/components/account/config/account/delete-account.tsx, src/packages/next/components/account/config/account/name.tsx, src/packages/next/components/account/config/editor/jupyter.tsx, src/packages/next/components/landing/backups.tsx, src/packages/next/components/landing/compare.json, src/packages/next/lib/share/get-public-path-info.ts, src/packages/next/pages/api/v2/accounts/sign-out.ts, src/packages/next/pages/api/v2/shopping/cart/recent-purchases.ts, src/packages/next/pages/features/linux.tsx, src/packages/next/pages/features/r-statistical-software.tsx, src/packages/next/pages/features/sage.tsx, src/packages/next/pages/features/whiteboard.tsx
Most typos were found by codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Fix some typos in subset of src/packages

src/packages/assets/misc/talk-20121004/ui/default/slides.js, src/packages/assets/threejs/r73/CanvasRenderer.js, src/packages/assets/threejs/r73/OrbitControls.js, src/packages/assets/threejs/r73/Projector.js, src/packages/frontend/course/shared-project/actions.ts, src/packages/server/projects/control/util.ts
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Add missing semicolons (fixes recommendations from LGTM)

src/packages/frontend/course/students/students-panel.tsx
this fixes  #5788 (and well, also found a tiny bug where the number of omitted students isn't updated)
=> frontend/course: fix sorting students

src/packages/next/lib/landing/get-libraries.ts, src/packages/next/lib/landing/types.ts
this is a follow up, the main changes are how the actual data is generated. this avoids running into the same issue in the future.
**deploy** no functional change, hence no need to deploy this right away
=> next/software: be more careful

src/packages/database/postgres-blobs.coffee
more audacious would be a typescript rewrite 🙈
=> db/syncstrings: just whitespace to fix the indentation

src/packages/next/pages/policies/thirdparties.tsx
=> add reCAPTCHA to the list of 3rd parties

src/packages/frontend/editors/slate/elements/link/editable.tsx, src/packages/frontend/editors/slate/elements/references/editable.tsx, src/packages/frontend/editors/slate/elements/references/index.tsx, src/packages/frontend/editors/slate/elements/references/type.ts, src/packages/frontend/editors/slate/elements/types-ssr.ts, src/packages/frontend/editors/slate/elements/types.ts, src/packages/frontend/editors/slate/markdown-to-slate/parse-markdown.ts, src/packages/frontend/editors/slate/markdown-to-slate/parse.ts, src/packages/frontend/editors/slate/markdown-to-slate/types.ts, src/packages/frontend/editors/slate/slate-to-markdown.ts
#5684 
I'm highly prioritizing this now, since I realized it suddenly can corrupt markdown files just by opening them, and that's not good!
=> work in progress implementing proper support for reference links

src/packages/hub/auth.ts, src/packages/next/pages/auth/ROUTING.md, src/packages/next/pages/auth/password-reset.tsx, src/packages/next/pages/auth/password-reset/[id].tsx, src/packages/next/pages/auth/sign-in.tsx, src/packages/next/pages/auth/sign-up.tsx, src/packages/next/pages/auth/try.tsx, src/packages/next/pages/auth/verify/[token].tsx
this is just a file for documentation, a few headers, and well, a check for the hub to avoid a surprise picking a name, that's handled elsewhere
=> hub/next: sort out and document /auth/* endpoint handling

src/packages/frontend/frame-editors/code-editor/actions.ts, src/packages/frontend/frame-editors/frame-tree/frame-context.ts, src/packages/frontend/frame-editors/frame-tree/frame-tree.tsx, src/packages/frontend/frame-editors/frame-tree/hooks.ts, src/packages/frontend/frame-editors/frame-tree/title-bar.tsx, src/packages/frontend/frame-editors/whiteboard-editor/actions.ts, src/packages/frontend/frame-editors/whiteboard-editor/canvas.tsx, src/packages/frontend/frame-editors/whiteboard-editor/editor.ts, src/packages/frontend/frame-editors/whiteboard-editor/elements/code/control.tsx, src/packages/frontend/frame-editors/whiteboard-editor/elements/code/index.tsx, src/packages/frontend/frame-editors/whiteboard-editor/elements/frame.tsx, src/packages/frontend/frame-editors/whiteboard-editor/focused-edge-create.tsx, src/packages/frontend/frame-editors/whiteboard-editor/hooks.ts, src/packages/frontend/frame-editors/whiteboard-editor/math.ts, src/packages/frontend/frame-editors/whiteboard-editor/not-focused.tsx, src/packages/frontend/frame-editors/whiteboard-editor/pages.tsx, src/packages/frontend/frame-editors/whiteboard-editor/position.tsx, src/packages/frontend/frame-editors/whiteboard-editor/search.tsx, src/packages/frontend/frame-editors/whiteboard-editor/share/canvas.tsx, src/packages/frontend/frame-editors/whiteboard-editor/share/index.tsx, src/packages/frontend/frame-editors/whiteboard-editor/share/util.ts, src/packages/frontend/frame-editors/whiteboard-editor/tools/navigation.tsx, src/packages/frontend/frame-editors/whiteboard-editor/tools/panel.tsx, src/packages/frontend/frame-editors/whiteboard-editor/tools/spec.ts, src/packages/frontend/frame-editors/whiteboard-editor/tools/upload.tsx, src/packages/frontend/frame-editors/whiteboard-editor/types.ts, src/packages/frontend/frame-editors/whiteboard-editor/whiteboard.tsx
The first commit already represents something that basically fully works with basic functionality.  However, I plan more, and there are some annoyances with this.
=> add a notion of pages to the whiteboard 

src/packages/frontend/project/trial-banner.tsx, src/packages/frontend/project/warnings/common.ts, src/packages/frontend/project/warnings/no-network.tsx, src/packages/frontend/project/warnings/oom.tsx, src/packages/next/components/store/quota-config.tsx, src/packages/server/licenses/purchase/product-id.ts, src/packages/util/consts/billing.ts, src/packages/util/licenses/purchase/consts.ts, src/packages/util/upgrades/quota.ts
well, there is more to consider than I thought. in any case, I came up with a mix of several factors
- minimum 3gb of disk, since that's what we provide in any case. the main implication is this raises the absolute minimum you can get for a project.
- as a tradeoff, this slightly increases the GCP factor (+6.6%)
- the OOM banner points to boost licenses, if there is at least one license attached
- in turn, there is no longer a 500mb for free mem increase, if you were after the 1gb minimum. i.e. you get what you paid for.
=> moderate price increase

src/packages/next/components/landing/content.tsx, src/packages/next/components/landing/info.tsx, src/packages/next/components/landing/sign-in.tsx, src/packages/next/pages/features/jupyter-notebook.tsx, src/packages/next/pages/features/latex-editor.tsx, src/packages/next/pages/features/linux.tsx, src/packages/next/pages/features/octave.tsx, src/packages/next/pages/features/python.tsx, src/packages/next/pages/features/r-statistical-software.tsx, src/packages/next/pages/features/sage.tsx, src/packages/next/pages/features/teaching.tsx, src/packages/next/pages/features/terminal.tsx, src/packages/next/pages/features/whiteboard.tsx
This started mainly to add a few more details to the teaching page, but I ended up tweaking a few details all over the place. Also, the whiteboard title was too large.
=> Tweak landing pages

src/packages/frontend/components/icon.tsx, src/packages/next/components/store/boost.tsx, src/packages/next/components/store/member-idletime.tsx, src/packages/next/components/store/quota-config-presets.tsx, src/packages/next/components/store/quota-config.tsx, src/packages/next/components/store/site-license.tsx, src/packages/util/consts/site-license.ts
This adds a section in the purchase form to offer a few presets with some explanation text. The main idea is if you don't know what to select, you don't have to think about cpu/ram/disk.
=> Store quota presets

src/packages/next/components/store/quota-config.tsx
=> next/store: fix shared ram explanation, to be suitable for licenses and boosts

src/packages/server/initial-onprem-setup.ts
root problem was the heuristic generates the name from the email address, but any name with a dot is rejected by that `is_valid_username` check.
=> onprem: improve generated admin name

src/packages/next/components/licenses/managed.tsx, src/packages/next/components/store/boost.tsx, src/packages/next/components/store/member-idletime.tsx, src/packages/next/components/store/quota-config-presets.tsx, src/packages/next/components/store/toggle-explanations.tsx
- mention explicitly what to do if you are conducting a course and need to cover more students (not a boost)
- offer to select a managed license to tweak the corresponding parameters
where I'm stuck with is a strange react warning. it's still working fine for me, so I don't know what's going on or how to avoid it. "`label` of `value` is not same as `label` in Select options" when selecting a value in the dropdown list.
=> Store: clarify boosting 

src/packages/frontend/project/settings/quota-console.tsx, src/packages/frontend/project/settings/run-quota/run-quota.tsx, src/packages/frontend/project/settings/upgrade-usage.tsx, src/packages/util/types/dedicated.ts
=> frontend/project quotas: special casing "dedicated vm" extra explanation text

src/packages/frontend/project/settings/project-capabilites.tsx, src/packages/frontend/project/websocket/api.ts, src/packages/project/configuration.ts, src/packages/util/code-formatter.ts
fixes #6089 (and zig was just an innocent victim of this, because it comes last…)
=> project/config: fix silly brittle code for collecting formatting capabilities

src/packages/frontend/app/active-content.tsx, src/packages/frontend/app/page.tsx
- see #6092
- this is simply showing a generic warning box, when there is still no sign in happening after ~5 seconds (if it still happens later, this resolved to show the project)
- this only applies for those URLs, which point to a specific project
=> frontend connecting: user might have to sign in

src/packages/next/pages/policies/privacy.tsx
Update JAMS link per Sept 12 email from Privacy Shield <privacyshield@trade.gov>.
=> update JAMS link

src/packages/next/components/auth/in-place-sign-in-or-up.tsx, src/packages/next/components/store/add-box.tsx, src/packages/next/components/store/boost.tsx, src/packages/next/components/store/cost-info-bar.tsx, src/packages/next/components/store/dedicated.tsx, src/packages/next/components/store/index.tsx, src/packages/next/components/store/sign-in-to-purchase.tsx, src/packages/next/components/store/site-license.tsx, src/packages/next/components/store/store-inplace-signup.tsx, src/packages/next/lib/hooks/profile.ts
the goal of this PR is to make the prices public. i.e. this shifts the requirement to be signed in to a later point, and also adds a warning about this.
=> store: public prices

src/packages/next/components/store/util.ts
this is just a follow up of specifying a project to receive a license. if there is no such query param, don't clutter the console with a warning about it.
=> store: suppress silly warning

src/packages/database/postgres/passport.ts, src/packages/next/lib/share/get-vhost-info.ts, src/packages/next/pages/index.tsx, src/packages/util/db-schema/accounts.ts, src/packages/util/db-schema/copy-paths.ts, src/packages/util/db-schema/projects.ts, src/packages/util/db-schema/public-paths.ts
This includes a few tweaks to indices and speed up of queries. No actual change in functionality.
=> db index updates

src/packages/next/components/store/boost.tsx, src/packages/next/components/store/quota-query-params.ts, src/packages/next/components/store/site-license.tsx, src/packages/next/components/store/usage-and-duration.tsx
* fix "user=..."
* only encode necessary params
=> store/param encoding: only encode whitelisted params and fix user

src/packages/frontend/project/named-server-panel.tsx
Fix typo in "Visal" Studio Code.
- [ x] Testing instructions are provided, if not obvious
- [ x] Release instructions are provided, if not obvious
=> Fix typo in named-server-panel.tsx

src/packages/static/src/startup-banner.tsx
images with >1000px width are ridiculously large
=> landing: limit size of custom image

src/packages/next/lib/landing/types.ts
Just a new edge case. No need to deploy a new version.
=> software: url in ComputeComponents is optional

.github/workflows/make-and-test.yml, src/packages/database/pool/util.test.ts
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
This PR includes https://github.com/sagemathinc/cocalc/pull/6232
=> github actions: cache using setup-node@v3

src/packages/frontend/index.sass
=> frontend: make sure all anchor links are a pointer 

src/packages/next/package-lock.json, src/packages/next/package.json, src/packages/next/pages/_app.tsx
- https://github.com/sindresorhus/modern-normalize
- fixes #6285
=> next: install modern-normalize to fix #6285

src/packages/pnpm-lock.yaml, src/packages/static/package.json
since webapp-error-reporter imports it via a require
=> pnpm: install awaiting in static

src/cocalc.code-workspace
with that, the jest test extension knows that this is a multi-package repository and hence can run the tests for each package automatically, while coding
=> adding a vscode workspace file

src/packages/next/components/store/index.tsx, src/packages/util/misc.ts
- instead of throwing an error, this just triggers an assignment error. hence we see this when compiling, but no longer have to fear that exception :man_shrugging: 
- use this in the store to throw our custom 404
=> util: tame "unreachable" 

src/packages/frontend/components/sortable-list.tsx, src/packages/frontend/editors/task-editor/drag.tsx, src/packages/frontend/editors/task-editor/list.tsx, src/packages/frontend/frame-editors/jupyter-editor/cell-notebook/actions.ts, src/packages/frontend/index.sass, src/packages/frontend/jupyter/actions.ts, src/packages/frontend/jupyter/cell-list.tsx, src/packages/frontend/jupyter/commands.ts
Just something that is more useful that nothing...
=> Jupyter cell drag and drop

src/packages/frontend/project/explorer/action-box.tsx
- ref https://github.com/sagemathinc/cocalc/issues/6370 … I added the case where there is a space around the extension as a blocker for renaming
- I also added a red warning, if there are other reasons why you can't rename. e.g. right now if the file is too long, the button is disabled and not telling you why.
=> frontend/files: revisit file rename/duplicate warnings

src/packages/database/pool/util.test.ts
I see this almost daily … https://github.com/sagemathinc/cocalc/actions/runs/4112713577/jobs/7097967074
=> db/test: fix #6387

src/packages/frontend/components/dropdown-menu.tsx, src/packages/frontend/frame-editors/whiteboard-editor/tools/edit-bar.tsx, src/packages/frontend/project/settings/compute-image-selector.tsx, src/packages/frontend/site-licenses/admin/upgrades.tsx
* whiteboard: "other operations"
* software environment dropdown in project settings
* the upgrade preset dropdown in admin's site license editor
=> Antd deprecation dropdown menu part 2

src/packages/frontend/frame-editors/latex-editor/build-command.tsx
in the latex build frame:
* engine selection dropdown menu
* getting rid of react-bootstrap alerts
=> frontend/latex/build: modernize some code

src/packages/hub/client.coffee
- should fix #6444 … that missing "locals." was always missing
- I also added an extra check, just in case
=> hub/client: fix #6444

src/packages/frontend/frame-editors/x11-editor/apps.ts
=> frontend/x11: add buttons for jurism and zotero

src/packages/pnpm-lock.yaml, src/packages/server/auth/sso/oauth2-user-profile-callback.ts, src/packages/server/auth/sso/openid-parser.ts, src/packages/server/package.json
* Provides working OAuth1 SSO flow (should not break OAuth2 SSO, but still not check). 
* Improve creation Profile from SSO data, if provided «realname» attr.
* Small diffs for easy verifications.
- [* ] Testing instructions are provided, if not obvious
- [*] Release instructions are provided, if not obvious
=> [needs review] Provides working OAuth1 SSO flow (should not break OAuth2 SSO)

src/packages/frontend/project/no-internet-banner.tsx, src/packages/frontend/project/page/project-state-hook.ts, src/packages/frontend/project/project-banner.tsx, src/packages/frontend/project/settings/restart-project.tsx, src/packages/frontend/project/trial-banner.tsx
- ticket  #6496
- there is still one exception, when there are too many trial projects running
- I also made some minor refactorings
=> frontend/project: hide trial banner when project not running

src/packages/frontend/components/setting-box.tsx, src/packages/frontend/project/settings/about-box.tsx
- fixes #6498
- adds line wrapping, works fine. more advanced things like using overflow/ellipsis/etc. didn't work … or needs more work than I want to spend on this
=> frontend/project/settings: fix long title wrapping in about title

src/packages/next/components/landing/index-list.tsx, src/packages/next/components/landing/info.tsx, src/packages/next/components/landing/pricing-item.tsx, src/packages/next/components/landing/sub-nav.tsx, src/packages/next/components/store/link.tsx, src/packages/next/components/support/create.tsx, src/packages/next/components/support/tickets.tsx, src/packages/next/pages/pricing/dedicated.tsx, src/packages/next/pages/pricing/index.tsx, src/packages/next/pages/pricing/institutions.tsx, src/packages/next/pages/pricing/onprem.tsx, src/packages/next/pages/pricing/products.tsx, src/packages/next/pages/pricing/subscriptions.tsx, src/packages/next/pages/support/community.tsx, src/packages/next/pages/support/new.tsx, src/packages/static/src/crash.tsx
- "ask" create support form: add a 4th "purchase" category
- add a prices/institutions page
- mention cocalc cloud price, make the links buttons for the contact form
- various small fixes, including html titles
=> cocalc cloud price and institutional price schema

src/packages/next/components/landing/pricing-item.tsx, src/packages/next/pages/pricing/institutions.tsx
I get the point of the disclaimer. In this version, however, I made this more explicit by adding an overcommitment ratio and explained this in a separate paragraph. Also, this reduces the prices by a lot and should be easier to follow.
=> next/pricing/institutions: introduce "overcommitment"

src/packages/backend/logger.ts, src/packages/hub/auth.ts, src/packages/server/auth/sso/oauth2-user-profile-callback.ts, src/packages/server/auth/sso/passport-login.ts
This is mainly adding log lines, since a callback that's supposed to be called, somehow isn't.
=> sso/oauth: adding more logging and reorganizing imports

src/packages/server/openai/chatgpt.ts, src/packages/util/db-schema/openai.ts
user data misses data expiration
=> server/chatgpt: add data expiration if PII is set

src/packages/frontend/frame-editors/frame-tree/title-bar.tsx, src/packages/package.json, src/packages/pnpm-lock.yaml
I only checked that tests pass.
=> node: update to typescript 5 and update jest as well

src/packages/hub/auth.ts
this fixes  #6611 by properly using `next(Error)` + typing
=> hub/auth: fix state exception

src/packages/project/jupyter/jupyter-blobs-disk.ts
delete files fix and be more precise about how many are deleted
=> project/blobstore-disk: fix crash uncaught unlink

src/packages/server/auth/sso/oauth2-user-profile-callback.ts
This is just a line for debugging, to track down a mysterious exception.
=> auth/oauth: log returned body, for debugging

src/packages/project/jupyter/jupyter-blobs-disk.ts
Just a few tweaks after seeing this in practice and going through the code again.
=> project/blobstore/disk: minor tweaks

src/packages/frontend/editors/task-editor/editor.tsx, src/packages/frontend/jupyter/confirm-dialog.tsx, src/packages/frontend/jupyter/find-and-replace.tsx, src/packages/frontend/jupyter/insert-image.tsx, src/packages/frontend/project/deleted-file.tsx, src/packages/frontend/project/info/project-info.tsx, src/packages/frontend/project/page/home-page/chatgpt-generate-jupyter.tsx
- bit of refactoring to avoid all those error messages in development
- sorting and cleaning up some imports
=> frontend: antd.Modal visible is deprecated

src/packages/backend/tcp/enable-messaging-protocol.ts
- tcp messaging protocol: fixing an equality test (for blobs) and some cleanup/typing
I'm setting this to review, despite the mini changes, since there is this bugfix for the equality check. I don't know how to really test this, though. Jupyter and LaTeX works for me, so, I guess this is fine.
=> Project decaffeniate: Part 2

src/packages/frontend/frame-editors/crm-editor/tables/accounts.ts, src/packages/pnpm-lock.yaml, src/packages/server/openai/client.ts, src/packages/server/package.json, src/packages/server/salesloft/client.ts, src/packages/server/salesloft/people.ts, src/packages/server/salesloft/sync.ts, src/packages/util/db-schema/accounts.ts, src/packages/util/db-schema/site-settings-extras.ts
GOAL:
- enter api key
- new cocalc accounts ==> corresponding salesloft people
- info about cocalc usage ==> status info to salesloft
=> salesloft: basic integration

src/packages/frontend/frame-editors/terminal-editor/commands-guide.tsx, src/packages/frontend/project/explorer/compute-file-masks.ts, src/packages/frontend/project/explorer/types.ts, src/packages/frontend/project/page/flyouts/components.tsx, src/packages/frontend/project/page/flyouts/files.tsx, src/packages/frontend/project/page/flyouts/log.tsx, src/packages/frontend/project_store.ts
this adds masked files in the flyout files explorer
=> frontend/flyout: "masked files" + some refactoring/typing consistency

src/packages/frontend/_projects.sass, src/packages/frontend/project/explorer/path-navigator.tsx, src/packages/frontend/project/history/log-entry.tsx, src/packages/frontend/project/page/flyouts/body.tsx, src/packages/frontend/project/page/flyouts/components.tsx, src/packages/frontend/project/page/flyouts/files.tsx, src/packages/frontend/project/page/flyouts/header.tsx, src/packages/frontend/project/page/flyouts/log.tsx, src/packages/frontend/project/page/flyouts/state.ts, src/packages/frontend/project/search/body.tsx, src/packages/frontend/project_actions.ts, src/packages/frontend/project_store.ts, src/packages/pnpm-lock.yaml, src/packages/util/misc.test.ts, src/packages/util/misc.ts
various small tweaks, e.g. how search looks, showing all activity in logging, file keyboard navigation, ...
=> Flyout tweaks 3

src/packages/frontend/project/page/flyouts/log.tsx
=> Flyout tweaks 3 fixes

src/packages/frontend/project/explorer/types.ts, src/packages/frontend/project/page/file-tabs.tsx, src/packages/frontend/project/page/flyouts/components.tsx, src/packages/frontend/project/page/flyouts/files.tsx, src/packages/frontend/project/page/flyouts/log.tsx, src/packages/frontend/project/page/flyouts/state.ts, src/packages/frontend/project/page/page.tsx, src/packages/frontend/project_actions.ts, src/packages/frontend/project_store.ts, src/packages/util/misc.test.ts, src/packages/util/misc.ts, src/packages/util/theme.ts
- indicate active editor
- wrapping long lines in file log
- sanitizing values coming from local storage
- "-editor" a global prefix, use misc functions instead of ad-hoc code
=> flyout: few additonal fixes

src/packages/frontend/components/copy-to-clipboard.tsx, src/packages/frontend/course/configuration/terminal-command.tsx, src/packages/frontend/frame-editors/course-editor/course-tab-bar.tsx, src/packages/frontend/frame-editors/crm-editor/views/view-menu/export.tsx, src/packages/next/components/store/quota-config.tsx
- Input.Group → Space.Compact
- TabPane → Tab items in course
- similarly, tabs in store/upgrades
=> frontend: antd deprecations

src/packages/frontend/antd-bootstrap.tsx, src/packages/frontend/project/page/flyouts/components.tsx, src/packages/frontend/project/page/flyouts/files-bottom.tsx, src/packages/frontend/project/page/flyouts/files.tsx, src/packages/jupyter/redux/project-actions.ts
this fixes #6807 
this depends on https://github.com/sagemathinc/cocalc/pull/6811 to avoid merge conflicts. hence that PR must be merged first, then this one.
=> fix flyout adhoc file creation

src/packages/frontend/project/explorer/path-navigator.tsx
just a silly bug, different implementation fixes #6810
=> frontend/explorer/path-nav: fix breadcrumb history

src/packages/project/sync/server.ts
exception:
```
TypeError: Cannot destructure property 'n' of 'this.num_connections' as it is undefined.
at SyncTableChannel.save_and_close_if_possible (/cocalc/github/src/packages/project/dist/sync/server.js:299:17)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
This can happen due to calling close first, then setting the state flag. 
```
close(this); // don't call this.log after this!
this.closed = true;
```
This PR adds a state "closing", to avoid trying to access `this.log` or `this.num_connections` while it is being closed.
Alternatively, I wonder if `this.closed` should be set to true earlier in the close method?
=> project: avoid crash when this.num_connections is undefined

src/packages/frontend/frame-editors/code-editor/actions.ts, src/packages/frontend/frame-editors/frame-tree/editor.tsx, src/packages/frontend/frame-editors/frame-tree/frame-tree-drag-bar.tsx, src/packages/frontend/frame-editors/frame-tree/leaf.tsx
- fix #6826
- remove general window listener, which isn't necessary and never removed (feels like a bug)
- switch to use debounce from lodash, not underscore
- some import and function signature type fixes, but no change in the code
=> frontend/frame-tree: trigger resize if container div resizes

src/packages/frontend/project/page/flyouts/files.tsx
I'm optimistic this fixes #6832
=> frontend/flyout: eliminate local file search state 

src/packages/frontend/file-associations.ts
since I just came across that file type ...
=> frontend: support *.ini files

src/packages/frontend/components/color-picker.tsx, src/packages/frontend/notifications/notification-news.tsx, src/packages/frontend/package.json, src/packages/frontend/project/page/flyouts/components.tsx, src/packages/hub/package.json, src/packages/next/package.json, src/packages/pnpm-lock.yaml, src/packages/static/package.json
- newest antd, mainly because I noticed discrepancies with the documentation
- newest webpack & friends
testing: well, hard to test everything. so far it looks good. I hoped this fixes HMR, but no, it's the same as before. Besides more deprecation messages, there must have been a change with buttons. "ghost" is a cross cutting boolean aspect, not a "type". easy to fix.
=> npm: update antd and webpack

src/packages/frontend/account/settings/email-verification.tsx, src/packages/frontend/admin/page.tsx, src/packages/frontend/frame-editors/crm-editor/fields/account.tsx, src/packages/frontend/package.json, src/packages/frontend/project/page/flyouts/components.tsx, src/packages/frontend/project/page/flyouts/settings.tsx, src/packages/frontend/purchases/purchases-page.tsx, src/packages/frontend/purchases/statements-page.tsx, src/packages/frontend/purchases/subscriptions.tsx, src/packages/next/package.json, src/packages/pnpm-lock.yaml
- frontend/settings/account: convert email verification to functional component
- antd 5.8.3
- collapse panel is deprecated
- frontend/settings/purchases: also adding the footer
- same for statements
- admin page
- flyout/settings
- crm/account collapsible element
- frontend/purchases: license description
- frontend/purchases/subscription: license collapsable.panel
the only real change here is the antd update. I checked a few things, but I wasn't able to spot any problems. This whole PR is mainly about reducing the number of deprecation warnings. (there are more, this is just a step in the right direction)
=> frontend: misc updates

src/packages/next/pages/policies/privacy.tsx
I *think* that we can publish it now, because we are already listed as participating in DPF:
https://www.dataprivacyframework.gov/s/participant-search/participant-detail?id=a2zt0000000TUtjAAG&status=Active
Paragraphs that had explicitly suggested text from DPF website are replaced with those, others are edited to replace Privacy Shield with DPF.
=> Switch from Privacy Shield to Data Privacy Framework

src/packages/frontend/project/page/flyouts/files.tsx
=> frontend/flyout/files: hide ".." if there is an active search 

src/packages/frontend/project/history/log-entry.tsx, src/packages/frontend/project/history/types.ts, src/packages/frontend/project/settings/compute-image-selector.tsx, src/packages/frontend/project/settings/project-control.tsx, src/packages/frontend/project/settings/software-consts.ts, src/packages/frontend/project_actions.ts, src/packages/next/components/landing/cocalc-com-features.tsx
fixes https://github.com/sagemathinc/cocalc/issues/6884
1. introduces a new `SoftwareEnvironmentEvent`
2. records it if the environment changes
3. displays it in the list of log entries
=> frontend/log: record software environment change

src/packages/frontend/account/licenses/managed-licenses.tsx
=> Fix a typo

src/packages/next/pages/policies/accessibility.tsx
It is unlikely that we will have to change it in the near future, but some customers don't like to see an old date on it.
=> Drop the date on VPAT

src/packages/frontend/purchases/license-editor.tsx
=> Explain why the end date cannot be edited

src/cocalc.code-workspace, src/packages/next/components/store/dedicated.tsx, src/packages/util/upgrades/dedicated.ts
I think it's best to just state the values and point to their website.
=> store: disk speed wording

src/packages/frontend/site-licenses/purchase/quota-editor.tsx
=> cocalc-cloud/dedicated vm: just a mistake with the label name

src/packages/frontend/project/explorer/explorer.tsx, src/packages/frontend/project/explorer/file-listing/file-listing.tsx, src/packages/frontend/project/explorer/file-listing/file-row.tsx, src/packages/frontend/project/page/flyouts/components.tsx, src/packages/frontend/project/page/flyouts/files-header.tsx, src/packages/frontend/project/page/flyouts/files.tsx
- in flyout/files, gray out file extensions
- make the header its own component, can't hurt
- source format some of the explorer files
=> Flyout files extension

src/packages/next/components/store/overview.tsx
=> Make Voucher and PAYGO the second row in the store

src/packages/util/compute-images.ts
This is just a trivial change, adds an environment to our list of historic ones.
=> software: add Ubuntu 22.04 frozen on 2023-09-11

src/packages/next/components/landing/cocalc-com-features.tsx, src/packages/next/components/landing/info.tsx, src/packages/next/components/share/proxy-input.tsx, src/packages/next/pages/api/v2/public-paths/listing-cached.ts, src/packages/next/pages/index.tsx, src/packages/next/pages/pricing/products.tsx, src/packages/server/public-paths/listing-cached.ts
- on index page, make the table of shared files hidden by default
- some minor changes as well
- make the pricing/product page look a bit better and a bit more dense in information
- mention pay-as-you-go in more places
=> next/index: tweak landing page

src/packages/server/mentions/notify.ts
This is just a small note in the sent email, to tell users to not just reply.
=> mention: add note to email about how to reply

src/packages/next/pages/vouchers/index.tsx
=> Update Voucher Center

src/packages/frontend/lib/should-open-in-foreground.ts, src/packages/frontend/project/explorer/file-listing/file-row.tsx, src/packages/frontend/project/history/utils.ts, src/packages/frontend/project/page/flyouts/file-list-item.tsx, src/packages/frontend/project/page/flyouts/files.tsx, src/packages/frontend/project/search/body.tsx, src/packages/util/misc.ts
- flyout/log: fix error when opening a file, as part of that adding types to `should_open_in_foreground` and moving it to the frontend code
- flyout/log: make file action entries actually work, and only for a single file under the click
=> Fix flyout log context errors

src/packages/frontend/site-licenses/site-license-public-info-component.tsx, src/packages/frontend/site-licenses/site-license-public-info.tsx, src/packages/util/licenses/describe-quota.ts
- show run limit and tweak style and wording a little bit
- fixes #6989
=> tweak displayed license text

src/packages/frontend/collaborators/project-invite-tokens.tsx
* First discussed here → https://github.com/sagemathinc/cocalc/discussions/6483
* Connected issue to implement #7019
=> Implemented #7019 https://github.com/sagemathinc/cocalc/issues/7019

src/packages/frontend/project/explorer/explorer.tsx, src/packages/frontend/project/explorer/mini-terminal.tsx
=> #6680: Enabled mini terminal close button. Tweaked button placement.

src/packages/frontend/project/page/flyouts/active-top.tsx, src/packages/frontend/project/page/flyouts/active.tsx, src/packages/frontend/project/page/flyouts/utils.ts
few minor tweaks and a fix for the active files flyout
=> Flyout active tweaks

src/packages/frontend/project/open-files.ts, src/packages/frontend/project/page/flyouts/active-starred.tsx, src/packages/frontend/project/page/flyouts/active.tsx, src/packages/frontend/project/page/utils.ts, src/packages/frontend/project_actions.ts, src/packages/frontend/project_store.ts
- refactoring
- recently closed → closed files and internally, recently → just
- exception when using context menu
- avoid accidental unstarring of a file
=> Flyout active tweaks #2

src/packages/frontend/project/context.tsx, src/packages/frontend/project/info/components.tsx, src/packages/frontend/project/page/file-tab.tsx
=> frontend/project info: do not show erroneous cgroup info 

.github/workflows/make-and-test.yml, src/scripts/check_doc_urls.py
This standalone script tests, if all URLs in the source pointing to the documentation, actually hit an existing page. This could be part of the test suite, although it's kind of a headache, if it fails because of a change in the documentation or the server is down …
Hmm, I've added this as a second job, independent of the build job. So, it's easy to disable or ignore.
@novoselt this could be useful for you
```
hsy@x2:~/p/cocalc/src$ ./scripts/check_doc_urls.py 
Checking 69 URLs...
✓ https://doc.cocalc.com/chat.html
✓ https://doc.cocalc.com/howto/low-memory.html
✓ https://doc.cocalc.com/api/index.html
✓ https://doc.cocalc.com/howto/install-julia-package.html
✓ https://doc.cocalc.com/howto/pluto.html
✓ https://doc.cocalc.com/api
✓ https://doc.cocalc.com/cocalc-cloud.html
✓ …
```
=> add url doc check script

src/packages/frontend/editors/markdown-input/multimode.tsx, src/packages/frontend/editors/slate/editable-markdown.tsx, src/packages/frontend/project/new/new-file-page.tsx
this fixes the chat/text @palm2 mention
ref: #7119
=> frontend/chat/text: fix @palm2

src/packages/frontend/account/avatar/avatar.tsx, src/packages/frontend/account/chatbot.ts, src/packages/frontend/chat/side-chat.tsx, src/packages/frontend/components/google-gemini-avatar.tsx, src/packages/frontend/components/language-model-icon.tsx, src/packages/frontend/editors/markdown-input/mentionable-users.tsx, src/packages/frontend/frame-editors/chatgpt/model-switch.tsx, src/packages/frontend/jupyter/insert-cell/ai-cell-generator.tsx, src/packages/pnpm-lock.yaml, src/packages/server/openai/chatgpt.ts, src/packages/server/openai/client.ts, src/packages/server/package.json, src/packages/server/purchases/create-purchase.ts, src/packages/util/db-schema/openai.ts, src/packages/util/db-schema/purchase-quotas.ts, src/packages/util/db-schema/purchases.ts, src/packages/util/db-schema/site-settings-extras.ts
This disables palm2 and adds/fixes enough for gemini pro to make it work.
=> AI: gemini pro instead of palm2

src/packages/frontend/editors/markdown-input/mentionable-users.tsx, src/packages/server/openai/chatgpt.ts, src/packages/server/openai/client.ts, src/packages/util/db-schema/openai.ts
- respect `USER_SELECTABLE_LANGUAGE_MODELS` in metionable users
- hide error message – not only for specific calls, but there is now also a try/catch for "evaluate" (which is used by the v2 api and hub/client)
=> follow up gemini pro

src/packages/util/licenses/describe-quota.ts
=> #7132: License edits now display number of allowed simulataneously running projects

src/packages/next/components/store/cart.tsx
...and moved license period into description box.
See screenshot for new view:
=> #7173: Removed license `run_limit` edit button in `ShoppingCart` component

src/packages/frontend/project/page/flyouts/active.tsx, src/packages/frontend/project/page/flyouts/file-list-item.tsx
* fix alignment #7206 
* tweak revealing starred files
=> frontend/flyout: tweak col alignments

src/packages/frontend/project/page/flyouts/new.tsx
* fixes for automatic/manual file name and extension logic. e.g.
* this fixes inconsistencies, when you click on an extension and then change the autogenerated filename
* enter an extension manually to a filename, but then click on a button to switch back to automatic
* or when you switch from creating a directory back to a file and vice versa
* also, this adds a bottom create filename button, based on user feedback
=> frontend/flyout/new: various fixes 

src/packages/pnpm-lock.yaml, src/packages/server/llm/index.ts, src/packages/server/package.json
* update to latest gen ai lib, just a patch release
* for debugging, add a switch to throw the error
=> server/llm/gemini: update lib and optionally throw error

src/packages/frontend/frame-editors/latex-editor/pdfjs.tsx
=> frontend/latex/pdf: fix horizontal dragging 

src/packages/frontend/sagews/chatgpt.ts
follow up of https://github.com/sagemathinc/cocalc/pull/7278
=> sagews/help me fix: use current llm

src/package.json
This is a simple version update of pnpm. I don't know if we really need this. In any case, I saw warnings about it being outdated, which confused me, because I had a recent version installed on my computer. Indeed, there was an older version installed in that `node_module/.bin` dir due to this.
=> npm: update pnpm in src root dir

src/packages/next/components/auth/sign-in.tsx
New view (with anonymous sign in):
New view (without anonymous sign in):
=> Fixes #7315: Updated sign in component to include sign up link.

src/packages/next/components/testimonials.tsx
This adds the Spitzer testimonial. I shortened it a little bit, and well, I tried to figure out some affiliations, but without more context I can't.
=> next/testimonial: John Spitzer

src/packages/hub/package.json, src/packages/package.json, src/packages/pnpm-lock.yaml
minor patch-updates for two dependencies
=> npm: webpack-dev-middleware and follow-redirects

src/packages/frontend/jupyter/cell.tsx
=> frontend/jupyter/ai cell: fix #7387

src/packages/util/compute-images.ts
project software env: adding ubuntu2204-2024-02-07 snapshot. this is long overdue and this particular one has been in use without much trouble for quite some time now.
=> frontend/software env: adding ubuntu2204-2024-02-07 snapshot

src/packages/next/pages/about/team/index.tsx
Just a simple verbiage update.
=> Updated about page verbiage.

src/packages/database/user-query/user-get-query.ts, src/packages/frontend/frame-editors/crm-editor/views/view-menu/search.tsx, src/packages/util/db-schema/operators.ts
this is necessary for the CRM data, to filter the accounts/tags field
my main worry is, I hope this does not break anything else.
=> support querying elements in an array

src/packages/database/user-query/user-get-query.ts, src/packages/frontend/frame-editors/crm-editor/views/view-menu/search.tsx, src/packages/util/db-schema/operators.ts
- This expands a bit on top of #7439
- Adds minimum and maximum length filters (i.e. to see if there is at least one tag, etc.)
- also adding IS/NOT IS
what's obviously missing is support for concatenating several conditions, but that's not part of this
=> crm/arrays: upper and lower bounds on the number of elements

.github/workflows/make-and-test.yml
See https://github.com/pnpm/pnpm/releases/tag/v9.0.1
=> github ci pnpm 9.0.1

src/packages/database/postgres/news.ts, src/packages/next/components/landing/index-list.tsx, src/packages/next/components/landing/news-banner.tsx, src/packages/next/pages/news/edit/[id].tsx, src/packages/util/types/news.ts
fixes for #7446: add back the about category (since we use it) and align title and icon in that index list (and also make the padding the same on both sides)
=> events PR followup

src/packages/next/pages/about/team/index.tsx
This contains my follow up commit for #7411 because I don't know how to push to @schrodingersket branch directly.
context: https://github.com/sagemathinc/cocalc/pull/7468#issuecomment-2068945152
=> My changes on top of #7411

src/packages/pnpm-lock.yaml, src/packages/server/package.json
Trivial package update, should make it work.
=> npm: update langchain google for gemini pro 1.5

src/packages/frontend/jupyter/cell-input.tsx, src/packages/frontend/jupyter/main.tsx
This adds the necessary extra check to show or hide the AI button in a jupyter cell.
=> courses: fix disabling some vs. all AI tools for LLM in Jupyter

src/packages/frontend/jupyter/insert-cell/ai-cell-generator.tsx
During dev of these LLM tools in jupyter, I repeatedly saw this and also some weird "hangs". Maybe it's related, maybe not. In any case, the idea of this patch is to render and compute as little as possible by default. Only get the values when the popup shows the content. Errors are below.
what I saw:
=> jupyter/ai-cell-generator: get rid of precomputed values

src/packages/frontend/compute/api.ts, src/packages/frontend/compute/cloud/google-cloud/accelerator.tsx, src/packages/frontend/compute/cloud/google-cloud/specs.tsx, src/packages/frontend/compute/cloud/hyperstack/specs.tsx, src/packages/frontend/compute/create-compute-server.tsx, src/packages/frontend/compute/google-cloud-config.tsx, src/packages/frontend/compute/images.tsx, src/packages/frontend/compute/nvidia.tsx, src/packages/frontend/compute/public-templates.tsx, src/packages/frontend/compute/select-image.tsx, src/packages/frontend/project_store.ts, src/packages/next/components/auth/in-place-sign-in-or-up.tsx, src/packages/next/components/landing/compute-server-templates.tsx, src/packages/next/components/landing/compute-servers.tsx, src/packages/next/components/landing/header.tsx, src/packages/next/components/landing/sign-in.tsx, src/packages/next/components/landing/sub-nav.tsx, src/packages/next/pages/api/v2/compute/get-template.ts, src/packages/next/pages/api/v2/compute/get-templates.ts, src/packages/next/pages/features/ai.tsx, src/packages/next/pages/features/compute-server.tsx, src/packages/next/pages/features/index.tsx, src/packages/next/pages/index.tsx, src/packages/server/compute/templates.ts, src/packages/util/compute/templates.ts, src/packages/util/db-schema/compute-servers.ts
=> Compute templates on landing page

src/packages/frontend/purchases/purchases.tsx, src/packages/util/db-schema/llm-utils.ts, src/packages/util/db-schema/purchase-quotas.ts
Charge for Gemini 1.5 and adding a context limited variant like with the others.
=> llm: charge for gemini 1.5

src/packages/frontend/frame-editors/llm/llm-selector.tsx
=> frontend/llm-selector: make "paid" use the warning type

src/packages/frontend/jupyter/cell-buttonbar.tsx, src/packages/frontend/jupyter/llm/cell-tool.tsx, src/packages/util/db-schema/llm-utils.ts
- event tracking names do not have dashes, only underscores
- remove start/stop button tracking in small button bar, since it generates too much data
- include the model when submitting the ai tool task
=> LLM jupyter tweaks

src/packages/project/upload.ts
Well, #7513 is a bit mysterious, since there is a try/catch block. However, this patch adds an extra check and throws a more human readable error message.
=> project/upload: check explicitly for write perms to avoid #7513

src/packages/frontend/chat/chatroom.tsx, src/packages/frontend/chat/message.tsx
temporarily  disable llm cost estimation until getting mentions is modified accordingly
=> frontend/chat: disable llm cost estimation

src/packages/frontend/frame-editors/llm/title-bar-button.tsx, src/packages/util/db-schema/llm-utils.ts
disable large context window models until we know they work well
=> llm: disable large context window models 

src/packages/server/mentions/handle.ts, src/packages/util/db-schema/copy-paths.ts, src/packages/util/db-schema/mentions.ts
Similar to how we do with other tables like file_access_log, this adds an expire field to the mentions table.
=> add expiration to mentions

src/packages/frontend/frame-editors/code-editor/actions.ts, src/packages/frontend/frame-editors/frame-tree/frame-tree.tsx, src/packages/frontend/frame-editors/frame-tree/title-bar.tsx, src/packages/frontend/frame-editors/llm/consts.ts, src/packages/frontend/frame-editors/llm/context.tsx, src/packages/frontend/frame-editors/llm/create-chat.ts, src/packages/frontend/frame-editors/llm/help-me-fix.tsx, src/packages/frontend/frame-editors/llm/title-bar-button.tsx, src/packages/frontend/jupyter/insert-cell/ai-cell-generator.tsx, src/packages/frontend/jupyter/llm/cell-tool.tsx, src/packages/frontend/launch/actions.ts, src/packages/frontend/project/page/home-page/ai-generate-document.tsx
- :warning: https://github.com/sagemathinc/cocalc/pull/7569 must be merged first
- code refactoring, e.g. variable names
- always show the context
- debounced token calc
- show preview of what's actually being sent to the LLM
- close if clicking outside the dialog (otherwise, you're kind of lost if the dialog is larger than your viewport)
- save/restore command
- hide in AI restricted projects
=> Ai assist tweaks

src/packages/frontend/frame-editors/frame-tree/commands/const.ts, src/packages/frontend/frame-editors/frame-tree/commands/editor-menus.ts, src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx, src/packages/frontend/frame-editors/frame-tree/commands/manage.tsx, src/packages/frontend/frame-editors/frame-tree/commands/menus.ts, src/packages/frontend/frame-editors/frame-tree/commands/types.ts, src/packages/frontend/frame-editors/frame-tree/title-bar.tsx, src/packages/frontend/frame-editors/jupyter-editor/editor.ts, src/packages/frontend/project/page/home-page/ai-generate-document.tsx, src/packages/frontend/project/page/home-page/ai-generate-examples.ts, src/packages/frontend/project/page/home-page/ai-generate-utils.ts
- fix #7578
- but I named it "Help me write..." and it's in a global var, to make tweaking it easy
- add a File → "[AI] Help me write..." menu entry for supported extensions
=> AI Generator tweaks

src/packages/util/db-schema/llm-utils.ts
tweaking the llm prices based on their websites
=> llm pricing: there are a couple of small changes

src/packages/server/compute/set-detailed-state.ts
=> #7616: Fixed parameter binding when querying full `detailed_state` object for a compute server.

src/packages/util/db-schema/llm-utils.ts
just a trivial detail, no impact on production, no need to deploy it.
=> util/llm: sync default settings of available LLM services with db defaults

src/packages/util/compute-images.ts
recording the previous `ubuntu2204-2024-05-13` compute environment
=> compute environment ubuntu2204-2024-05-13

src/packages/server/llm/anthropic.ts, src/packages/server/llm/test/00.test.ts, src/packages/util/db-schema/llm-utils.ts, src/packages/util/db-schema/purchase-quotas.ts
- disable existing sonnet
- enable sonnet 3.5 with a context window, like the others
- tweak descriptions to what the api doc says about them
- make it non-free, to avoid hitting quota limits (I want to investigate them in another PR in more detail).
- tested it, works very good, and added a backend test
=> llm: claude sonnet 3.5

src/packages/next/pages/pricing/onprem.tsx
Only changes the default body of the ticket.
=> Encourage users to provide some details for CoCalc Cloud requests

src/packages/database/postgres/site-license/hook.ts, src/packages/database/postgres/site-license/quota-site-settings.ts, src/packages/frontend/compute/onprem-config.tsx, src/packages/frontend/course/configuration/envvars-config.tsx, src/packages/frontend/course/configuration/student-project-software-environment.tsx, src/packages/frontend/project/settings/datastore.tsx, src/packages/next/components/landing/cocalc-com-features.tsx, src/packages/next/pages/auth/ROUTING.md, src/packages/next/pages/pricing/onprem.tsx, src/packages/util/quota.test.ts, src/packages/util/upgrades/consts.ts, src/packages/util/upgrades/quota.ts
=> rename "CoCalc Cloud" → "CoCalc OnPrem"

src/packages/frontend/project/trial-banner.tsx
basically add tracking when it initiates a shutdown
=> frontend/trial-banner: tweak tracking

src/packages/frontend/project/trial-banner.tsx
=> frontend/trial-banner: fix typo by removing VC from the text

src/packages/database/postgres-server-queries.coffee, src/packages/database/postgres/syncdoc-history.ts, src/packages/frontend/account/delete-account.tsx, src/packages/frontend/client/users.ts, src/packages/frontend/compute/google-cloud-config.tsx, src/packages/frontend/course/actions.ts, src/packages/frontend/course/assignments/actions.ts, src/packages/frontend/course/configuration/actions.ts, src/packages/frontend/course/shared-project/actions.ts, src/packages/frontend/course/store.ts, src/packages/frontend/course/student-projects/actions.ts, src/packages/frontend/course/students/actions.ts, src/packages/frontend/course/students/deleted-account.tsx, src/packages/frontend/course/students/students-panel-student.tsx, src/packages/frontend/course/students/students-panel.tsx, src/packages/frontend/course/sync.ts, src/packages/frontend/course/types.ts, src/packages/frontend/projects/actions.ts, src/packages/hub/api/examples.md, src/packages/hub/client.coffee, src/packages/next/pages/api/v2/accounts/get-names.ts, src/packages/server/accounts/get-name.ts, src/packages/util/message.d.ts, src/packages/util/message.js
=> Issue 3243

src/packages/frontend/compute/public-templates.tsx
=> properly place text in compute server templates

src/packages/frontend/client/users.ts, src/packages/frontend/course/students/actions.ts, src/packages/frontend/course/students/students-panel.tsx, src/packages/hub/client.coffee, src/packages/server/accounts/search.ts, src/packages/util/message.js
Fixes #7832 
See it working:
https://github.com/user-attachments/assets/b36a8e89-eb42-4d1f-956c-c719ab3ca356
=> Restrict student search to use only emails

src/packages/frontend/account/actions.ts
=> frontend: fix account_delete

src/packages/comm/x11-apps.ts
this is a trivial addition and cleaner typing
=> frontend/x11: add xfractint and tweak typing a little bit

src/packages/next/package.json, src/packages/pnpm-lock.yaml
testing: I tried opening a couple of next pages and everything was fine
=> npm: update next to 14.2.22

src/packages/frontend/codemirror/css.js, src/packages/next/pages/_app.tsx, src/packages/util/db-schema/accounts.ts
=> codemirror: add a couple of themes 

src/packages/frontend/cspell.json, src/packages/frontend/project/page/software-env-upgrade.tsx
This is just a weird edge case, but nonetheless good to fix -- fixes #8141
=> frontend/software upgrade banner: fix edge case 

src/packages/frontend/account/account-page.tsx, src/packages/frontend/purchases/balance-button.tsx
follow up of #8142 because silly-me forgot to hide it everywhere
=> frontend: disable the balance button in account settings

src/packages/next/pages/policies/privacy.tsx
- remove excessive text on advertizing - we don't do it
- clarify data location: US or explicitly chosen
- add EU/UK representative contact info
- make some headers uniform with the others
=> Update Privacy Policy

src/packages/frontend/cspell.json, src/packages/frontend/site-licenses/purchase/quota-editor.tsx, src/packages/util/types/gpu.ts, src/packages/util/types/site-licenses.ts
This is just a small generalization -- context #8161
=> frontend/license: allow configuring the GPU resource name

src/packages/frontend/chat/llm-msg-regenerate.tsx, src/packages/frontend/cspell.json, src/packages/util/db-schema/llm-utils.ts
gemini pro is discontinued, hence disabling it
=> LLM: disable gemini-pro and fix a text spacing issue

src/packages/frontend/purchases/license-editor.tsx
=> Adjust subscription editor text

src/packages/frontend/compute/configuration.tsx
=> frontend/compute: fix typo

src/packages/backend/data.ts, src/packages/backend/nats/cli.ts, src/packages/backend/nats/conf.ts, src/packages/pnpm-lock.yaml, src/packages/server/nats/tiered-storage/archive.ts, src/packages/server/nats/tiered-storage/backup.ts, src/packages/server/nats/tiered-storage/index.ts, src/packages/server/nats/tiered-storage/restore.ts, src/packages/server/package.json
Address this scalability ticking time bomb for CoCalc ASAP:  
https://github.com/nats-io/nats-server/issues/3533#issuecomment-2817231963
=> Nats tiered storage

src/packages/hub/package.json, src/packages/pnpm-lock.yaml
With that, I can still upload files to my dev project.
=> npm: update formidable

src/packages/database/settings/auth-sso-types.ts, src/packages/pnpm-lock.yaml, src/packages/server/hub/auth.test.ts, src/packages/server/hub/auth.ts, src/packages/server/package.json, src/scripts/auth/gen-sso.py
no change for existing configs, safe to merge
=> sso/auth: customize separator for dot-object

src/cocalc.code-workspace, src/packages/next/components/auth/sign-in.tsx, src/packages/next/components/auth/sign-up.tsx, src/packages/next/pages/api/v2/auth/sign-in.ts, src/packages/next/pages/api/v2/auth/sign-up.ts, src/packages/next/pages/auth/sign-in.tsx, src/packages/util/auth.ts
pretty simple fix to limit the password length. ~~what's left is testing.~~
=> next/api: limit password length

src/packages/frontend/project/project-banner.tsx
=> frontend/no-internet: fix broken logic #8407

src/packages/frontend/project/page/activity-bar.tsx
=> frontend/activity bar: make full pages the default for everyone

src/packages/next/pages/software/index.tsx
=> next/software: tweak software img line selection buttons

src/packages/next/pages/pricing/onprem.tsx
fixes #8545 + rewording everything to be more concise
=> next/onprem: add NASA statement #8545 and do some rewording

src/packages/frontend/frame-editors/llm/use-llm-history.ts
I saw Event Emitter leak warnings for the jupyter cell's llm tool. Either the useAsyncEffect didn't clean up properly or the function always changed, I don't know. In any case, this is now just a "useEffect" and the update function is referenced. With that, no more such warnings...
=> frontend/llm: fix event emitter leak in use-llm-history

src/packages/frontend/frame-editors/llm/help-me-fix-utils.ts, src/packages/frontend/sagews/chatgpt.ts, src/packages/frontend/sagews/sagews.coffee
* this fixes #8546 
* ironically, this was completely broken, because "full: true" must be set for the getHelp to actually mention an LLM
* it also adds a native confirmation yes/no banner. there was nothing in place, despite the "...". This is not pretty, but better than before.
=> frontend/sagews: add "give me a hint" button to aid users

src/packages/frontend/jupyter/cell-buttonbar-menu.tsx, src/packages/frontend/jupyter/commands.ts
=> frontend/jupyter: add Clear Output option to individual cell context menu

src/packages/backend/data.ts, src/packages/hub/hub.ts
This makes it possible to configure more hub params via environment variables. No change in default settings.
=> hub: configure more params via env variables
